### ISSUE TITLE
T100 should not hit on import builtins

### ISSUE THREAD

**Issue by LefterisJP** [charliermarsh/ruff#1032]
Seen with `ruff==0.0.155`

Simply doing an import builtins seems to hit us with `file:1:1 - T100 Import for `builtins` found

This should not be happening as there is legitimate reasons to import that module.

Seems to be a bug in flake-debugger 3.1.1
![2022-12-04_13-40](https://user-images.githubusercontent.com/1658405/205491023-cc85bcbe-29b4-4df9-9ea7-2378e1de6caf.png)

A reason to import builtins can be seen here: https://github.com/python/mypy/issues/14245

Got to that mypy problem actually by switching to PEP585 syntax thanks to ruff autofix :)

**Comment by charliermarsh** [comment]
Yeah flagging `import builtins` is bad and far too strict. Will fix.
