### ISSUE TITLE
RUF004 is not autofixable

### ISSUE THREAD

**Issue by LefterisJP** [charliermarsh/ruff#1038]
This is with ruff `0.0.155`

Consider the following:

```python
a = 1
while a < 10:
    a += 1

exit()
```

running ruff on it with RUF004 activated works and detects the problem.
But if you try to fix it with `ruff --fix` it does not autofix it. And afaics this should be autofixable.

**Comment by charliermarsh** [comment]
It’s because sys isn’t imported, and we don’t have the ability to add it to the import list (yet) since edits are currently localized.

**Comment by charliermarsh** [comment]
(Or, that’s my guess — I’m on the subway :))

**Comment by LefterisJP** [comment]
No worries :)

Do you think it's something ruff can fix at some point?

**Comment by charliermarsh** [comment]
Yes absolutely!

**Comment by charliermarsh** [comment]
It’s tracked somewhat obliquely by #835 so I’m going to close this one out in favor of the existing issue.

**Comment by LefterisJP** [comment]
> It’s tracked somewhat obliquely by #835 so I’m going to close this one out in favor of the existing issue.

Sure no problem. I fixed it in our case by adding import sys manually and changing one exit to sys.exit(). Then ruff did autofix all the rest on its own ;)
