### ISSUE TITLE
Archlinux AUR package

### ISSUE THREAD

**Issue by mortymacs** [charliermarsh/ruff#1044]
Hi,

I've prepared the AUR package for ArchLinux-based distributions.
Here is the link: https://aur.archlinux.org/packages/python-ruff

Cheers,
Mort

**Comment by mortymacs** [comment]
@charliermarsh, I'm updating it manually as I don't have access to the repo to trigger a pipeline. But we can do something to make it automated. I can give you ownership of the AUR package and you can keep it updated by this Github Action: https://github.com/marketplace/actions/publish-aur-package
What's your idea?

**Comment by charliermarsh** [comment]
Yeah I'm open to that. How is the `PKGBUILD` file created?

**Comment by charliermarsh** [comment]
PR would be awesome if you're up for it.

**Comment by mortymacs** [comment]
I have good news!
The ArchLinux community officially prepared the package, and now it's in the official repository (https://archlinux.org/packages/community/x86_64/ruff/). Now, anyone can install it by `pacman -S ruff` without needing any AUR package.
So, I'm gonna close this issue :)

**Comment by charliermarsh** [comment]
@mortymacs - Oh, amazing, thanks! I'll add a note to the docs.
