### ISSUE TITLE
One aliased import per line rule

### ISSUE THREAD

**Issue by smackesey** [charliermarsh/ruff#1046]
The codebase I work on uses code like this for explicit re-exports in many `__init__.py` files:

```
from .utils import (
    test_directory as test_directory,
    test_id as test_id
)
```

It's useful to have code like this have exactly one import per line-- it's easier to tell at a glance what is being exported.

It's possible I've missed something but I don't think either `isort` or `ruff` offers a way to reliably achieve this formatting. By default, both formatters produce (1) below. If you turn on Isort's `combine-as` or ruff's `combine-as-imports` and you are under the line length limit, then you get (2).

```
# (1) One aliased import per line in separate import statements

from .utils import test_directory as test_directory
from .utils import test_id as test_id

# (2) Multiple imports per line if under line limit

from .utils import test_directory as test_directory, test_id as test_id
```

To get around this, we currently disable `isort` using `# isort: off` comments when we use this pattern. The lack of ability to do something similar in `ruff` is preventing us adopting `ruff` in place of `isort`.

I propose an option that forces aliased imports to a single line, but still groups them together in a single import statement-- then we wouldn't even need to turn off the import sorter.

**Comment by charliermarsh** [comment]
Happy to support this.

If there's only a single import, are you imaging that it still enforces the same style? E.g.:

```py
from .utils import (
    test_directory as test_directory,
)
```

Or would single-imports be retained on their own lines.

**Comment by smackesey** [comment]
Somewhat ambivalent but I prefer #1 to #283 

```
# 1
from .utils import (
    test_directory as test_directory,
)

# 2
from .utils import test_directory as test_directory
```

**Comment by charliermarsh** [comment]
Cool, I can add this now and cut another release.

**Comment by charliermarsh** [comment]
Would it make sense to _always_ enforce this (one-per-line) behavior? Or at least for all `import-from` statements? Or would it be inconvenient if it applied beyond explicit re-exports?

**Comment by charliermarsh** [comment]
(For now, I'll just apply this to `from` blocks where every member is a re-export.)

**Comment by smackesey** [comment]
I think the rule makes sense for all aliased imports-- parsing multiple "foo as bar" clauses on the same line can be difficult, regardless of whether they're explicit reexports (i.e. redundant aliases) or not. But if it only applies to re-exports, that would still solve our problem.

**Comment by charliermarsh** [comment]
@smackesey - #1047 implements this as `force-wrap-aliases`. For now, the rules are: enforce multi-line formatting if an import-from has more than one member, and at least one member is aliased. But I'm happy to do whatever. (We don't combine straight imports, so it doesn't touch `import os as os`.)

**Comment by smackesey** [comment]
Ask and ye shall receive-- thanks!

>For now, the rules are: enforce multi-line formatting if an import-from has more than one member, and at least one member is aliased.

Sounds reasonable.

**Comment by charliermarsh** [comment]
Cool, that's going out in [v0.0.158](https://github.com/charliermarsh/ruff/releases/tag/v0.0.158) (building now). Since, as far as I know, you'll be the first user of the option, let me know if you'd like it tweaked to better fit the use-case!
