### ISSUE TITLE
I001 weird asterisk behavior

### ISSUE THREAD

**Issue by guyrosin** [charliermarsh/ruff#1050]
Given the following two imports:
```
from some_module import *
from some_module import some_class
```
Ruff raises `I001` and autofixes to this invalid import statement: 
```from some_module import *, some_class```

**Comment by guyrosin** [comment]
In addition: `# noqa: I001` doesn't seem to ignore this error

**Comment by UnknownPlatypus** [comment]
I had a similar issue with multiline wrapping resulting in invalid python code:

```diff
-from .subscription import * # type: ignore  # some very long comment explaining why this needs a type ignore
+from .subscription import ( # type: ignore  # some very long comment explaining why this needs a type ignore
+    *,
+)
```

I think star import should probably be special cased.

I'm happy to work on a MR if needed

**Comment by charliermarsh** [comment]
Good call, will fix today.

**Comment by charliermarsh** [comment]
@guyrosin - In the interim, you can use `isort: off` to ignore this --

```py
# isort: off
from some_module import *
from some_module import some_class
# isort: on
```

**Comment by UnknownPlatypus** [comment]
@charliermarsh fyi, the other star import related case I mentioned above is still broken with `0.0.161`

Should I create another issue for that ?

**Comment by charliermarsh** [comment]
@UnknownPlatypus - Oh sorry! I missed that. Feel free to create another issue, I'll fix it tonight.

**Comment by UnknownPlatypus** [comment]
No worries! 

thank for the great work on this project, would love ton contribute but I'm not yet skilled enough with rust.
I'm creating another issue for the above use case!

Cheers
