### ISSUE TITLE
`flake8-annotations` rules do not ignore functions with type overloads

### ISSUE THREAD

**Issue by joouha** [charliermarsh/ruff#1053]
Hello,

Checking the following using flake8-annotations gives no output when a function is typed using overloads:

```python
from typing import overload

@overload
def myfunc(i: int) -> "int":
    ...

@overload
def myfunc(i: "str") -> "str":
    ...

def myfunc(i):
    return i
```

However, ruff warns of missing types in the overloaded function:

```bash
$ ruff --select=ANN example.py

Found 2 error(s).
example.py:14:1: ANN201 Missing return type annotation for public function `myfunc`
example.py:14:12: ANN001 Missing type annotation for function argument `i`
```

**Edit:** It looks like ANN201 : ANN206 are affected by this

**Comment by charliermarsh** [comment]
Gonna call this a bug since flake8-annotations seems to handle it just fine.
