### ISSUE TITLE
[bug] ruff chokes when fixing invalid comparison (`F632`)

### ISSUE THREAD

**Issue by smackesey** [charliermarsh/ruff#1057]
This `F632`-triggering line (and several similar ones in our codebase) caused `ruff --fix` to choke:

```
type_check_fn=lambda _, value: isinstance(value, int) and value % 2 is 0,
```

Error message:

```
[2022-12-05][08:09:02][ruff::pyflakes::plugins::invalid_literal_comparisons][ERROR] Failed to fix invalid comparison: Failed to extract CST from source
```

Subsequent runs of `ruff --fix` print no error message but don't apply the fix either (though I think this is the cache? Running with `--no-cache` prints the error again).

**Comment by charliermarsh** [comment]
I wonder if the comma is being included in the lambda expression span, will check it out.

**Comment by charliermarsh** [comment]
This is going out in [v0.0.159](https://github.com/charliermarsh/ruff/releases/tag/v0.0.159) (building now).
