### ISSUE TITLE
request: add trailing commas

### ISSUE THREAD

**Issue by MartinBernstorff** [charliermarsh/ruff#1058]
Only thing in my pre-commit toolchain that Ruff hasn't replaced yet. Would love to see it, and thanks for all your work!

https://github.com/asottile/add-trailing-comma

**Comment by bluetech** [comment]
There's also [flake8-commas](https://github.com/PyCQA/flake8-commas/). It has these rules:

Code | message
-- | --
C812 | missing trailing comma
C813 | missing trailing comma in Python 3
C814 | missing trailing comma in Python 2
C815 | missing trailing comma in Python 3.5+
C816 | missing trailing comma in Python 3.6+
C818 | trailing comma on bare tuple prohibited
C819 | trailing comma prohibited

**Comment by Avasam** [comment]
`add-trailing-commas` also has [unhug-trailing-paren](https://github.com/asottile/add-trailing-comma#unhug-trailing-paren), [unhug-leading-paren](https://github.com/asottile/add-trailing-comma#unhug-leading-paren) and [avoids arbitrary indentation](https://github.com/asottile/add-trailing-comma#multi-line-method-invocation-style----why).
Which is not enforced by Ruff or Autopep8. Even Black only enforces it when magic commas are used:
```py
# This is found acceptable by Ruff, Autopep8 and Black
print(1,
      2,
      3,
      4,
      5)
      
# This is what add-trailing-commas changes is to
print(
    1,
    2,
    3,
    4,
    5,
)
```
So Ruff hasn't yet completely replaced it for me, though I'd love to see it get there. Is this the right place or should I open a new issue?

**Comment by sisrfeng** [comment]
@Avasam 
https://github.com/asottile/add-trailing-comma, not \ 
https://github.com/asottile/add-trailing-commas
