### ISSUE TITLE
[bug?] Questionable docstring first line fix (`D205`)

### ISSUE THREAD

**Issue by smackesey** [charliermarsh/ruff#1084]
I ran `ruff --fix` (with `D205` selected) to format our docstrings and it did this to docstrings with leading paragraphs:

```
### Before

def get_class_definitions(name: str, schema: dict) -> Dict[str, Dict[str, SchemaType]]:
    """
    Parses an Airbyte source or destination schema, turning it into a representation of the
    corresponding Python class structure - a dictionary mapping class names with the fields
    that the new classes should have.

### After

def get_class_definitions(name: str, schema: dict) -> Dict[str, Dict[str, SchemaType]]:
    """
    Parses an Airbyte source or destination schema, turning it into a representation of the

    corresponding Python class structure - a dictionary mapping class names with the fields
    that the new classes should have.
```

These leading paragraphs are indeed violations of Google style, where the summary is supposed to fit on one line. But I don't think the behavior of `--fix` here makes sense, as it assumes a multiline leading paragraph is really a one-line summary followed by a second paragraph, when in most cases it's probably just a paragraph.

**Comment by charliermarsh** [comment]
Yeah this has come up before, and I'm not happy with the current behavior. Not sure this should even be fixable because of false positives like this. Maybe if there's _more_ than one line between the summary and description? Or perhaps if the summary line appears on the first line? But that could still be a multi-line summary.

**Comment by smackesey** [comment]
IMO it should not be fixable. The only thing that would make sense to me is if the first line ends with a period, but that would still produce the occasional false positive.

**Comment by charliermarsh** [comment]
Yeah, what _can_ be safely fixed is this:

```py
def get_class_definitions(name: str, schema: dict) -> Dict[str, Dict[str, SchemaType]]:
    """
    Here's the summary line followed by two empty lines (instead of one).


    Parses an Airbyte source or destination schema, turning it into a representation of the
    corresponding Python class structure - a dictionary mapping class names with the fields
    that the new classes should have.
```

**Comment by smackesey** [comment]
To follow up on this-- we have many multiline docstring summaries, but would still like a variant of this rule to work. I realize that if the summary is on multiple lines, it can be hard to determine where it actually ends-- but have you considered detecting e.g. section starts, rst directives, or bulleted lists?

So this:

```
def foo():
"""Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque adipiscing faucibus
felis, ac ullamcorper nisl commodo ac. Etiam fermentum, urna nec viverra euismod, massa
 dui lobortis urna, ac porttitor elit nisl vel lacus. Suspendisse commodo sapien vel nibh aliquet semper. 
Args:
```

Becomes:

```
def foo():
"""Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque adipiscing faucibus
felis, ac ullamcorper nisl commodo ac. Etiam fermentum, urna nec viverra euismod, massa
 dui lobortis urna, ac porttitor elit nisl vel lacus. Suspendisse commodo sapien vel nibh aliquet semper. 

Args:
```
