### ISSUE TITLE
U00X rules ignoring target-version

### ISSUE THREAD

**Issue by bryevdv** [charliermarsh/ruff#1113]
ref: https://github.com/bokeh/bokeh/pull/12653#issuecomment-1331091295

With `target-version = "py38"` we were seeing errors with auto-fix diffs like:

```diff
-TypeOrInst: TypeAlias = Union[Type[T], T]
+TypeOrInst: TypeAlias = type[T] | T
 
-Init: TypeAlias = Union[T, UndefinedType, IntrinsicType]
+Init: TypeAlias = T | UndefinedType | IntrinsicType
```
but `type` is not usable as a replacement for `Type` until Python 3.9 (https://peps.python.org/pep-0585/)

**Comment by charliermarsh** [comment]
Very odd, will take a look!

**Comment by charliermarsh** [comment]
@bryevdv - Would you be open to a PR on Bokeh upgrading Ruff to latest? (The `U` prefix was changed to `UP` (backwards-compatible but shows a warning), and `M001` was moved to `RUF100`. Would be happy to upgrade you to insulate against the churn.)

**Comment by charliermarsh** [comment]
(Just closing since I believe this is fixed upstream, but do let me know if you want a free upgrade!)

**Comment by bryevdv** [comment]
Thanks for the offer @charliermarsh but we are going to pin and update at a slower intentional pace (probably monthly) 😄

**Comment by charliermarsh** [comment]
Sounds good. I’m always happy to help with version bumps so don’t hesitate to reach out! (The check code changes described above should be the only backwards-incompatible changes.)
