### ISSUE TITLE
[Question] Re-raising errors and BLE001

### ISSUE THREAD

**Issue by ThirVondukr** [charliermarsh/ruff#1119]
Not sure if this is the right place to ask since this is a check from flake8-blind-except, but:
Using this check is a bit hard in some cases without ignoring it, for example when we want to report an exception and explicitly re-raise it:
```py
try:
    return handler(request)
except Exception as e:
    sentry_sdk.capture_exception(e)
    raise
```

In my opinion catching `Exception` should be ok as long as you re-raise it 🤔

**Comment by charliermarsh** [comment]
Some discussion here about this being a good idea: https://github.com/PyCQA/flake8-bugbear/issues/174

**Comment by JonathanPlasse** [comment]
It has been implemented [here](https://github.com/Zac-HD/flake8-trio/blob/5072c7d9e4afa340b94ef98fa901afdd563cac65/flake8_trio.py#L606-L608).
We could use the same approach.

**Comment by charliermarsh** [comment]
Yeah I just didn't feel it was worth the complexity vs. the common case right now vs. some other things I need to get done. You're very welcome to work on it if you'd like, @JonathanPlasse!
