### ISSUE TITLE
Consider changing "consider" error messages

### ISSUE THREAD

**Issue by smackesey** [charliermarsh/ruff#1134]
Something about this doesn't feel right:

```
ruff --fix --extend-ignore=F401 .
Found 2 error(s).
python_modules/automation-internal/automation_internal/cloud/check/old_images.py:79:9: PLR1722 Consider using `sys.exit()`
python_modules/automation-internal/automation_internal/infra/terragrunt.py:318:5: PLR1722 Consider using `sys.exit()`
2 potentially fixable with the --fix option.
```

Why am I only supposed to "consider" fixing these but not all the other issues Ruff flags? Ruff exits with error code 1 if there are errors-- most users will use ruff in a context where they try to get 0, for which you have to fix or ignore these (same as for other errors). So IMO it should just say: `use sys.exit()`.

**Comment by charliermarsh** [comment]
Hah, I think we took this from [Pylint](https://pylint.pycqa.org/en/latest/user_guide/messages/refactor/consider-using-sys-exit.html), but yeah, agree.
