### ISSUE TITLE
feature-request: Create a recommended workaround for files with match statements

### ISSUE THREAD

**Issue by j-carson** [charliermarsh/ruff#1138]
Right now, if a file uses the match statement, you have to manually exclude the file from ruff in your environment. It would be better to have an official workaround, such as:

1. Ruff automatically falls back to running flake8 when the match statement is encountered 
2. Providing a way to mark one function as noqa, but still lint the rest of the file
3. Some other workaround I haven't thought of?

The goal is not to have to manually create an appropriate special treatment for each file that is not compatible and to still have some code-quality checks on the offending file

**Comment by charliermarsh** [comment]
We support `match` statements as of v0.0.250 -- so hopefully no longer an issue!
