### ISSUE TITLE
Erroneous F821 on classes with parameter type annotations

### ISSUE THREAD

**Issue by cjfuller** [charliermarsh/ruff#114]
If I run ruff on a file containing a class with a type annotation at class level, it incorrectly gives F821 (undefined name).

Examples:

```python

from dataclasses import dataclass


@dataclass
class Bad:
    x: int


@dataclass
class AlsoBad:
    x: int = 3


class StillBad:
    x: int

    def __init__(self):
        self.x = 3


class Ok:
    x = 3
```

Running `ruff <filename>` on this file gives:
```
ruff_test.py:6:5: F821 Undefined name `x`
ruff_test.py:11:5: F821 Undefined name `x`
ruff_test.py:15:5: F821 Undefined name `x`
```
(flake8 gives no errors)

Ruff version 0.0.28, python 3.8.13, ubuntu 22.04.1.

**Comment by cjfuller** [comment]
Actually I guess that this also happens with top-level definitions too:
```python
y: int = 4
```
also gives 
```
ruff_test.py:25:1: F821 Undefined name `y`
```

**Comment by charliermarsh** [comment]
I think I have to fix this in RustPython.
