### ISSUE TITLE
Pattern matching

### ISSUE THREAD

**Issue by jgsimard** [charliermarsh/ruff#1146]
Hi, 
do you plan to support pattern matching as introduced in 3.10 ? I get 

E999 SyntaxError: invalid syntax

Thanks

**Comment by charliermarsh** [comment]
Yeah I definitely plan on supporting it. It requires some big upgrades to the parser so hasn't happened yet, but it will.

**Comment by charliermarsh** [comment]
Closing as a duplicate of #282.
