### ISSUE TITLE
`F821 Undefined name` when definition is after usage

### ISSUE THREAD

**Issue by samuelcolvin** [charliermarsh/ruff#119]
Ruff looks great, congratulations. I'd love to use it one day on pydantic instead of flake8.

---

The following code is valid python and runs fine

```py
def main():
    foo()

def foo():
    print('this is foo')

main()
```

However ruff returns:

```
test.py:2:5: F821 Undefined name `foo`

Found 1 error(s).
```

Running ruff on pydantic's code base is currently returning 151 `F821` errors, so it's a fairly common problem.

**Comment by charliermarsh** [comment]
Thank you! Really flattered by the interest.

This is a legit bug. We have to defer checking function scopes until we've parsed the rest of the module. It's known but unhandled. Gonna use this issue for tracking.

**Comment by samuelcolvin** [comment]
great, thanks so much.
