### ISSUE TITLE
Suggestion: use PEP8-default max line length of 79

### ISSUE THREAD

**Issue by vytas7** [charliermarsh/ruff#1208]
Not really an issue _per se_ since the default of 88 is documented in README, but a discussion point.

Shouldn't `ruff` default to the same maximum line length of 79 as [specified in PEP8](https://peps.python.org/pep-0008/#maximum-line-length)?
Apart from just the sake of following PEP8, this makes `ruff` incompatible with `flake8` if using both with default settings.

**Comment by charliermarsh** [comment]
I do appreciate the suggestion but I opted for 88 for consistency with Black. I don't think there's really a right answer here (though I could document it).
