### ISSUE TITLE
Add a JSON schema for `ruff.toml`

### ISSUE THREAD

**Issue by charliermarsh** [charliermarsh/ruff#1217]
And submit it to https://github.com/SchemaStore/schemastore. That way, you'll get autocomplete in editors, etc.

**Comment by charliermarsh** [comment]
Yeah

**Comment by charliermarsh** [comment]
Note though that `ruff.toml` won't be drop-in identical to `pyproject.toml`. It'll be like [`hatch.toml`](https://hatch.pypa.io/latest/environment/) -- so, identical to `pyproject.toml`, but without `[tool.ruff]`.

**Comment by edgarrmondragon** [comment]
I've got a draft for this using https://github.com/GREsau/schemars :)
