### ISSUE TITLE
`exclude` and `extend-exclude` options seem ignored when running with pre-commit

### ISSUE THREAD

**Issue by WilliamJamieson** [charliermarsh/ruff#1220]
`ruff` is really awesome, and I have begun to use it in many of my projects as it is orders of magnitude faster than `flake8` and others like it.

In one of my projects I tried to add `ruff` to be run by pre-commit, see spacetelescope/jwst#7395. This project has a list of directories to be excluded listed in its `pyproject.toml` file. However, when running `ruff` via pre-commit `ruff` found errors in files within these excluded directories, despite trying both `exclude` and `extend-exclude` in the `pyproject.toml`. The only solution I found was to additionally exclude these directories in the `.pre-commit-config.yaml` for the `ruff` hook, which is not ideal.

Is this a user error or a bug in `ruff` (or its pre-commit hook)?

**Comment by charliermarsh** [comment]
Let me take a look...

**Comment by charliermarsh** [comment]
I think the problem is that `ruff` still checks files if they're passed directly, e.g.:

```
~/workspace/ruff on * main
∴ cargo run jwst/jwst/fits_generator/
    Finished dev [unoptimized + debuginfo] target(s) in 0.11s
     Running `target/debug/ruff jwst/jwst/fits_generator/`

~/workspace/ruff on * main
∴ cargo run jwst/jwst/fits_generator/main.py
    Finished dev [unoptimized + debuginfo] target(s) in 0.11s
     Running `target/debug/ruff jwst/jwst/fits_generator/main.py`
Found 3 error(s).
jwst/jwst/fits_generator/main.py:31:24: F401 `astropy.io.fits` imported but unused
jwst/jwst/fits_generator/main.py:115:17: E722 Do not use bare `except`
jwst/jwst/fits_generator/main.py:280:20: F401 `docutils` imported but unused
2 potentially fixable with the --fix option.
```

And the way pre-commit works is that it passes all changed files (IIRC) to the command directly.

I _think_ this is the same behavior as Black. If I add this to `pyproject.toml`:

```
[tool.black]
exclude = 'jwst/fits_generator'
```

Then I see:

```
∴ black jwst/fits_generator
No Python files are present to be formatted. Nothing to do 😴
~/workspace/ruff/jwst on * feature/pre-commit
∴ black jwst/fits_generator/generators.py
reformatted jwst/fits_generator/generators.py

All done! ✨ 🍰 ✨
1 file reformatted.
```

So not 100% sure how to resolve, need to look into the options...

**Comment by charliermarsh** [comment]
There's a workaround [here](https://github.com/psf/black/issues/438#issuecomment-424813931) that's discouraged but running Ruff over your codebase is fast enough that I personally think this is ok.

**Comment by charliermarsh** [comment]
Otherwise, I do think you have to duplicate the exclusions in the hook definition, like in the [Black example](https://github.com/psf/black/issues/438#issue-348511789):

```
repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
      exclude: migrations
```

**Comment by WilliamJamieson** [comment]
I know from experience with `black` in `astropy` that [`force-exclude`](https://github.com/astropy/astropy/blob/d31499bb3d4d4cf02981c9b7fdd35bc37c62ad54/pyproject.toml#L49-L63) does work as expected for `astropy`'s [`.pre-commit-config.yaml`](https://github.com/astropy/astropy/blob/d31499bb3d4d4cf02981c9b7fdd35bc37c62ad54/.pre-commit-config.yaml#L82-L85).

I don't think `ruff` has a `force-exclude` configuration option right now. However, that might be one way to handle this case.

**Comment by charliermarsh** [comment]
Oh cool. We could probably support that...

**Comment by charliermarsh** [comment]
I guess the downside of `force-exclude` (apart from added complexity / a thing to implement + support) is that you're kind of providing an escape hatch that goes against the intention of the tool ("ruff path/to/file should check file no matter what"), in order to workaround a limitation in another tool. But I do see the dilemma...

**Comment by WilliamJamieson** [comment]
> I guess the downside of `force-exclude` (apart from added complexity / a thing to implement + support) is that you're kind of providing an escape hatch that goes against the intention of the tool ("ruff path/to/file should check file no matter what"), in order to workaround a limitation in another tool. But I do see the dilemma...

One compromise to this issue would be to have a flag (`--no-exclude`?) which would prevent `ruff` from considering any of the set exclusion criteria.

I imagine the discussion in psf/black#438 and psf/black#1032 may shed light on why `force-exclude` maybe useful.

**Comment by egeres** [comment]
I had this issue because I was only adding `include` to the dirs I wanted to check. As @charliermarsh said, the pre-commit ignores that and feeds ruff with files that shouldn't. Adding an `exclude` list fixed this issue for me. So I went from this:

```toml
include = ["app/**/*.py", "tests/**/*.py", "examples/**/*.py"]
```

to this:

```toml
exclude = ["sketches/**"]
```
