### ISSUE TITLE
Removal of unused imports leads to syntax error

### ISSUE THREAD

**Issue by squiddy** [charliermarsh/ruff#1226]
See #1206 

Running `ruff --select F401 --fix` against

```python
x = 1; import sys
import os

if True:
    x = 1; import sys
    import os
```

produces

```

if True:

```

**Comment by charliermarsh** [comment]
:)

![Screen Shot 2022-12-12 at 10 51 48 PM](https://user-images.githubusercontent.com/1309177/207222204-bef48747-a94d-44dc-aab9-ec00f9fffa28.png)

**Comment by charliermarsh** [comment]
I feel like the `else` should be:

```rust
Ok(Fix::deletion(stmt.location, stmt.end_location.unwrap()))
```

...but... why didn't I do that in the first place?

**Comment by charliermarsh** [comment]
(At least, that logic does the right thing for the case above.)

**Comment by charliermarsh** [comment]
I'm guessing it's a formatting thing, the version above doesn't leave behind as many empty newlines. That's my guess at least. We should probably either do `Ok(Fix::deletion(stmt.location, stmt.end_location.unwrap()))` and accept the newlines (Black will clean them up), _or_ only do the above when the statement is the only statement on the line (which will require looking at the text content, probably).

**Comment by charliermarsh** [comment]
What do you think, @squiddy?

**Comment by squiddy** [comment]
I think I saw you mentioning that you plan for ruff to become a formatter itself. With that in mind, I'd slightly prefer accepting newlines over introspecting the line further. Let's have black (or humans) fix the newline issue and let ruff deal with it eventually.

The fix ideally can also handle this scenario:

```python
import sys; import bar
bar
```

Removing just the statement, based on its location, yields:

```
; import bar
bar
```

**Comment by charliermarsh** [comment]
(Is the latter invalid syntax? Or just undesirable?)

**Comment by squiddy** [comment]
Hehe, now I needed to check myself again. It is invalid.

**Comment by charliermarsh** [comment]
Ok cool :)

**Comment by charliermarsh** [comment]
I am working on this, it's just a bit tricky. But I think I've mostly figured out the rules.
