### ISSUE TITLE
`F401 imported but unused` when symbol is only used for type hints

### ISSUE THREAD

**Issue by amotl** [charliermarsh/ruff#123]
Hi Charlie,

maybe similar to #83, `ruff` also marks spots as "imported but unused", where the imported symbols are only used within type hints.

With kind regards,
Andreas.

#### Example
```python
import dataclasses
from datetime import datetime


@dataclasses.dataclass
class Message:
    message: str
    datetime: datetime
```

**Comment by charliermarsh** [comment]
Wow, this is really tricky, I think it's because the type hint is `datetime: datetime` (as opposed to something like `x: datetime`), so we were parsing the left-hand side first, then assumed `: datetime` was a reference to that left-hand side. Good catch :)

**Comment by amotl** [comment]
Oh wow, so I've catched that case accidentally ;]. Thank you for fixing it so quickly again!
