### ISSUE TITLE
"Unnecessary variable assignment before `return`" is too eager

### ISSUE THREAD

**Issue by DanCardin** [charliermarsh/ruff#1233]
Some minimal example:
```python
def foo():
    bar = 4
    x()
    return bar
```

`x()` arbitrary function call can have side-effects. This is a dirt simple example, but it's not hard to imagine sequences of statements which would mutate `bar`'s value between the assignment and the return, even if there aren't direct references to `bar` itself (which seems to be the current heuristic).

Thus, it seems to me to be too eager to flag this, so long as there are potentially side-effectful operations between the assignment and the `return`. and given that most operations can be side-effectful, really i guess this just means, I'm suggesting it should mostly be checking for sequential statements like so:

```
x = 4
return x
```

**Comment by charliermarsh** [comment]
I'm torn on this! Almost any statement can be side-effectful -- even something like `a = b + c` could actually involve operator overloading under-the-hood and thus make use of `bar`. So, I guess the suggestion is that we make this check much more conservative, and only flag when there are no expressions between the assignment and the return?

**Comment by charliermarsh** [comment]
Closing for now.
