### ISSUE TITLE
0.0.179 not on PyPI

### ISSUE THREAD

**Issue by g-as** [charliermarsh/ruff#1236]
Not a big deal, but I though I'd warn you in case there's a broken workflow somewhere.

**Comment by charliermarsh** [comment]
Very strange, thank you. For some reason the release creation didn't kick off the GitHub Action?

**Comment by charliermarsh** [comment]
Let me see if it resolves itself with [v0.0.180](https://github.com/charliermarsh/ruff/releases/tag/v0.0.180).

**Comment by charliermarsh** [comment]
Not sure what happened, maybe a GitHub error, but [v0.0.180](https://pypi.org/project/ruff/) is now up (which contains just one bug fix on top of v0.0.179).
