### ISSUE TITLE
Settings: Support the `ignore` option also within `pyproject.toml`

### ISSUE THREAD

**Issue by amotl** [charliermarsh/ruff#124]
Hi again,

after running into #119 as well, we tried to ignore `F821` by adding it to the `pyproject.toml` file within the `[tool.ruff]` section, like:
```
[tool.ruff]
ignore = ["F821"]
```

However, `ruff` complained with:
```
Failed to load pyproject.toml: unknown field `ignore`, expected one of `line-length`, `exclude`, `select` for key `tool.ruff` at line 199 column 1
```

It looks like the option, although being implemented within `settings.rs`, is currently only available as a command line option, to be used like `ruff --ignore=F821 .`. I think it would be sweet to be en par with `flake8` in this case, because `ignore` will probably be a popular option.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Other than that, I don't know if the program should fall back to a default configuration without further ado.
```
Falling back to default configuration...
```
At the first sight, the problem from the misconfiguration outlined above was not easy to spot, because the subsequent very large admonition output made the original error message scroll above the fold [^1].

Would making `ruff` fail hard be an option here?

[^1]: We are using `line-length = 120`, so the output was pretty huge.

**Comment by charliermarsh** [comment]
Good call, can definitely support this.

**Comment by amotl** [comment]
Thank you very much!
