### ISSUE TITLE
Support rules for flake8-datetimez

### ISSUE THREAD

**Issue by Yasu-umi** [charliermarsh/ruff#1249]
https://github.com/pjknkda/flake8-datetimez

I started impl at [here](https://github.com/Yasu-umi/ruff/tree/feature/flake8-datetimez).
I'll create pull req in this year, or should I create draft now ? I already implemented 1 / 9 rule.

Thanks for develop incredibly fast linter !

**Comment by charliermarsh** [comment]
Awesome. I’m happy to take a look whenever. We can merge before implementing the entire plugin, but it’d be good to have _most_ of the rules implemented first.

**Comment by charliermarsh** [comment]
Done by @Yasu-umi!

**Comment by sasanjac** [comment]
As the original flake8 plugin, this implementation also misses `.astimezone()`-calls on naive datetime objects. I implemented a fix (here)[https://github.com/pjknkda/flake8-datetimez/pull/10] but the project seems abandoned, so I'm going to fix it here instead.

**Comment by Kilo59** [comment]
@sasanjac did you ever end up implementing the `.astimezone()` for ruff?
Is there an issue or PR I can follow your progress and potentially help out?

**Comment by sasanjac** [comment]
Unfortunately, I haven't got around to it but I might tackle it later this month unless you want to have a go at it.
