### ISSUE TITLE
Implement the config options for flake8-unused-arguments

### ISSUE THREAD

**Issue by lovetox** [charliermarsh/ruff#1254]
Hi, this is very useful check but we cant use it because it detects **kwargs / *args as unused.
I believe its not necessary to mark this unsued vars, as bei convention **kwargs / *args is in most cases expected to not be used as it acts as a catch all.
I have to say i never seen a codebase that prefixes that with underscore.

i was not able to use any of the config options

i tried

```
[tool.ruff.flake8-unused-arguments]
unused-arguments-ignore-variadic-names = "true"
```

but no luck

**Comment by charliermarsh** [comment]
Yeah I can add that option. Are there others that are important to you right now?

**Comment by lovetox** [comment]
I would say `unused-arguments-ignore-variadic-names` is the most important

Did you implement everything from that package?

Because i see no errors on `overload-functions`, or `empty stub` functions currently, which i find ok, because it makes no sense to check those, i mean both have no implementation obviously no arg will be used.

Im not sure if you implement the checks on abstract methods and dunder, but if,i probably would like to disable them.

These 2 are probably less important:

unused-arguments-ignore-lambdas
unused-arguments-ignore-nested-functions

**Comment by charliermarsh** [comment]
Yes, we ignore overloaded and stub functions, and I think we ignore abstract methods when we can detect them (not always possible because we aren't doing deep static analysis, e.g., when extending a parent class). I'd have to review the code though.

**Comment by g-as** [comment]
@charliermarsh 

Are you sure that overloaded functions are ignored?

With
```python
import typing


@typing.overload
def concat(a: str, b: str) -> str:
    ...

@typing.overload
def concat(a: int, b: int) -> str:
    ...


def concat(a, b):
    return f"{a}{b}"
```
on latest *ruff* i'm getting
```
site_register/toto.py:5:12: ARG001 Unused function argument: `a`
site_register/toto.py:5:20: ARG001 Unused function argument: `b`
site_register/toto.py:9:12: ARG001 Unused function argument: `a`
site_register/toto.py:9:20: ARG001 Unused function argument: `b`
```

**Comment by charliermarsh** [comment]
Lemme check.

**Comment by charliermarsh** [comment]
I think I was mixing up unused arguments with missing type annotations.

**Comment by charliermarsh** [comment]
Tracking here: #1372.

**Comment by charliermarsh** [comment]
@g-as - Fixed in https://github.com/charliermarsh/ruff/pull/1373. Will cut a new release tonight, want to fix a few more things.
