### ISSUE TITLE
Feature request: autofixable check for `-> None` return of `__init__(self)` with no other arguments

### ISSUE THREAD

**Issue by thomkeh** [charliermarsh/ruff#1263]
mypy has this somewhat silly rule that you have to annotate an `__init__` that doesn't have any arguments beyond `self` with `-> None`: https://mypy.readthedocs.io/en/stable/class_basics.html#annotating-init-methods

It would be great if ruff could automatically fix this!

**Comment by charliermarsh** [comment]
Oh yeah, we can definitely do that. I think this would be considered an autofix of `ANN204`.

**Comment by charliermarsh** [comment]
Let me know if this works for you once the next release is out. You may also want to set:

```toml
[tool.ruff.flake8-annotations]
mypy-init-return = true
```

Otherwise, it'll _always_ add `-> None` to `__init__` (instead of only doing so when it has no typed arguments).

**Comment by thomkeh** [comment]
Will do!

**Comment by charliermarsh** [comment]
Should be live in [v0.0.184](https://github.com/charliermarsh/ruff/releases/tag/v0.0.184) :)
