### ISSUE TITLE
`# noqa` not respected in docstrings.

### ISSUE THREAD

**Issue by pawelrubin** [charliermarsh/ruff#1297]
The `# noqa` directive is not respected in docstrings.

### Steps to reproduce

Run `ruff` on the following snippet

```python
"""
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt # noqa
"""


def foo():
    """
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt # noqa
    """


class Bar:
    """
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt # noqa
    """
```

### Expected result
Since each line longer than 88 characters end with a `# noqa`, there should be no errors.

### Actual result
```
Found 3 error(s).
snippet.py:2:1: E501 Line too long (96 > 88 characters)
snippet.py:8:1: E501 Line too long (100 > 88 characters)
snippet.py:14:1: E501 Line too long (100 > 88 characters) 
```

**Comment by charliermarsh** [comment]
For multi-line strings, noqa comments are required to be placed on the closing line, rather than in the string body itself.

Can you try moving the noqa to just after the closing quotes, and report back?

**Comment by charliermarsh** [comment]
See the [README](https://github.com/charliermarsh/ruff#ignoring-errors) for an example, but let me know if you continue to see issues!

**Comment by pawelrubin** [comment]
Hi @charliermarsh. I missed the note in the README. Moving the `# noqa` directive to the closing quote solves the issue. Thank you for the quick response.
