### ISSUE TITLE
Support GitLab-compatible Code Climate output format

### ISSUE THREAD

**Issue by teucer** [charliermarsh/ruff#1298]
Is it possible to generate code climate json format? I would like to use it for GitLab code quality jobs.

**Comment by charliermarsh** [comment]
We can definitely support this (we already support `--format=github`, for GitHub Actions). Can you link me to any documentation on the format spec, to make sure I'm looking at the right thing?

**Comment by teucer** [comment]
[Here](https://docs.gitlab.com/ee/ci/testing/code_quality.html#implementing-a-custom-tool) and [here](https://github.com/codeclimate/platform/blob/master/spec/analyzers/SPEC.md#data-types)

**Comment by charliermarsh** [comment]
This just requires adding a new `SerializationFormat`, and implementing the format spec in `printer.rs#write_once`.
