### ISSUE TITLE
[feature-request] Environment variable interpolation for config paths

### ISSUE THREAD

**Issue by smackesey** [charliermarsh/ruff#1316]
Environment variable interpolation in certain config settings could be very useful, specifically in the `extend` field.

Our use case is that we have a second internal repo where we've had to maintain a copy in `pyproject.toml` of the config from our main repo. But ideally we could just do this:

```
[tool.ruff]
extend` = "${MAIN_REPO}/pyproject.toml"
# ... a few internal-specific settings
```

This becomes more useful the more repos you have.

**Comment by charliermarsh** [comment]
This seems pretty straightforward, do you know of / if other tools support this?

**Comment by charliermarsh** [comment]
It looks like Mypy does this: https://mypy.readthedocs.io/en/stable/config_file.html#confval-files

**Comment by charliermarsh** [comment]
Will add

**Comment by charliermarsh** [comment]
Starting with `extend` for expediency and simplicity, but let me know if you need this for other paths too.

**Comment by charliermarsh** [comment]
(`src` also supports this now.)

**Comment by smackesey** [comment]
Sweet-- just wanna say you're doing an a fantastic job building a great tool for teams working on monorepos (not to mention all the other great stuff about ruff). You've implemented basically everything on my wishlist to date.

I try to get the pyright maintainer (the other big tool we're going to be using) to implement a lot of this simple quality-of-life stuff but he rejects virtually every request and IMO pyright is consequently full of user-unfriendly APIs and blind-spots. In contrast you're typically knocking these out the day I raise them. Great job, this will help us a lot with Dagster when the transition PR merges. I'll definitely write a post on the Dagster blog about it.

**Comment by charliermarsh** [comment]
Thank you! Really happy to hear it. From my perspective, it's been super beneficial for _Ruff_ too to have all of your feedback and input, and I'm grateful for it. Your issues are always very thoughtful and well-communicated, and the work we're doing here will be a huge boon to other projects (especially monorepos) in the future.

> I'll definitely write a post on the Dagster blog about it.

This would be extremely cool, I would of course love to see that :)
