### ISSUE TITLE
[bug] Different import sorting rules in `ruff-lsp` and command line

### ISSUE THREAD

**Issue by smackesey** [charliermarsh/ruff#1319]
Sample case: file `python_modules/libraries/dagster-aws/dagster_aws/emr.py` in [Dagster](https://github.com/dagster-io/dagster). The language server does not recognize `dagster_aws` as first party, so it wants to do this:

```
# notice `dagster_aws` grouped with third-party imports
import boto3
import dagster
import dagster._check as check
from botocore.exceptions import WaiterError
from dagster_aws.utils.mrjob.utils import _boto3_now, _wrap_aws_client, strip_microseconds
```

Same result doing this:

```
$ cat python_modules/libraries/dagster-aws/dagster_aws/emr/emr.py | ruff --select=I001 --stdin-filename python_modules/libraries/dagster-aws/dagster_aws/emr/emr.py -
```

But command line `$ ruff .` from the repo root gives correct behavior of auto-detect of first-party package:

```
# `dagster_aws` correctly given first-party status
import boto3
import dagster
import dagster._check as check
from botocore.exceptions import WaiterError

from dagster_aws.utils.mrjob.utils import _boto3_now, _wrap_aws_client, strip_microseconds
```

**Comment by charliermarsh** [comment]
What's the right branch to test from?

**Comment by charliermarsh** [comment]
Ah, yeah, this is an oversight. Will fix.

**Comment by smackesey** [comment]
`sean/ruff` if you still need a branch

**Comment by charliermarsh** [comment]
(Just forgot to thread through the `__init__.py` in the stdin case.)

**Comment by charliermarsh** [comment]
Will cut another release tonight to include this.
