### ISSUE TITLE
[feature-request] `required-version` option

### ISSUE THREAD

**Issue by smackesey** [charliermarsh/ruff#1331]
Black has a nice little option called `required-version`:

```
  --required-version TEXT         Require a specific version of Black to be
                                  running (useful for unifying results across
                                  many environments e.g. with a pyproject.toml
                                  file). It can be either a major version
                                  number or an exact version.
```

This is really useful for scenarios where black has been bumped but not all developers have updated their environments. It would be good for ruff to have a similar option (settable in config file and CLI) to help keep teams in sync.

**Comment by charliermarsh** [comment]
Cool, easy enough!

**Comment by charliermarsh** [comment]
(This can probably go out today.)

**Comment by charliermarsh** [comment]
Ok, took me a bit to get to this :)
