### ISSUE TITLE
Support for docformatter rules

### ISSUE THREAD

**Issue by cpcloud** [charliermarsh/ruff#1335]
We [just moved our linting setup over to ruff](https://github.com/ibis-project/ibis/pull/5057) and it's great!

It would be amazing if we could remove our [`docformatter`](https://github.com/PyCQA/docformatter) dependency as well in favor of `ruff`.

**Comment by charliermarsh** [comment]
Awesome :)

Yeah I've used `docformatter` in the past, it's great! I wonder how much of its functionality is covered by our `pydocstyle` support with autofix enabled. I'd need to do a full audit... But I'd definitely _like_ Ruff to be a full replacement for `docformatter` in that sense.

**Comment by charliermarsh** [comment]
Okay cool! (Note that some of the `D` rules are conflicting, like "No blank line before class" vs. "One blank line before class", since we support a couple different docstring conventions: https://github.com/charliermarsh/ruff#does-ruff-support-numpy--or-google-style-docstrings)

**Comment by cpcloud** [comment]
Yeah, the list of ignores I'm using for that category of lints is ... long.

**Comment by charliermarsh** [comment]
It might be easier to explicitly enable via `--select` if you want? I can post the list here if you post your ignores (and I could add it to the docs).

**Comment by cpcloud** [comment]
It's actually not too bad:

```
ignore = [
  "E501",
  "PGH003",
  "RET504",
  "RET505",
  "RET506",
  "RET507",
  "RET508",
  "D100", # public module
  "D101", # public class
  "D102", # public method
  "D103", # public function
  "D105", # magic methods
  "D107", # init
  "D202", # blank lines after function docstring
  "D203", # blank line before class docstring
  "D205", # blank line between summary line and description
  "D213", # Multi-line docstring summary should start at the second line
  "D402", # First line should not be the function's signature
  "D417", # Missing argument descriptions
]
```

**Comment by cpcloud** [comment]
And then of course this bit:

```
[tool.ruff.per-file-ignores]
"*test*.py" = ["D"] # ignore all docstring lints in tests
```

**Comment by charliermarsh** [comment]
Ah okay yeah, in that case it's more concise to specify the ignores than the selects, which would be like:

```toml
select = [
  "D104",
  "D106",
  "D200",
  "D201",
  "D204",
  "D206",
  "D207",
  "D208",
  "D209",
  "D210",
  "D211",
  "D212",
  "D214",
  "D215",
  "D300",
  "D301",
  "D400",
  "D403",
  "D404",
  "D405",
  "D406",
  "D407",
  "D408",
  "D409",
  "D410",
  "D411",
  "D412",
  "D413",
  "D414",
  "D415",
  "D416",
  "D418",
  "D419",
]
```

**Comment by charliermarsh** [comment]
Closing for now since I think we actually have good coverage here.
