### ISSUE TITLE
Cannot select specific flake8-errmsg checks

### ISSUE THREAD

**Issue by rhkleijn** [charliermarsh/ruff#1347]
In my project I want to enable EM102 and EM103 from flake8-errmsg, but not EM101.

However, enabling any of the flake8-errmsg checks seems to enable all of them.

For example, both
```bash
$ echo "raise Exception('a string literal')" | ruff - --select EM --ignore EM101
```
and
```bash
$ echo "raise Exception('a string literal')" | ruff - --select EM102,EM103
```
also enable the EM101 check:
```bash
-:1:17: EM101 Exception must not use a string literal, assign to variable first
```

**Comment by charliermarsh** [comment]
Ah yeah that's a legitimate oversight. Will fix this today (but not right now, gotta run).

**Comment by charliermarsh** [comment]
Ok I lied, I fixed it. It will go out in the next release.
