### ISSUE TITLE
Option to enable all lints

### ISSUE THREAD

**Issue by bluetech** [charliermarsh/ruff#1357]
My preferred usage is to enable all lints, then `extend-ignore` the ones I don't want with a comment. (This strategy only makes sense if using a pinned version of ruff).

Currently to enable all available lints, I list all of the prefixes in `extend-select`, but that's a bit long and won't catch any new prefixes if/when they become available.

I tried `extend-select = [""]` (empty string being a prefix of everything), but it's not accepted.

Maybe there's a way to do this that I missed?

**Comment by charliermarsh** [comment]
Not possible right now! But it’s definitely a reasonable request. I need to think on what the API should look like…

**Comment by charliermarsh** [comment]
I'm considering adding the special code `ALL` to signal this, like `ruff --select ALL /path/to/file.py`.

**Comment by bluetech** [comment]
`ALL` sounds good I think.

The docs say

> When breaking ties between enabled and disabled checks (via select and ignore, respectively), more specific prefixes override less specific prefixes.

So `ALL` would be treated as least specific right?

**Comment by charliermarsh** [comment]
Yeah, it would probably be special-cased to be less specific.

**Comment by fredrikaverpil** [comment]
This feature is 🔥🔥🔥
Thank you!!!
