### ISSUE TITLE
Improve B025 location

### ISSUE THREAD

**Issue by harupy** [charliermarsh/ruff#1359]
### Current

![image](https://user-images.githubusercontent.com/17039389/209443467-d1c72776-e8e9-47db-a327-24d25b7878e9.png)

- B025 is raised against the try statement
- Difficult to identify duplicate locations

### Proposed

![image](https://user-images.githubusercontent.com/17039389/209443473-f6d83ba3-6378-46d4-9cdd-338ff7e3ab32.png)

- B025 is raised against each duplicate
- Easy to identify duplicate locations

**Comment by harupy** [comment]
Happy to file a PR if the proposal sounds reasonable.

**Comment by charliermarsh** [comment]
Sounds good to me!
