### ISSUE TITLE
pre-commit hook does not consider configuration in pyproject.toml.

### ISSUE THREAD

**Issue by amirnaeimi** [charliermarsh/ruff#136]
I have tested pre-commit hook and it works fine but when I tried to implement a new configuration in ```pyproject.toml```, I realized it does not consider the configuration. 
```
[tool.ruff]
line-length = 200
ignore = ['E501', 'F841']
```
I still get the error E501 even though I have ignored it.
![Screenshot from 2022-09-09 23-50-25](https://user-images.githubusercontent.com/56680993/189450730-1d9d7f60-6cae-40c6-8c7a-24028ccd7c88.png)

**Comment by charliermarsh** [comment]
Thanks! Are there pyproject files in any of the subdirectories that are being linted?

**Comment by amirnaeimi** [comment]
Nope :) it's in root project!

**Comment by charliermarsh** [comment]
I think this may have been solved by some of the recent fixes to pathing. Please let me know if you continue to see it.

**Comment by amirnaeimi** [comment]
@charliermarsh thanks for the fix :100:
