### ISSUE TITLE
B010 not required by ruff, but is required by flake8 bugbear.

### ISSUE THREAD

**Issue by ghuls** [charliermarsh/ruff#1362]
```
# If # noqa: B010 is not set.
$ flake8 test_B010.py
test_B010.py:7:5: B010 Do not call setattr with a constant attribute value, it is not any safer than normal property access.

$ ruff test_B010.py

$ ruff --extend-select RUF100 test_B010.py
test_B010.py:7:75: RUF100 Unused `noqa` directive for: B010
Found 1 error(s).
1 potentially fixable with the --fix option.
```

```python
$ cat test_B010.py 
def test():
    def local_func(self):
        return self

    setattr(local_func, "__comment_section__", "Local function comment")  # noqa: B010
    return local_func
```

**Comment by charliermarsh** [comment]
Thanks! Will fix.

**Comment by charliermarsh** [comment]
This actually looks right to me -- are you enabling the `B` checks? They're not enabled by default (only `E` and `F`).

<img width="868" alt="Screen Shot 2022-12-24 at 1 45 41 PM" src="https://user-images.githubusercontent.com/1309177/209447987-57cd0db7-3071-4d60-b883-0f6683eee90e.png">

**Comment by ghuls** [comment]
> This actually looks right to me -- are you enabling the `B` checks? They're not enabled by default (only `E` and `F`).

Ah, I didn't know this. The warning message gave me the impression that it was enabled.

**Comment by charliermarsh** [comment]
Yeah, I can improve the message there.

**Comment by charliermarsh** [comment]
Tracking here: https://github.com/charliermarsh/ruff/issues/1364.
