### ISSUE TITLE
`F401 imported but unused` for imports used in forward reference type hints

### ISSUE THREAD

**Issue by nikolaik** [charliermarsh/ruff#139]
Similar to #123 but not quite.

Using the technique described in https://docs.python.org/3/library/typing.html#typing.TYPE_CHECKING

```python
if TYPE_CHECKING:
    from .models import Fruit. # F401 `models.Fruit` imported but unused 

def is_editable(fruit: 'Fruit'):
    fruit.is_editable()

**Comment by charliermarsh** [comment]
This seems to work for me, do you know what version you're on? Is this the exact code snippet that trips an error?

**Comment by nikolaik** [comment]
I tried reducing the example to a minimum, but I removed too much. Sorry about that. The actual issue seems to appear when [type aliases](https://docs.python.org/3/library/typing.html#type-aliases) references forward references.

```python
# ruffies.py:
from typing import Union, TYPE_CHECKING

if TYPE_CHECKING:
    from models import Fruit, Nut

Edibles = Union['Fruit','Nut']

def is_editable(fruit: Edibles):
    fruit.is_edible()
```
gives
```console
$ ruff ruffies.py
ruffies.py:4:5: F401 `models.Nut` imported but unused
ruffies.py:4:5: F401 `models.Fruit` imported but unused

Found 2 error(s).
```

**Comment by charliermarsh** [comment]
Ah thanks, this makes sense!

**Comment by charliermarsh** [comment]
The fix here is that we need to take into account `Union` and other typing structures.
