### ISSUE TITLE
[playground, bug] Autofix doesn't work on the playground

### ISSUE THREAD

**Issue by Sawbez** [charliermarsh/ruff#1392]
As seen in this image, the online playground doesn't allow you to quickfix `F401`, which has an autofix programmed in. None of the sidebar settings are changed.
![image](https://user-images.githubusercontent.com/63512091/209580466-13c99fc9-41f2-430d-98e7-0df75c3b3c8a.png)
Testing with other different categories (`W292`, `I001`) provides a similar result.

The original code is:
```python
import sys
import os

print(os.listdir())
```

**Comment by charliermarsh** [comment]
You're too fast, the playground isn't ready for primetime!
