### ISSUE TITLE
Publish README via mdBook

### ISSUE THREAD

**Issue by ischaojie** [charliermarsh/ruff#1398]
Currently, the README file so long to tired to read, Maybe can create specialized docs' Dir (Using mkdocs or some others).

**Comment by charliermarsh** [comment]
Just publishes their README via mdBook: https://just.systems/man/en/. I think this alone could be useful for us maybe. And would probably only take an hour or so to hook up...

See: https://github.com/casey/just/blob/master/bin/generate-book/src/main.rs.

**Comment by ischaojie** [comment]
Woo, that is amazing. But I worry that as more and more instructions are added to the README file, it will become difficult to maintain, although it is easy to generate a book.

**Comment by ischaojie** [comment]
I notice that `ruff` intends to use `mkdocs` to build the documentation, but it looks like it just moves the entire README file to the `docs` folder. For a better reading experience, it would be nice to have a script that splits the README into multiple chapter files (or a one-off, with subsequent updates made directly under docs). If possible I would create a pull request for this purpose.

**Comment by charliermarsh** [comment]
Yeah I'm gonna split it up.

**Comment by charliermarsh** [comment]
It'll come soon :)

**Comment by charliermarsh** [comment]
We're now live at https://beta.ruff.rs/docs/.
