### ISSUE TITLE
Allow users to select what version of pyupgrade they want to use

### ISSUE THREAD

**Issue by colin99d** [charliermarsh/ruff#1419]
Pyupgrade allows users to select which version of python to lint until. This functionality will be CRITICAL for anyone who wants to use Ruff, while keeping backwards compatibility. Would love to flesh out implementation fully, and the I can work on it once #827 is complete.

**Comment by charliermarsh** [comment]
I believe we support this via the [`target-version`](https://github.com/charliermarsh/ruff#target-version) setting, but let me know if I'm misunderstanding!

**Comment by charliermarsh** [comment]
(Closing but just let me know if I've misunderstood.)

**Comment by colin99d** [comment]
I know I havent been adding this functionality into my PRs? Do I need to just add a target_version requirement to them?

**Comment by charliermarsh** [comment]
We don't support versions before 3.7, so anything that's marked as 3.7+ doesn't need this logic. But otherwise, you can look at the LRU cache (3.8+) case as an example:

```rust
if self.settings.enabled.contains(&CheckCode::UP011)
    && self.settings.target_version >= PythonVersion::Py38
{
    pyupgrade::plugins::unnecessary_lru_cache_params(self, decorator_list);
}
```

**Comment by colin99d** [comment]
Oh, perfect! I definitely missed this. Thanks for explaining it to me.
