### ISSUE TITLE
[Question] Is there autofix for E501 and how do I turn it on?

### ISSUE THREAD

**Issue by simkimsia** [charliermarsh/ruff#1421]
i'm one of your latest stars after you hit 4k.

So I'm a newbie.

I have searched in the issue before posting this.

I know you labelled E501 as not autofix in the readme file. 

I was wondering if this means there is autofix but it's not turned on, OR there isn't autofix at all?

If there isn't what's your recommended for the autofix for format on save? i'm using vscode.

Thank you

**Comment by ThirVondukr** [comment]
If it's not labeled as auto-fixable in readme then it's not (at least currently), I personally run black, isort and then ruff

**Comment by simkimsia** [comment]
@ThirVondukr why still need isort when it's already autofix? https://github.com/charliermarsh/ruff#isort-i

**Comment by ThirVondukr** [comment]
@simkimsia Isort and ruff didn't/don't produce identical results

**Comment by charliermarsh** [comment]
Welcome!

E501 isn't autofixable right now. It will be in the future, in some cases, but that requires implementing a full autoformatter.

If you want to use Ruff with Black (such that Ruff handles lint errors, and Black handles formatting), you could try this configuration:

```json
{
    "[python]": {
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.fixAll": true
        }
    },
    "python.formatting.provider": "black"
}
```
