### ISSUE TITLE
Multiple "Found n error(s)" in pre-commit

### ISSUE THREAD

**Issue by JadHADDAD92** [charliermarsh/ruff#1423]
I ran the pre-commit on all files and I noticed that the result is reported in a fractionated manner as shown in the image below
![SCR-20221228-j6g](https://user-images.githubusercontent.com/27054843/209815644-7edbc0eb-ab09-42d1-b9ed-72ee0aa690f0.png)
I was expecting an overall result at the end with the total number of errors found.

Is this an expected behaviour? I can't seem to get the pattern of when the result is displayed, it's not per module, nor per rule 🤷‍♂️ 

ruff version: v0.0.198

**Comment by charliermarsh** [comment]
Ah, I think we need to set `require_serial: true` in the hook. I added that, but the mirror-maker seems to have ignored or reverted it. Will find a way to fix.

**Comment by charliermarsh** [comment]
(To be clear, user error on my part, not the mirror-maker's fault.)

**Comment by charliermarsh** [comment]
Ok, this should be fixed in the next release.
