### ISSUE TITLE
[feature-request] Support dry run for --fix via --diff flag

### ISSUE THREAD

**Issue by salmiakki** [charliermarsh/ruff#1430]
It's scary to apply automatic fixes before taking a look at them.

It would be nice to have a dry run option (`--dry-run`?) that outputs the patch to stdout.

**Comment by charliermarsh** [comment]
Yeah that could be useful. I'm not sure what the right output format would be. Write the changed files to disk as `.bak` or `.tmp` variants? Just dump the patches to stdout?

As an aside: ESLint has [`--fix-dry-run`](https://eslint.org/docs/latest/user-guide/command-line-interface#--fix-dry-run), but it just disables writing the fixes to disk. If you want to get the fixes without writing them, you have to specify `--format json`, to get the fixes in JSON format. I find this a bit clearer than what we do today (always write to disk if `--fix` is set, but generate fixes if `--fix` is not set and `--format json` is set).

**Comment by charliermarsh** [comment]
Can you think of other tools that implement this kind of thing, and how they handle it?

**Comment by salmiakki** [comment]
Definitely diff to stdout.

Maybe printing the whole file in addition to the diff could be useful as well. Other than that I can't really see myself using anything else.

***

For prior art:

`black` has 

```
  --diff                          Don't write the files back, just output a
                                  diff for each file on stdout.
```

`goftm` has

```
-d
	Do not print reformatted sources to standard output.
	If a file's formatting is different than gofmt's, print diffs
	to standard output.
```

**Comment by rhkleijn** [comment]
isort also has `--diff`
See https://pycqa.github.io/isort/docs/configuration/options.html#show-diff

**Comment by charliermarsh** [comment]
Ok cool, we’ll call it diff and print to stdout (one diff per changed file).

**Comment by salmiakki** [comment]
@charliermarsh Are you for real? This is insane. Thanks!

**Comment by charliermarsh** [comment]
Haha :) It's a good idea! You're welcome!

This'll go out in the next release, later tonight. Would love to hear if it works for you (or doesn't!).
