### ISSUE TITLE
Add a flag for disabling the update check or make it opt-in

### ISSUE THREAD

**Issue by stinos** [charliermarsh/ruff#1437]
Something like `--no-update-check`. It's fairly uncommon for a commanline tool to have an update check, let alone one which is activated depending on log level and cannot be disabled (or I'm missing something, also possible). Alternative: don't do the update check by default but on demand only.

**Comment by bluetech** [comment]
`-q` disables the update check entirely (including the network call).

https://github.com/charliermarsh/ruff/blob/058ee8e6bf6ce482b8ac7423049fe3b9cc9e80a0/src/main_native.rs#L271-L275

**Comment by not-my-profile** [comment]
I don't think ruff should by default check for updates secretly in the background every time you run it ... that very much breaks the user expectations for a command-line tool. I think it would be better to just add some stderr output to `-V` / `--version` like:

```
You can check if a new version is available at https://pypi.org/project/ruff/.

To update ruff via pip run:

    pip install ruff --upgrade
```

**Comment by stinos** [comment]
> `-q` disables the update check entirely (including the network call).

I'm aware. But `-q` also means no output so one cnnot have verbose output and no update check. I'm actually not quite sure what the rationale is behind tying update on/off to log level.

**Comment by charliermarsh** [comment]
Sure, we can add a setting to disable this.

**Comment by charliermarsh** [comment]
(Typing the update to log level is a side effect of the log level goal: show the check violations, and no other output.)

**Comment by charliermarsh** [comment]
Going out in [v0.0.200](https://github.com/charliermarsh/ruff/releases/tag/v0.0.200).

**Comment by bluetech** [comment]
Congratulations on 200 releases! Ruff is really terrific.

**Comment by charliermarsh** [comment]
@bluetech - Thank you so much! That means a lot. I love hearing it :)

**Comment by stinos** [comment]
> Going out in v0.0.200.

Ok that was quick, thanks!!
