### ISSUE TITLE
Subsequent runs with --diff give no result

### ISSUE THREAD

**Issue by rhkleijn** [charliermarsh/ruff#1439]
I tried the new `--diff` functionality from #1430 / #1431 and found that it works nicely on the first run, but subsequent runs give no result.
To reproduce:

```bash
$ echo "import os" > main.py
$ ruff main.py --diff
```
gives this output
```
--- main.py
+++ main.py
@@ -1 +0,0 @@
-import os

Would fix 1 error(s).
```
as expected.

But this second call produces no output:
```bash
$ ruff main.py --diff
```

When I manually remove `.ruff-cache` it works again on the next run. I am not familiar with ruff's internals but it might be some interaction with caching.

**Comment by charliermarsh** [comment]
Ah yeah, this makes sense. Will fix.

**Comment by charliermarsh** [comment]
For now you can run with -n to disable the cache. (It shouldn’t be noticeably slower unless you have an enormous codebase.)

**Comment by charliermarsh** [comment]
Going out in [v0.0.200](https://github.com/charliermarsh/ruff/releases/tag/v0.0.200).
