### ISSUE TITLE
Feature Request: Ruff doesn't support expanding star imports

### ISSUE THREAD

**Issue by code-yeongyu** [charliermarsh/ruff#1459]
I would like to say first that I feel amazing about your product and think it's super awesome and useful. I was surprised by the speed of Ruff and cannot go back to the past without using it.

I noticed that Ruff does not currently support the option to expand star imports. This feature is mentioned in the benchmark code that compares Ruff with autoflake. It would be great if this feature could be added to Ruff in the future.

Thanks.

**Comment by charliermarsh** [comment]
Thank you, that's awesome to hear :)

**Comment by charliermarsh** [comment]
I agree, we should support this.

It looks like `autoflake` only allow this when you have a single star import (and it basically just imports everything that's undefined from that module). We should be able to support that behavior. It'd be nice to do even better (e.g., detect which module each undefined name came from)... but parity is not too hard.

**Comment by charliermarsh** [comment]
On further reflection, I'd like to pass on this one for now. I understand why it's useful, but the rate of false positives seems really high given the autoflake strategy.
