### ISSUE TITLE
Add autofix for "unused variable"

### ISSUE THREAD

**Issue by charliermarsh** [charliermarsh/ruff#1460]
To start, we can just mimic `autoflake`, whose logic is relatively simple: https://github.com/PyCQA/autoflake/blob/60eeb31082bf5290341e84a008d5c832fb04fd13/autoflake.py#L664.

**Comment by charliermarsh** [comment]
(Not "trivial" but could be a good first issue if anyone's interested given that the `autoflake` logic can mostly be ported over.)

**Comment by beci** [comment]
I would take it!
