### ISSUE TITLE
Implement `flake8-implicit-str-concat`

### ISSUE THREAD

**Issue by pradyunsg** [charliermarsh/ruff#1461]
👋🏽 

- [ ] [error code TBD] implicitly concatenated string literals on one line
- [ ] [error code TBD] implicitly concatenated string literals over continuation line
- [ ] [error code TBD] explicitly concatenated string should be implicitly concatenated

I was looking at integrating `ruff` into pip's linting pipeline, and noticed that the specific flake8 plugins that we use aren't implemented already. This specific one is useful to flag when black reformats strings to implicitly concat by reflowing lines.

**Comment by charliermarsh** [comment]
Hey, really cool to see you interested in Ruff! I've read a lot of your comments on the Python forums 🙈 

Happy to implement this, looks relatively straightforward assuming there are no relevant / subtle differences in the tokenization.

**Comment by charliermarsh** [comment]
Yeah I can almost certainly ship this tomorrow if not tonight. (Probably not tonight, gotta log off soon.)

**Comment by charliermarsh** [comment]
Ok, I was just kidding, I implemented it in #1463, so it'll go out tonight in the end-of-day release.

**Comment by charliermarsh** [comment]
I used the same codes as the originating plugin (`ISC001`, `ISC002`, and `ISC003`). That plugin doesn't seem to have any tests, so I wrote a small suite, but would appreciate any feedback on bugs or incompatibilities.

**Comment by pradyunsg** [comment]
Wow, I wasn't expecting this to be closed by the time I woke up.

> Ok, I was just kidding, I implemented it in #1463, so it'll go out tonight in the end-of-day release.

No kidding, I really appreciate your expedient response here!

> I've read a lot of your comments on the Python forums 🙈

🙈

> Hey, really cool to see you interested in Ruff!

You've built a really cool thing, standing on the shoulders of really cool projects (am thinking of Rust _and_ RustPython here). :)

I'm excited to see the slowest linter in our setup get replaced with something that nearly finishes in the time Python takes to startup!

> That plugin doesn't seem to have any tests, so I wrote a small suite, but would appreciate any feedback on bugs or incompatibilities.

Definitely! Taking a look at the PR, that looks about right. I'll give it a drive after my work day, and let you know how that goes! :)

**Comment by pradyunsg** [comment]
TIL expedient doesn't mean what I thought it did.
