### ISSUE TITLE
Generate a man page for the `ruff` CLI

### ISSUE THREAD

**Issue by not-my-profile** [charliermarsh/ruff#1470]
Ruff is already packaged for several Linux distributions and command-line tools on Linux are traditionally documented in man pages.

Compared to `--help` the man page could explain how the CLI works in more detail e.g. which checks are enabled by default, that you can select checks by the prefixes of their codes, an overview of which prefixes are available, etc.

**Comment by squiddy** [comment]
One option could be to use https://docs.rs/clap_mangen/latest/clap_mangen/ as a base for that manpage.

Additionally, `clap_mangen` will use the input of [`Command.after_help`](https://docs.rs/clap/latest/clap/builder/struct.Command.html#method.after_help) in the `EXTRA` section.

```rust
Command::new("myprog")
    .after_help("Does really amazing things for great people... but be careful with -R!")
```

**Comment by not-my-profile** [comment]
Closing this in favor of our subcommand help approach (`ruff rule` #2288, `ruff linter` #2294, `ruff config` #2775).
