### ISSUE TITLE
Lint `pyproject.toml` according to the 'Declaring project metadata' spec

### ISSUE THREAD

**Issue by not-my-profile** [charliermarsh/ruff#1472]
[Declaring project metadata](https://packaging.python.org/en/latest/specifications/declaring-project-metadata/) (based on [PEP 621](https://peps.python.org/pep-0621/)) defines how metadata in `pyproject.toml` should be defined. Unless I am missing something there doesn't appear to be an existing lint plugin we could model this after, which would make this a RUF check.

This is basically the same idea as rust-lang/rust-clippy/issues/6431 but for Python/pyproject.toml/ruff instead of Rust/Cargo.toml/clippy.

Sidenote: Maybe we want to use [pyproject-toml-rs](https://github.com/PyO3/pyproject-toml-rs) for the parsing step?

**Comment by charliermarsh** [comment]
(I know there's [`validate-pyproject`](https://github.com/abravalheri/validate-pyproject) but it may not be relevant at all, I haven't looked closely.)

**Comment by not-my-profile** [comment]
Oh, yes I did miss that ... it does appear to be relevant. Although our checks could probably be more in-depth.

**Comment by charliermarsh** [comment]
(I really haven't looked at that project at all, it was just the first thing that came to mind, maybe unhelpful...)

**Comment by JonathanPlasse** [comment]
There is also taplo that is more general and validates schéma.

**Comment by JonathanPlasse** [comment]
- Does #4496 close this issue?
