### ISSUE TITLE
Fixing I001 turns file with CRLF line endings into mixed line endings

### ISSUE THREAD

**Issue by rhkleijn** [charliermarsh/ruff#1477]
When fixing `I001` import related lint errors the fix introduces `\n` line endings even if the file originally was `\r\n` only. (On windows  `\r\n` line endings are widely used.)

To reproduce:
```bash
$ echo -e -n '"""A file with CRLF line endings."""\r\nimport sys\r\nimport os\r\n' > crlf.py

$ python -c "from pathlib import Path;print(Path('crlf.py').read_bytes())"
b'"""A file with CRLF line endings."""\r\nimport sys\r\nimport os\r\n'

$ ruff crlf.py --select I001 --fix
Found 1 error(s) (1 fixed, 0 remaining).

$ python -c "from pathlib import Path;print(Path('crlf.py').read_bytes())"
b'"""A file with CRLF line endings."""\r\nimport os\nimport sys\n'
```

The last output contains mixed `\r\n` and `\n` line endings. 
It results e.g. in `pylint` subsequently complaining about [mixed-line-endings / C0327](https://pylint.pycqa.org/en/latest/user_guide/messages/convention/mixed-line-endings.html).

If the original file consistently uses a single line ending convention it would be nice if the fix would adhere to the same convention.

**Comment by charliermarsh** [comment]
Thanks. We should be able to fix this.

**Comment by squiddy** [comment]
I'm looking into this.
