### ISSUE TITLE
Fixing I001 in file with Cr Lf line endings fails after 100 iterations

### ISSUE THREAD

**Issue by rhkleijn** [charliermarsh/ruff#1490]
With `ruff 0.0.203` the reproducer from #1477 now results in a loop, and the `I001` linting error ends up not being fixed.

```
$ echo -e -n '"""A file with CRLF line endings."""\r\nimport sys\r\nimport os\r\n' > crlf.py

$ python -c "from pathlib import Path;print(Path('crlf.py').read_bytes())"
b'"""A file with CRLF line endings."""\r\nimport sys\r\nimport os\r\n'

$ ruff crlf.py --select I001 --fix

warning: Failed to converge after 100 iterations.

This likely indicates a bug in `ruff`. If you could open an issue at:

https://github.com/charliermarsh/ruff/issues

quoting the contents of `crlf.py`, along with the `pyproject.toml` settings and executed command, we'd be very appreciative!

crlf.py:2:1: I001 Import block is un-sorted or un-formatted
Found 101 error(s) (100 fixed, 1 remaining).
```

**Comment by charliermarsh** [comment]
\cc @squiddy

**Comment by charliermarsh** [comment]
I'm wondering (though hard for me to iterate and test) if this is also the cause of the [CI failure](https://github.com/charliermarsh/ruff-lsp/actions/runs/3810657619/jobs/6482868822) I'm seeing in `ruff-lsp`.

**Comment by charliermarsh** [comment]
It does seem to be the case: https://github.com/charliermarsh/ruff-lsp/actions/runs/3810683049/jobs/6482911720.

**Comment by charliermarsh** [comment]
I'll try to figure out how to reproduce this in the morning. I don't have access to a windows machine so it's a little tricky.

**Comment by squiddy** [comment]
Very sorry about that. It's morning here so I'm having a look.

**Comment by squiddy** [comment]
Found the culprit. `isort::plugins::check_imports` does a check whether the sorting of imports yielded any difference. The implementation of `dedent` uses `\n` which always results in a difference, so ruff always supports an issue that needs fixing.

Example: a properly sorted file is still continously fixed:

`echo -e -n 'import os\r\nimport sys\r\n' | cargo run -- - --select I001 --fix`

I'll prepare a fix.
