### ISSUE TITLE
Move away from blackd in favor of single black invocations

### ISSUE THREAD

**Issue by squiddy** [charliermarsh/ruff#1511]
See black_compatibility_test.

> Ok cool. My only hesitation is around robustness. If we see flakiness on CI (e.g., from waiting for `blackd` to startup, or other daemon-related issues), I may ask that we convert back to `black`, since I'd rather CI be reliable than fast (at least, on that order of magnitude).

_Originally posted by @charliermarsh in https://github.com/charliermarsh/ruff/pull/1206#discussion_r1050098161_

**Comment by charliermarsh** [comment]
That's the first time I've seen it fail!

**Comment by squiddy** [comment]
Ah okay, I've seen it a couple times, but mainly on pull request. If it didn't bother you yet, we can also close this one.

**Comment by charliermarsh** [comment]
Ok it sounds like it's worth rolling back then. Not urgent though if it's easy for you, go for it :)

**Comment by andersk** [comment]
I didn’t see the context here, but was it a `blackd` startup failure? I note that we’re only waiting a total of 1 second for `blackd` to start (10 × 100 ms), which seems low for a Python project.

**Comment by squiddy** [comment]
From what I remember it's been startup failures. And you're right, it's only 1 second (I thought it was longer). So increasing the wait time would also be an option.

**Comment by charliermarsh** [comment]
Yeah that's probably my fault -- I think I reduced them a bit before merging. Let's bump them and close for now. Can always revisit.
