### ISSUE TITLE
Generalize import-rewrite infrastructure

### ISSUE THREAD

**Issue by charliermarsh** [charliermarsh/ruff#1522]
In #1488, we added some infra to rewrite `mock` imports. But the problem is quite general. We've done similar stuff for `six` imports.

You can see how [pyupgrade](https://github.com/asottile/pyupgrade/blob/97ed6fb3cf2e650d4f762ba231c3f04c41797710/pyupgrade/_plugins/imports.py) handles this problem.

We should at least implement the `REPLACE_EXACT` logic since (I think?) that's what we have for `mock`.

**Comment by charliermarsh** [comment]
I need to look at where else this would be useful.

**Comment by charliermarsh** [comment]
This is largely handled by #2049.

**Comment by JonathanPlasse** [comment]
Does it support adding a new import?

**Comment by charliermarsh** [comment]
No, but that's tracked in #835.
