### ISSUE TITLE
[Feature request] Support `.editorconfig`

### ISSUE THREAD

**Issue by rassie** [charliermarsh/ruff#1530]
Would you be open to supporting `.editorconfig` for the `line-length` setting (called `max_line_length`)?

Currently, it's a small chore to setup the `line-length` correctly -- `black`, `isort` and `ruff` and also the editor need them separately (editor needs the setting for reflowing comments, which `black` doesn't do). Introducing `.editorconfig` to a project solves the editor and the `isort` problem and  if `ruff` supported it too, there would only be two settings to change if needed (one if `ruff` really becomes a formatter too).

(Caveat: `max_line_length` is somehow still not part of the EditorConfig spec a decade later, but is apparently widely supported by editors).

**Comment by andersk** [comment]
Sort of a corresponding issue for Black:

- psf/black#2401

but maybe someone should open a better one.

**Comment by silverwind** [comment]
`max_line_length` is unfortunately a [non-standard](https://editorconfig.org/#file-format-details) editorconfig option that may not be so widely supported.

But I do see editorconfig useful for formatting (specifically `indent_size`, but almost all standard properties are useful to a formatter) and it should be used when other configurations options are absent, e.g. at the lowest priority.

**Comment by charliermarsh** [comment]
I'm currently hesitant to support `.editorconfig` since I'd really like to avoid supporting multiple configuration formats and having to merge settings defined across multiple configuration formats.

**Comment by silverwind** [comment]
Fine with me, I don't mind a explicit separate config, even if it's going to be duplicate with the `.editorconfig`, which imho every repo must have.

**Comment by dbarnett** [comment]
Hmm, I understand not wanting unnecessary complexity, but it's unfortunate to leave the situation where users can end up specifying conflicting settings in different industry-standard configs and have them silently warring each other (e.g. editor indenting to 4, then ruff format re-indenting everything to 2, then editor creating more 4-space indents).

**Comment by heygarrett** [comment]
Can I nominate this for reconsideration? I would love to avoid adding an additional configuration file to a project that already has an EditorConfig file and only uses Python as an alternative to Bash scripts.

**Comment by Qix-** [comment]
If nothing else, being able to generate an editorconfig based on the ruff formatting rules would be great. Was missing that today.
