### ISSUE TITLE
`ruff` badge

### ISSUE THREAD

**Issue by matteosantama** [charliermarsh/ruff#1535]
A nice wish-list item is a `ruff` badge that other projects can display in their `README.md`, similar to how `mypy`, `black`,  and `isort` have badges (see the badges on [this](https://github.com/matteosantama/dantzig) repo).

**Comment by charliermarsh** [comment]
I do want to do this... I'm not sure what it takes exactly.

Just closing as a duplicate of #989.

**Comment by charliermarsh** [comment]
We added a badge!

[![Ruff](https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/charliermarsh/ruff/main/assets/badge/v0.json)](https://github.com/charliermarsh/ruff)
