### ISSUE TITLE
Adding Codespell

### ISSUE THREAD

**Issue by colin99d** [charliermarsh/ruff#1536]
It would be cool to add codespell to our CI. Let me know if you want this done. (Also its a fairly simple python linter, so we could add it to ruff itself eventually, but that is probably out of scope for now).

**Comment by not-my-profile** [comment]
What is codespell?

**Comment by colin99d** [comment]
It is a linter written in python that has a mapping of common misspellings, and maps it to correct spellings of words. So it pretty much checks your code for spelling errors. 
https://github.com/codespell-project/codespell

**Comment by colin99d** [comment]
Most of the work is just the text files they maintain, the code itself is 1,200 lines of python total:
https://github.com/codespell-project/codespell/blob/master/codespell_lib/_codespell.py

**Comment by not-my-profile** [comment]
Codespell apparently doesn't support CamelCase (https://github.com/codespell-project/codespell/issues/196), so I don't think using it on a Rust codebase makes much sense given how prelevant CamelCase is in Rust.

**Comment by colin99d** [comment]
The real benefits here are for messages to users, so that we avoid embarrassing misspellings. This means that this is a pretty small negative. However, if you have a better library to use I am all for it.
