### ISSUE TITLE
Document glob syntax

### ISSUE THREAD

**Issue by not-my-profile** [charliermarsh/ruff#1545]
The glob syntax is described in the [globset documentation](https://docs.rs/globset/latest/globset/#syntax). However that documentation mentions some settings (`literal_separator` and `backslash_escape`) and users won't know if ruff has these enabled or disabled.

I think it would make sense to:

1. set the `value_name = "FILE_PATTERN"` clap option for all arguments that take file patterns, so that `--help` shows e.g.
   ```
    --exclude <FILE_PATTERN>
    --extend-exclude <FILE_PATTERN>
    ```
2. document the syntax for `<FILE_PATTERN>` via the `after_help` clap option of the `Cli` struct

**Comment by marscher** [comment]
That seems like a good location to reference the upstream docs.
