### ISSUE TITLE
Introduce a Rust module for all lint implementations

### ISSUE THREAD

**Issue by not-my-profile** [charliermarsh/ruff#1547]
The code is currently split up across the following Rust modules:

* ast
* autofix
* cache
* checkers
* checks
* checks_gen
* cli
* commands
* cst
* directives
* docstrings
* eradicate
* flake8_2020
* flake8_annotations
* flake8_bandit
* flake8_blind_except
* flake8_boolean_trap
* flake8_bugbear
* flake8_builtins
* flake8_comprehensions
* flake8_datetimez
* flake8_debugger
* flake8_errmsg
* flake8_implicit_str_concat
* flake8_import_conventions
* flake8_print
* flake8_quotes
* flake8_return
* flake8_simplify
* flake8_tidy_imports
* flake8_unused_arguments
* fs
* isort
* iterators
* lex
* lib_native
* linter
* logging
* mccabe
* message
* noqa
* packages
* pandas_vet
* pep8_naming
* printer
* pycodestyle
* pydocstyle
* pyflakes
* pygrep_hooks
* pylint
* python
* pyupgrade
* resolver
* ruff
* rustpython_helpers
* settings
* source_code_generator
* source_code_locator
* source_code_style
* updates
* vendor
* visibility

62 top-level modules is a lot and makes the codebase hard to grasp and navigate, so I recommend moving all modules that implement specific rules/checks/lints ([whatever we call  them](https://github.com/charliermarsh/ruff/issues/1546)) under a common  module, so for example:

* lints
  * eradicate
  * flake8_2020
  * flake8_annotations
  * flake8_bandit
  * flake8_blind_except
  * flake8_boolean_trap
  * flake8_bugbear
  * flake8_builtins
  * flake8_comprehensions
  * flake8_datetimez
  * flake8_debugger
  * flake8_errmsg
  * flake8_implicit_str_concat
  * flake8_import_conventions
  * flake8_print
  * flake8_quotes
  * flake8_return
  * flake8_simplify
  * flake8_tidy_imports
  * flake8_unused_arguments
  * isort
  * mccabe
  * pandas_vet
  * pep8_naming
  * pycodestyle
  * pydocstyle
  * pyflakes
  * pygrep_hooks
  * pylint
  * pyupgrade
  * ruff

So e.g. `ruff:flake8_builtins` would become `ruff:rules:flake8_builtins`, `ruff:ruff` would become `ruff:rules:ruff`, etc.

**Comment by charliermarsh** [comment]
This seems reasonable to me.

**Comment by squiddy** [comment]
Slightly related: Any thoughts on splitting up the code into multiple crates? From my limited understanding this is one way to go for faster compiles. Multiple crates can be compiled in parallel. I did some profiling the other day and a release build takes quite some time because everything is one crate currently.

**Comment by charliermarsh** [comment]
Agreed. Are you interested in exploring that? I'd be happy to review a proposal.

**Comment by colin99d** [comment]
I have another question here. I am not aware of a specific example of this happening, but if two lints do the exact same thing, are we ever going to track that and only run it once (or at least have a flag to do this)?

**Comment by colin99d** [comment]
For example, I believe pylint and flake8 both have a line length checker.

**Comment by charliermarsh** [comment]
This problem exists today. The way I view it is that we may want a one-to-many mapping between `CheckKind` and `CheckCode` -- so we'd only have one implementation of the check, but it could map to multiple valid codes. I'm not sure it's really worth the complexity though.

**Comment by squiddy** [comment]
> Agreed. Are you interested in exploring that? I'd be happy to review a proposal.

Certainly, but with vacations over this will happen on the weekend the earliest. :)

**Comment by charliermarsh** [comment]
Take your time of course, and thank you as always :)

**Comment by kaos** [comment]
> Slightly related: Any thoughts on splitting up the code into multiple crates? From my limited understanding this is one way to go for faster compiles. Multiple crates can be compiled in parallel. I did some profiling the other day and a release build takes quite some time because everything is one crate currently.

I'm here hoping to find a crate I could use in a rust project to re-use the AST logic to do some custom node visiting. Perhaps the core AST related parts could be in a published crate? :) 
I'm rather new to Rust but happy to assist if this makes sense to y'all..

**Comment by not-my-profile** [comment]
@kaos ruff uses the parser from [RustPython](https://github.com/RustPython/RustPython), which unfortunately [has not been published to crates.io in over 2 years](https://crates.io/search?q=%22rustpython%22) for some reason. The relevant issue for that is https://github.com/RustPython/RustPython/issues/4179.

**Comment by charliermarsh** [comment]
@kaos - Yeah my suggestion would be to use the RustPython parser. You have to depend on the Git hash directly for now, unfortunately.

**Comment by kaos** [comment]
I think I can work with that. Thanks for the quick responses. 🙏🏽

**Comment by charliermarsh** [comment]
I'd also like to adopt a more typical project structure. E.g., we could follow `ripgrep`, and have a top-level `crates` directory,  with a single library facade (`crates/grep`), and the binary distributed as the top-level `Cargo.toml`.

**Comment by not-my-profile** [comment]
I think I rather have the crates in the top-level directory, which I think is also quite common (e.g. [clippy has this structure](https://github.com/rust-lang/rust-clippy/)).

However I don't really think it's that important. What I do dislike is the top-level `ruff` directory since it's non-descriptive ... I think it would make sense to move all the Python-distribution-specific stuff (pyproject.toml etc.)  to `ruff_python/` or something like that.

**Comment by charliermarsh** [comment]
Happy to review a PR for that if anyone gets around to it, probably requires a bunch of Maturin reconfiguration.

**Comment by charliermarsh** [comment]
A distinction that does seem potentially useful, from `ripgrep`, is that the library crate is published separately from the binary.

**Comment by charliermarsh** [comment]
Or maybe @messense knows how to rename the top-level `ruff` dir.

**Comment by messense** [comment]
You could move `ruff` to `python/ruff` and set `python-source` in pyproject.toml

```toml
[tool.maturin]
python-source = "python"
```

**Comment by charliermarsh** [comment]
Oh nice, thank you very much.
