### ISSUE TITLE
noqa comments do not work on multiline function signatures

### ISSUE THREAD

**Issue by marscher** [charliermarsh/ruff#1548]
Ruff-0.0.204 accepts `noqa` selector comments if the signature is contained in one line. But it fails if the signature gets wrapped along multiple lines. The latter sometimes happens for long parameters lists leading to too long lines.

Ruff ignores C901 as expected
```python
def foo(a: int, b: float) -> float:  # noqa: C901
    pass
```

Ruff reports C901 for this:
```python
def foo(a: int,
            b: float
) -> float:  # noqa: C901
    pass
```

**Comment by charliermarsh** [comment]
The desired placement is like this:

```py
def foo(  # noqa: C901
    a: int,
    b: float,
) -> float:
    pass
```

Which is consistent with Flake8, so I think this is working as intended!

**Comment by marscher** [comment]
Thanks for the clarification! I will now blame my IDE :+1:
