### ISSUE TITLE
issue with import reordering when original lines have noqa comments. 

### ISSUE THREAD

**Issue by ghuls** [charliermarsh/ruff#1551]
ruff combines import lines with and without noqa comments

File after `isort`:
```python
from aaa import used_function_a
from bbb import unused_function_b  # noqa: F401
from bbb import first_used_function_b
from ccc import used_function_c
from ddd import used_function_d

used_function_a()
first_used_function_b()
used_function_c()
used_function_d()
```

After `ruff --fix --select I001`
```python
from aaa import used_function_a
from bbb import unused_function_b, unused_function_b  # noqa: F401
from ccc import used_function_c
from ddd import used_function_d

used_function_a()
first_used_function_b()
used_function_c()
used_function_d()
```

**Comment by charliermarsh** [comment]
Hmm yeah. `isort` can do stuff like this too -- for example, this:

```py
from module import (
    # noqa: F401
    foo,
    bar
)
```

Becomes:

```py
from module import bar, foo  # noqa: F401
```

I think `isort` generally puts any `from` import with an inline comment on its own line, which doesn't seem ideal to me either.

Probably the "right" fix here is to output:

```py
from aaa import used_function_a
from bbb import (
    first_used_function_b,
    unused_function_b,  # noqa: F401
)
from ccc import used_function_c
from ddd import used_function_d
```

What do you think?

**Comment by ghuls** [comment]
I am happy with the latter.

**Comment by charliermarsh** [comment]
This might be a regression because I thought we _did_ do this. Regardless, will fix.

**Comment by ghuls** [comment]
You do it, but I think only if you have 3 from imports for the same module. It took a bit of time to make this minimal case to reproduce it because of this.
