### ISSUE TITLE
I001 + UP026 fix collision leads to invalid trailing comma

### ISSUE THREAD

**Issue by andersk** [charliermarsh/ruff#1572]
You’ve probably noticed this from the failing CI, but here’s a minimal test case:

```python
if True:
    from mock import mock, a, b, c
```

After `ruff --select=I001,UP026`:

```python
if True:
    from unittest.mock import a, b, c, 
```

which has an invalid trailing comma.

**Comment by andersk** [comment]
Oh yes, you have (#1570).

**Comment by charliermarsh** [comment]
😅
