### ISSUE TITLE
Ruff does not invalidate cache when configuration changes (PL001)

### ISSUE THREAD

**Issue by ThirVondukr** [charliermarsh/ruff#1589]
I ran into weird behavior with ruff cache and PT001 check, but other checks potentially could be affected too.

## Steps to reproduce:
1. Add `fixture-parenthesis` option
```toml
[tool.ruff.flake8-pytest-style]
fixture-parentheses = true
```
2. Run `ruff` so cache directory is generated:
```py
import pytest

@pytest.fixture
def my_fixture() -> int:
    return 42
```
3. Change `fixture-parentheses` to opposite value
4. Run `ruff` again, same output should be generated

I made a repository with reproducible example: https://gitlab.com/ThirVondukr/ruff-issues/-/tree/f231fe4bb3752fab0c866925c9eba241e24c609e
Here's a failed CI run: https://gitlab.com/ThirVondukr/ruff-issues/-/jobs/3545437297

**Comment by charliermarsh** [comment]
Thank you! Fixed. Just an oversight.
