### ISSUE TITLE
PT006 autofix: should maintain the replaced string's quote style instead of always using `"`

### ISSUE THREAD

**Issue by bluetech** [charliermarsh/ruff#1592]
Currently the PT006 autofix replaces e.g. `'first, second'` with `("first", "second")`. It would be better if it would maintain the string's quote style, in this example `('first', 'second')`.

Code where `"` is hardcoded currently:

https://github.com/charliermarsh/ruff/blob/8b277138de351801560d903658958b7967f80dde/src/flake8_pytest_style/plugins/parametrize.rs#L142-L160

I couldn't quickly find a way to get the quote style of the string (is this info available on a string literal ast `Expr`?) so I'm just lazily opening an issue :)

**Comment by charliermarsh** [comment]
You can use `checker.style.quote()` to get the quotation style for the file, if you want to add to your PR or open a separate PR :)

**Comment by charliermarsh** [comment]
Actually, I'm in this code anyway so will fix real quick.

**Comment by saadmk11** [comment]
@charliermarsh I was about to send a PR for this. :laughing:

**Comment by charliermarsh** [comment]
@saadmk11 - Feel free!

**Comment by charliermarsh** [comment]
@saadmk11 - I think it'd be nice to use `SourceCodeGenerator` entirely instead of manually crafting the expression, e.g.:

```rust
generator.unparse_expr(
    &create_expr(ExprKind::Tuple {
            ...
    })
)
```

**Comment by saadmk11** [comment]
> @saadmk11 - I think it'd be nice to use `SourceCodeGenerator` entirely instead of manually crafting the expression, e.g.:
> 
> ```rust
> generator.unparse_expr(
>     &create_expr(ExprKind::Tuple {
>             ...
>     })
> )
> ```

Yup That's what I did. :) It was quite interesting to learn how `SourceCodeGenerator` works.

**Comment by edgarrmondragon** [comment]
TIL about `SourceCodeGenerator `. Thanks for fixing this @saadmk11 !
