### ISSUE TITLE
Parity Reference

### ISSUE THREAD

**Issue by danieleades** [charliermarsh/ruff#1593]
The readme is pretty comprehensive in showing the supported lints, in relation to their corresponding flake8-plugins. I'm more interested in the inverse.

That is, I have a codebase that makes extensive use of flake8 plugins for linting. I would like a reference of which plugins can be *completely* replaced by ruff so that I can incrementally remove them where they overlap.

Is there some way to parse this?

For example, under the readme section for flake8-bugbear I see a list of all of the bugbear lints supported by Ruff. Short of manually cross-referencing against the bugbear docs, is there some way for me to check whether i can remove the bugbear plugin entirely by using ruff?

**Comment by danieleades** [comment]
Another example- when replacing isort with ruff (at least in my repo) the package isn't automatically detected by ruff as a 'known first party' module, so this config needs to be added

**Comment by bluetech** [comment]
For me https://github.com/charliermarsh/ruff#how-does-ruff-compare-to-flake8 answered this question -- the ones with `X/Y` are incomplete, the rest are complete.

**Comment by danieleades** [comment]
> For me https://github.com/charliermarsh/ruff#how-does-ruff-compare-to-flake8 answered this question -- the ones with `X/Y` are incomplete, the rest are complete.

it comes close, though if we confine the dicussion only to the examples i give above-

- ruff doesn't implement all of bugbear's 'opinionated' lints
- the fact that isort infers the root package and ruff does not is not documented

**Comment by charliermarsh** [comment]
Thanks @danieleades. I'll add a section to note a few of those incompatibilities.

**Comment by charliermarsh** [comment]
> Another example- when replacing isort with ruff (at least in my repo) the package isn't automatically detected by ruff as a 'known first party' module, so this config needs to be added

If you post your project structure, I'm happy to help with the configuration. Ruff typically _can_ infer the root, unless you're using namespace packages.

**Comment by danieleades** [comment]
> > Another example- when replacing isort with ruff (at least in my repo) the package isn't automatically detected by ruff as a 'known first party' module, so this config needs to be added
> 
> If you post your project structure, I'm happy to help with the configuration. Ruff typically _can_ infer the root, unless you're using namespace packages.
> 

Sure - dont think I'm doing anything particularly strange

https://github.com/danieleades/sphinx-graph

By the way, it only affected the 'tests' directory. Isort and ruff didn't agree on how to group the imports in tests/ unless ruff had the additional config.
