### ISSUE TITLE
Comments are getting shifted on imports

### ISSUE THREAD

**Issue by blink1073** [charliermarsh/ruff#1602]
I believe #1562 introduced a regression for us in [jupyter-server/jupyter_server_terminals@`b536f62` (#73)](https://github.com/jupyter-server/jupyter_server_terminals/pull/73/commits/b536f6252b138fcffcbb0bb61b38ed8faf2476f6).

We had formerly used:

```python
from jupyter_server.prometheus.metrics import (  # type:ignore[attr-defined]
    TERMINAL_CURRENTLY_RUNNING_TOTAL,
)
```

But it now gets mangled to:

```python
from jupyter_server.prometheus.metrics import (
    TERMINAL_CURRENTLY_RUNNING_TOTAL,  # type:ignore[attr-defined]
)
```

Which results in a mypy error.

**Comment by charliermarsh** [comment]
Thanks! Will take a look.

**Comment by charliermarsh** [comment]
Looks like it was introduced in #1380.

**Comment by charliermarsh** [comment]
I'll fix this today (but probably not for a few hours).

**Comment by blink1073** [comment]
No worries, we have a work-around for now.  Thanks!

**Comment by charliermarsh** [comment]
Thanks for filing :)

**Comment by charliermarsh** [comment]
\cc @squiddy in case he gets to it first

**Comment by blink1073** [comment]
Thanks again!
