### ISSUE TITLE
Autofix for `PIE790` leaves whitespace in the affected line

### ISSUE THREAD

**Issue by edgarrmondragon** [charliermarsh/ruff#1610]
Test file:

```python
"""Test module."""


class MyClass:
    """This is a class."""

    def __init__(self) -> None:
        """Initialize my class."""
        pass
```

Output:

```diff
$ ruff --select ALL --diff pie790.py
--- pie790.py
+++ pie790.py
@@ -6,4 +6,4 @@
 
     def __init__(self) -> None:
         """Initialize my class."""
-        pass
+        
```

**Comment by edgarrmondragon** [comment]
I think I have the fix for this. Will send a PR.

**Comment by charliermarsh** [comment]
Thanks. I feel like we have some code somewhere that deletes the entire line if it's the only statement on the line...

**Comment by charliermarsh** [comment]
Or maybe we don't.

**Comment by charliermarsh** [comment]
I think if that code went through `autofix/helpers.rs#delete_stmt`, it would do the right thing. But that requires a bit more wiring, I think I was lazy.

**Comment by edgarrmondragon** [comment]
@charliermarsh thanks for tip, `delete_stmt` made it super easy :D!
