### ISSUE TITLE
Way to mute `A new version of ruff is available:` warning

### ISSUE THREAD

**Issue by samuelcolvin** [charliermarsh/ruff#1629]
Ruff is moving very fast which is great, but it means it's virtually impossible to reliably use the latest version.

It would therefore be useful to mute the "A new version of ruff is available:" message via a setting.

I have a process for upgrading dependencies, I don't want every package I use to warn me that it's out of date.

I know the message is only printed if I haven't run ruff recently, but still slightly distracting.

**Comment by samuelcolvin** [comment]
Solved, sorry about the noise.

Ironically, I was using an old version of ruff which didn't have that option.

**Comment by charliermarsh** [comment]
Hahah :)

No apology needed, the docs aren't very user-friendly right now, it's on my mind!
