### ISSUE TITLE
SyntaxError for PEP 634 Structural Pattern Matching

### ISSUE THREAD

**Issue by radupotop** [charliermarsh/ruff#1634]
I get a `E999 SyntaxError: invalid syntax. Got unexpected token` whenever structural pattern matching occurs. e.g.:

```
def http_error(status):
    match status:
        case 400:
            return "Bad request"
        case 404:
            return "Not found"
        case 418:
            return "I'm a teapot"
        case _:
            return "Something's wrong with the internet"
```

I'm running Python 3.10.9

**Comment by charliermarsh** [comment]
Yeah this is the one language feature we don't yet support unfortunately. It's being tracked here: #282.
