### ISSUE TITLE
Implement `autoflake`

### ISSUE THREAD

**Issue by charliermarsh** [charliermarsh/ruff#1647]
- [x] Remove unused imports (`F401`)
- [x] Remove duplicate keys (`F601`)
- [x] Remove unused variables (`F841`)
- [ ] Expand star imports (`F403`)
- [ ] Useless `pass` statements

**Comment by charliermarsh** [comment]
I'm hesitant to add autofix for `F601` and `F403`, because the right behavior isn't clear, and automatically fixing them is very likely to cause problems.

I'd be open to autofixing `F601` in the case that the values are duplicated too.

**Comment by charliermarsh** [comment]
Happy with this for now. I'm not planning to do star imports with the current approach, and we already do some subset of `pass` statements.

**Comment by cclauss** [comment]
What about trying the https://github.com/asmeurer/removestar approach to an F403 fixer?

**Comment by sanmai-NL** [comment]
@charliermarsh 

The last item
> Useless pass statements

is already implemented as https://beta.ruff.rs/docs/rules/unnecessary-pass/

**Comment by RobertDeRose** [comment]
Why is F841 considered `unsafe`?
