### ISSUE TITLE
color ANSI controls being printed when using ruff on a GitBash console on windows

### ISSUE THREAD

**Issue by joaompinto** [charliermarsh/ruff#1669]
The problem only happens when running GitBash within a vscode terminal window, on a regular GitBash window the ANSI emulation works as expected.

```
$ ruff .
Found 1 error(s).
←[1mtest.py←[0m←[36m:←[0m1←[36m:←[0m8←[36m:←[0m ←[1;31mF401←[0m `httpx` imported but unused
1 potentially fixable with the --fix option.
$ flake8
.\test.py:1:1: F401 'httpx' imported but unused

```

**Comment by joaompinto** [comment]
![ruff_controls](https://user-images.githubusercontent.com/1143125/210880221-54196928-027d-4d26-a7f0-37856d992934.PNG)

**Comment by charliermarsh** [comment]
There's an environment variable you can set to disable them entirely -- is that sufficient?

E.g. `NO_COLOR=1 ruff .`

**Comment by joaompinto** [comment]
Yes, that works for me. Thanks
