### ISSUE TITLE
GitHub Actions output is missing file names and line numbers

### ISSUE THREAD

**Issue by charliermarsh** [charliermarsh/ruff#1693]
See: https://github.com/pypa/hatch/pull/702#issuecomment-1373727049.

Here's an example: https://github.com/pypa/hatch/actions/runs/3853184547/jobs/6565955257.

The action comments appear in the right spot in the "Files changed" tabs, but should the locations also be visible in the logs?

**Comment by ofek** [comment]
I think it should also be visible in the logs because the errors are from a newly released version of Ruff rather than any files I actually changed

**Comment by charliermarsh** [comment]
Are you suggesting that the line numbers and such were visible before, but are no longer visible?

**Comment by ofek** [comment]
Yes definitely but I don't remember how long ago

**Comment by charliermarsh** [comment]
Thanks, I'll look into it today.

**Comment by charliermarsh** [comment]
Relevant: https://github.com/golangci/golangci-lint-action/issues/119

**Comment by charliermarsh** [comment]
I think this is "working as intended" from the perspective of GitHub's workflow commands.

Users can disable workflow commands (so they won't get inline comments, just build logs) with `--format text` or setting `GITHUB_ACTIONS=false` when invoking Ruff.

But the other thing we can do is add explicit additional text to the logs, even if it won't be picked up by GitHub, like:

<img width="884" alt="Screen Shot 2023-01-06 at 12 22 00 PM" src="https://user-images.githubusercontent.com/1309177/211064415-b4cc3df5-0ec3-48b8-b429-32f469a869ed.png">

**Comment by ofek** [comment]
Yes that would be nice! Do you know why in that example output the first error was showing the file and line numbers and the rest weren't? Was the first error just malformed and was accidentally being printed?

**Comment by charliermarsh** [comment]
I'm wondering that too. Not sure yet...

**Comment by charliermarsh** [comment]
Two fixes here:

- The GitHub reporting is now opt-in (`ruff --format=github .`) instead of auto-detecting via the `GITHUB_ACTIONS` env var.
- When running with `--format=github`, we now preserve the location information:

![Screen Shot 2023-01-06 at 3 08 06 PM](https://user-images.githubusercontent.com/1309177/211098952-40052821-9aed-4b96-9baa-9fbea44c4c4a.png)

**Comment by ofek** [comment]
Thanks!
