### ISSUE TITLE
Allow Ruff's format to be overridden by an environment variable

### ISSUE THREAD

**Issue by charliermarsh** [charliermarsh/ruff#1716]
See: #1697.

**Comment by not-my-profile** [comment]
I don't really see the point ... can't you just run ruff with `--format $RUFF_FORMAT`?

**Comment by messense** [comment]
> I don't really see the point of adding builtin support for that ... can't you just run ruff with `--format $RUFF_FORMAT`?

It'd be nice to not have to change a configuration file (like `.pre-commit.yaml`) to change format, `--format $RUFF_FORMAT` would require the `RUFF_FORMAT` environment variable to be present all the time.

**Comment by charliermarsh** [comment]
Yeah I agree -- I do think there's value to this option specifically.

**Comment by jolpica** [comment]
To anyone coming across this and unable to get this working, the environment variable has been renamed to `RUFF_OUTPUT_FORMAT` in newer versions of ruff.
