### ISSUE TITLE
Implement W291 (trailing whitespace)?

### ISSUE THREAD

**Issue by harupy** [charliermarsh/ruff#1734]
It'd be nice if Ruff could detect trailing whitespace:

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/17039389/211179938-4a48eefd-483d-4f07-972b-11e539501a92.png">

(even though black can eliminate them)

**Comment by charliermarsh** [comment]
I don't know if it's relevant (haven't thought through how we would implement trailing whitespace), but I started implementing Pycodestyle's logical line detection in https://github.com/charliermarsh/ruff/pull/1130 -- although I felt at the time that it was a bit too slow to be worthwhile as a default.

**Comment by charliermarsh** [comment]
Do these checks typically exclude trailing whitespace within strings?

**Comment by not-my-profile** [comment]
Black preserves trailing whitespace in multiline strings (as it should). I just checked and pycodestyle does trigger W291 for trailing whitespace within multiline strings. To be honest I don't really see the point of this lint.

**Comment by charliermarsh** [comment]
I think it's a perfectly useful rule, _if you don't use an autoformatter_.

**Comment by not-my-profile** [comment]
Haha yes I don't see why you wouldn't.^^

**Comment by harupy** [comment]
@not-my-profile Agreed! Let me close this.

**Comment by harupy** [comment]
> 
Black preserves trailing whitespace in multiline strings (as it should). I just checked and pycodestyle does trigger W291 for trailing whitespace within multiline strings. To be honest I don't really see the point of this lint.

Yes, black does. We can align with black and ignore trailing whitespace in a string (as shown in the attached screenshot).
