### ISSUE TITLE
Improve CI performance

### ISSUE THREAD

**Issue by charliermarsh** [charliermarsh/ruff#1743]
A few ideas (all of which should be benchmarked prior to committing):

- [x] Skip `--release` in CI builds
- [x] Install `insta` via [`rust-cargo-install`](https://github.com/marketplace/actions/rust-cargo-install) (#1750)
- [ ] Try out [`cargo nextest`](https://nexte.st/)
- [x] Try out [`rust-cache`](https://github.com/Swatinem/rust-cache) action (#1750)

**Comment by charliermarsh** [comment]
(I feel like our build cache is really bad, though I don't understand why.)

**Comment by charliermarsh** [comment]
Oh, maybe the problem is that we need to use separate caches for the different actions.

**Comment by colin99d** [comment]
Awesome!! I guess I need to improve my fuzzy finder (;.

**Comment by ducaale** [comment]
>- Try out [`rust-cache`](https://github.com/Swatinem/rust-cache) action

This option seems to halve the CI duration time (~8m vs ~5m). The `Clippy` step is a bottleneck at the moment, but I believe splitting it into two jobs will speed things up further.

**Comment by max-sixty** [comment]
FYI for binaries like `cargo-insta`, you probably want https://github.com/PRQL/prql/blob/b88083c63a83c235d454ab5eff190e1661fea048/.github/actions/test-rust/action.yaml#L41, which caches just the binary — so the runner doesn't need to pull a huge cache. The cache size is then just few MBs, and it loads in a few seconds.

**Comment by Boshen** [comment]
FYI you can replace the `uses: actions-rs/toolchain@v1` step with a simple `rustup show`. 
I used this in the rome repo and it's working great.

https://github.com/rome/tools/blob/e0325d39ed9276eda6c08f973f4edd1af99e9b40/.github/workflows/main.yml#L29-L30

This'll save a few seconds from installing the plugin, and as a bonus, you no longer need to manually sync your Rust version.

(Hi from twitter 👋 )

**Comment by charliermarsh** [comment]
@Boshen - Oh nice! Thank you! I tried it briefly (https://github.com/charliermarsh/ruff/pull/1769) but think it needs some fiddling since we use nightly for `rustfmt` and need to support the WASM target. Maybe I'll come back to it later :)

**Comment by charliermarsh** [comment]
@Boshen - I looked through the originating PR on those changes -- should I also be doing a cache clean at the end of the job?

**Comment by charliermarsh** [comment]
Closing for now as I think we've gotten through most of the items, and CI got way faster.

**Comment by not-my-profile** [comment]
My latest PR does some minor edits to `.github/workflows/ci.yaml` and the CI is now taking 9m 33s just to run `cargo install cargo-insta`. Would separating the `cargo insta test --all` into its own `.yaml` file help with that?

**Comment by charliermarsh** [comment]
@not-my-profile - I wouldn't expect those changes to impact the install time. But they're definitely invalidating the cache given the `Cargo.toml` and `Cargo.lock` modifications. Is it possible that it's just a cold-cache artifact, and that discrepancy will go away once it's merged etc.?

**Comment by not-my-profile** [comment]
Yes I am quite certain that it's a cold-cache effect. My point was that having the `cargo insta` in its own `.yml` file probably would result in fewer cache invalidations.

I was only slightly annoyed by the long build time since I was repeatedly editing the `ci.yaml` file but since we generally only seldomly do that and the cache works as expected feel free to ignore my comment.^^

**Comment by messense** [comment]
I think it's because [crates.io-index](https://github.com/rust-lang/crates.io-index) [squashed into one commit](https://internals.rust-lang.org/t/cargos-crate-index-upcoming-squash-into-one-commit/8440) today, which makes the git clone delta calculation extremely slow when you have old caches.

**Comment by max-sixty** [comment]
FYI if it's a cold cache effect, this approach does get its own cache line https://github.com/charliermarsh/ruff/issues/1743#issuecomment-1376857341...
