### ISSUE TITLE
Support the builtins configuration variable from flake8

### ISSUE THREAD

**Issue by kovidgoyal** [charliermarsh/ruff#1745]
It would be useful to me to support the builtins flake8 configuration variable. It allows telling flake8 that some names have been added to the python global namespace and so should not be reported as Undefined name errors.

A common use case for this is python translations. The stdlib module recommends adding the underscore as the gettext() function globally via builtins.__dict__. ruff currently complains that _ is an undefined name with no way to globally override that.

**Comment by charliermarsh** [comment]
Sounds reasonable!

**Comment by charliermarsh** [comment]
(This can ship today, very easy.)

**Comment by kovidgoyal** [comment]
Cool, thanks.
