### ISSUE TITLE
__future__ import should not trigger I001

### ISSUE THREAD

**Issue by zpz** [charliermarsh/ruff#1751]
I suspect I'm missing something. I have this in pyproject.toml

[tool.ruff]
target-version = "py38"
select = ["E", "F"]
extend-select = ["I001"]
ignore = ["E501"]

The `__future__` imports, which should be the first import, trigger I001 errors. Isort says it doesn't have this issue https://github.com/PyCQA/isort/issues/1637

I think `__future__` on the first line should be the internal behavior, or there should be an option about that. Am I missing something?

**Comment by charliermarsh** [comment]
Can you include the exact Python file or snippet that reproduces the issue?

**Comment by zpz** [comment]
My bad. My code had ``from __future__ import annotations`` followed immediately by other imports. I have many files like this: standard lib imports are one block, including the ``__future__`` at the beginning. When it complained about "unsorted" issue, I was surprised, and I did not let ``ruff`` "fix" it (fearing it would mess it up). When I did let it fix it, it added a blank line after ``__future__``, so that is OK. Then I read the message again, it says something like unsorted "in the import block", so that makes sense, too. If ``__future__`` was in its own block, it would not complain.

Not sure whether this needs some call out in the documentation. After all, I was confused at first.

Please feel free to close.

**Comment by charliermarsh** [comment]
Ah yeah, that makes sense. We could do a better job of communicating the specific issues that Ruff is flagging when it comes to organizing imports. (Right now, it just tells you that there's _something_ wrong with the set of imports.) Thanks for the thorough reply.
