### ISSUE TITLE
json.schemastore.org is not up to date

### ISSUE THREAD

**Issue by JonathanPlasse** [charliermarsh/ruff#1765]
Hi,
There is `flake8-pytest-style` missing in the schema from [json.schemastore.org](https://json.schemastore.org/ruff.json).

**Comment by JonathanPlasse** [comment]
In [schemastore/CONTRIBUTING.md](https://github.com/SchemaStore/schemastore/blob/master/CONTRIBUTING.md) it is said:
> Keep single source of truth. Do not copy an external schema here, but point the catalog to the external schema.

Maybe we should open a pull request to link to [ruff.schema.json](https://raw.githubusercontent.com/charliermarsh/ruff/main/ruff.schema.json) instead.

**Comment by JonathanPlasse** [comment]
I went ahead and made a [pull request](https://github.com/SchemaStore/schemastore/pull/2724).

**Comment by charliermarsh** [comment]
Unfortunately, the Schema Store doesn't support URLs for embedded schemas. So we can't point it to a URL if we want the schema to appear for `pyproject.toml` files. I initially implemented it as a URL (https://github.com/SchemaStore/schemastore/pull/2673), then intentionally changed it to bundle in the repo to support `pyproject.toml` files (https://github.com/SchemaStore/schemastore/pull/2683). It's an unfortunate limitation, but for now we have to update it periodically.

**Comment by charliermarsh** [comment]
We should just be sure to update the schema in the store periodically. It looks like it was updated three days ago to include `flake8-pytest-style`: https://github.com/SchemaStore/schemastore/pull/2718/files.

**Comment by layday** [comment]
The linked commit added the `flake8-pytest-style` codes but not the config section.  There's other codes and sections missing, e.g. `PIE`.  I wonder if updates could be automated somehow?

**Comment by charliermarsh** [comment]
I’ll update it today. We could definitely automate it, but I’m worried about spamming the Schema Store repo. I’ll ask in the PR.

**Comment by sasanjac** [comment]
> Unfortunately, the Schema Store doesn't support URLs for embedded schemas. So we can't point it to a URL if we want the schema to appear for `pyproject.toml` files

What exactly does not support embedded schemas? Can we not just add something like this to `catalog.json`:
```json
{
  "name": "Ruff",
  "description": "JSON schema for Ruff, a fast Python linter",
  "url": "https://github.com/charliermarsh/ruff/blob/v0.0.256/ruff.schema.json",
  "fileMatch": ["ruff.toml"],
  "versions": {
    "0.0.253": "https://github.com/charliermarsh/ruff/blob/v0.0.253/ruff.schema.json",
    "0.0.254": "https://github.com/charliermarsh/ruff/blob/v0.0.254/ruff.schema.json",
    "0.0.255": "https://github.com/charliermarsh/ruff/blob/v0.0.255/ruff.schema.json",
    "0.0.256": "https://github.com/charliermarsh/ruff/blob/v0.0.256/ruff.schema.json"
  }
}
```

And then update only new versions after their release? That would keep a single source of truth and reduce the amount of work necessary to update the schema as well as reduce the possibility of errors when copying manually.

This approach works in `VSCode`:
- `yaml`: `YAML` extension
- `toml`: `Even Better TOML` extension
- `json`: `JSON Schema Store Catalog` extension

**Comment by charliermarsh** [comment]
The issue is that we want autocompletion to work in `pyproject.toml`, which requires that we reference the `ruff.toml` schema in the `pyproject.toml` schema, which in turn requires that both [schemas exist locally in the SchemaStore](https://github.com/SchemaStore/schemastore/blob/master/CONTRIBUTING.md#how-to-ref-from-schema_xjson-to-schema_yjson). We _used_ to link via a URL like that, but then autocompletion would only work in `ruff.toml` files IIRC. Perhaps I'm misunderstanding though.

**Comment by sasanjac** [comment]
What tool provides the autocompletion? I have working autocompletion in `pyproject.toml` with `Even Better TOML`. You can test it for example with `starship.toml`. Its schema is also hosted externally, but the it is working fine with autocompletion.
