### ISSUE TITLE
__path__ is not detected as a builtin for F821

### ISSUE THREAD

**Issue by sanga** [charliermarsh/ruff#177]
Eg

`print(__path__)`

Produces "F821 Undefined name `__path__`"

**Comment by charliermarsh** [comment]
Will fix :)

**Comment by charliermarsh** [comment]
Can you give a bit more context on where `__path__` _should_ be considered defined? I think it's only present when in an `__init__.py` module, or something like that...

**Comment by sanga** [comment]
I'm actually not sure without checking the docs to be honest. Definitely at least in `__init__.py` - that's where I hit this bug. But it's ok in any module that's part of a package too isn't it? This is the best link I could find from pythons docs https://docs.python.org/3/reference/import.html#module-path

**Comment by charliermarsh** [comment]
Thanks, you were totally right!
