### ISSUE TITLE
Incorrect label for docstring error

### ISSUE THREAD

**Issue by colin99d** [charliermarsh/ruff#1775]
<img width="766" alt="Screenshot 2023-01-10 at 9 04 07 PM" src="https://user-images.githubusercontent.com/72827203/211700931-26bf31e0-6885-490d-9330-9a892bf0926d.png">

I believe the wording on this warning is incorrect. It is fixed by switching to triple quotes. However, it says you need double quotes.

**Comment by colin99d** [comment]
I thought it also might be referring to that as well. I can try to have a fix in for that tonight!

**Comment by charliermarsh** [comment]
It looks like that code isn't robust to single character docstrings (like `"` instead of `"""`).

**Comment by charliermarsh** [comment]
`"` should be valid. It shouldn't matter if you use three quote characters or one quote character, for the sake of _that_ rule.

**Comment by charliermarsh** [comment]
Might help to look at `pydocstyle/rules.rs#triple_quotes`, and `TRIPLE_QUOTE_PREFIXES`. We should check the prefix rather than doing a `.contains` call.
