### ISSUE TITLE
PIE794 fixer removes wrong code and doens't detect one use case

### ISSUE THREAD

**Issue by spaceone** [charliermarsh/ruff#1787]
ruff 0.0.218
`ruff --select PIE794 foo.py`
```
class foo:
    bar = 1 
    bar = 2
```
→ not detected at all

`ruff --select PIE794 --fix foo.py`
```
class foo(object):
    bar = 1 
    bar = 2
```
→ changes into:
```
class foo(object):
    bar = 1 
    
```
1. this is wrong. bar should be `2`
2. it leaves 4 trailing spaces behind (`W293`)

**Comment by charliermarsh** [comment]
Thank you! All correct. Will fix.

**Comment by charliermarsh** [comment]
(Will hopefully get to this later today.)

**Comment by charliermarsh** [comment]
I think it's not clear that `bar = 1` should be removed instead of `bar = 2`. I know that semantically, it's correct, in that `bar = 2` is the value that's resolved when you run the code. But I feel like this check is more likely to occur in situations in which you redefine a field that you already defined? In which case, the second instance would be the "error"?

**Comment by charliermarsh** [comment]
I fixed the other two issues in #1794. We can keep discussing since the last thing is sort of subjective.

**Comment by spaceone** [comment]
> I think it's not clear that `bar = 1` should be removed instead of `bar = 2`. I know that semantically, it's correct, in that `bar = 2` is the value that's resolved when you run the code. But I feel like this check is more likely to occur in situations in which you redefine a field that you already defined? In which case, the second instance would be the "error"?

hm, I don't want to risk a behavior change by using the autofixers, so I would change that to the semantically-correct version. If it was wrong before the linter shows you this and you can act upon it.

**Comment by charliermarsh** [comment]
Yeah that's a reasonable argument. Okay, I'll do another pass on this.
