### ISSUE TITLE
Ignore `__exit__` for ARG002

### ISSUE THREAD

**Issue by ofek** [charliermarsh/ruff#1796]
This method is implemented for classes to support being used as a context manager and it would be nice to add an exception for this method because the arguments are often unused. For example, this is what I've been doing:

```python
    def __exit__(
        self,
        exc_type: type[BaseException] | None,  # noqa: ARG002
        exc_value: BaseException | None,  # noqa: ARG002
        traceback: TracebackType | None,  # noqa: ARG002
    ) -> None:
        # cleanup logic
```

**Comment by charliermarsh** [comment]
Sounds good.

**Comment by charliermarsh** [comment]
Perhaps we should omit all "magic" methods...?
