### ISSUE TITLE
SIM401 should not apply to non-concrete default values

### ISSUE THREAD

**Issue by thomasdesr** [charliermarsh/ruff#1809]
Thanks again for Ruff ❤️ 

As of `ruff==0.0.219` `SIM401` seems to be incorrectly applied when the default value is not a constant value.

```python
import asyncio


async def some_async_func():
    await asyncio.sleep(10)


async def foo():
    d = {"key": "value"}
    key = "key"

    if key in d:
        value = d[key]
    else:
        value = await some_async_func()

    return value
```

Believes it can be simplified (& maybe more dangerously will be auto-fixed) to:
```python
import asyncio


async def some_async_func():
    await asyncio.sleep(10)


async def foo():
    d = {"key": "value"}
    key = "key"

    value = d.get(key, await some_async_func())

    return value

```

However these two are not interchangeable as `some_async_func()` may be arbitrarily expensive as demonstrated here by the `asyncio.sleep(10)`

Note: This is also a bug in upstream flake8-simplify https://github.com/MartinThoma/flake8-simplify/issues/166

**Comment by charliermarsh** [comment]
Ahh, good catch! We can fix this.

**Comment by thomasdesr** [comment]
Thanks!

**Comment by charliermarsh** [comment]
I went off some heuristics (ignore any expressions containing function calls, awaits, etc.) — let me know if it misses anything going forward.

**Comment by thomasdesr** [comment]
They look like sufficient for my code base! Thanks!

**Comment by charliermarsh** [comment]
Makes sense, I can fix that.
