### ISSUE TITLE
C405 fixer causes E231

### ISSUE THREAD

**Issue by spaceone** [charliermarsh/ruff#1821]
foo.py:
`SKIP = set(('interfaces/restart/auto',))`

`ruff --fix foo.py` causes:
`SKIP = {'interfaces/restart/auto',}`
which is detected as `E231` by `flake8`:
`foo.py:1:34: E231 missing whitespace after ','`

**Comment by charliermarsh** [comment]
I was initially gonna say we shouldn't fix this, but I guess it's like, the specific case of a tuple with a trailing comma (to signify a tuple) that isn't a "magic trailing comma" (from Black's perspective).
