### ISSUE TITLE
[question/request] processing stdin?

### ISSUE THREAD

**Issue by FrancescElies** [charliermarsh/ruff#1823]
With other tools like black one can pass a file via stdin `cat myfile.py | black -` and it will be formatted.

Could ruff do something similar `cat myfile.py | ruff -`, or does ruff need to know the path of the file?

This could be helpful in the case where an editor would pass the contents of a buffer via stdin and get those contents ruffed.

Thanks in advance

**Comment by charliermarsh** [comment]
(So broadly speaking: we output the errors, unless you pass `--fix`, in which case we pass you the fixed contents.)

**Comment by FrancescElies** [comment]
aha, ok thanks adding `--fix` flag does the trick 🎊 `cat setup.py | ruff - --fix`
