### ISSUE TITLE
Ruff with Ale in Nvim Shows errors on things that should be ignored

### ISSUE THREAD

**Issue by colin99d** [charliermarsh/ruff#1829]
Not sure if this is an issue here or with Ale. From the output of `ruff .`, you can see that S101 is being ignored. However, in the file itself I still see the warning.
<img width="1973" alt="Screenshot 2023-01-12 at 1 48 08 PM" src="https://user-images.githubusercontent.com/72827203/212153088-be007d18-ddf7-42fe-bbd5-2c1c7d4f4217.png">

**Comment by colin99d** [comment]
And here is the config:
```
let g:ale_linters = { "python": ["ruff", "pylint"], "rust": ["analyzer"] }
let g:ale_fixers = {
\       "*": ["remove_trailing_lines", "trim_whitespace"],
\       "python": ["black", "ruff"],
\       "rust": ["rustfmt"],
\}
```

Also, we should probbably put instructions for this in the README, since this seems a lot easier than the suggested way of using ruff in vim.

**Comment by charliermarsh** [comment]
Not super familiar with this tool... My best guess is that it's not passing the filename to Ruff? So we can't find the config?

**Comment by john-kurkowski** [comment]
> My best guess is that it's not passing the filename to Ruff?

Exactly. dense-analysis/ale#4414

**Comment by colin99d** [comment]
This is definitely the issue! Thanks! Charlie, should I replace our current README with Ale since the config is WAY easier? It also one of the most popular vim tools.

**Comment by charliermarsh** [comment]
Gonna close since I think this is handled by the upstream issue.

@colin99d - Can you add a section for it similar to what we have for `efm` and `null-ls`?
