### ISSUE TITLE
Option to disable ANSI color output.

### ISSUE THREAD

**Issue by thisfred** [charliermarsh/ruff#1830]
I would love a CLI flag that allows me to disable the colored output, rather than have to filter it out with `sed` in places that don't speak ANSI.

Use cases: Running this in some CI contexts, piping output to a file and then opening that in a text editor.

**Comment by charliermarsh** [comment]
You can actually set `NO_COLOR=1`, like `NO_COLOR=1 ruff ...`.

**Comment by charliermarsh** [comment]
(So it's an env var, not a CLI flag, but hopefully that's ok for what you're describing?)

**Comment by thisfred** [comment]
Thank you, that's great, sorry I missed this, it may be something to point out in the documentation.

**Comment by charliermarsh** [comment]
No prob, I don't think it's in the docs anywhere!

I think `CLICOLOR` also works? But I haven't tried it: https://github.com/charliermarsh/ruff/issues/526
