### ISSUE TITLE
Wrong conversion for SIM110

### ISSUE THREAD

**Issue by Hoxbro** [charliermarsh/ruff#1831]
I hope you don't get tired of hearing it, but great work you and the other contributors are doing :+1: 

I have this small example code that simplifies the code a bit too much. 

``` python
def sim110_error(vals):
    for val in vals:
        if isinstance(val, dict):
            return True
        elif isinstance(val, list):
            return True
    return False
```

When running `ruff file.py --isolated --select=SIM` it return ```SIM110 Use `return any(isinstance(val, dict) for val in vals)` instead of `for` loop```, my version is 0.0.219.

No simplification is done if I comment out the `return False`.

**Comment by charliermarsh** [comment]
Thank you! I really appreciate it! And it always helps to hear :)

Yeah, this looks wrong. Let me take a look...

**Comment by charliermarsh** [comment]
(Also: great issue, thanks for including a clear test case and using `--isolated`...)

**Comment by charliermarsh** [comment]
Looks like `flake8-simplify` has the same problem:

```
❯ flake8 foo.py --isolated --select SIM
foo.py:2:5: SIM110 Use 'return any(isinstance(val, dict) for val in vals)'
```

(Which doesn't mean we shouldn't fix it.)

**Comment by Hoxbro** [comment]
> (Which doesn't mean we shouldn't fix it.)

Sounds good. 

Just noting that adding a nested if-statement will still simplify the problem. 

``` python
def sim110_error(vals):
    for val in vals:
        if isinstance(val, dict):
            return True
        elif isinstance(val, list):
            if len(val) > 1:
                return True
    return False
```

**Comment by charliermarsh** [comment]
Will go out in a bit, as part of v0.0.220.

**Comment by charliermarsh** [comment]
I'd like to also simplify this case, which we currently miss:

```py
for val in vals:
    if isinstance(val, dict):
        return True
else:
    return False
```
