### ISSUE TITLE
Rule E203 not supported? 

### ISSUE THREAD

**Issue by gabohc** [charliermarsh/ruff#1842]
When running flake8-to-ruff, it warns that 'E203'  is an unsupported prefix code. The docs say that ruff supports pycodestyle rules E (https://pycodestyle.pycqa.org/en/latest/intro.html#error-codes).

Am I missing something here?

**Comment by charliermarsh** [comment]
No, that's right! [We don't support some of the E-level rules that are made redundant by Black.](https://github.com/charliermarsh/ruff#how-does-ruff-compare-to-flake8)

And here's a [link](https://github.com/charliermarsh/ruff#pycodestyle-e-w) to the E-level rules that we do support.

This work is being tracked in https://github.com/charliermarsh/ruff/issues/1073.

**Comment by gabohc** [comment]
Oh, thanks, I was misreading it. Sorry

**Comment by charliermarsh** [comment]
No prob!

**Comment by awgymer** [comment]
I just ran into this but following the links from the README to the docs on the supported `E` codes I can see `E203` in [the list](https://beta.ruff.rs/docs/rules/#error-e)? Are the docs out of date here?

**Comment by JonathanPlasse** [comment]
Yes, they should not be present.

**Comment by charliermarsh** [comment]
Yeah, I think they accidentally got added when I moved from a feature flag to a debug assertion for the pycodestyle rules.
