### ISSUE TITLE
Support flake8-no-pep420 rule INP001

### ISSUE THREAD

**Issue by nefrob** [charliermarsh/ruff#1844]
PyPI link: https://pypi.org/project/flake8-no-pep420/.

Checks for the existence of an `__init__.py` file in each directory of a python project. Looked through the checkers and didn't see one for file name or path based checks so not sure if Ruff can easily support this right now. The rule itself is fairly short otherwise ([code](https://github.com/adamchainz/flake8-no-pep420/blob/main/src/flake8_no_pep420/__init__.py)).

**Comment by charliermarsh** [comment]
Yeah we can just add a `filesystem` checker in `src/checkers.rs`. Seems straightforward enough!
