### ISSUE TITLE
Support flake8-logging-format ?

### ISSUE THREAD

**Issue by neutrinoceros** [charliermarsh/ruff#1850]
Hi, thanks a lot for making ruff, I'm amazed by the quality and performances of this fantastic tool !

[`flake8-logging-format`](https://pypi.org/project/flake8-logging-format) isn't crucial to my workflow, but it's the only flake8 plugin I use that isn't supported yet *and* doesn't have an open ticket to follow already so I figured I'd open one for reference.

Keep it up !

**Comment by edgarrmondragon** [comment]
I'm working on some of these. For tracking:

- [ ] `G001`: Logging statements should not use `string.format()` for their first argument
- [ ] `G002`: Logging statements should not use `%` formatting for their first argument
- [ ] `G003`: Logging statements should not use `+` concatenation for their first argument
- [ ] `G004`: Logging statements should not use `f"..."` for their first argument (only in Python 3.6+)
- [ ] `G010`: Logging statements should not use `warn` (use warning instead)
- [ ] `G100`: Logging statements should not use `extra` arguments unless whitelisted
- [ ] `G101`: Logging statement should not use `extra` arguments that clash with LogRecord fields
- [ ] `G200`: Logging statements should not include the exception in logged string (use `exception` or `exc_info=True`)
- [ ] `G201`: Logging statements should not use `error(..., exc_info=True)` (use `exception(...)` instead)
- [ ] `G202`: Logging statements should not use redundant `exc_info=True` in `exception`

**Comment by charliermarsh** [comment]
I'm going to tentatively close this, and we can open issues for those two remaining rules as they come up.
