### ISSUE TITLE
E712 (Comparison to True should be cond is True) should be ignored when comparison is against pandas.Series

### ISSUE THREAD

**Issue by rsokolewicz** [charliermarsh/ruff#1852]
using `ruff==0.0.215`

The following snippet raises an E712 when running `ruff`:

``` python
import pandas as pd

df = pd.DataFrame({"x" : [False, True]})
df["x"] != False
```

and the autofix replaces `df["x"] != False` with `df["x"] is not False`. The two are unfortunately not equivalent and the latter leads to errors from pandas.

**Comment by charliermarsh** [comment]
Pretty hard to avoid until we can infer that `df` is a DataFrame here.

**Comment by akanz1** [comment]
Can we prevent the autofix from applying this specific rule?

**Comment by nils-borrmann-y42** [comment]
The same problem happens in sqlalchemy queries (`.select(foo != bar)` is not equivalent to `.select(foo is not bar)`)

**Comment by charliermarsh** [comment]
Before I disable autofix for this rule entirely... you can disable it for your project via:

```toml
[tool.ruff]
unfixable = ["E712"]
```

Is that sufficient here?

**Comment by akanz1** [comment]
Works for me, thanks! :)

**Comment by rsokolewicz** [comment]
In my data analysis and data science projects I end up ignoring this rule more often than having it autofixed, so I ended up using

```
[tool.ruff]
ignore = ["E712"]
```

instead. There are a few other cases where autofixing `== True` to `is True` will break code, namely when comparing against booleans that have a package-specific implementation such as numpy (`numpy.bool_`) or pytorch (`toch.bool`).

**Comment by charliermarsh** [comment]
Yeah, that makes sense. I think I'm going to close this for now given that we have some workarounds (users should either disable the rule entirely, or, if they want the rule to be enabled but want to avoid false fixes, should use `unfixable`).

**Comment by Faolain** [comment]
This just broke our code using SQLAlchemy converting

```
signup_code = (
    db.session.query(SignupCode)
    .filter(SignupCode.code == code, SignupCode.used == False)
    .first()
)
```

to 

```
 signup_code = (
        db.session.query(SignupCode)
        .filter(SignupCode.code == code, SignupCode.used is False)
        .first()
    )
```

which it definitely shouldn't have autofixed. Can this instead be a suggestion provided but something that is not autofixed? Can prevent a lot of headaches.

**Comment by charliermarsh** [comment]
This is marked in the codebase as a "Suggested" autofix, which in a future release will require running with additional command-line flags to explicitly opt-in to fixing.

**Comment by LarsenCundric** [comment]
Got the same issue where a sql query `param == False` was "fixed to `not param` which broke the code.
