### ISSUE TITLE
Support linting for python files without extension

### ISSUE THREAD

**Issue by joshuachapnick-bc** [charliermarsh/ruff#1853]
Is it possible to add support for linting files without `.py, .pyi` extensions (or override the check)? We use a CLI written in python that does not have a `.py` extension which causes ruff to fail when running.

**Comment by charliermarsh** [comment]
If you pass the file directly (“ruff path/to/file/without/an/extension”), we should lint it regardless of the extension, which is what I’ve seen other projects do. Does that help here? Or insufficient?

**Comment by joshuachapnick-bc** [comment]
That doesn't seem to work. I have a github action set up that runs `ruff <filename> --config pyproject.toml` and ruff returns `error <filename> is not supported; Ruff only supports .py and .pyi files`

**Comment by joshuachapnick-bc** [comment]
Is there some flag I can pass to override that error?

**Comment by joshuachapnick-bc** [comment]
Looks like my ruff version was out of date.

**Comment by charliermarsh** [comment]
Ah ok, that was gonna be my next question. Great!

**Comment by joshuachapnick-bc** [comment]
Thanks for the quick response!
