### ISSUE TITLE
D400 Confusion

### ISSUE THREAD

**Issue by nstarman** [charliermarsh/ruff#1858]
In https://github.com/astropy/astropy/pull/14272#discussion_r1070093557 we are looking to turn on D400, but possibly encountered a bug.  While D400 says a line should end in a period, it's D401 that requires imperative phrasing. With D401 turned off, is a question mark not a suitable alternative to a period?
Thanks in advance for the clarification.

**Comment by charliermarsh** [comment]
There's actually a separate rule for this, `D415`, which allows period, question mark, or exclamation point.

**Comment by nstarman** [comment]
Ah! Thanks, we will swap D400 for D415.

**Comment by charliermarsh** [comment]
Sweet :)
