### ISSUE TITLE
Migrate existing violations to use named fields

### ISSUE THREAD

**Issue by charliermarsh** [charliermarsh/ruff#1871]
Purely a mechanical refactor, but right now all the structs use anonymous fields.

Check out #1887 for an example of the kind of conversion we want to apply, to all structs in `violations.rs`.

**Comment by sladyn98** [comment]
@charliermarsh I read your tweet and would like to get started with contributing to this repository, is this issue still up for grabs. If yes I would like to give this a shot.

**Comment by charliermarsh** [comment]
@sladyn98 - That'd be great! Feel free to do it in pieces if you'd like, a few structs or even one-at-a-time, whatever you prefer.

**Comment by sladyn98** [comment]
@charliermarsh For example for this struct if I want to make changes to this one do i have to make changes to another file that defines this struct,  like you did in this example https://github.com/charliermarsh/ruff/pull/1887

```
    pub struct UnusedImport(pub String, pub bool, pub bool);
```

**Comment by charliermarsh** [comment]
Yeah, in that case, you'd need to change `pub struct UnusedImport(pub String, pub bool, pub bool)` in `violations.rs`, and then the `violations::UnusedImport(full_name.to_string(), ignore_init, multiple)` references in `src/checkers.rs`.

**Comment by charliermarsh** [comment]
Done by #2317!
