### ISSUE TITLE
Add support for isort remove_redundant_aliases option

### ISSUE THREAD

**Issue by nefrob** [charliermarsh/ruff#1875]
Ref: https://pycqa.github.io/isort/docs/configuration/options.html.
> Tells isort to remove redundant aliases from imports, such as import os as os. This defaults to False simply because some projects use these seemingly useless aliases to signify intent and change behaviour.

Configuration in ruff:
```toml
[tool.ruff.isort]
remove_redundant_aliases = true

**Comment by mkniewallner** [comment]
This might be redundant with `PLC0414` check from `pylint`: https://github.com/charliermarsh/ruff#convention-plc.

**Comment by charliermarsh** [comment]
Yeah I believe we implement this (with autofix) as `PLC0414`.

**Comment by nefrob** [comment]
Sweet thanks! Closing this issue.
