### ISSUE TITLE
Implement B028 rule from bugbear

### ISSUE THREAD

**Issue by LefterisJP** [charliermarsh/ruff#1893]
flake8-bugbear just released an update to add an interesting rule: https://pypi.org/project/flake8-bugbear/

> B028: Consider replacing f"'{foo}'" with f"{foo!r}" which is both easier to read and will escape quotes inside foo if that would appear. The check tries to filter out any format specs that are invalid together with !r. If you’re using other conversion flags then e.g. f"'{foo!a}'" can be replaced with f"{ascii(foo)!r}". Not currently implemented for python<3.8 or str.format() calls.

It hits in some places in rotki's codebase but I am not gonna go change them all manually :smile: 

It would be great if ruff also detects it and auto-fixes it.

**Comment by LefterisJP** [comment]
Hmm okay now that I am looking at it with a closer look though I think this rule may not be as smart as its definition makes it out to be. Take the following code for example:

```python
class Person:

    def __init__(self, name: str, age: int) -> None:
        self.name = name
        self.age = age

    def __str__(self) -> str:
        return f'{self.name} who is {self.age} years old'

    def __repr__(self) -> str:
        return f'{id(self)}'


john = Person('John', 24)
print(f'"{john}"')
print(f'{john!r}')
```

Since `__repr__` is implemented, the `!r` version is different.

```
"John who is 24 years old"
140039984729776
```

Running flake8 with that bugbear rule active still seems to advice to change it:

```
test.py:17:7: B028 'john' is manually surrounded by quotes, consider using the `!r` conversion flag.
```

And doing so would be a bug.

I wonder if it would be possible to only make it warn you if str == repr for the variable in question.

**Comment by LefterisJP** [comment]
> @LefterisJP interesting test case, even numeric types have a problem - see [PyCQA/flake8-bugbear#329](https://github.com/PyCQA/flake8-bugbear/issues/329) and also [PyCQA/flake8-bugbear#332](https://github.com/PyCQA/flake8-bugbear/issues/332) - it looks likely the B028 check will be disabled by default

Yeah I think this rule may not be a good idea at all. I will leave it to @charliermarsh to decide but feel free to close.

**Comment by charliermarsh** [comment]
Ah yeah, ok, looks like it's being renamed to [B907](https://github.com/PyCQA/flake8-bugbear/pull/333), so lets close for now.
