### ISSUE TITLE
UP011 is incorrectly replacing `lru_cache(max_size)=None`

### ISSUE THREAD

**Issue by henribru** [charliermarsh/ruff#1913]
The UP011 rule replaces `functools.lru_cache(max_size=None)` with `functools.lru_cache`. The corresponding rule in pyupgrade replaces it with `functools.cache`: https://github.com/asottile/pyupgrade#replace-functoolslru_cachemaxsizenone-with-shorthand. 

Tested with ruff 0.0.222

**Comment by charliermarsh** [comment]
Thank you! Fixing now. Just an oversight.

**Comment by charliermarsh** [comment]
@henribru - Yeah this is a known limitation (and pyupgrade doesn't fix that case either, IIRC). In that case, we actually need to modify the _import_ too, to include `cache`. So for now, we flag it, but can't fix it.

Another case of #835.

**Comment by henribru** [comment]
@charliermarsh That's a fair limitation, but still the message is pretty misleading since it's telling you to remove the parameters instead of changing `lru_cache` to `cache`. Just removing `max_size=None` changes the behavior, so it's not "unnecessary"

**Comment by henribru** [comment]
Note that pyupgrade separates this into two rules, one that converts `lru_cache()` into `lru_cache` and one that converts `lru_cache(max_size=None)` into `cache`. The current error message works for the first case, but it seems misleading for the second

**Comment by charliermarsh** [comment]
Ah right -- I'll modify the error message.

**Comment by charliermarsh** [comment]
Fixed in #1938.

**Comment by henribru** [comment]
Thanks again for all your hard work, I really appreciate it!

**Comment by charliermarsh** [comment]
Thanks for being persistent on this one even after I closed it out -- you were totally right!
