### ISSUE TITLE
F841 fix results in statement without effect or syntax error for multiline assignments

### ISSUE THREAD

**Issue by sbrugman** [charliermarsh/ruff#1917]
### Example for statement without effect

```
def fn(a, b):
    sample = a if a is not None \
        else b
    pass
```

Result:

```
def fn(a, b):
   a if a is not None \
        else b
    pass
```

Expected:
```
def fn(a, b):
    pass
```

### Example for invalid syntax

```
def fn(a, b):
    sample = (
        a
        if a is not None
        else b
    )
    pass
```

Result:

```
def fn(a, b):
    a
        if a is not None
        else b
    )
    pass
```

Expected:
```
def fn(a, b):
    pass
```

### To reproduce

`ruff example.py --select F841 --fix`

## Proposed solution
- Make fix take multiline assignments into account (https://github.com/charliermarsh/ruff/blob/main/src/rules/pyflakes/rules/unused_variable.rs#L53)

### Version

ruff 0.0.223

**Comment by charliermarsh** [comment]
Definitely looks like a bug (in the latter case — the former was us being conservative, but we could be more aggressive). Will take a look! Thanks for the clear issue.
