### ISSUE TITLE
Error: wanted string or inline table for key `tool.ruff.target-version`

### ISSUE THREAD

**Issue by thisfred** [charliermarsh/ruff#1924]
Since today I'm suddenly getting this error when I run ruff (either standalone or under pre-commit):

```
Error: wanted string or inline table for key `tool.ruff.target-version`
```

The strange thing is, it makes no difference whether that string is present in my pyproject.toml, like:

```toml
[tool.ruff]
target-version = "py38"
```

or whether I remove it (or entirely remove pyproject.toml), and run either:

```bash
ruff --target-version=py38 some_file.py
```
or:
```bash
ruff some_file.py
```

I am entirely willing to believe I somehow messed up my virtual environment, but I've rebuilt it from scratch several times now, and also tried running ruff as part of pre-commit, which installs its own dependencies, so I'm really mystified.

I've tried going back versions, and it doesn't seem to make a difference either, always the same error.

On Friday this was all working for me. I did update to a newer version of ruff today, so I'm wondering if something changed, and that something is being cached outside of the python env even when I try to downgrade to older versions using pip.

versions I've tried:

0.0.223
0.0.219
0.0.209

**Comment by thisfred** [comment]
I've tried running with `-v` or `--verbose` but no more information is output.

**Comment by charliermarsh** [comment]
Very strange... What happens if you create a file like:

```toml
[tool.ruff]
target-version = "py38"
```

And then run explicitly with `ruff --config ./pyproject.toml some_file.py`?

**Comment by thisfred** [comment]
Explicitly passing the config file does seem to work, so that's a  workaround, but I'm still completely baffled as to why it doesn't work with the default file location. (I am sure it is able to find the file there, because when in desperation I changed the option name to `target_version` (with an underscore instead of a dash), it complained that that option doesn't exist...

**Comment by thisfred** [comment]
As another data point, if I pass pyproject.toml explicitly with --config, it doesn't complain, even when `target-version` is not set in that file at all, and additionally, if I name the file anything other than `pyproject.toml`, it fails with ```
Unrecognized settings file: `/path/to/project/mypyproject.toml`, no matter the contents of that file.
```

**Comment by charliermarsh** [comment]
(Yeah I believe we rely on the name, because we have to distinguish between `ruff.toml` and `pyproject.toml` files.)

**Comment by charliermarsh** [comment]
Is it possible that you have a "user" pyproject.toml file in the global config dir specified [here](https://github.com/dirs-dev/directories-rs#basedirs)?

**Comment by thisfred** [comment]
I don't think so: I do have one, one directory level up from the project I'm working in, but that's above the git root, yet still below my home directory, and not in one of the locations specified there. I'll do some more digging.

What I wonder is if it is somehow related to `target-version` being specified in other (non-ruff) stanzas in the pyproject.toml. Black has its own key by that name, which takes an array rather than a string, for instance, but I would expect ruff's parser to ignore everything that doesn't start with `[tool.ruff...]`, so that's probably also not it.

**Comment by thisfred** [comment]
oh, ok, actually your suggestion was correct. With the following directory structure:

```
~/
  all_projects/
    pyproject.toml
    the_project/
      .git
      pyproject.toml
```

the pyproject.toml one level above the working directory does seem to get picked up when running ruff from within `the_project/`.

**Comment by thisfred** [comment]
Maybe this is intended behavior, but it did surprise me a little.

**Comment by charliermarsh** [comment]
Oh, ok, great! (And thanks for the kind words :))

Yeah, that behavior _is_ intended. When we check a given file, we find the first `pyproject.toml` in the same directory, or any parent directory.

I totally understand how that could be surprising. It does have some benefits though. For one thing, it makes it possible to run Ruff across a bunch of separate Python projects with a single `ruff` invocation, since each file will use the "right" `pyproject.toml`. It also means that you can run `ruff` from any directory, and it'll lint any given file the same way (which wouldn't be true if, e.g., we used the `pyproject.toml` from the current working directory).

There's a little bit more on that strategy in [the docs](https://github.com/charliermarsh/ruff#pyprojecttoml-discovery). As always, suggestions welcome on how to make it clearer or less surprising :)
