### ISSUE TITLE
document pyupgrade min py version determination

### ISSUE THREAD

**Issue by nstarman** [charliermarsh/ruff#1937]
In pyupgrade one can pass the minimum python version for which pyupgrade should find and apply improvements: e.g. ``—py29-plus``. I can't find documentation for how this is done in Ruff's implementation of pyupgrade.

**Comment by sbrugman** [comment]
`target-version` is used for that https://github.com/charliermarsh/ruff#target-version

**Comment by nstarman** [comment]
Thanks!
