### ISSUE TITLE
flake8-commas autofixes even when rule is not included in list of fixables

### ISSUE THREAD

**Issue by rhkleijn** [charliermarsh/ruff#1939]
Using version 0.0.224 of ruff I ran into the following with the flake8-commas rules:

Consider this minimal example:
```python
# nocomma.py
print(
    1
)
```

When running `ruff nocomma.py --select COM --fix --fixable I001` the file gets changed even though the `COM` rules were not included in the list of fixables:

```python
# nocomma.py
print(
    1,
)
```
I would expect it to just report the violation and not alter any files.

**Comment by charliermarsh** [comment]
Let me take a look!

**Comment by charliermarsh** [comment]
Sorry, that's just an oversight. Will fix now.
