### ISSUE TITLE
Possible overlap between SIM300 and PLC2201

### ISSUE THREAD

**Issue by rabelux** [charliermarsh/ruff#1954]
From my understanding the rules [C2201](https://pylint.pycqa.org/en/latest/user_guide/messages/convention/misplaced-comparison-constant.html) (PLC2201 in ruff) and [SIM300](https://github.com/MartinThoma/flake8-simplify#sim300) are pretty much the same.
If that's the case I'd suggest to drop one in favour of the other.

PLC2201 got introduced in #1023, SIM300 in #1539.

**Comment by charliermarsh** [comment]
Yeah I agree with this. My gut reaction is to remove `PLC2201. In the future, we should be able to map rules to multiple codes for compatibility purposes (see, e.g., #1941 which lays the foundation), although there are some questions to answer around how that works with `--select ALL`, `# noqa` , etc.

**Comment by charliermarsh** [comment]
These rules are actually _slightly_ different because the Pylint rule flags any comparison (e.g., `i >= 5`).

**Comment by charliermarsh** [comment]
I'll probably extend SIM300 to flag those cases too.
