### ISSUE TITLE
Automatically enable `--format=github` if the environment looks like GitHub Actions?

### ISSUE THREAD

**Issue by woodruffw** [charliermarsh/ruff#1973]
Thanks again for maintaining `ruff`! I'm trying to roll it out to more projects at Trail of Bits, and it's been very satisfying to see the speedups we're getting/the additional things it can catch 🙂 

This is a feature request for a (very small) QoL improvement: automatically enabling `--format=github` (`SerializationFormat::Github`) if `ruff`'s invoked environment looks like GitHub Actions.

My rationale here is that GitHub Actions have a distinguishable environment (you can always be relatively confident you're in one if both `CI` and `GITHUB_ACTIONS` are set), and the act of being invoked in a GitHub Action *probably* implies user intent to have annotations rather than the standard formatting. This also makes the "intelligent" choice possible even when `ruff` is nested in a build system or task runner that's meant to be run both locally and in CI, e.g. `make lint` will do the right thing in both cases.

If there's interest, I'm happy to submit a PR for this!

## Downsides

This arguably makes `ruff` too clever, which is a good reason to not want this! I'm totally happy using one of the alternatives below if this is how you feel as `ruff`'s maintainers; just figured I'd open the issue to gauge interest.

## Alternatives considered

* Setting `RUFF_FORMAT=github` explicitly. This would work perfectly fine!
* Passing `--format=github` through all of our various makefiles/build abstractions. This is workable, just a little tedious 🙂

**Comment by edgarrmondragon** [comment]
@woodruffw this was actually removed a few weeks ago: https://github.com/charliermarsh/ruff/pull/1697

**Comment by woodruffw** [comment]
Ah, dang -- yeah, I could have sworn I saw this behavior before, but I thought I had imagined it!

The rationale there makes sense to me! Using `RUFF_FORMAT` is no major lift for us, so I'll go with that.

Thanks for the fast response!

**Comment by charliermarsh** [comment]
Thanks for the thoughtful issue @woodruffw (and so glad to hear that Ruff is working for you). And thank you @edgarrmondragon for following up!
