### ISSUE TITLE
Getting F821 Undefined name "xyz" for typing.Literal values when imported indirectly

### ISSUE THREAD

**Issue by alisaifee** [charliermarsh/ruff#1976]
# Description

Ruff complains with `F821 Undefined name "xyz"` for the values described in arguments typed as `typing.Literal`. I was however only able to reproduce this when `Literal` is imported indirectly (i.e. not `from typing import Literal`).

As an example, the following file passes all checks:

```py
from typing import Literal

a: Literal["fu", "bar"] = "fu"
a = "bar"
```

But this does not:

- x.py
  ```py
  from typing import Literal
  __all__ = ["Literal"]
  ```

- y.py
  ```py
  from x import Literal
  a: Literal["fu", "bar"] = "fu"
  a = "bar"
  ```
- Output:
  ```
  $ ruff y.py
  y.py:2:12: F821 Undefined name `fu`
  y.py:2:18: F821 Undefined name `bar`
  ```

- Reproduced without any configuration changes.
- Ruff version:
  ```
  $ ruff --version
  ruff 0.0.225
  ```

**Comment by charliermarsh** [comment]
Yeah we don't track that the re-exported `Literal` in that case is the same as `typing.Literal`. 

We do have something to support this use-case though. If you want to treat every member of `x` as if it's a re-export of a `typing` member, you can do:

```toml
[tool.ruff]
typing-modules = ["x"]
```

(Relevant docs are here: https://github.com/charliermarsh/ruff#typing-modules)

**Comment by charliermarsh** [comment]
(The canonical use-case for this is projects that have some kind of compatibility shim over `typing` and `typing-extensions`.)

**Comment by alisaifee** [comment]
Neat, that is exactly the use case ([reference](https://github.com/alisaifee/coredis/blob/master/coredis/typing.py)).

**Comment by alisaifee** [comment]
I'll close this as it is clearly pointed out in the documentation (😅)

**Comment by charliermarsh** [comment]
Oh nice! Good to know that there are more examples of this, and glad it solves your problem :)

**Comment by henryiii** [comment]
Solves my problem too, thank you! Though I use relative imports, so it seems to not be triggering on `from .._compat.typing import Literal`. If I change it to absolute, then it works.

**Comment by charliermarsh** [comment]
Ah good call -- filed as #2005!

**Comment by charliermarsh** [comment]
@henryiii - Heads up, I also checked out `scikit_build_core` and verified that (e.g.) `F821` errors aren't being triggered for Literals with `typing-modules = ["scikit_build_core._compat.typing"]`.
