### ISSUE TITLE
make SIM201 fixer exceptions for comparision methods? 

### ISSUE THREAD

**Issue by spaceone** [charliermarsh/ruff#1986]
`SIM201` makes the following changes:

```
     def __ne__(self, other):
-        return not self == other
+        return self != other
```
This will of course end in a endless recursion.

Maybe the checker or fixer could ignore the occurrence in `__lt__`, `__le__`, `__eq__`, `__ne__`, `__ge__`, `__gt__`.

**Comment by charliermarsh** [comment]
Makes sense, we can fix this.
