### ISSUE TITLE
`typing-modules` should respect relative imports

### ISSUE THREAD

**Issue by charliermarsh** [charliermarsh/ruff#2005]
See: #1976.

**Comment by sbrugman** [comment]
Some relevant code sections in case anyone wants to take this (played around a bit, no fix yet):
- Import bindings: https://github.com/charliermarsh/ruff/blob/main/src/checkers/ast.rs#L3802
- Diagnostic:  https://github.com/charliermarsh/ruff/blob/main/src/checkers/ast.rs#L3890
- Matching 'Load' e.g.`Literal[...]`: https://github.com/charliermarsh/ruff/blob/main/src/checkers/ast.rs#L3266
- Checking for `typing-modules`: https://github.com/charliermarsh/ruff/blob/main/src/python/typing.rs#L214
- Relative imports: https://github.com/charliermarsh/ruff/blob/main/src/checkers/ast.rs#L237

**Comment by henryiii** [comment]
Closed by https://github.com/charliermarsh/ruff/pull/2615 ?

**Comment by charliermarsh** [comment]
Yes, thank you, I linked the wrong issue 🤦
