### ISSUE TITLE
RFE: infer `target-version` from project metadata

### ISSUE THREAD

**Issue by scop** [charliermarsh/ruff#2039]
`target-version` could in many cases be inferred from project metadata: 
- https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#requires-python
- https://packaging.python.org/en/latest/specifications/core-metadata/#core-metadata-requires-python

Would be great to see ruff do that to eliminate one maintenance chore.

Black is moving toward doing that, too. The implementation over there is obviously somewhat different, because they still take a list of target versions whereas ruff takes the minimum one (which I think is the better, yet less flexible approach). Perhaps some of that work can be reused in ruff: https://github.com/psf/black/pull/3219

**Comment by charliermarsh** [comment]
Perhaps we can use https://github.com/konstin/pep440-rs from @konstin to power the version parsing?

**Comment by ilkersigirci** [comment]
FYI: [black#3219](https://github.com/psf/black/pull/3219) was merged and shipped with black [23.1.0](https://github.com/psf/black/releases/tag/23.1.0)

**Comment by manueljacob** [comment]
Black’s target version inference is currently broken: https://github.com/psf/black/issues/3581. I’m currently working on a fix and would be happy to port the solution to ruff. However, before that, #2519 should be decided.

**Comment by charliermarsh** [comment]
Nice! I'm happy to support target ranges, it's just not totally clear to me what rules they would affect and how.

**Comment by JonathanPlasse** [comment]
Black have different behaviors depending on the versions for example.

**Comment by konstin** [comment]
one thing to consider is that the behavior in https://github.com/psf/black/issues/3581 (`>3.7` still implying 3.7 code styles) is most likely unintended and imho `>3.7` (as opposed to `>3.7.1` or `>=3.7`) should raise a warning (or you could emit linter errors for ruff's own configuration :D)

**Comment by JonathanPlasse** [comment]
Should we close this issue?

**Comment by konstin** [comment]
yep

**Comment by charliermarsh** [comment]
I created https://github.com/charliermarsh/ruff/issues/3487 to track inferring this info at runtime.
