### ISSUE TITLE
Support for --builtins-ignorelist in flake8-builtins checks

### ISSUE THREAD

**Issue by ehdr** [charliermarsh/ruff#2053]
[flake8-builtins](https://pypi.org/project/flake8-builtins/) provides a [`--builtins-ignorelist` option](https://pypi.org/project/flake8-builtins/#options) that lets you ignore a custom list of builtins, e.g.:
```
flake8 --builtins-ignorelist id,copyright *.py
```

Have you considered adding the corresponding config option to ruff? I'd imagine something like
```
[tool.ruff.flake8-builtins]
builtins-ignorelist = ["id", "copyright"]
```

**Comment by charliermarsh** [comment]
Yeah we can definitely support that.

**Comment by ehdr** [comment]
Thanks @charliermarsh and @saadmk11 !

**Comment by charliermarsh** [comment]
All @saadmk11 :)
