### ISSUE TITLE
Implement `tryceratops`

### ISSUE THREAD

**Issue by sbrugman** [charliermarsh/ruff#2056]
- [x] [TC002](https://github.com/guilatrova/tryceratops/blob/main/docs/violations/TC002.md): Create your own exception
- [x] [TC003](https://github.com/guilatrova/tryceratops/blob/main/docs/violations/TC003.md): Avoid specifying long messages outside the exception class
- [x] [TC004](https://github.com/guilatrova/tryceratops/blob/main/docs/violations/TC004.md): Prefer TypeError exception for invalid type
- [x] ~[TC100](https://github.com/guilatrova/tryceratops/blob/main/docs/violations/TC100.md): Check to continue~
- [x] ~[TC101](https://github.com/guilatrova/tryceratops/blob/main/docs/violations/TC101.md): Too many try blocks~
- [x] [TC200](https://github.com/guilatrova/tryceratops/blob/main/docs/violations/TC200.md): Use raise Exception from
- [x] [TC201](https://github.com/guilatrova/tryceratops/blob/main/docs/violations/TC201.md): Simply use raise
- [x] ~[TC202](https://github.com/guilatrova/tryceratops/blob/main/docs/violations/TC202.md): Don't ignore a broad exception without even logging~
- [x] [TC300](https://github.com/guilatrova/tryceratops/blob/main/docs/violations/TC300.md): Consider adding an else block
- [x] [TC301](https://github.com/guilatrova/tryceratops/blob/main/docs/violations/TC301.md): Avoid direct raises in try body
- [x] [TC400](https://github.com/guilatrova/tryceratops/blob/main/docs/violations/TC400.md): Use logging .exception instead of .error
- [x] [TC401](https://github.com/guilatrova/tryceratops/blob/main/docs/violations/TC401.md): Do not log the exception object

**Comment by alonme** [comment]
Taking TC201

**Comment by sbrugman** [comment]
For tracking: I'm working on TC004

**Comment by karpa4o4** [comment]
@charliermarsh, i would like to do TC200.

**Comment by charliermarsh** [comment]
Awesome -- thanks all! Will review as they come in :)

**Comment by karpa4o4** [comment]
I'll take TC301 next.

**Comment by Flowake** [comment]
I'd like to implement TC400, which would be my first rule so it might take a few days. Would that be fast enough ?

**Comment by charliermarsh** [comment]
@Flowake - Sure! Take your time. Feel free to open a draft PR and ask questions there if you run into any.

**Comment by karpa4o4** [comment]
I'll take TC002 next.

**Comment by bigluck** [comment]
Ciao, I'm testing the new implementation, but I'm getting this error: `TRY300 Consider else block`

<img width="472" alt="Screenshot 2023-01-26 at 22 16 04" src="https://user-images.githubusercontent.com/1511095/214952122-ab8ea72f-51a7-400a-bd00-59f5eebd1427.png">

Isn't it a false positive?
Thanks so much

**Comment by charliermarsh** [comment]
Hmm, comparing to the original plugin, I think what's incorrect is the highlighted region. It seems to want you to do this (omitting some intermediary lines since I had to copy from the screenshot :)):

```py
try:
    assert isinstance(value, list) is False
except Exception as exc:
    msg = ""
    raise EnsureStrException(msg)
else:
    return str(value)
```

**Comment by charliermarsh** [comment]
(Fixed in #2228.)

**Comment by bigluck** [comment]
Superb, thanks!

**Comment by jacopotagliabue** [comment]
@charliermarsh me and luca should buy you lunch in BKL - ping me on [linkedin](https://jacopotagliabue.it/) or whatever and I'm happy to buy you lunch. Thanks for all the great work!

**Comment by colin99d** [comment]
Taking TC401
