### ISSUE TITLE
ERA001 triggered with SPDX license identifiers

### ISSUE THREAD

**Issue by jdknight** [charliermarsh/ruff#2064]
Have a project which uses `SPDX-License-Identifier` definitions at the top of each source file. A minimized example file (`__init__.py`) is as follows:

```
# SPDX-License-Identifier: BSD-2-Clause

def test():
    print('hello')
    return 0
```

This causes an `ERA001` error to be generated:

```
$ ruff __main__.py
__init__.py:1:1: ERA001 Found commented-out code
Found 1 error(s).
1 potentially fixable with the --fix option.
```
---

Other notes:

- `ruff --version` reports `ruff 0.0.228`
- Using `eradicate` or `flake8-eradicate` does not generate an error
- Removing the colon will prevent the error, but breaks the format of the [SPDX ID](https://spdx.dev/ids/)
- Appending `  # noqa: ERA001` will prevent the error, but results in an invalid SPDX ID value
- Existing workaround is to ignore `ERA001`

**Comment by charliermarsh** [comment]
I'm not certain _why_ that's being detected, but you can instruct the plugin to ignore comments of that form with:

```toml
[tool.ruff]
task-tags = ["SPDX-License-Identifier"]
```

Just tested it out myself, so gonna close for now, but let me know if it doesn't solve the problem for you!

**Comment by jdknight** [comment]
Thanks! Adding the identifier to the `task-tags` option removes the errors for me.
