### ISSUE TITLE
Implement `flake8-typing-imports`

### ISSUE THREAD

**Issue by Secrus** [charliermarsh/ruff#2096]
https://github.com/asottile/flake8-typing-imports

* [ ] [`TYP001`](https://github.com/asottile/flake8-typing-imports) | guard import by `TYPE_CHECKING`
* [ ] [`TYP002`](https://github.com/asottile/flake8-typing-imports) | `@overload` is broken in <3.5.2
* [ ] [`TYP003`](https://github.com/asottile/flake8-typing-imports) | `Union[Match, ...]` or `Union[Pattern, ...]` must be quoted in <3.5.2
* [ ] [`TYP004`](https://github.com/asottile/flake8-typing-imports) | `NamedTuple` does not support methods in 3.6.0
* [ ] [`TYP005`](https://github.com/asottile/flake8-typing-imports) | `NamedTuple` does not support defaults in 3.6.0
* [ ] [`TYP006`](https://github.com/asottile/flake8-typing-imports) | guard `typing` attribute by quoting

**Comment by charliermarsh** [comment]
We're planning to implement `flake8-type-checking` (#1785) which, IIUC, covers `TYP001`. I'm _not_ a huge fan of supporting `TYP002` through `TYP005` since we only support Python 3.7+. So I'm tempted _not_ to implement this plugin. Any reactions to what you'd get from #1785?

**Comment by Secrus** [comment]
Didn't notice that this is gonna be covered by #1785. Sorry for a waste of time on that

**Comment by charliermarsh** [comment]
No prob at all.

**Comment by JonathanPlasse** [comment]
The [configuration](https://github.com/snok/flake8-type-checking#configuration) of `flake8-typing-imports` is not implemented.
- [ ] `exempt-modules`
- [ ] `strict`
- [ ] `pydantic-enabled`
- [ ] `pydantic-enabled-baseclass-passlist`
- [ ] `fastapi-enabled`
- [ ] `fastapi-dependency-support-enabled`
- [ ] `cattrs-enabled`

We should reopen this issue.

**Comment by charliermarsh** [comment]
@JonathanPlasse - I think you're referring to `flake8-type-checking`? I've opened a new issue for configuration at #2195. (I think a new issue is appropriate.)

**Comment by JonathanPlasse** [comment]
Oops, my bad. :sweat_smile:

**Comment by skshetry** [comment]
`TYP001` is a bit different than the checks in `flake8-type-checking`. It checks if the `typing` module has a given attribute or not for the specific python version.

So, if I have the following import with `min_python_version=3.8.0` set:
```python
from typing import TypeGuard
```

it'll complain as:
```console
script.py:1:1: TYP001 guard import by `if TYPE_CHECKING:`: TypeGuard
(not in 3.8.0, 3.8.1, 3.8.2, 3.8.3, 3.8.4, 3.8.5, 3.8.6, 3.8.7, 3.8.8, 3.8.9, 3.8.10, 3.8.11, 3.8.12, 3.8.13, 3.8.14, 3.8.15, 3.9.0, 3.9.1, 3.9.2, 3.9.3, 3.9.4, 3.9.5, 3.9.6, 3.9.7, 3.9.8, 3.9.9, 3.9.10, 3.9.11, 3.9.12, 3.9.13, 3.9.14, 3.9.15)
from typing import TypeGuard
^
```

as `TypeGuard` was only introduced in 3.10.

**Comment by charliermarsh** [comment]
@skshetry - I think you might be confusing this with [`flake8-typing-imports`](https://github.com/asottile/flake8-typing-imports) (which has different rules, and uses a different code prefix)

**Comment by charliermarsh** [comment]
@skshetry - Totally and that does seem useful. (I thought `flake8-typing-imports` was only relevant for linting pre-3.7 code, which we don't really support, but I misunderstood that check.)

**Comment by charliermarsh** [comment]
I'm tracking in #2302.
