### ISSUE TITLE
F821 on a `Literal` type that isn't directly imported by the current module

### ISSUE THREAD

**Issue by joerick** [charliermarsh/ruff#2105]
We're getting a F821 on a Literal type over in https://github.com/pypa/cibuildwheel/pull/1405 . I've isolated this to the following-

Two files are needed-

**script.py**
```python
from __future__ import annotations

from script_typing import Literal

testing_archs: list[Literal["x86_64", "arm64"]]
testing_archs = ['x86_64']
print(testing_archs)
```

**script_typing.py**
```python
import sys

if sys.version_info < (3, 8):
    from typing_extensions import Literal
else:
    from typing import Literal
```

Here's what happens:
```sh
$ ruff --isolated --fix script.py 
script.py:5:29: F821 Undefined name `x86_64`
script.py:5:39: F821 Undefined name `arm64`
Found 2 error(s).
```

This happens without any pyproject.toml configuration

Version: `ruff 0.0.230`.

*p.s. ruff seems pretty incredible! the speed 🤯*

**Comment by sbrugman** [comment]
There is an option that should help in this case: https://github.com/charliermarsh/ruff#typing-modules

```
[tool.ruff]
typing-modules = ["cibuildwheel.typing"]
```

**Comment by joerick** [comment]
Ah, thanks for pointing that out, I suppose @henryiii found that option before I did!

Then I think the issue is perhaps the relative import. See this new recreation:

 -  📁 `mymodule`

     -  📄 `__init__.py`
     -  📄 `script.py`

        ```python
        from __future__ import annotations

		from .script_typing import Literal

		testing_archs: list[Literal["x86_64", "arm64"]]
		testing_archs = ['x86_64']
		print(testing_archs)
		```
	 -  📄 `script_typing.py`

	    ```python
	    import sys

		if sys.version_info < (3, 8):
		    from typing_extensions import Literal
		else:
		    from typing import Literal

		__all__ = ['Literal']

		```

 -  📄 `pyproject.toml`

    ```toml
    [tool.ruff]
	typing-modules = ['mymodule.script_typing']
	```

```
$ ruff mymodule                     
mymodule/script.py:5:29: F821 Undefined name `x86_64`
mymodule/script.py:5:39: F821 Undefined name `arm64`
Found 2 error(s).
```

**Comment by joerick** [comment]
In this version, changing the import in script.py to `from mymodule.script_typing import Literal` silences the error.

**Comment by henryiii** [comment]
Dup #2005

**Comment by joerick** [comment]
Ah, I didn't know enough about typing-modules to realise this was dupe. Apologies!

**Comment by charliermarsh** [comment]
All good, thanks everyone for helping out here!
