### ISSUE TITLE
D401 raised on classes and modules in v 0.0.230

### ISSUE THREAD

**Issue by niccolomineo** [charliermarsh/ruff#2109]
Hi, just reporting that v. 0.0.230 raises a `D401` for classes and modules too. Is this on purpose?

**Comment by charliermarsh** [comment]
Ah I thought we had fixed that in #2071! Do you mind linking a snippet to reproduce? Thanks :)

**Comment by charliermarsh** [comment]
Oh wait, sorry, that commit didn't make it into v0.0.230.

**Comment by charliermarsh** [comment]
I will cut v0.0.231 now.

**Comment by edgarrmondragon** [comment]
@charliermarsh I think the `v0.0.231` release failed because github terminated it after 6 hours: https://github.com/charliermarsh/ruff/actions/runs/3989207120/jobs/6841354318

**Comment by charliermarsh** [comment]
Oh thank you, let me try it again.

**Comment by charliermarsh** [comment]
Ok, release is out, hopefully fixed!
