### ISSUE TITLE
RET503 - broken autofix/false positive

### ISSUE THREAD

**Issue by akx** [charliermarsh/ruff#2119]
I found a snippet where RET503 erroneously adds a `return` inside a loop.

The violation is also a bit suspect; it's not uncommon to early-return from a generator.

### A minimal code snippet that reproduces the bug
```
class X:
    def prompts(self, foo):
        if not foo:
            return []

        for x in foo:
            yield x
            yield x + 1
```
> ret503_bug.py:8:13: RET503 Missing explicit `return` at the end of function able to return non-`None` value
```diff
$ cargo run -- --select=RET --no-cache --isolated ./ret503_bug.py --fix --diff
--- ret503_bug.py
+++ ret503_bug.py
@@ -6,3 +6,4 @@
         for x in foo:
             yield x
             yield x + 1
+            return None
```
### The current Ruff version (`ruff --version`)
cc63a4be6a1bce9b4045826cece50cd84d61d876, but reproducable with 0.0.230 too

**Comment by charliermarsh** [comment]
It's probably safest to disable these checks entirely for generators.
