### ISSUE TITLE
Implement `pyupgrade` import replacements

### ISSUE THREAD

**Issue by stinodego** [charliermarsh/ruff#2152]
I noticed Ruff is missing this nice lint from pyupgrade:
https://github.com/asottile/pyupgrade#import-replacements

Basically, it replaces `from typing import Sequence` with the new `from collections.abc import Sequence` and similar.

**Comment by charliermarsh** [comment]
There's a PR out for this (#2049) from @colin99d but I haven't had a chance to review it yet!

**Comment by stinodego** [comment]
Oh great, thanks! I had missed that. Will keep an eye on that one.

Feel free to close this in favor of https://github.com/charliermarsh/ruff/issues/827 ; otherwise I'll close this myself once the PR is merged.
