### ISSUE TITLE
COM812 causes syntax error for Python 3.3

### ISSUE THREAD

**Issue by spaceone** [charliermarsh/ruff#2153]
1.
```
$ cat foo.py
def foo(*a,**kw): return (a, kw)
foo(
    1,2,3,
    *[4,5,6],
    foo=7
)
$ ruff --isolated --select COM812 --target-version py33 --fix foo.py                                                 
Found 1 error(s) (1 fixed, 0 remaining).
$ docker run -it -v "$PWD":/usr/src/myapp python:3.3 python /usr/src/myapp/foo.py
  File "/usr/src/myapp/foo.py", line 6
    )
    ^
SyntaxError: invalid syntax
$ cat foo.py
def foo(*a,**kw): return (a, kw)
foo(
    1,2,3,
    *[4,5,6],
    foo=7,
)
```

2. which is the minimum supported Python version? This could be mentioned explicitly in the README. (we are still supporting Python 2.7 for ~2 years). The command line accepts `py33` as minimum.
3. the format for `--target-version` can not easily be guessed and could be added as example to the `--help` output. `3.5` is invalid while `py35` is valid.

**Comment by charliermarsh** [comment]
We only support Python 3.7 onward. I'll clarify this in a few places.
