### ISSUE TITLE
B007 may break code

### ISSUE THREAD

**Issue by spaceone** [charliermarsh/ruff#2156]
```
$ cat foo.py
FMT = '{foo} {bar}'
for foo, bar in [(1, 2)]:
    if foo:
        print(FMT.format(**locals()))
$ ruff --select B007 --fix foo.py
Found 1 error(s) (1 fixed, 0 remaining).
$ cat foo.py
FMT = '{foo} {bar}'
for foo, _bar in [(1, 2)]:
    if foo:
        print(FMT.format(**locals()))
$ python3 foo.py
Traceback (most recent call last):
  File "foo.py", line 4, in <module>
    print(FMT.format(**locals()))
KeyError: 'bar'
```

I don't know what to do with this. Maybe just ignore it / WONTFIX.
What could be possible to mark some fixers as safe/unsafe for side-effects.

**Comment by charliermarsh** [comment]
In this case, we should probably detect the use of `locals` and avoid flagging B007 at all. So I think I consider this a bug...

But separately: we are working on marking fixes as safe and unsafe, and allowing users to set their desired fix level.

You can also turn off autofix for B007 or any set of rules by adding this to your `pyproject.toml`:

```toml
[tool.ruff]
unfixable = ["B007"]
```
