### ISSUE TITLE
TRY200 false positive for re-raising original/currently handled exception

### ISSUE THREAD

**Issue by scop** [charliermarsh/ruff#2171]
ruff 0.0.233 issues TRY200 for the following cases:

```python
try:
    raise RuntimeError
except Exception:
    # ...do something...
    raise
```

```python
try:
    raise RuntimeError
except Exception as ex:
    # ...do something...
    raise ex
```

I don't think TRY200 should be issued when re-raising the exception currently being handled (plain `raise`) or when the original exception is being explicitly re-raised.

**Comment by charliermarsh** [comment]
Yeah that seems like an error to me.

**Comment by charliermarsh** [comment]
Tryceratops doesn't flag that, so definitely a bug.

**Comment by charliermarsh** [comment]
I'll fix this real quick, so that we avoid ever releasing this version. (Are you building from source? :))

**Comment by scop** [comment]
Thanks! Not building from source, looks like I managed to grab 0.0.233 before it was yanked.
