### ISSUE TITLE
Suggest fixes to users

### ISSUE THREAD

**Issue by cnpryer** [charliermarsh/ruff#218]
Hi! Love this project. Looking forward to helping out in whatever way I can.

If not already implemented, are there plans to offer suggestions for those auto-fixable changes?

One thing I enjoy about `clippy` is using it as a learning instrument. New suggested changes help me understand what might be idiomatic, what may not. As a new Python user I'd love to have that same experience.

**Comment by charliermarsh** [comment]
That's a nice idea! Right now, we have a `--fix` flag that will automatically fix a small subset of issues. It'd be cool to suggest those fixes directly to the user (as in clippy) when `--fix` is disabled.

**Comment by charliermarsh** [comment]
I would say we now do this. It's not exactly the same as Clippy, but we do show you the fix message with `--show-source`.
