### ISSUE TITLE
`--add-noqa` is unintuitive

### ISSUE THREAD

**Issue by not-my-profile** [charliermarsh/ruff#2187]
I would expect `--add-noqa` to only add the directive to violations that ruff cannot fix but it in fact adds it everywhere.

Even worse the following just ignores the `--fix` option and does not fix anything but adds `noqa` everywhere:

```
ruff foo.py --add-noqa --fix
```

I think at least the former should be clearly explained in the option description in `--help` and the latter should result in an error until that is supported.

**Comment by charliermarsh** [comment]
I think a reasonable thing to do for now would be to warn users that `--fix` is incompatible with `--add-noqa` (and recommend that users run `ruff --fix .` and then `ruff --add-noqa .`).

I view `--add-noqa` as something that's run once, or perhaps a few times, as an upgrade tool. In that light, it might be fine as a separate subcommand.
