### ISSUE TITLE
Wrong `respect-gitignore` example in Readme/Reference

### ISSUE THREAD

**Issue by johbrust** [charliermarsh/ruff#2191]
Hi,

the example description in [this Readme/Reference section](https://github.com/charliermarsh/ruff#respect-gitignore) on how to set the `respect-gitignore` option via `toml` file is shown as `respect_gitignore` (with an underscore instead of a hyphen), which will cause a TOML parse error.

ruff version 0.0.235

**Comment by charliermarsh** [comment]
Thanks!
