### ISSUE TITLE
Implement configuration options from `flake8-type-checking`

### ISSUE THREAD

**Issue by charliermarsh** [charliermarsh/ruff#2195]
- [x] `exempt-modules`
- [x] `strict`
- [ ] `pydantic-enabled`
- [ ] `pydantic-enabled-baseclass-passlist`
- [ ] `fastapi-enabled`
- [ ] `fastapi-dependency-support-enabled`
- [ ] `cattrs-enabled`

See: #1785

**Comment by charliermarsh** [comment]
@sondrelg - not urgent, but any input on these options based on your experience? Any thing you'd warn me about, etc.?

**Comment by sbrugman** [comment]
Is it feasible to create another script in addition to `add_rule.py` and `add_plugin.py`, e.g. `add_option.py`?
Not sure if this can be automated, didn't look into it. Could be a good thought to have in mind when new options are implemented.

ps. @charliermarsh some other options are labelled `isort` but I think should also have the `configuration` tag

**Comment by sasanjac** [comment]
I don't understand the problem for `pydantic` support. Can't we just assume that every class that has `pydantic.BaseModel` as a base class needs to have the types of their class attributes checked at runtime?

**Comment by charliermarsh** [comment]
Oh, I believe we do now require that class attributes are present at runtime.

**Comment by charliermarsh** [comment]
Weird to link to a tweet for reference but: https://twitter.com/charliermarsh/status/1623389778375843840

**Comment by sondrelg** [comment]
> I don't understand the problem for `pydantic` support. Can't we just assume that every class that has `pydantic.BaseModel` as a base class needs to have the types of their class attributes checked at runtime?

What if you do this?

```python
# a.py

class AppBaseModel(BaseModel):
    name: str  # every model in my app will have this attribute
``` 

```python
# b.py 
from a import AppBaseModel

class Foo(AppBaseModel):
```

It's been a while since we discussed it, but I think there's a number of way to assume incorrectly. And since the consequence of a false negative is potential runtime errors in your prod app, we should try to avoid that at all costs.

Does that make sense @sasanjac?

**Comment by sasanjac** [comment]
> 



> Does that make sense @sasanjac?

No, because `Foo.mro()` still contains `BaseModel`.

**Comment by charliermarsh** [comment]
@sondrelg - I don't _think_ so but I haven't really looked back on it. You can see the docs [here](https://docs.python.org/3/reference/simple_stmts.html#annotated-assignment-statements). The logic is that if you're in a module or class scope, the annotations need to be added to `__annotations__`, so they end up getting evaluated at runtime. In a function scope, there's no such construct, so they just get skipped.

There are some comments from Python core contributors in that thread: https://twitter.com/MissingClara/status/1623435238289608709

**Comment by sasanjac** [comment]
> nvm, my brain left me there for a bit.
> 
> > Does that make sense @sasanjac?
> 
> ~No, because `Foo.mro()` still contains `BaseModel`.~

But can't we then turn the procedure around? Explicitely state all base classes that inherit from BaseModel?

**Comment by ofek** [comment]
Tangentially related: is there a way to enforce imports that must be present like `from __future__ import annotations`?

**Comment by charliermarsh** [comment]
@ofek - Yeah, we support it via [`required-imports`](https://github.com/charliermarsh/ruff#required-imports) (which maps to [`I002`](https://github.com/charliermarsh/ruff/blob/main/docs/rules/missing-required-import.md)).

**Comment by sondrelg** [comment]
> > nvm, my brain left me there for a bit.
> > > Does that make sense @sasanjac?
> > 
> > 
> > ~No, because `Foo.mro()` still contains `BaseModel`.~
> 
> But can't we then turn the procedure around? Explicitely state all base classes that inherit from BaseModel?

The example above isn't the worst case - we could have `n` layers of base classes and mixins to traverse located in `m` different files. Since flake8 operates in a one-file-at-the-time type of way, leaving the scope of the single file was not something that seemed worth the investment in the original plugin, but maybe ruff has some foundations that make it worth considering :slightly_smiling_face:

**Comment by sasanjac** [comment]
Yeah I totally forgot about that. But why don't leave it up to the user to specify all `pydantic` base classes in the config file? I mean with the default config, the user will encounter runtime errors anyway.

**Comment by sondrelg** [comment]
Mostly because no one has requested it :slightly_smiling_face:  How will they run into runtime errors anyway?

**Comment by sasanjac** [comment]
Because with the default config they will move all typing imports into the `TYPE_CHECKING` block.
For me it just seems the most straightforward way to have something like `type-checking-pydantic-enabled-baseclasses` instead of dropping the config options.

**Comment by sondrelg** [comment]
Maybe just call it `type-checking-pydantic-baseclasses`? Yeah I don't see why not if you want that feature :slightly_smiling_face:

**Comment by sasanjac** [comment]
Ok, now I only have to learn rust 🙈

**Comment by charliermarsh** [comment]
The remaining options are covered by #3292 (albeit with an API that differs from the original `flake8-type-checking`), thanks to @sasanjac!
