### ISSUE TITLE
F841 reported when locals() is called in current scope

### ISSUE THREAD

**Issue by jack1142** [charliermarsh/ruff#220]
I found this while comparing some of pylint's errors to flake8/ruff's - pyflakes ignores unused variables if `locals()` is used in the current scope:
```py
def locals_example_defined_before():
    value = 42  # no message on flake8 but ruff reports it
    return locals()
```

Looking at pyflakes's unit tests, they also have a test case checking that the message still gets reported if locals() was called in a different scope:
```py
def a():
    locals()
    def a():
        b = 1
        return
```

**Comment by charliermarsh** [comment]
Thanks, this is a known limitation, needs to be fixed!
