### ISSUE TITLE
Issues with `B009` and `B010` autofix

### ISSUE THREAD

**Issue by WilliamJamieson** [charliermarsh/ruff#2202]
I found that running the autofix for `B009` and `B010` can break code in a very specific circumstance, specifically when it is applied to:

- https://github.com/asdf-format/asdf/blob/ae9b77cdc8d69f1f1fd136ff48c9a523a86c18af/asdf/types.py#L85
-  https://github.com/asdf-format/asdf/blob/ae9b77cdc8d69f1f1fd136ff48c9a523a86c18af/asdf/types.py#L149

Will deeply break my code.

Based on this discussion thread: https://github.com/astropy/astropy/pull/14275#discussion_r1072555924, I think the issue is in how python handles `__X` access meaning this issue is likely limited to only cases where the attribute being set or gotten is of the form `__X`.

I think the solution might be to avoid making an autofix when the fixed string in question has the prefix `__` but no suffix `__`.

**Comment by charliermarsh** [comment]
Oh interesting! Will fix now.

**Comment by charliermarsh** [comment]
Thank you for flagging this.

**Comment by charliermarsh** [comment]
Ah right, ok, the double underscore causes name mangling.

**Comment by WilliamJamieson** [comment]
Thanks for such a fast response!

**Comment by sciyoshi** [comment]
Oh sorry @charliermarsh - didn't see you were already fixing! 😅

**Comment by charliermarsh** [comment]
No prob! Thanks so much for hopping on it!
