### ISSUE TITLE
configurable list for A001 exceptions

### ISSUE THREAD

**Issue by spaceone** [charliermarsh/ruff#2203]
the config could have a list of exceptions for A001, A002, A003 builtin-variable-shadowing.
For example `license` and `copyright` are not very useful and can imho be overwritten.

**Comment by spaceone** [comment]
See also https://docs.python.org/3/library/constants.html#constants-added-by-the-site-module

These constants aren't even available always.

**Comment by charliermarsh** [comment]
Makes sense. PR welcome :) I likely won't get to it today.

**Comment by charliermarsh** [comment]
Good call :)

**Comment by axitkhurana** [comment]
Is that what https://github.com/charliermarsh/ruff#builtins-ignorelist is for or did I misunderstand that config?

**Comment by charliermarsh** [comment]
Oh, you're right, that's exactly what it's for. I just totally forgot we supported it >.<
