### ISSUE TITLE
Support pydocstyle `ignore_decorators` and `property_decorators` options

### ISSUE THREAD

**Issue by edgarrmondragon** [charliermarsh/ruff#2205]
- [x] `ignore-decorators`: ignore any functions or methods that are decorated by a function with a name fitting the `<decorators>` regular expression (https://github.com/charliermarsh/ruff/pull/3229)
- [x] `property-decorators`: consider any method decorated with one of these decorators as a property, and consequently allow a docstring which is not in imperative mood

**Comment by charliermarsh** [comment]
Should `pycodestyle` in the issue name be `pydocstyle`?

**Comment by edgarrmondragon** [comment]
> Should `pycodestyle` in the issue name be `pydocstyle`?

Yup 😅. Updated

**Comment by charliermarsh** [comment]
I think we should probably do this not via regex, but via module identifiers, for consistency with other settings:

```toml
[tool.ruff.pydocstyle]
ignore-decorators = ["foo.bar.baz", ...]
```

**Comment by edgarrmondragon** [comment]
I'm working on `ignore-decorators`

**Comment by staticssleever668** [comment]
I'll work on `property-decorators`

**Comment by charliermarsh** [comment]
@staticssleever668 - Awesome, thank you! https://github.com/charliermarsh/ruff/pull/3229 is probably a good reference, hopefully helpful.
