### ISSUE TITLE
ruff --explain BLE001 wrong

### ISSUE THREAD

**Issue by spaceone** [charliermarsh/ruff#2210]
```
$ ruff --explain BLE001
blind-except

Code: BLE001 (flake8-bugbear)

Message formats:

* Do not catch blind exception: `{name}
```
says it comes from `flake8-bugbear` while it comes from https://pypi.org/project/flake8-blind-except/.

I guess it's because of substring matching, where `B` is sorted before `BLE`.

**Comment by charliermarsh** [comment]
\cc @not-my-profile, maybe from a recent refactor?

**Comment by not-my-profile** [comment]
Ah yes my bad ... fix incoming!

**Comment by charliermarsh** [comment]
Thanks!
