### ISSUE TITLE
SIM103 changes behavior

### ISSUE THREAD

**Issue by spaceone** [charliermarsh/ruff#2218]
```
$ cat foo.py
def foo(bar: int) -> bool:
        if bar:
                return True
        else:
                return False

assert foo(1) is True
$ python3 foo.py
$ ruff --isolated --select SIM103 --fix foo.py                                                                                                                              
Found 1 error (1 fixed, 0 remaining).
$ cat foo.py                                                                                                                                                                
def foo(bar: int) -> bool:
        return bar

assert foo(1) is True
$ python3 foo.py
Traceback (most recent call last):
  File "foo.py", line 4, in <module>
    assert foo(1) is True
AssertionError
```

maybe `SIM103` could try to detect if the input is a boolean and otherwise wrap it in a `bool()` call?

**Comment by spaceone** [comment]
SIM210 is similar and adds `bool()` wrapping.

**Comment by charliermarsh** [comment]
This is probably difficult to avoid right now.

**Comment by charliermarsh** [comment]
I guess we could _always_ wrap in `bool()`? It'd be extra strange to write this code if `bar` were a bool.

**Comment by andersk** [comment]
Seems better to be timid than wrong; it’s easier for the user to observe that an extra `bool()` can be removed than that a missing `bool()` should be added.

We could have a heuristic that checks if the test expression is a comparator that’s known to probably return boolean? (There are exceptions like `numpy` arrays and `z3` constraints, but such exceptions probably aren’t being used as an `if` test.)

**Comment by spaceone** [comment]
this has been improved in 1dd9ccf7f61487781844d8efb38a1b869ec263f9:

`bool()` wrapping is not done for comparisions anymore.
