### ISSUE TITLE
Add RUF999 adding noqa comments

### ISSUE THREAD

**Issue by spaceone** [charliermarsh/ruff#2227]
A new code e.g. `RUF999` in combination with `--select` would be helpful which just adds `# noqa: XXX`  statements to findings of the selected codes.
Of course it should be excluded from `ALL`.

**Comment by charliermarsh** [comment]
Have you tried `ruff --add-noqa --select ...`?

**Comment by charliermarsh** [comment]
(It may not do exactly what you want, but curious if it works for this.)

**Comment by spaceone** [comment]
oh crazy! thanks!
