### ISSUE TITLE
PD011 in random code

### ISSUE THREAD

**Issue by spaceone** [charliermarsh/ruff#2229]
I had a function such as:
```
$ cat foo.py
def foo(parser):
        parser.values.foo

$ ruff --select PD011 --fix foo.py
foo.py:2:2: PD011 Use `.to_numpy()` instead of `.values`
Found 1 error.
```

I don't use pandas.
I don't know the details of this check. Maybe further access can be checked? Or if `pandas` is imported in the code?
Otherwise just close the issue and I add this to the ignore list.

**Comment by charliermarsh** [comment]
I thought we did do something like this (check if Pandas is imported). Let me check...

**Comment by charliermarsh** [comment]
I'd recommend disabling `PD` altogether... It's kind of tough to condition these on the presence of `import pandas` statements, since it's not required to import Pandas in a module in order for any given variable to be a DataFrame.

**Comment by mmdanziger** [comment]
Ran into this problem with [`torch.max`]() when you do multi-dimensional max you get a namedtuple with attrs `indices` and `values` as in the example code:

```
>>> a = torch.randn(4, 4)
>>> a
tensor([[-1.2360, -0.2942, -0.1222,  0.8475],
        [ 1.1949, -1.1127, -2.2379, -0.6702],
        [ 1.5717, -0.9207,  0.1297, -1.8768],
        [-0.6172,  1.0036, -0.6060, -0.2432]])
>>> torch.max(a, 1)
torch.return_types.max(values=tensor([0.8475, 1.1949, 1.5717, 1.0036]), indices=tensor([3, 0, 0, 1]))
```

In our code-base, this was picked up by `PD011`. Perhaps there can be logic for cases where the use of `.values` are not pandas related, such as this.
