### ISSUE TITLE
Line length should be calculated by number of chars in UTF-32 (E501)

### ISSUE THREAD

**Issue by sgryjp** [charliermarsh/ruff#223]
As of v0.0.40, ruff uses [number of bytes in UTF-8](https://github.com/charliermarsh/ruff/blob/v0.0.40/src/check_lines.rs#L38) as line length but flake8 (actually pycodestyle) uses [number of characters in UTF-32](https://github.com/PyCQA/pycodestyle/blob/2.9.1/pycodestyle.py#L279). Because of this difference, ruff may report E501 for lines containing characters which requires multiple bytes.

In the example below, '亜' (U+4E9C, `E4 BA 9C` in UTF-8) is counted as 1 by flake8 but 3 by ruff:

```shell
$ cat linelength.py
# -------1---------2---------3---------4---------5---------6---------7---------8----5678
_ = "---------------------------------------------------------------------------AAAAAAA"
_ = "---------------------------------------------------------------------------亜亜亜亜亜亜亜"
$ flake8 --max-line-length=88 linelength.py
$ ruff linelength.py
Found 1 error(s).
./linelength.py:3:89: E501 Line too long (102 > 88 characters)
```

Note that using number of characters in UTF-32 is not the best way to measure "visual" width of a line but pycodestyle [chose that way in 2016](https://github.com/PyCQA/pycodestyle/pull/345). So, to be compatible with flake8, I think ruff should follow the same way.

_(Amended the example: '亜' is actually 3 bytes in UTF-8, not 2 bytes...)_

**Comment by charliermarsh** [comment]
Resolved by #224.
