### ISSUE TITLE
EXE003 should allow a pytest hashbang?

### ISSUE THREAD

**Issue by spaceone** [charliermarsh/ruff#2233]
`EXE003` complains about the hashbang `#!/usr/bin/pytest-3` which is valid.

**Comment by charliermarsh** [comment]
Can you link to any relevant docs?

**Comment by charliermarsh** [comment]
Happy to change it, would just be nice to have something to link to.

**Comment by spaceone** [comment]
what exactly do you need? the docs at https://docs.pytest.org/ don't mention this or the command line arguments.
https://docs.pytest.org/en/7.2.x/how-to/usage.html is about the invocation but this is not listed.
the paths may also vary between operating systems.

**Comment by charliermarsh** [comment]
Yeah not sure what I was expecting. But I'll fix this anyway.
