### ISSUE TITLE
Implement isort option lines_after_imports

### ISSUE THREAD

**Issue by timbedard** [charliermarsh/ruff#2243]
The isort configuration is missing the [lines_after_imports](https://pycqa.github.io/isort/docs/configuration/options.html#lines-after-imports) option. 😭

I rely on this one. Any chance it can be added?

Thanks for the amazing tool. ❤️

**Comment by reidswan** [comment]
Mind if I tackle this one?

**Comment by charliermarsh** [comment]
Feel free!
