### ISSUE TITLE
Question: Motivation for using nightly Rust

### ISSUE THREAD

**Issue by MichaReiser** [charliermarsh/ruff#2245]
I've started contributing to ruff and was surprised why the clippy and rustfmt jobs failed on my PR, but they both passed locally. I then studied the CI logs and noticed that the CI uses the Rust nightly channels for clippy and formatting. I should have known to use the nightly channel because the CONTRIBUTING.md that states clearly the use of the nightly channel for linting and formatting. Nevertheless, having to use the nightly channels made it harder for me to contribute because I had to figure out how to update my outdated nightly channel installation, and I also didn't know which version to install (nightly is a moving target). 

That's why I wanted to raise the question of the motivation behind using the nightly channel. Is there a plan to move off nightly after certain features lands in stable? Are these features so important to us (e.g. missing some rustfmt options) to justify the added burden for contributors?

**Comment by charliermarsh** [comment]
Great question and something I'd love to get more input on.

The use of nightly, to me, is entirely about the availability of the various `rustfmt` options:

- `condense_wildcard_suffixes`
- `format_strings`
- `group_imports`
- `hex_literal_case`
- `imports_granularity`
- `normalize_comments`
- `normalize_doc_attributes`
- `reorder_impl_items`
- `wrap_comments`

(Off the top of my head, I don't know if we rely on any `clippy` checks that aren't in stable (do any such checks exist?). The decision to use nightly was entirely motivated by `rustfmt`.)

Some of these are nice-to-haves, some I find very useful and would, admittedly, be sad to lose -- most of all, I think, is the comment wrapping and normalization. But, I'm willing to be convinced that these aren't worth the added burden. (The good thing here is that removing these options wouldn't trigger any formatting changes to the existing code; they'd just prevent them from being applied going forward.)

To make them explicit, here are a few things to consider as we make this decision:

1. How much do we care about these extra `rustfmt` options?
2. Is there any sense for when we'd expect these to arrive in stable? (Not your responsibility to answer -- if anything, it's mine as the person that introducer the changes.)
3. Would we ever use nightly Rust "everywhere", to avoid the distinction between build and dev targets? (This likely introduces a lot of the same problems, but it's worth asking.)

For now, I'm leaning on reverting given that this isn't the first time it's come up, and we can always reintroduce them later when they stabilize.

**Comment by charliermarsh** [comment]
> Maybe you meant toolchain rather than targets?

Yup, that's what I meant.

**Comment by colin99d** [comment]
I can vouch that the nightly formatters have broken my code before. It split a string in between the '\' and 'n', turning a newline character into an 'n'. Not the end of the world of course, but it was annoying.

**Comment by charliermarsh** [comment]
Alright, let's nix it! I can remove later today, but anyone is welcome to beat me to it.

(I assume @MichaReiser has no objections but would be great to have his thumbs-up as the original author of the issue.)

**Comment by MichaReiser** [comment]
Sounds good to me. Not having `group_imports` and `imports_granularity` will certainly result in messier use statements but can be easily solved once the options become stable.

**Comment by charliermarsh** [comment]
Closed by #2278.
