### ISSUE TITLE
--add-noqa adds duplicated noqa comment

### ISSUE THREAD

**Issue by spaceone** [charliermarsh/ruff#2253]
```sh
$ cat foo.py
from foo import (  # noqa: F401
        bar
)
$ ruff --select F401 --add-noqa foo.py
Added 1 noqa directives.
$ cat foo.py
from foo import (  # noqa: F401
        bar  # noqa: F401
)

```

**Comment by charliermarsh** [comment]
Ah thank you. I probably didn't extend `--add-noqa` to handle those "parent-style" comments when we added support for them.

**Comment by charliermarsh** [comment]
Does `--select RUF100 --fix` remove the dupe? (Still a bug.)

**Comment by spaceone** [comment]
yes, `ruff --select RUF100,F401 --fix foo.py` restores the original version
