### ISSUE TITLE
Implement com2ann?

### ISSUE THREAD

**Issue by spaceone** [charliermarsh/ruff#2259]
https://pypi.org/project/com2ann/ is a nice project, which could be considered to be added.
it tansforms type comments into real annotations:

```diff
-def foo():
-    # type: () -> None
+def foo() -> None:
```

**Comment by charliermarsh** [comment]
I think I want to cut scope here, because I've generally tried to avoid implementing rules that feel like one-time 2-to-3 (or 3.5-to-3.7 etc.) upgrades (as opposed to upgrades that are consistently useful on Python 3 code).
