### ISSUE TITLE
Implement autofix for C417

### ISSUE THREAD

**Issue by spaceone** [charliermarsh/ruff#2262]
A fixer for `C417` would be helpful.

```diff
-map(lambda x: x * 2, bar)
+[x * 2 for x in bar]
```

In #970 this is marked as done for `R1728` but ruff doesn't know this code.

**Comment by sbrugman** [comment]
I could take this one, encountered in another codebase too.

The fixer should be probably be a generator rather than a list.
The tracking issues do not distinguish between the rule and the autofix for now I think, so that might be why its crossed out. The alias should be `PYR1728`.
