### ISSUE TITLE
Exempt `typing` from TCH by default?

### ISSUE THREAD

**Issue by scop** [charliermarsh/ruff#2267]
ruff 0.0.236

It would seem to me that `typing` should be exempted from TCH by default.

For example:
```python
from typing import Any

def foo() -> Any:
    return 1
```

Unless I'm missing something, use of the type checking block that satisfies this check requires importing `TYPE_CHECKING` from `typing`, which loads `typing`, thus nullifying the usefulness for this for `typing` imports.

```
>>> import sys
>>> "typing" in sys.modules
False
>>> from typing import TYPE_CHECKING
>>> "typing" in sys.modules
True
```

flake8-type-checking's README points to two "examples in the wild", both of which contain `typing` imports, neither of which places them in the `TYPE_CHECKING` block:
- https://github.com/python-poetry/poetry/blob/714c09dd845c58079cff3f3cbedc114dff2194c9/src/poetry/factory.py#L1:L33
- https://github.com/snok/asgi-correlation-id/blob/main/asgi_correlation_id/middleware.py#L1:L12

flake8-type-checking also contains this note:
https://github.com/snok/flake8-type-checking/blob/main/flake8_type_checking/checker.py#L601-L603
...along with some other conditions regarding `typing` import aliasing and `typing.cast` imports above that commentary. I haven't dug into them nor if ruff currently has any corresponding functionality.

**Comment by ngnpope** [comment]
There is a small advantage to moving, e.g. `from typing import Any, Generic, ParamSpec, TypeAlias, TypeVar, ...`, into a `TYPE_CHECKING` block: Reducing the amount of cruft littering the module globals at runtime.

**Comment by charliermarsh** [comment]
We could make it part of `exempt-modules` by default, that way it's configurable.

**Comment by ngnpope** [comment]
Also, is this happening because you have `strict = true`? You can also set `exempt-modules = ["typing"]` if you want to prevent this happening...

**Comment by scop** [comment]
No `strict = true` here. I understand I could exempt it for myself, I just think it would be a better default for most cases, therefore suggesting it here.

**Comment by charliermarsh** [comment]
Yeah I think the least surprising thing would be to exempt typing and typing extensions by default.

**Comment by scop** [comment]
`typing_extensions` is a bit different, as I think it can be entirely put within `TYPE_CHECKING` and the import actually avoided at runtime. Therefore I'd personally not exempt it by default. But no strong opinions on that here.

**Comment by charliermarsh** [comment]
Yeah makes sense. I'll add `typing`.
