### ISSUE TITLE
Prefer Single Quotes

### ISSUE THREAD

**Issue by jackdesert** [charliermarsh/ruff#2275]
How do I get this message to prefer single quotes instead of double?

Version: ruff 0.0.236

    # run.py
    greeting = 'Hello'

`$ ruff --select Q --isolated run.py`

Message: 
`run.py:1:12: Q000 Single quotes found but double quotes preferred`

But the README says that the message for Q000 is "Double quotes found but single quotes preferred".
(Screenshot below)
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/791315/215192390-978e45dd-e607-4896-8a39-8d20f2d3b33f.png">

**Comment by charliermarsh** [comment]
It’s configurable via pyproject.toml. The default is to prefer double quotes: https://github.com/charliermarsh/ruff#flake8-quotes

(I can paste a code snippet when I’m back at my computer, but hopefully the docs give you a good lead!)

**Comment by jackdesert** [comment]
I was actually delighted to see the version the README---it gave me hope that preferring single quotes must be an option somehow :)

**Comment by jackdesert** [comment]
By the way I did get pyproject.toml connected and was able to configure flake8-quotes there :)
