### ISSUE TITLE
small README formatting typo

### ISSUE THREAD

**Issue by the-matt-morris** [charliermarsh/ruff#2290]
First of all...this library is just amazing.  Thank you for the hard work to make this happen.

I noticed very minor typos in README, I will open a PR for it.

(missing backticks on a couple of these bullets)
![image](https://user-images.githubusercontent.com/102183561/215242182-cd2573e5-4425-4ccd-b26e-3b9bf04a5e4f.png)

**Comment by charliermarsh** [comment]
Oops, thank you! PR welcome!
