### ISSUE TITLE
flake8-sql

### ISSUE THREAD

**Issue by Mister7F** [charliermarsh/ruff#2295]
Would it be possible at some point to implement the plugin "flake8-sql" ?

See https://github.com/pgjones/flake8-sql

(even if it's optionnal, it would be great)

**Comment by rassie** [comment]
I'm not particularly opposed (but neither am I anyone to listen to in this project), but this feels like more of a formatter than a linter problem. Apart from Q441 and Q442 the rules are somewhat easily replaced by something like [format-sql](https://pypi.org/project/format-sql/) or formatting capabilities of [sqlparse](https://sqlparse.readthedocs.io/). The proper question is of course, how to make a generic SQL formatter format code inside a Python string, so maybe this is an example of a more generic problem -- how do we format structured formate inside Python strings? I think we are probably looking at a plugin for SQL, JSON, HTML etc. within the upcoming plugin system. But those are just my two cents.

**Comment by charliermarsh** [comment]
I _am_ interested in multi-language support eventually but I think extending to SQL right now would be challenging and I'd rather focus elsewhere. Will revisit in time!

**Comment by edgarrmondragon** [comment]
For linting SQL, it's hard to beat https://github.com/sqlfluff/sqlfluff/ at the moment. It's really comprehensive with support for multiple dialects and formatters, like jinja and dbt.
