### ISSUE TITLE
Error with -V flag to display version

### ISSUE THREAD

**Issue by lcheylus** [charliermarsh/ruff#2299]
With the latest version (commit 861df12269fbe73931b0b41ea2561f665f16e3ba), build OK on Debian/testing amd64 with Rust 1.65.

I have an error when I'm trying to use `-V` flag to display the current version : 
```
$ ./target/release/ruff -V
error: unexpected argument '-V' found

  note: to pass '-V' as a value, use '-- -V'
```

No error with `--version` flag : 
```
./target/release/ruff --version
ruff 0.0.236
```

**Comment by charliermarsh** [comment]
\cc @not-my-profile

**Comment by charliermarsh** [comment]
I got it.
