### ISSUE TITLE
Make it easier to run the ruff

### ISSUE THREAD

**Issue by chirag127** [charliermarsh/ruff#2305]
I would appreciate if a command `ruff .` can be there to lint all the files in the current working directory.

**Comment by charliermarsh** [comment]
Hmm, `ruff .` should already work. What happens when you run that command?

**Comment by chirag127** [comment]
> Hmm, `ruff .` should already work. What happens when you run that command?

Ah it's already there, i think it might be better to write it in the document. So, I have made a pull request for it.

**Comment by charliermarsh** [comment]
Closed by #2307.
