### ISSUE TITLE
Make a discord server. 

### ISSUE THREAD

**Issue by chirag127** [charliermarsh/ruff#2313]
Is it possible Make an interactive communication medium for asking small queries if there is not one yet?

**Comment by charliermarsh** [comment]
I'll do this soon.

**Comment by not-my-profile** [comment]
I'd personally vote for something more privacy friendly ... maybe a channel on https://libera.chat/, which is automatically accessible via IRC and [Matrix](https://matrix.org/) (and they even have a nice web-frontend for IRC so you can use it entirely without any account).

**Comment by chirag127** [comment]
> I'd personally vote for something more privacy friendly ... maybe a channel on https://libera.chat/, which is automatically accessible via IRC and [Matrix](https://matrix.org/) (and they even have a nice web-frontend for IRC so you can use it entirely without any account).

What is that? I would like either telegram or discord.

**Comment by akhildevelops** [comment]
> I'd personally vote for something more privacy friendly ... maybe a channel on https://libera.chat/, which is automatically accessible via IRC and [Matrix](https://matrix.org/) (and they even have a nice web-frontend for IRC so you can use it entirely without any account).

I would vote for discord.

**Comment by charliermarsh** [comment]
I'm planning to use Discord for this.

From my perspective, it's the most popular choice for OSS projects, and will thus require the least activation energy for the average user to participate and get involved. (I also already use it to participate in a number of similar communities, so selfishly, it's just helpful for me to put this on Discord vs. monitoring another discussion channel.)

I totally understand that some users won't want to use Discord... but I think the reality is that some people will inevitably disagree with whatever I choose... 😅 

I'll add a few caveats / clarifications, though:

- No user or contributor should feel required to be part of the Discord.

- If you want to chat with me 1:1 through some other synchronous channel, like Matrix, I'm happy to do that. I don't want to fragment the community by maintaining two community channels on different apps, but I'm definitely happy to engage 1:1 elsewhere.

- I really want GitHub to continue to be a source of truth and to continue growing as a form of searchable documentation. So I'll likely ask people to open Issues if they run into a new problem or new question. (Not always, of course -- we'll figure it out the right heuristics as we go.) This has been my main hesitation around adopting _any_ form of synchronous chat.

**Comment by chirag127** [comment]
> I'm planning to use Discord for this.
> 
> From my perspective, it's the most popular choice for OSS projects, and will thus require the least activation energy for the average user to participate and get involved. (I also already use it to participate in a number of similar communities, so selfishly, it's just helpful for me to put this on Discord vs. monitoring another discussion channel.)
> 
> I totally understand that some users won't want to use Discord... but I think the reality is that some people will inevitably disagree with whatever I choose... 😅
> 
> I'll add a few caveats / clarifications, though:
> 
> * No user or contributor should feel required to be part of the Discord.
> * If you want to chat with me 1:1 through some other synchronous channel, like Matrix, I'm happy to do that. I don't want to fragment the community by maintaining two community channels on different apps, but I'm definitely happy to engage 1:1 elsewhere.
> * I really want GitHub to continue to be a source of truth and to continue growing as a form of searchable documentation. So I'll likely ask people to open Issues if they run into a new problem or new question. (Not always, of course -- we'll figure it out the right heuristics as we go.) This has been my main hesitation around adopting _any_ form of synchronous chat.

You could easily sync discord with matrix and many other platform, so, the discord is best option and then people who wanna use matrix can use Matrix by synchronisation.

**Comment by akhildevelops** [comment]
GitHub Discussions is also one of the good platforms for the community to discuss different topics. 

Ex: https://github.com/meilisearch/meilisearch/discussions

**Comment by charliermarsh** [comment]
It's live! I'll be hanging on Discord here: https://discord.gg/Z8KbeK24. Come join.

**Comment by chirag127** [comment]
> @charliermarsh The invite link seems to be expired.

Ya, the invite link was limited to 7 days.

**Comment by charliermarsh** [comment]
Oops, sorry -- here's the updated link (and I'll update the comment above and docs): https://discord.gg/c9MhzV8aU5

**Comment by utikpuhlik** [comment]
@charliermarsh hi, could you please update the invite link?

**Comment by MichaReiser** [comment]
I just tested it and the link seems still valid. Any chance you're running into the same as https://github.com/astral-sh/ruff/issues/14004#issuecomment-2448135076

**Comment by utikpuhlik** [comment]
@MichaReiser nice! it works

**Comment by carlosferreyra** [comment]
> Oops, sorry -- here's the updated link (and I'll update the comment above and docs): https://discord.gg/c9MhzV8aU5

as of the date of this comment, the link doesn't work when clicking directly, BUT it does work if you copy-paste at the discord UI.
