### ISSUE TITLE
autofix for TCH (flake8-type-checking) rules

### ISSUE THREAD

**Issue by LefterisJP** [charliermarsh/ruff#2329]
I enabled the TCH rules to see what it suggests and finds in rotki's codebase. I got about ~700 hits.

They don't seem like bad suggestions. I .. ehm ... just don't want to do it manually and without knowing the internals of ruff well I can imagine all TCH rules should be autofixable.

**Comment by charliermarsh** [comment]
It's non-trivial (but also not impossible) because it requires rewrites across various parts of the file -- we have to remove an import from one part of a file, add it to another part which could be non-adjacent, etc.

**Comment by LefterisJP** [comment]
> It's non-trivial (but also not impossible) because it requires rewrites across various parts of the file -- we have to remove an import from one part of a file, add it to another part which could be non-adjacent, etc.

I understand. In some rules you would also need to adjust types and wrap them in quotes if the import is moved inside an `if TYPE_CHECKING` block.

**Comment by Kilo59** [comment]
>I understand. In some rules you would also need to adjust types and wrap them in quotes if the import is moved inside an if TYPE_CHECKING block.

I would expect these fixes to be paired with a `from __future__ import annotations` import.
Should also make it easier to implement.

**Comment by LefterisJP** [comment]
Nice suggestion @Kilo59! One question. Do you know from which version of python `from __future__ import annotations` will no longer be required? I thought it was supposed to be 3.10 but seems like this is not the case?

**Comment by charliermarsh** [comment]
I believe it will be Python 3.12 at the earliest.

https://docs.python.org/3/library/__future__.html#id2
https://mail.python.org/archives/list/python-dev@python.org/message/VIZEBX5EYMSYIJNDBF6DMUMZOCWHARSO/

**Comment by MaximZayats** [comment]
Hi, @charliermarsh!

Do you have any news/plans on this ?
I don't think the auto-fix should be a big problem in case of using `from __future__ import annotations`.
What do you think?

**Comment by charliermarsh** [comment]
I'm currently working on this.
