### ISSUE TITLE
Can `DEFAULT_EXCLUDE` use glob-style items?

### ISSUE THREAD

**Issue by amotl** [charliermarsh/ruff#233]
Hi again,

at #232, I learned more about the internals of `ruff`, and how to configure it properly - thank you very much.

On this matter, I humbly wanted to ask if the `DEFAULT_EXCLUDE` list would be capable of accepting and evaluating glob-style items? We are using the convention of `.venv36`, `.venv37`, etc., for having multiple virtualenv folders within our working trees.

https://github.com/charliermarsh/ruff/blob/09b926fd59115afc8f47c191b86ad7c47c79889e/src/settings.rs#L54-L76

With kind regards,
Andreas.

#### Stats
```
time ruff .
real	0m0.195s
user	0m0.084s
sys	0m0.232s
```
```
time ruff --extend-exclude=.venv36 .
real	0m0.099s
user	0m0.012s
sys	0m0.116s
```

**Comment by charliermarsh** [comment]
I think the fact that we now support `.gitignore` and friends probably covers this need.
