### ISSUE TITLE
Regression with ruff 0.0.42 on relative exclude files

### ISSUE THREAD

**Issue by amotl** [charliermarsh/ruff#234]
Hi again,

apologies for creating so many issues and for sometimes missing to catch up, because the pace is so fast. I hope you still appreciate my feedback.

After adjusting our exclude pattern recently as outlined at https://github.com/charliermarsh/ruff/issues/203#issuecomment-1249055408 and https://github.com/jpmens/mqttwarn/commit/fad50af912e, we just had to downgrade to ruff 0.0.40 (https://github.com/jpmens/mqttwarn/commit/041a3f425d) to make it work again.

Currently, on 0.0.42, `ruff` would croak on both configuration variants of `extend-exclude`. There is probably another thing amongst the recent changes I am missing here?

```
tests/etc/functions_bad.py:0:0: E999 SyntaxError: unexpected indent at line 6 column 5
```
```toml
extend-exclude = [
  "./tests/etc/functions_bad.py"
]
```
```toml
extend-exclude = [
  "tests/etc/functions_bad.py"
]
```

Keep up the spirit and with kind regards,
Andreas.

P.S.: Just to make it clear: [`tests/etc/functions_bad.py`](https://github.com/jpmens/mqttwarn/blob/0.29.1/tests/etc/functions_bad.py) _intentionally_ has bad formatting, because we use it as a canary for running our plugin machinery on bad input files. That is why we need to make `ruff` skip it.

**Comment by charliermarsh** [comment]
Sorry, will look into this now.

**Comment by charliermarsh** [comment]
Legitimate bug thank you! I assume you're running `ruff .`?

**Comment by amotl** [comment]
> I assume you're running `ruff .`?

We are actually running `ruff` only on a subdirectory of `mqttwarn` yet, per [`ruff tests`](https://github.com/jpmens/mqttwarn/blob/ee3a736e7dd88442c837e38b5600817d4e3591a6/pyproject.toml#L59).

**Comment by charliermarsh** [comment]
Hopefully fixed in v0.0.43 (building now) but please let me know if not! I cloned your repo and tested on that directly.

**Comment by charliermarsh** [comment]
Apologies for all the churn here. The strategy for inclusion / exclusion has stabilized a lot so I don't anticipate any more breakages or API changes (apart from backwards-compatible changes, like ignoring `.venv*`).

**Comment by amotl** [comment]
No worries about those hiccups. Speaking for me, I was happy to help on the corresponding teething issues, and I am sure @jack1142 enjoys it equally well. Cheers!

P.S.: I will report back about the outcome on 0.0.43, but I am sure it will be fixed. Thanks for going the extra mile by cloning our repo.

**Comment by amotl** [comment]
🌧️ Build failed. -- https://github.com/charliermarsh/ruff/actions/runs/3091788765/jobs/5002298427

**Comment by amotl** [comment]
Hi again. @charliermarsh: I can confirm that ruff 0.0.43 works excellent again. Thank you once more for fixing it so quickly.
