### ISSUE TITLE
False positive for `G201` and `G202`?

### ISSUE THREAD

**Issue by ngnpope** [charliermarsh/ruff#2356]
We may have a situation where we have a callback function defined to handle exception, e.g. this generic catch-all when using a resolver from `aws-lambda-powertools`:

```python
from __future__ import annotations

from typing import Any

from aws_lambda_powertools.event_handler import ALBResolver, Response
from aws_lambda_powertools.logging import Logger
from aws_lambda_powertools.utilities.typing import LambdaContext

app = ALBResolver()
logger = Logger()


@app.get("/")
def handle_default() -> Response:
    raise Exception  # Something went wrong...


@logger.inject_lambda_context
def lambda_handler(event: dict[str, Any], context: LambdaContext) -> dict[str, Any]:
    return app.resolve(event, context)


@app.exception_handler(Exception)
def handle_exception(exc: Exception) -> Response:
    event = app.current_event
    extra = {"path": event.path, "method": event.http_method, "status": 500}
    message = "An unexpected error occurred."
    logger.error(message, exc_info=exc, extra=extra)
    return Response(
        status_code=500,
        payload={"error": message},
        content_type="application/json",
    )
```

I get the following:

```console
❯ ruff --version
ruff 0.0.237

❯ ruff --select G bug.py 
bug.py:28:12: G201 Logging `.exception(...)` should be used instead of `.error(..., exc_info=True)`
Found 1 error.
```

For context, `Logger.exception()` is defined as:

```python
class Logger(Filterer):
    ...

    def exception(self, msg, *args, exc_info=True, **kwargs):
        """
        Convenience method for logging an ERROR with exception information.
        """
        self.error(msg, *args, exc_info=exc_info, **kwargs)

    ...
```

There are two issues here:

1. I'm not using `exc_info=True`, I'm explicitly passing the exception object
2. The guidance to use `.exception(...)` really only applies in an `except:` block
   - This is because passing `exc_info=True` calls `sys.exc_info()` under the hood
   - And `sys.exc_info()` cannot be guaranteed to have an exception outside of `except:`
      ```console
      ❯ python -c 'import sys; print(sys.exc_info())'
      (None, None, None)
      ```

Given the definition of `.exception(...)`, it looks as though we ought to be able to bypass `G201` by passing `exc_info=exc` to `.exception(...)` instead of `.error(...)`, but that gives the following:

```console
❯ ruff --select G bug.py 
bug.py:28:31: G202 Logging statement has redundant `exc_info`
Found 1 error.
```

Which is also incorrect... It's only redundant if it is `exc_info=True`, the default value.

So I believe the following should change:
- Only flag up `G201` in an `except:` block and only when `.error(...)` is passed `exc_info=True` or `exc_info=sys.exc_info()`
- Only flag up `G202` for `.exception(..., exc_info=True)` or `.exception(..., exc_info=sys.exc_info())`
- Consider whether `.exception(..., exc_info=exc)` should be forced back to `.error(..., exc_info=exc)` with a new rule
  - _The only benefit of `.exception(...)` is to pass `exc_info=True` automatically. It's syntactic sugar._

**Comment by ngnpope** [comment]
Also note that `G201` flags up for `.error(..., exc_info=False)` and `.exception(..., exc_info=False)` which are both wrong.

**Comment by ngnpope** [comment]
I think `flake8-logging-format` also gets these wrong, but fixing things is always good! 😉

**Comment by charliermarsh** [comment]
The one area I'm happy to deviate from "upstream" is when there are clear false positives or false negatives that can improved reliably :)

**Comment by charliermarsh** [comment]
I'm going to fix this quickly so that it can be included in today's release.
