### ISSUE TITLE
Allow BLE001 if future.set_exception is used

### ISSUE THREAD

**Issue by JonathanPlasse** [charliermarsh/ruff#2360]
```python
try:
    client.loop_read()
except Exception as exc:
    if not self._disconnected.done():
        self._disconnected.set_exception(exc)
```
In [asyncio-mqtt](https://github.com/sbtinstruments/asyncio-mqtt/), we use `asyncio.Future.set_exception(exc)` to handle the exception.
- Would it be ok to allow it the same as #2212?

I can work on it.
We could use a visitor as mentioned [here](https://github.com/charliermarsh/ruff/issues/1119#issuecomment-1341171085) to handle it.

**Comment by charliermarsh** [comment]
That seems reasonable, but we should probably also consider whether it affects any of the `TRY` rules and should be allowed there too.
