### ISSUE TITLE
Improve settings documentation to include possible values for enum types

### ISSUE THREAD

**Issue by messense** [charliermarsh/ruff#2372]
For example https://beta.ruff.rs/docs/settings/#pydocstyle doesn't say what's the possible values for the type `Convention`.

<img width="854" alt="image" src="https://user-images.githubusercontent.com/1556054/215639860-35b09e1d-6842-439b-aa6d-f22009e2a365.png">

**Comment by charliermarsh** [comment]
Definitely! I wonder if we can autogenerate these.

**Comment by messense** [comment]
I think it's a little tricky to autogenerate there, `#[option(possible_values = "x,y,z")]` certainly will work but it feels tedious, and we don't have access to the actual value type in the proc-macro.

https://github.com/charliermarsh/ruff/blob/ad8693e3deddbd8e178546dad7be5759ebf1a095/ruff_macros/src/config.rs#L119-L159

**Comment by charliermarsh** [comment]
Yeah. I guess there are few enough values that we can just update them manually as a first pass.

**Comment by charliermarsh** [comment]
I can do it, don't mind.
