### ISSUE TITLE
A way to list per-file-ignore rules for debugging

### ISSUE THREAD

**Issue by Alphasite** [charliermarsh/ruff#2373]
Hi! 

Thank you for building this fantastic tool, I had a small request, or guidance on how to contribute a feature my self, is there a way to get debug output for the `per-file-ignores` rules, so i can understand exactly what the created globs were. 

(for background: i couldn't figure out why no variant of `**/test/**/*` wasn't working and it turns out that per-file-ignores are calculated relative to the extended `ruff.toml` file, which was an issue in my case as my config file was in a sibling folder, rather than the parent, so the pattern would never be able to match files in the current directory). 

I ended up adding a hack to debug this and finally figured out the issue, but it would be helpful if there was a verbosity level which printed this information: 
```
        settings.per_file_ignores
            .iter()
            .for_each(|(absolute, basename, _)| {
                println!("ignoring: abs: {} basename: {}", absolute.glob(), basename.glob())
            });
```
example output:
```
ignoring: abs: /Users/me/Workspace/gitlab.eng.comp.com/something/server/**/test/**/* basename: **/test/**/*
...
```

Thanks.

**Comment by charliermarsh** [comment]
Let me see what we include under the various CLI flags...

**Comment by charliermarsh** [comment]
I'll add this to the `-v` logging.

**Comment by charliermarsh** [comment]
In the meantime, though, if you just want to see the resolved regexes, you can do `ruff foo --show-settings`. Look at the `per_file_ignores` section, and take a look at the `re`. (All filenames are converted to absolute, so those are what get matched against the regexes.)

**Comment by Alphasite** [comment]
Oh, i hadn't realized those were in there, thank you!

**Comment by charliermarsh** [comment]
No worries! It could be nice if we _also_ told you when a pattern matched a file. We already do that for `exclude` (if you set `--verbose`).
