### ISSUE TITLE
Bug in `RUF100` autofixer

### ISSUE THREAD

**Issue by stinodego** [charliermarsh/ruff#2379]
Using all default settings and `select = ["RUF"]`, the following `noqa` statement is incorrectly fixed.

Before:
```python
"shape:  (6,)\nSeries: '' [duration[μs]]\n[\n\t0µs\n\t1µs\n\t2µs\n\t3µs\n\t4µs\n\t5µs\n]"  # noqa: E501
```

After:
```python
"shape:  (6,)\nSeries: '' [duration[μs]]\n[\n\t0µs\n\t1µs\n\t2µs\n\t3µs\n\t4µs\n\t5µs\n]"  # noq
```

I'm on Ruff version 0.0.237, Python 3.11.0.

**Comment by charliermarsh** [comment]
Thank you for filing!

**Comment by stinodego** [comment]
I was surprised, as I hadn't run into a bug yet. Keep up the good work!
