### ISSUE TITLE
Union is upgraded to "|" pipe character even though target version is Python 3.9

### ISSUE THREAD

**Issue by KelSolaar** [charliermarsh/ruff#2382]
Hi,

This only happens when `from __future__ import annotations` is used:

Given `target-version = "py39"` and the following snippet:

```python
from __future__ import annotations

from typing import Literal, Union


def foo(bar: Union[Literal["John", "Wayne"], str] = "John"):
    ...
```

The snippet is upgraded:

```python
from __future__ import annotations

from typing import Literal


def foo(bar: Literal["John", "Wayne"] | str = "John"):
    ...
```

- Ruff 0.0.237

**Comment by burgholzer** [comment]
Could it be that you copied the same snippet twice by accident?

The rewrite is perfectly valid for Python 3.7+ whenever `from __future__ import annotations` is present due to postponed evaluation of annotations (see https://peps.python.org/pep-0563/).

**Comment by thomkeh** [comment]
You can turn this behavior off with

```toml
[tool.ruff.pyupgrade]
# Preserve types, even if a file imports `from __future__ import annotations`.
keep-runtime-typing = true
```

**Comment by KelSolaar** [comment]
> Could it be that you copied the same snippet twice by accident?

Yes! Copy-paste fail, just fixed.

> See also the original pyupgrade implementation: https://github.com/asottile/pyupgrade/blob/97ed6fb3cf2e650d4f762ba231c3f04c41797710/pyupgrade/_plugins/typing_pep604.py#L118-L126

So this is interesting because I'm using `pyupgrade` and it does not update them which is why I was surprised that they were in the first place. Looking `pyupgrade`, `keep_runtime_typing` attribute is off by default: https://github.com/asottile/pyupgrade/blob/97ed6fb3cf2e650d4f762ba231c3f04c41797710/pyupgrade/_data.py#L31 which evaluates to `True` in the code that uses it, i.e. `not state.settings.keep_runtime_typing`.

**Comment by charliermarsh** [comment]
@KelSolaar - Just trying to keep up -- does this seem to be working as intended, or na?

**Comment by KelSolaar** [comment]
Sorry, yes it does perfectly, the default behaviour is different compared to `pyupgrade`, unsure if it needs to be or documented.

**Comment by charliermarsh** [comment]
I think the default behavior is maybe the same? If I run `pyupgrade foo.py --py39` over that code, it does upgrade it. I have to run `pyupgrade foo.py --py39 --keep-runtime-typing` to avoid the upgrade.

With Ruff, if I run `ruff --fix` over that file with `target-version = "py39"`, it also fixes it. If I add this to my `pyproject.toml`, it doesn't:

```toml
[tool.ruff.pyupgrade]
keep-runtime-typing = true
```

So I think in either case, you have to enable that setting? But maybe I'm just misunderstanding :) Going to close for now though!

**Comment by KelSolaar** [comment]
Thanks, maybe it is a default when used with the precommit hooks but we never specified this parameter and it never upgraded for us. It does not really matter anyway as we will be using Ruff from now on! :D
