### ISSUE TITLE
PIE804 with PEP8 naming conflict

### ISSUE THREAD

**Issue by spaceone** [charliermarsh/ruff#2387]
```python
def foo(NotPep8NamingCompliant=True, **kwargs):
    pass


foo(**{
    "NotPep8NamingCompliant": True,
})
foo(
    NotPep8NamingCompliant=True,
)
```

The function parameter name is not compliant to PEP8 naming:
`foo.py:1:10: N803 argument name 'NotPep8NamingCompliant' should be lowercase`
But functions sometimes allows to receive `**keyword arguments` instead of non-pep8-conform names.

When calling the function with keyword-arguments `PIE804` complains about:
```foo.py:5:1: PIE804 Unnecessary `dict` kwargs```

I would like to allow giving keyword arguments via `**keyword_args` if the dict-keys aren't PEP8 naming conform.
And therefore only complain about names which look OK when calling the function.

**Comment by charliermarsh** [comment]
Hate saying no to things that have a reasonable motivation but to me this feels like it'd add more complexity than is worthwhile for a somewhat specific context.

**Comment by spaceone** [comment]
OK, your decision. If there is no other need for this in the community: My alternative is to add `noqa` comments then.

**Comment by charliermarsh** [comment]
I'm going to close for now. If this comes up a few more times, I'll definitely reconsider!

**Comment by spaceone** [comment]
yes, can you set the issue status to `wontfix` ? (easier to filter then).

**Comment by charliermarsh** [comment]
Good call, done.
