### ISSUE TITLE
new rule for `not foo not in bar`

### ISSUE THREAD

**Issue by spaceone** [charliermarsh/ruff#2394]
I have hard to understand code like:
`not foo not in bar`
Neither ruff not flake8 does complain about it.

As far as I tested this is equal to `foo in bar` !?!
So a new rule could add a check for this.

The code was created by https://github.com/charliermarsh/ruff/issues/2219.

**Comment by charliermarsh** [comment]
We fixed the SIM rule to avoid generating expressions of that form (#2219) so I'm comfortable closing this one out.
