### ISSUE TITLE
Possible `--interactive` flag/mode for use with `--fix`?

### ISSUE THREAD

**Issue by ngnpope** [charliermarsh/ruff#2395]
This is more just throwing an idea in the pot for consideration down the line.

What about an interactive mode for applying autofix patches à la `git add --patch`?

I saw #2390 and wondered whether this could be useful to skip over unsafe or incorrect changes...
Right now it's apply fixes to all files or none unless manually crafting the list of files on the command line.

**Comment by charliermarsh** [comment]
\cc @MichaReiser regarding "review mode"

**Comment by charliermarsh** [comment]
Consolidating into https://github.com/charliermarsh/ruff/issues/4361.
