### ISSUE TITLE
Q000 for multiline strings with different quotes

### ISSUE THREAD

**Issue by samuelcolvin** [charliermarsh/ruff#2400]
code:

```py
    assert s.to_python(123) == (
        "123 info=SerializationInfo(include=None, exclude=None, mode='python', by_alias=True, exclude_unset=False, "
        "exclude_defaults=False, exclude_none=False, round_trip=False)"
    )
```

Is resulting in "Q000 Double quotes found but single quotes preferred"

As you can see the first line has a single quote in it, so needs to use double quotes, the second line doesn't but by conversion you'd expect to keep using double quotes for the whole multi-line string.

**Comment by samuelcolvin** [comment]
Tried on latest ruff, getting the same error.

**Comment by charliermarsh** [comment]
Makes sense! Thanks for filing.

**Comment by samuelcolvin** [comment]
Just for reference, same error reported on flake8-quotes in 2019 - https://github.com/zheller/flake8-quotes/issues/82

**Comment by charliermarsh** [comment]
Do you think this should be an _error_, or merely permitted?

```py
    assert s.to_python(123) == (
        "123 info=SerializationInfo(include=None, exclude=None, mode='python', by_alias=True, exclude_unset=False, "
        'exclude_defaults=False, exclude_none=False, round_trip=False)'
    )
```

**Comment by samuelcolvin** [comment]
personally I would say an error, but I'm fine with permitted too, especially since you had to do that (or add `noqa`) until now.

**Comment by charliermarsh** [comment]
I did some testing -- I probably need to treat it as "permitted", because Black changes them back. That is, Black changes this:

```py
(
    '"abc"'
    'abc'
)
```

...to...

```py
(
    '"abc"'
    "abc"
)
```

(Black will also truncate the whitespace, but omitted that change for clarity.)

It wouldn't be a huge deal in practice, since if you're using this plugin with `"double"` preference, you're compatible with Black anyway; and if you're using it with `"single"` preference, you're already incompatible with Black. But I'd prefer to avoid the potential of introducing a fix loop.

**Comment by samuelcolvin** [comment]
agreed

**Comment by samuelcolvin** [comment]
Wonderful, thanks.

**Comment by charliermarsh** [comment]
Is there any branch etc. that I could test this on just to ensure compatibility? :)

It'll go out in tonight's release.

**Comment by samuelcolvin** [comment]
See https://github.com/pydantic/pydantic-core/pull/374, there's currently a bunch of `noqa`s.

**Comment by charliermarsh** [comment]
👍 Thanks, looking good on that branch

**Comment by samuelcolvin** [comment]
👍 (on mobile, so this is a reaction)
