### ISSUE TITLE
Implement `isort` custom sections and ordering

### ISSUE THREAD

**Issue by ngnpope** [charliermarsh/ruff#2419]
`isort` has support for configuring [custom sections and ordering](https://pycqa.github.io/isort/docs/configuration/custom_sections_and_ordering.html).

This support would also need to be tied in with [`no-lines-before`](https://github.com/charliermarsh/ruff#no-lines-before) for the custom sections.

I would imagine that the following `isort` configuration:

```ini
known_django=django
known_pandas=pandas,numpy
sections=FUTURE,STDLIB,DJANGO,THIRDPARTY,PANDAS,FIRSTPARTY,LOCALFOLDER
no_lines_before=DJANGO,LOCALFOLDER
```

Would become the following in `ruff`:

```toml
[tool.ruff.isort]
no-lines-before = ["django", "local-folder"]
section-order = ["future", "standard-library", "django", "third-party", "pandas", "first-party", "local-folder"]

[tool.ruff.isort.sections]
django = ["django"]
pandas = ["pandas", "numpy"]
```

**Comment by spaceone** [comment]
Support for `known-local-folder` would be nice.

**Comment by charliermarsh** [comment]
Isn't `local-folder` always denoted by a relative import? What does `known-local-folder` do?

**Comment by spaceone** [comment]
local-folder is the name of the section/category while known-local-folder are the modules/packages which should be treated for the local-folder section.

e.g.:
```
sections=FUTURE,STDLIB,FIRSTPARTY,THIRDPARTY,LOCALFOLDER
known_local_folder=myproject,test,foo
```

it has nothing to do with relative imports.

**Comment by g-as** [comment]
Aren't you mixing `known_first_party` and `known_local_folder`?

https://pycqa.github.io/isort/docs/configuration/options.html#known-first-party

https://pycqa.github.io/isort/docs/configuration/options.html#known-local-folder
> Force isort to recognize a module as being a local folder. Generally, this is reserved for relative imports (from . import module).

**Comment by spaceone** [comment]
> Aren't you mixing `known_first_party` and `known_local_folder`?
Kind of yes, but we use this to separate our "known first party" modules from some special modules (some only for "testing" and one which can only be imported in a special C application): We use it as visual separation from other modules.

> I guess `isort` supports including non-relative imports in local folder? Strikes me as unusual!
yes, I think the implementation of it is just a regular "section", so no special behavior.

→ So for me it's not important if I just add another section which I name by myself or use the standard isort section "known-local-folder".

**Comment by QuentinN42** [comment]
Hey, I'll try to implement the `[tool.ruff.isort.sections]` feature :)

**Comment by QuentinN42** [comment]
After reading the code, I think I first need to pass an MR about allowing section order.

If I understand right the code in the [PyCQA/isort GH](https://github.com/PyCQA/isort), they [return a str in the place module](https://github.com/PyCQA/isort/blob/3a72e069635a865a92b8a0273aa829f630cbcd6f/isort/place.py#L15) to be able to [order it dynamically in the place module](https://github.com/PyCQA/isort/blob/3a72e069635a865a92b8a0273aa829f630cbcd6f/isort/parse.py#L455).

@charliermarsh today we use an enum `ImportType` to order all imports :

https://github.com/charliermarsh/ruff/blob/36d134fd41a8378f1c3f7bb69a7053ecefb17cff/crates/ruff/src/rules/isort/categorize.rs#L14-L24

What do you think about changing that to a BTreeMap or an HashMap to allow runtime update of it (custom categorize) ?

**Comment by charliermarsh** [comment]
I wish I had some way to assess the importance or popularity of this functionality, since it does introduce a bunch of complexity. Does anyone want to make a strong case for it?

(I personally tend not to use any of isort's configuration options, but I've been open to adding them over time as other's have put together PRs, since they generally haven't introduced _too_ much complexity. Though I may end up regretting supporting those over time, we'll see :))

(Having not looked at the code much...) if we do go forward with this, I might suggest adding a `UserDefined(String)` variant to `ImportType`, rather than changing to to a stringy-typed map. Or even treating that as an entirely separate struct, like:

```rs
pub enum Section {
  KnownType(ImportType),
  UserDefined(String),
}
```

Since we're dealing with two orthogonal concepts: whether a module is first-part or third-party etc., vs. whether it should be categorized in a certain section.

**Comment by Redoubts** [comment]
I suspect this is going to be popular in the dark matter that is closed-source business code. 

But I think it’s also good if you have something like 

‘’’
from my_special_loader import a_module
import a_module.submodule
‘’’
 isort would reverse the order without the ability to configure sections.

**Comment by Atilla** [comment]
This might not be a very helpful contribution, but:

I am following this because I want to replace our closed-source business code repo linters with ruff. We have a bunch of those `isort` rules, mostly to split django-related 3rd party stuff from the rest of it, as far as I can observe. 

People looked at the diff without this on, and I'm pretty sure I could convince them to just stop using that grouping, some even prefer it. But it's a very large diff in the repo :)

**Comment by charliermarsh** [comment]
No, that's very helpful! I'm just trying to build some intuition for how important it is, so any data points are welcome (this goes for all commenters and onlookers :)).

**Comment by mastacheata** [comment]
We have the django stuff as a separate section cause there's usually a lot of that and having that grouped together just looks "nicer".  

Obviously there's no technical need for changing the order or the spacing for such a block, it's just a convention we have in our repo of about 900 files which would be changed should we replace isort with the corresponding selector in ruff.

**Comment by QuentinN42** [comment]
It's particulary usefull in the monorepo / big projects : 
You quickly get like 30 lines of imports...

Being able to create some groups like :

- Datascience : `numpy`, `pandas` ...
- Software: `redis`, `pika` ...
- Core: `my_s3`, `my_logger` ...
- Metier: `my_worker`, `scheduler` ...

Transform this :
```python
import numpy
import my_s3
import my_logger
import my_worker
import pandas
import pika
import redis
import scheduler
```
Into this :
```python
import numpy
import pandas

import pika
import redis

import my_s3
import my_logger

import my_worker
import scheduler
```

**Comment by QuentinN42** [comment]
But yes I'ts not required at all as a priority.
I think we can take some time to think about the best way of implementing it here without copying 1 to 1 isort features.
I will read the release notes and issues of this feature on the isort repo and place a summary here so we have some base work material.

**Comment by charliermarsh** [comment]
Seems like there's enough demand + concrete use-cases for this to at least be worth exploring, and scoping out how much complexity it actually adds to the implementation.

**Comment by g-as** [comment]
My 2c:

one of my use cases, that has not been mentioned yet, is adding a test deps section to isolate test tooling imports in test files:
```toml

known_tests_deps = ["factory", "faker", "pytest", "pytest_django", "respx", "testfixtures", "time_machine"]

```

**Comment by QuentinN42** [comment]
Here is the first MRs in the isort repo : https://github.com/PyCQA/isort/pull/275

I don't find any discussions about the implementation.

Maybe we want to define some sections in a list : thx like

```toml
[[tool.ruff.import-section]]
name="my_section_name"
line-before = true  # or no-lines-before
packages = [ "pandas", "..." ]
```

Then we can order section with a list of string.

Or we can add a `level` (int) in this section that allow us to get rid of this section order string.

PS : this is not a real proposition, I just want to put here as most ideas to be able to take the better decision

**Comment by vviikk** [comment]
Is anyone working on this? We are now using Ruff in a huge repo ❤️ . But `isort` remains in use because have a custom section ordering.

Thanks!

**Comment by charliermarsh** [comment]
@vviikk - To my knowledge it's not currently being worked on. Up for grabs if someone wants to take it :)

**Comment by QuentinN42** [comment]
I will be happy to contribute on this but I didn't have much time last month.
Happy to have ideas of implementations or discussions about the following options :

- The "copy isort features 1 to 1"
  - simple migration
  - not really scalable
- The sections as a list with `section-order` (section define an import block but we keep the `section-order` in the `isort` block)
  - Can have custom params in each section
  - Can copy section from others repo easily
  - The import order is easy to view / edit
  - The import order needs to be edited each time a new section is added
- The sections as a list with `level` (section define an import block with a level and the section ordering is computed at runtime)
  - Can have custom params in each section
  - Can copy section from others repo easily
  - The import order may be hard to view / edit in repo with a lot of sections (but can be mitigated with levels with large padding)
  - The import order is automatically computed each time a new section is added

**Comment by rpep** [comment]
> I wish I had some way to assess the importance or popularity of this functionality, since it does introduce a bunch of complexity. Does anyone want to make a strong case for it

Just wanted to add a +1 for this - at the moment this would be something that blocks us from adopting Ruff wholesale on a large commercial project. For us, we want (as we do this with isort already) separation out of core Django and Django REST Framework imports from OS imports and then some other tools we use (Pandas, NumPy).

**Comment by charliermarsh** [comment]
Implemented in #3900.

The API looks like this:

```toml
[tool.ruff.isort]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
no-lines-before = ["bug"]

[tool.ruff.isort.sections]
django = ["django"]
```

**Comment by mastacheata** [comment]
@charliermarsh I think your example for how the API looks is missing the django section in the section-order part (unless this changed between creating the PR and accepting it)

**Comment by charliermarsh** [comment]
@mastacheata - Hah, thank you, fixed 🤦

**Comment by rpep** [comment]
Looks great! Thank you for implementing this so quickly :)

**Comment by huynguyengl99** [comment]
Hi, I can use isort `sections` only if I install ruff directly from github `poetry add git+https://github.com/charliermarsh/ruff.git`. If I install from pypi it would show `unknow field section-order` (image 2). So the code still not yet deliver to pypi, is it right? (Although when I install it from git it still shows the same version - image 3).
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/49433085/232577900-8948c508-4ba0-47de-9802-b32e28bf1389.png">
<img width="1630" alt="image" src="https://user-images.githubusercontent.com/49433085/232578508-cc7e0961-1803-4db1-a324-15bafbaf8283.png">
<img width="363" alt="image" src="https://user-images.githubusercontent.com/49433085/232578660-7ef79eae-3ea5-41ad-8929-e87f82b91de8.png">

**Comment by charliermarsh** [comment]
I think someone commented-then-deleted but yes, this'll go out in the next release this week :)

**Comment by huynguyengl99** [comment]
Hi, the comment was mine, but after checking that the main code is not the pypi latest distribution, I have deleted it 😂 But anyway, thank you a lot for the awesome tool, I will completely migrate to Ruff after the Isort custom feature release 😁.

**Comment by ddahan** [comment]
Thanks for this, it's amazing to be able to get rid of another package!

Is there any plan to update the related JSON schema? I wrote an issue about it: https://github.com/charliermarsh/ruff/issues/4218
