### ISSUE TITLE
RUF100 wipes unknown noqa's

### ISSUE THREAD

**Issue by henryiii** [charliermarsh/ruff#2424]
I have a custom flake8 plugin that's specific for a project (it wouldn't make sense to port it to Ruff ;) ). I've moved everything else to Ruff, and this still is much faster than flake8 used to be running everything! But I'm unable to enable RUF100 since this is an unknown directive.

Would it make sense to have a user-settable "known-noqa" or "ignore-noqa" setting that could tell RUF100 to ignore these noqa statements? Or should I just add RUF100 to the noqa? Another idea that would help in some cases (including this one) would be to split unknown and unused noqa cleanup.

**Comment by charliermarsh** [comment]
We have a setting for this! You should be able to mark codes that Ruff doesn't know about, but should respect, via [`external`](https://github.com/charliermarsh/ruff#external).

**Comment by charliermarsh** [comment]
LMK if that works for what you're describing. If not, happy to figure something out :)

**Comment by henryiii** [comment]
That's exactly what I was looking for, thanks! Sorry for not finding it, I assumed it would be mentioned in RUF 100's description, I guess.
