### ISSUE TITLE
Feature request: Ignore specific rule on per file basis via in-file comment

### ISSUE THREAD

**Issue by mmarras** [charliermarsh/ruff#2446]
I know we can ignore specific files per toml (`per-file-ignores`) and we can also ignore the whole file by putting `# ruff: noqa`  at the top of the file. Also I can do `--extend-ignore=<rule>`.

But how about if I want to ignore only one specifc rule in this file?

The first solution per toml file is not possible for my workflow, the last one does not help with a --pre-commit huck. Would it be possible to allow for it via the in-line comment alla `# ruff: noqa: N803`. 

Background, I am programming a physics based model and N803 is giving me hell, as we use capital variables because they do have commonly understood physical meaning (t for time and T for temperature).

**Comment by Alphasite** [comment]
I suspect `extends-per-file-ignore` would solve many of the common use cases for this as well. That is biting me a little as well for our monorepo.

**Comment by charliermarsh** [comment]
You can always turn off the `N803` violation entry (`ignore = ["N803"]` in your `pyproject.toml`), but I assume you want to keep it enabled, and just disable it in select files -- is that right?

**Comment by mmarras** [comment]
> 

That is correct. I‘m working on a django app, which, as explained earlier, encapsulates a physics based model. So here N803 and friends should be off as upper-case concerns meaning, but in general we like the idea of keeping things lower-case in all other apps in general. 

Also for this specific project, the .toml is managed by the repo owner, many people contributing apps. And we have pre-commit hooks in place which prevent you from pushing changes to config files. Of course I could ask for a change or force-commit, I was just thinking why not make #ruff: noqa more fine-grained, would be the perfect match for my use-case.

**Comment by charliermarsh** [comment]
Flake8 intentionally doesn't support this IIUC. Clippy (Rust's linter) does support something like it although their system is very powerful and effectively allows you to turn rules on and off in any scope.

**Comment by mmarras** [comment]
Awesome! Thanks for picking this one up in no time. On Feb 17, 2023, at 02:59, Charlie Marsh ***@***.***> wrote:﻿
Closed #2446 as completed via e081455.

**Comment by yasirroni** [comment]
For those that come here but did not understand how to use that, see the docs on per-file-ignores [here](https://beta.ruff.rs/docs/settings/#per-file-ignores). An example is how FastAPI use that [here](https://github.com/tiangolo/fastapi/blob/66e03c816b8185d6ee8fc6d10fbb410bcb385105/pyproject.toml#L177-L186).

**Comment by egeres** [comment]
It would be great if the standard for ruff and flake8 assumed that `# ruff: noqa: N803`'s added on the very first lines of a file applied universally, or maybe even have a different syntax (?). But I understand this is too narrow of a requirement and it kinda defeats the purposes of being forced to write good quality code

**Comment by charliermarsh** [comment]
Yes, you can use `# ruff: noqa` or (for example) `# ruff: noqa: F401` to turn off violations all violations or a specific rule, respectively, within a given file. (`# flake8: noqa` is also supported for compatibility.)

**Comment by 1vecera** [comment]
I'd still like to be able to define it on a per-file basis so that different sets of rules apply to different portions of the project. 

Use case:
- My tests have a very lax set of rules when it comes to code quality
- My pipeline code has bit more relax set of rules
- My tests have nearly no rules apply to them

Writing #noqa 100x times wastes effort and generates hard-to-maintain code. @charliermarsh - I'd be happy for your view.

**Comment by MichaReiser** [comment]
@1vecera have you tried [`per-file-ignore`](https://docs.astral.sh/ruff/settings/#lint_per-file-ignores)?
