### ISSUE TITLE
Question: How can I ignore a rule in one directory?

### ISSUE THREAD

**Issue by MartinThoma** [charliermarsh/ruff#2457]
Thanks for this awesome tool :pray: 

I would like to enable all rules, but disable some in some directories. For example `S101 Use of assert detected` should be disabled in the `tests` directory (but only there). How do I do that?

**Comment by sbrugman** [comment]
This can be achieved using the following settings in `pyproject.toml`:

```
[tool.ruff.per-file-ignores]
"tests/*" = ["S101"]
```

**Comment by MartinThoma** [comment]
Nice! Thank you ❤️

**Comment by charliermarsh** [comment]
If you're having any trouble debugging those paths, `ruff --show-settings /path/to/file.py` will show you the resolved configuration including the regular expressions, and `ruff -v /path/to/file.py` will include debug logging that will tell you when a file is matched, and to what codes.
