### ISSUE TITLE
SIM300: Yoda condition... autofix drops left parenthesis

### ISSUE THREAD

**Issue by Jeremiah-England** [charliermarsh/ruff#2466]
```sh
ruff --select SIM300 --fix --diff test.py
```

The first parenthesis is dropped in the autofix here and the second parenthesis ends up in he wrong place. 

```diff
--- test.py
+++ test.py
@@ -1,3 +1,3 @@
 number = 1
-if 0 < (number - 100):
+if number - 100 > 0):
     print(number)
```

It should be like this:

```diff
--- test.py
+++ test.py
@@ -1,3 +1,3 @@
 number = 1
-if 0 < (number - 100):
+if (number - 100) > 0:
     print(number)
```

Ruff version: `0.0.239`.

Also, thanks for working on Ruff! It's super useful.

Edit: I see now you could strip out the parenthesis in that example completely. But that seems like a job for separate formatting rule. And my real-life example involved a walrus operator `:=` where the parenthesis were necessary.

**Comment by charliermarsh** [comment]
Woah, very strange! Taking a look.

**Comment by charliermarsh** [comment]
I have a few more minutes before bed so maybe I can fix it tonight :joy:
