### ISSUE TITLE
PLE0605 (invalid-all-format) doesn't recognize list constructor

### ISSUE THREAD

**Issue by eriknw** [charliermarsh/ruff#2486]
Quick follow-up to #2314 
```python
__all__ = list(names)
```
also doesn't work (ruff v0.0.239)

**Comment by charliermarsh** [comment]
:)

![Screen Shot 2023-02-02 at 12 33 06 PM](https://user-images.githubusercontent.com/1309177/216399173-4d3940e3-e186-42b4-a6c5-c04ed87f164e.png)

**Comment by charliermarsh** [comment]
Will get this into the next release (tomorrow or Saturday).
