### ISSUE TITLE
Automatically add all required pragmas to pass

### ISSUE THREAD

**Issue by adriangb** [charliermarsh/ruff#250]
Adding a tool like `ruff` or any linter to an existing unchecked codebase can be really painful.

Traditionally this is done by having include files and gradually ratcheting up the strictness. There are several issues with this approach, including forgetting to add a new file, renaming files or even knowing when to ratchet up the strictness.

An alternative is to add `# type: ignore` or `# pragma` comments to every line that produces an error. This has the advantage that files can be moved / renamed / refactored without issues. And any new files, new functions, etc. will by default have typing/linting enforced.

Thus it would be really interesting if ruff had a `--add-ignores` option or something like that would go over the entire codebase and add ignores wherever necessary to get the whole thing to pass.

**Comment by charliermarsh** [comment]
Yeah this is cool, we should do it.

**Comment by charliermarsh** [comment]
Relatedly, we should do #251 _and_ have a setting to automatically remove unused `noqa` messages.

**Comment by adriangb** [comment]
I imagine this "autopragma" system would be quite similar except that the "fix" would be to add the right pragma comment (instead of deleting it). I think I'm going to watch how you handle #255 and study the autofix system a bit, and maybe I'll be able to handle this (no promises!)

**Comment by charliermarsh** [comment]
Oops, I may've beat you to it -- I have an initial implementation here: #256. (It isn't fully wired-up yet. I also opted to do it as its own flow rather than as a lint rule that can be autofixed but I may reverse that decision...)

**Comment by adriangb** [comment]
Yep you sure beat me! It would have taken me days but you got to it like a 🏎️
