### ISSUE TITLE
D210: `""" " """` string

### ISSUE THREAD

**Issue by spaceone** [charliermarsh/ruff#2510]
`""" "tar xf" in "Python" """` causes D210 but it would be impossible to fix that (except for using single-triple quotes, which would raise another issue)

**Comment by charliermarsh** [comment]
I think that should arguably be written as `"""\"tar xf\" in \"Python\""""`? Otherwise, you end up with quotes _inside_ the docstring, which probably isn't intended.

**Comment by charliermarsh** [comment]
I think escaping is the correct solution here, but happy to re-open if not.
