### ISSUE TITLE
Remove update-check support?

### ISSUE THREAD

**Issue by charliermarsh** [charliermarsh/ruff#2515]
This used to be on-by-default, then we made it off-by-default. I can find a _few_ usages of `update-check = true` via GitHub Code Search, but perhaps this isn't worth maintaining.

**Comment by JonathanPlasse** [comment]
I do not think there is a need to keep it.
As every day there is a new release (which is greatly appreciated), you just know you can update.

**Comment by akx** [comment]
👍 for getting rid of it.
