### ISSUE TITLE
Support multiple target versions

### ISSUE THREAD

**Issue by JonathanPlasse** [charliermarsh/ruff#2519]
- To implement #2039 we need to support multiple target versions.
- We should use the minimum target version for pyupgrade.
-  For isort known standard library, we should check that the module is present for all target version
- …

**Comment by charliermarsh** [comment]
What's the difference in practice between supporting a minimum version, and a range of versions?

**Comment by JonathanPlasse** [comment]
For isort known standard library, you could have some modules that are removed for later versions.
If you use the minimum version, you would have a false negative for the later versions if you use a dropped module.

**Comment by charliermarsh** [comment]
I guess I'm not sure _what_ should happen if you specify that your minimum version is `3.7`, and you import `tomllib`.

**Comment by JonathanPlasse** [comment]
It should report this as an error as it is not available in the Python 3.7 standard library.

**Comment by stinodego** [comment]
I know that `black` is actually trying to get rid of target ranges and wants to switch to a single minimum target version.

I don't think supporting target ranges is worthwhile.

**Comment by charliermarsh** [comment]
Yeah I'd like to only support a minimum target version until convinced otherwise (i.e., until that's proven insufficient).

**Comment by charliermarsh** [comment]
Closing for now as I'm okay with current behavior (only supporting minimums).
