### ISSUE TITLE
RUF005 autofix causes an endless loop

### ISSUE THREAD

**Issue by bluetech** [charliermarsh/ruff#2523]
The following code

```py
[] + x + [
]
```

causes an endless loop when run with `ruff --select RUF005 --fix --isolated x.py` and no `pyproject.toml`.

ruff 0.0.240

**Comment by charliermarsh** [comment]
Thanks!

**Comment by charliermarsh** [comment]
Wow it actually hangs. I thought you meant an autofix loop :joy:
