### ISSUE TITLE
How can auto-completion be set up for Ruff?

### ISSUE THREAD

**Issue by JonathanPlasse** [charliermarsh/ruff#2540]
I was wondering if there was a command to run to set up auto-completion for Ruff.

**Comment by charliermarsh** [comment]
We have `ruff generate-shell-completion [bash]` but no thorough docs.

**Comment by JonathanPlasse** [comment]
We could take [poetry documentation](https://python-poetry.org/docs/#enable-tab-completion-for-bash-fish-or-zsh) as inspiration.

**Comment by charliermarsh** [comment]
Yeah that looks good. We can add something to the README.

**Comment by charliermarsh** [comment]
PR welcome if anyone wants to draft it :joy: Otherwise I'll get to it later.

**Comment by JonathanPlasse** [comment]
I can work on it.
