### ISSUE TITLE
Have option to ignore unknown rule selector codes

### ISSUE THREAD

**Issue by mhvk** [charliermarsh/ruff#2557]
In `astropy`, we're very happily converting our style checking to `ruff` but the pace of `ruff` development causes some issues for me at least: I've set up my (emacs with flycheck) to auto-run `ruff`, but now any time the version of `ruff` installed on the system does not exactly match the one on which the exclude/include selection codes in `pyproject.toml` are based, such that a newly implemented (or removed) selector is not known, one just gets a failure and `ruff` does not run. (Specifically, in `astropy` we had listed `PLC2201` as something not to run, but this has been deprecated and now any time I visit a branch that does not yet have that one changed to `SIM300`, I get errors.) 

Such problems could be alleviated if there were an option for ignoring unknown selector codes and just run with the ones that are recognized. Would it be possible to implement this? I don't think it would even need a new code; it seems logical under "-q" (well, logical to the extent that I thought it was when I read "Print lint violations, but nothing else").

**Comment by charliermarsh** [comment]
Let me think on the broader request, but first: I'm sorry about the `PLC2201` thing. In hindsight, I should've changed that to a redirect (by pointing it to `SIM300`) rather than removing it entirely (which had the potential to cause breakages, as you experienced). It's not something that I anticipate happening often, and I'll try to be more careful about it going forward.

**Comment by charliermarsh** [comment]
I think my preference is to err on the side of keeping configuration strict, and to try and avoid backwards-incompatible changes as much as possible. I'm also hopeful that slowing the pace of new rule rollouts will make this less challenging for users.

**Comment by by-cx** [comment]
I am not sure how to deal with this:
![Image](https://github.com/user-attachments/assets/7babd8b8-6cda-4731-9922-68eb68d11362)
