### ISSUE TITLE
Ability to extend per-file-ignored

### ISSUE THREAD

**Issue by Alphasite** [charliermarsh/ruff#2558]
Hi i have a similar issue to !2446, in our mono repo we have a global `ruff.toml` file which has per file ignores specified in it and we would like to add sub-project specific ignores in the child `pyproject.toml` file, but currently that will override those provided in the parent toml. 

So i'd like to propose the addition of an `extend.per-file-ignores` so that we can add extra ignores without removing the ones provided in the parent config file.

**Comment by charliermarsh** [comment]
This will exist in the next release.
