### ISSUE TITLE
UP030 not fixable for multiline issues

### ISSUE THREAD

**Issue by spaceone** [charliermarsh/ruff#2579]
```python
print(
    "{0} {1}"
    "{2}".format(1, 2, 3)
)
```
is detected (`foo.py:2:5: UP030 [*] Use implicit references for positional format fields`) but cannot be autofixed.

**Comment by charliermarsh** [comment]
This is known and due to a limitation in LibCST, tracked by an issue in that repo: https://github.com/Instagram/LibCST/issues/846.
