### ISSUE TITLE
Make TCH005 (empty type checking block) autofixable

### ISSUE THREAD

**Issue by LefterisJP** [charliermarsh/ruff#2582]
ruff version: `0.0.237`

After some other auto-fixes I got some empty type checking blocks in a few files. Essentially:

```python
if TYPE_CHECKING:
    pass
```

Running ruff again detected them but it seems it can't autofix them. Only get the error: ` TCH005 Found empty type-checking block`
From a completely naive user perspective it seems easy to implement autofix for this, so just opening an issue for that.

**Comment by charliermarsh** [comment]
Ah yeah that's straightforward. Should make it into the next release.
