### ISSUE TITLE
SLF001 triggered when using a private static method within the class

### ISSUE THREAD

**Issue by twoertwein** [charliermarsh/ruff#2584]
```py
class A:
    def test(self):
        return A._static_but_private()  # SLF001

    @staticmethod
    def _static_but_private():
        return 0
```
It might be nice to allow the above.

**Comment by ngnpope** [comment]
This likely wouldn't be possible without type checking support in ruff?

You can use `self._static_but_private()` instead of `A._static_but_private()`.

**Comment by charliermarsh** [comment]
We can _probably_ support this, because we know `A` is bound to the current class there.

**Comment by twoertwein** [comment]
> You can use `self._static_but_private()` instead of `A._static_but_private()`.

That works for me. Feel free to close the issue.
