### ISSUE TITLE
Fixable error is not fixed

### ISSUE THREAD

**Issue by WhyNotHugo** [charliermarsh/ruff#2621]
Sample code: https://github.com/WhyNotHugo/python-barcode/blob/f824d00592daabbe62a9c9a68b7a3113c215207d/barcode/writer.py#L264

```console
> ruff .      
barcode/writer.py:264:17: SIM108 [*] Use ternary operator `xpos = bxs + (bxe - bxs) / 2.0 if self.center_text else bxs` instead of if-else-block
Found 1 error.
[*] 1 potentially fixable with the --fix option.

> ruff --fix .
barcode/writer.py:264:17: SIM108 [*] Use ternary operator `xpos = bxs + (bxe - bxs) / 2.0 if self.center_text else bxs` instead of if-else-block
Found 1 error.
```

But nothing is fixed. `pyproject.toml`:

```toml
[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm>=6.2"]

[tool.setuptools_scm]
write_to = "barcode/version.py"
version_scheme = "post-release"

[tool.black]
target-version = ['py37']

[tool.ruff]
select = [
    "E",
    "F",
    "W",
    "B0",
    "I",
    "UP",
    "N",
    "C4",
    "PT",
    "SIM",
    "TID",
]
target-version = "py37"

[tool.ruff.isort]
force-single-line = true
```

**Comment by charliermarsh** [comment]
The problem is likely that fixing this error would result in a line that exceeds the specified line length.

**Comment by charliermarsh** [comment]
Which is intended -- that we skip the fix -- but could be better communicated in the output.

**Comment by ngnpope** [comment]
Also related: https://github.com/charliermarsh/ruff/issues/1791.

It would be hard to know what to do with the placement of the comment too which may no longer make sense.

I guess it does say "potentially fixable" 😅

**Comment by WhyNotHugo** [comment]
Makes perfect sense to skip the change if there are comments.

But also agree that output should make clear what's up.

**Comment by charliermarsh** [comment]
We should probably detect that we _won't_ fix that case, and not add the `[*]`, and not include it in the list of potentially fixable errors.

**Comment by charliermarsh** [comment]
(Oh sorry, I didn't actually look at the code -- it is indeed because of the comment, that we avoid fixing it. But we should still make that clear.)

**Comment by spaceone** [comment]
shouldn't the comment cause that it's not detected as `SIM108` as the comment is the reason that it should not be written as one-liner?

**Comment by charliermarsh** [comment]
We used to have that behavior but I changed it. It led to confusing behavior like https://github.com/charliermarsh/ruff/issues/2442 whereby adding a `noqa` comment would turn off that check and lead to an unused `noqa`.
