### ISSUE TITLE
fix line-length failed 

### ISSUE THREAD

**Issue by linpan** [charliermarsh/ruff#2622]
`def format_record(record: dict) -> str:
    """
    Custom format for loguru loggers.
    Uses pformat for log any data like request/response body during debug.
    Works with logging if loguru handler it.

    Example:
    >>> payload = [{"users":[{"name": "Nick", "age": 87, "is_active": True}, {"name": "Alex", "age": 27, "is_active": True}], "count": 2}]
    >>> logger.bind(payload=).debug("users payload")
    >>> [   {   'count': 2,
    >>>         'users': [   {'age': 87, 'is_active': True, 'name': 'Nick'},
    >>>                      {'age': 27, 'is_active': True, 'name': 'Alex'}]}]
    """`
> demo/_logger.py:44:1: E501 Line too long (138 > 120 characters)

**Comment by charliermarsh** [comment]
Unfortunately `E501` isn't a "fixable" issue right now. If you take a look at the [index](https://github.com/charliermarsh/ruff#error-e) in the README, the rules with the hammer and wrench in the "Fix" column are fixable.
