### ISSUE TITLE
Ruff code actions in VS Code producing unexpected output

### ISSUE THREAD

**Issue by JRyanHall94** [charliermarsh/ruff#2625]
My issue is that when I save this file with these settings, I get unexpected behavior. Perhaps it's just the way that I have everything ordered in settings, but I tried adjusting things and couldn't figure out how to resolve this issue. Thanks in advance!

I am using black and ruff installed locally and I am formatting a file within an active venv in VS Code. My settings and the code are posted below, along with the unexpected output:

```
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    pass

```
becomes
```
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    pass
    pass

```
----------
Settings in VS Code:
```
{
    "ruff.path": [
        "/Library/Frameworks/Python.framework/Versions/3.11/bin/ruff"
    ],
    "[python]": {
        "editor.codeActionsOnSave": {
            "source.fixAll": true,
            "source.organizeImports": true
        }
    },
    "editor.formatOnSave": true,
    "python.formatting.provider": "black",
    "python.formatting.blackPath": "/Library/Frameworks/Python.framework/Versions/3.11/bin/black"
}
```
current ruff version: ruff 0.0.243
current black version: black, 23.1.0 (compiled: yes)
current Python version: Python 3.11.1

note that if I remove the ruff portion of the settings, black formats the file as expected.

**Comment by charliermarsh** [comment]
Thanks for filing! The problem is the double `pass` statement, right? The removal of `from django.db import models` is expected. Am I interpreting correctly?

**Comment by JRyanHall94** [comment]
Yes, absolutely 👍

**Comment by charliermarsh** [comment]
I'm just gonna close in favor of the corresponding issue in the `ruff-vscode` repo (linked above). Thank you for filing!
