### ISSUE TITLE
UP003 false-positive introduces bug

### ISSUE THREAD

**Issue by spaceone** [charliermarsh/ruff#2632]
```python
arg = 1   # any type, not string
type(arg)(' ') in arg
```

`ruff --fix --select UP003 foo.py` turns it into:

```python
arg = 1   # any type, not string
str in arg
```

**Comment by charliermarsh** [comment]
Can you explain what this code is doing? Heh I'm having a hard time understanding it.

**Comment by spaceone** [comment]
It's pseudocode, simplified from somewhere else where `arg` is not a `str`.
but that's irrelevant: 
`UP003` should fix `type(' ')` but not `type(something)(' ')` when it doesn't inspect what `something` is.
