### ISSUE TITLE
Same way to ban import of certain modules?

### ISSUE THREAD

**Issue by ehdr** [charliermarsh/ruff#2656]
It would be great to have a kind-of inverse of [`required-imports`](https://github.com/charliermarsh/ruff#required-imports), to **prevent** certain modules from being imported.

In our specific use case, we'd like to prevent certain modules from being imported only in `tests/*`.

Googling, I found some seemingly related solutions like [python-import-linter](https://921kiyo.com/python-import-linter/) and [pylint-restricted-imports](https://pypi.org/project/pylint-restricted-imports/), but haven't used either.

(And mandatory praise: ruff is ⭐ ! Please continue and build better versions of every tool in the Python ecosystem!)

**Comment by ngnpope** [comment]
Can you use [`banned-api`](https://github.com/charliermarsh/ruff#flake8-tidy-imports-tid) to achieve this?

I use something like the following:
```toml
[tool.ruff.flake8-tidy-imports]
[tool.ruff.flake8-tidy-imports.banned-api]
"dateutil.tz".msg = "Use `zoneinfo` instead."
"mock".msg = "Use `pytest-mock` instead."
"pytz".msg = "Use `zoneinfo` instead."
"unittest".msg = "Use `pytest` instead."
"unittest.mock".msg = "Use `pytest-mock` instead."
```

**Comment by ehdr** [comment]
Oh nice! Yes this looks very close to what I need, except, as you point out, that I'd need to also restrict it to only `tests/*` somehow.

**Comment by ehdr** [comment]
Beautiful! Ever closer.

For more detail, I want warning when we import from a certain top level module (e.g. `import top` or `from top import ...`), but allow importing from submodules of `top` (e.g. `import top.internal` or `from top.internal import ...`). Since [`flake8-tidy-imports`](https://pypi.org/project/flake8-tidy-imports/) seems to support `*` wildcards, would it be possible to change it so `"top".msg = "Import submodules directly instead."` matches only `top` exactly, and you'd have to specify the `top.*` wildcard if you want to match submodules too? I guess that would not be backwards compatible though.

**Comment by ngnpope** [comment]
Yeah, I think that's not possible as this stands.

**Comment by charliermarsh** [comment]
Thanks for the kind words :)

Ah yeah, that's not possible today -- to disallow the top-level import, but allow importing submodules, since we treat `from top.internal` as matching `top`. I was kind of hoping to avoid adding globbing there, just for simplicity. But I'll open a new issue to track that functionality. (I likely won't get to it soon, but it'd be good to know if others need this too.)

**Comment by charliermarsh** [comment]
Tracking here: #2660.
