### ISSUE TITLE
D417 with numpy docstyle?

### ISSUE THREAD

**Issue by tlambert03** [charliermarsh/ruff#2672]
This is either a feature request, or just a general question.  you let me know :)

I have a somewhat long config to enable something like numpy style docstrings **and** D417 (which is, for me, one of the most valuable docs rules).  I see that the readme explains that adding any docstyle convention overrides any additional config, which prevents me from just using that plus D417.  I'm wondering whether an exception could be made for D417 (it doesn't _seem_ incompatible with any other rules)?

See related issues in pydocstyle, https://github.com/PyCQA/pydocstyle/issues/394 and PR https://github.com/PyCQA/pydocstyle/pull/407

**Comment by ngnpope** [comment]
Duplicate of #2606?

**Comment by tlambert03** [comment]
yeah, special case.  thanks for pointing that out.  Will close here
