### ISSUE TITLE
Feature request: isort.force-to-top

### ISSUE THREAD

**Issue by henryiii** [charliermarsh/ruff#2695]
I couldn't see it listed elsewhere, so I'd like to point out `[tool.isort] force_to_top = ["setuptools"]`. It's useful for putting an import that must be imported before other imports (setuptools should be imported before distutils), or maybe for sticking pytest at the top.

**Comment by charliermarsh** [comment]
Closed by #2877.

**Comment by charliermarsh** [comment]
(Which will merge shortly.)
