### ISSUE TITLE
S112: why forbidden?

### ISSUE THREAD

**Issue by spaceone** [charliermarsh/ruff#2725]
why is `S112` disallowing this? 
```
for foo in bar:
    try:
        if foo['bar'][0] == baz:
            continue
    except (KeyError, IndexError):
        continue
```

I can live with disallowing `except Exception:` but I don't see above makes sense.

**Comment by charliermarsh** [comment]
I think that's a bug, we're not handling the tuple correctly.

**Comment by edgarrmondragon** [comment]
Just to confirm, @spaceone do you have [`check-typed-exception`](https://github.com/charliermarsh/ruff#check-typed-exception) set to true?

**Comment by charliermarsh** [comment]
I _think_ it's unrelated to that setting -- we have `checker.resolve_call_path(type_).map_or(true, ...)`, so if the value isn't resolvable to a reference (which would be the case for any tuple), then we'll trigger the check. But, testing now...
