### ISSUE TITLE
VS Code Extension Error - The language client is not ready yet

### ISSUE THREAD

**Issue by mason3k** [charliermarsh/ruff#2740]
Using version 2022.0.26 of the extension on Visual Studio Code 1.75.1:

When I use the command palette to run any Ruff linting command (auto-fix all fixable, restart server) I receive the following error in a pop-up:

"The language client is not ready yet"

Restarted VS Code to no effect. I have not customized any settings. 

Other specs:
![image](https://user-images.githubusercontent.com/48703453/218192145-9a8ec300-349b-4ade-a02f-00867738871c.png)

Thanks for the work you do; I'm excited about the project.

**Comment by sbrugman** [comment]
Thanks for reporting this. Probably the best place to report this issue is at the relevant repository: https://github.com/charliermarsh/ruff-vscode

**Comment by mason3k** [comment]
Thanks, I wi
