### ISSUE TITLE
CLI: --color=auto|no|yes

### ISSUE THREAD

**Issue by spaceone** [charliermarsh/ruff#2743]
The CLI should support `--color=auto|no|yes` where `auto` detects if the output is redirected into a pipe/file and prevent colorizing output in that case.

**Comment by charliermarsh** [comment]
We already support this via environment variables which I think is sufficient personally (see #1830).

**Comment by charliermarsh** [comment]
Any reason the env vars wouldn't work for you?

**Comment by spaceone** [comment]
env vars are OK. I didn't find them by grepping through the source code as it's probably in a external lib. maybe just document it in README.md

**Comment by spaceone** [comment]
ah, and detecting if the stdout filedescriptor is being redirected to a file should disable the color output as well imho. most unix tools do that.

**Comment by charliermarsh** [comment]
Does the external lib not handle that?

**Comment by spaceone** [comment]
i somehow don't get it working. even `NO_COLOR=1` prints ANSI escape sequences.

**Comment by spaceone** [comment]
for `--show-source` it seems `NO_COLOR=1` has no effect. but for the regular output it has. That's the bug.

**Comment by charliermarsh** [comment]
Hmm, it definitely works for me

**Comment by charliermarsh** [comment]
Ahh ok

**Comment by charliermarsh** [comment]
That makes sense

**Comment by charliermarsh** [comment]
`--show-source` goes through a separate mechanism, I'll look into it

**Comment by charliermarsh** [comment]
(Created separate issues for these.)

**Comment by Sarcasm** [comment]
> Any reason the env vars wouldn't work for you?
> -- https://github.com/astral-sh/ruff/issues/2743#issuecomment-1426368171

Discoverability.

I wanted to pipe `ruff check --show-source` to a pager:

```
ruff check --show-source src | less -F -X
```

Seeing the absence of color, the fastest way for me to find it, was to do:

```
$ ruff -h
$ ruff check -h
$ man ruff
No manual entry for ruff
```

So I had to google it, and found this issue.

If I search directly on the website I find:

> How can I disable Ruff's color output?
> -- https://beta.ruff.rs/docs/faq/#how-can-i-disable-ruffs-color-output

I feel like the command line `-h` is more discoverable.
The `--color=auto|yes|no` help documentation could mention the env vars for those who prefer to use that, but I think it's more common in CI or build scripts than for when the user needs it on the command line.

BTW ruff is great!
