### ISSUE TITLE
Link the docs in Github repo settings

### ISSUE THREAD

**Issue by sbrugman** [charliermarsh/ruff#2754]
Would be nice to have quick access to the [docs](https://beta.ruff.rs/docs/) in the repository menu on github. Would look similar to this:

<img width="340" alt="Screenshot 2023-02-11 at 01 38 46" src="https://user-images.githubusercontent.com/9756388/218227269-3180ef59-40f1-4a87-b789-874f5f80d1c5.png">

**Comment by charliermarsh** [comment]
Nice suggestion, done!
