### ISSUE TITLE
Error on E701 Multiple statements on one line (colon)

### ISSUE THREAD

**Issue by cclauss** [charliermarsh/ruff#2765]
Ruff v0.0.245 raises a `Multiple statements on one line (colon)` error while v0.0.244 did not.
`total_color = success_color_fn if all_green else lambda x: x`
`openlibrary/i18n/__init__.py:234:70: E701 Multiple statements on one line (colon)`

**Comment by charliermarsh** [comment]
Thanks! Will fix.
