### ISSUE TITLE
Link relevant settings in rule documentation

### ISSUE THREAD

**Issue by sbrugman** [charliermarsh/ruff#2766]
The individual rule documentation pages should reflect which settings are available that impact that rule. We could rely on the developers updating the documentation description with new rules and settings, but this is error prone. 

A dedicated section could help structure the related rules (did not find a good example in pylint etc.)

A more engineering heavy option is to keep track of a mapping between rules and options. (cc: @not-my-profile) This approach allows for automatic link generation, and linking from rule -> setting and vice versa.

Example:
- For [relative imports](https://beta.ruff.rs/docs/rules/relative-imports/) (link to strictness option seems broken, should be [this](https://github.com/charliermarsh/ruff#ban-relative-imports))
- For [unconventional-import-alias](https://beta.ruff.rs/docs/rules/unconventional-import-alias/), we have not linked the [relevant settings](https://beta.ruff.rs/docs/settings/#flake8-import-conventions) yet.

No strong preference, just putting the idea on the table.

**Comment by charliermarsh** [comment]
My preference for now is to do it manually 😅

**Comment by not-my-profile** [comment]
I know a nice way to do this ... I'll implement it after #2775 has been merged, since the refactors in that PR make implementing what I have in mind easier.

**Comment by charliermarsh** [comment]
Awesome :)
