### ISSUE TITLE
Allow `pyproject.toml` discovery to be disabled for subdirectories

### ISSUE THREAD

**Issue by isaacharrisholt** [charliermarsh/ruff#2769]
## Context

I'm working on a project templating tool in Python, using Ruff for linting (love it, by the way!). It's using a `pyproject.toml` file for config, as I'm using Poetry for environment management.

I'm storing the templates in the same directory as the tool, and one of those templates is a generic Poetry project template with some pre-commit hooks and tooling set up. This, of course, uses Ruff and includes a `pyproject.toml` file with Ruff config.

## My dilemma

Essentially, every time I run Ruff in the root of the project, two `.ruff_cache` directories are created - one in the root, and one in the directory where the Poetry project template lies. This isn't ideal, as this template then includes a `.ruff_cache` directory, which gets copied into new projects when the tool is run.

My current workaround is to exclude `.ruff_cache` directories from the Poetry build, but it would be nice to have a way to prevent the hierarchical behaviour in subdirectories so that this doesn't happen. I'm aware that there are other ways of solving my problem, but having 'default' `pyproject.toml` files is not an uncommon thing, so it would be nice to see a solution implemented in Ruff, if possible.

## The solution

I'm not familiar with the Ruff source code, so I can't suggest a technical solution, but my suggestion would be something along the lines of adding the following config option to the `pyproject.toml`:

```toml
[tool.ruff]
disable_pyproject_discovery = true
```

This would disable `pyproject.toml` discovery only in subdirectories of this `pyproject.toml` which would allow people to disable the feature in specific parts of their application, if they so desire.

Let me know what you think!

**Comment by not-my-profile** [comment]
Doesn't `extend-exclude = ["templates/"]` work? (assuming your directory is called `templates/`) ... if this doesn't work I think we should make it work rather than introducing yet another config option.

**Comment by isaacharrisholt** [comment]
Technically yes, but then I don't get linting in my templates! The package I'm writing allows arbitrary Python to be run upon rendering the template, and that Python is kept in the template directory. It would be great if that (and other Python in the directory) was linted.

**Comment by not-my-profile** [comment]
Ah ... in that case I think it would be better if you'd just rename those template files e.g. `pyproject.toml.template` or  `pyproject.toml.jinja2`. I think having `pyproject.toml` files that are disabled by some other `pyproject.toml` file would be quite confusing.

**Comment by isaacharrisholt** [comment]
That makes sense, and I do understand that I have a very niche problem, but I can't imagine I'm the only person who would want to disable the default behaviour here?

Happy to close this issue if you disagree!

**Comment by not-my-profile** [comment]
I don't really understand your use case. Your project templating tool would have to remove this `disable_pyproject_discovery` setting when it deploys the template, wouldn't it? Since you need to postprocess it anyway ... you could just as well rename the section to `[tool.ruff-disabled]` or change the file extension.

**Comment by isaacharrisholt** [comment]
No worries! I've got a workaround anyway, I just figured that not everyone will want automatic `pyproject.toml` discovery, and may prefer to have it disabled in part of their project.

**Comment by not-my-profile** [comment]
If other people end up wanting the same feature, we can always reconsider this :)
