### ISSUE TITLE
Infinite loop on unclosed parenthesis

### ISSUE THREAD

**Issue by andersk** [charliermarsh/ruff#277]
If you run ruff on this file with an unclosed parenthesis:

```python
print(
```

it loops forever allocating several GB of memory per second. This regression was introduced by 38b19b78b737ee3f2c0f781fb14950f4d4a97326. The problem is that

https://github.com/charliermarsh/ruff/blob/886def13bd2cfc2bfb20ad3c0e42991f5ac1e2cb/src/linter.rs#L87

produces an infinite stream of `Err(LexicalError { error: Eof, location: Location { row: 2, column: 1 } })` repeating forever, which doesn’t fit easily into a `Vec`.

**Comment by charliermarsh** [comment]
Oh good catch, thanks for filing. I wonder why this didn’t error before. Will take a look.
