### ISSUE TITLE
Incorrect double reverse in sorted rule C413

### ISSUE THREAD

**Issue by Skylion007** [charliermarsh/ruff#2772]
The comprehension fixits assume the user was unaware of the reverse=True keyword. This not always the case and it can be caused by an accidental double apply or an unnecessary attempt to ensure sorted is a stable sort (it is in recent Python versions). The fixits generated here are wrong

```python
b = range(10)
c = reversed(sorted(b, reverse=True))
```
the fixit suggests:
```python
b = range(10)
c = sorted(b, reverse=True)
```
which obviously wrong. The proper fixit would be:
```python
b = range(10)
c = sorted(b)
```

Version is ruff 0.0.244. 
Command is `ruff --select C example.py --fix`

**Comment by sbrugman** [comment]
Working on a fix
