### ISSUE TITLE
Document how to build the mkdocs documentation

### ISSUE THREAD

**Issue by not-my-profile** [charliermarsh/ruff#2802]
`CONTRIBUTING.md` should explain how you can build our mkdocs documentation so that you can preview your local changes.

**Comment by trag1c** [comment]
I can do this one :)

**Comment by not-my-profile** [comment]
Just a note: In particular I am talking about the dependencies that are needed ... these are currently only specified in the GitHub workflow file:

https://github.com/charliermarsh/ruff/blob/0123425be15a6b09f22bd23489c648e534fd9197/.github/workflows/docs.yaml#L18

These should instead be defined in e.g. `docs/requirements.txt` ... and the above command should be changed to a `pip install -r docs/requirements.txt`. And then the `CONTRIBUTING.md` file could tell you to run that same command.

**Comment by trag1c** [comment]
@not-my-profile Any suggestions on where exactly that section should be placed? 🤔

**Comment by not-my-profile** [comment]
Maybe before *Release process*.
