### ISSUE TITLE
New rule: warning accidental garbage collection of `asyncio.create_task`

### ISSUE THREAD

**Issue by Glyphack** [charliermarsh/ruff#2809]
I wanted to purpose a new lint rule. The `asyncio.create_task` function has a caveat, which is when you create a task in order to make sure it finishes you need to take a reference to it.
![image](https://textual.textualize.io/blog/images/async-create-task.jpeg)

I first read about this in [this post](https://textual.textualize.io/blog/2023/02/11/the-heisenbug-lurking-in-your-async-code/). Which also sites a lot of projects that are doing this wrong.

Is this something that ruff wants to support? I could give it a try to implement it in that case.

**Comment by edgarrmondragon** [comment]
This was requested in `flake8-async`: https://github.com/cooperlees/flake8-async/issues/5

**Comment by charliermarsh** [comment]
We could implement it as part of `RUF` for now. I'd support it!

**Comment by samuelcolvin** [comment]
amazing!

**Comment by charliermarsh** [comment]
Lol, I can do this today, I didn't realize there were so many upvotes on it.

**Comment by Lunarmagpie** [comment]
I didn't know I needed this lol
