### ISSUE TITLE
noqa: F40 as shorcut for noqa: F401,F403

### ISSUE THREAD

**Issue by cclauss** [charliermarsh/ruff#2818]
The linter directive `# noqa: F40` works as expected in flake8 while ruff requires `# noqa: F401,F403` to do something similar.  Would it be possible to adopt the same linter directive syntax?

**Comment by charliermarsh** [comment]
I think we're somewhat unlikely to support this. I know it works in Flake8, but I think the complexity of the implementation (plus having to support this with `--add-noqa`, and with the `RUF100`-style noqa enforcement) wouldn't outweigh the benefits, which don't seem that compelling to me. (I actually think it's good to encourage users to explicitly enumerate ignored codes, though it can be more tedious.)
