### ISSUE TITLE
E701 check in 0.0.245 disagrees with black for .pyi files

### ISSUE THREAD

**Issue by alex** [charliermarsh/ruff#2835]
In `.pyi` files, everything is stubbed out like:

```
def foo() -> int: ...

class MyClass: ...
```

This is how black formats them, but ruff is upset with them.

Example here: https://github.com/pyca/cryptography/actions/runs/4158646856/jobs/7194009425

Thanks

**Comment by charliermarsh** [comment]
Thanks -- this is resolved for E704 in the next release, but this is good reminder that I need to fix it for E701 and friends too.

**Comment by alex** [comment]
Thanks

On Sun, Feb 12, 2023 at 6:37 PM Charlie Marsh ***@***.***> wrote:
>
> Thanks -- this is resolved for E704 in the next release, but this is good reminder that I need to fix it for E701 and friends too.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***>



-- 
All that is necessary for evil to succeed is for good people to do nothing.
