### ISSUE TITLE
noqa: E501 not detected

### ISSUE THREAD

**Issue by spaceone** [charliermarsh/ruff#2849]
```python
    """
     >>> UsernameHandler(20).format_username('Foo[COUNTER2][COUNTER2]')  # noqa: E501 # doctest: +IGNORE_EXCEPTION_DETAIL
    """
```

doesn't ignore `E501`

**Comment by JonathanPlasse** [comment]
Is it intentional to have `# noqa: E501` inside the string?
Ruff does not read `noqa` inside string.
You must place the `noqa` after the string for it to work.
```python
    """
     >>> UsernameHandler(20).format_username('Foo[COUNTER2][COUNTER2]')  # noqa: E501 # doctest: +IGNORE_EXCEPTION_DETAIL
    """  # noqa: E501
```

**Comment by charliermarsh** [comment]
That’s correct — we don’t respect noqa comments _inside_ of strings.

**Comment by spaceone** [comment]
OK, feels better. But this was supported by `flake8` and then different with ruff. but `flake8` also support the ruff-noqa variant → switched the code to that.
