### ISSUE TITLE
`S608` Triggered on Exception

### ISSUE THREAD

**Issue by colin99d** [charliermarsh/ruff#2854]
I am getting an `S608` error on the following line of code:
`raise Exception(f"Select a valid asset from {', '.join(ASSETS)}")`

There is no use of SQL in the file.

**Comment by charliermarsh** [comment]
I think this is probably consistent with Bandit unfortunately.

**Comment by spaceone** [comment]
→ https://github.com/PyCQA/bandit/issues/984#issuecomment-1428001342
