### ISSUE TITLE
Implement SIM104 as an alias of UP028

### ISSUE THREAD

**Issue by Skylion007** [charliermarsh/ruff#2866]
I noticed SIM104 is unimplemented, but UP028 is and they are exactly the same rule. It would be great if an alias could be added to enable the rule for SIM104.

**Comment by sbrugman** [comment]
Thanks for flagging. These cases are tracked here: https://github.com/charliermarsh/ruff/issues/2186
Solution in progress: https://github.com/charliermarsh/ruff/pull/2517

**Comment by charliermarsh** [comment]
Thanks, commented there!
