### ISSUE TITLE
Options included via `ruff rule F841` (or equivalent) are unlinked

### ISSUE THREAD

**Issue by charliermarsh** [charliermarsh/ruff#2867]
Should we just make these direct links to the documentation rather than references?

<img width="868" alt="Screen Shot 2023-02-13 at 2 39 44 PM" src="https://user-images.githubusercontent.com/1309177/218557985-b0f5a95e-d14d-47f6-888d-9069983cac6f.png">

**Comment by charliermarsh** [comment]
Alternatively, should we rewrite these links during `ruff rule`?

**Comment by ngnpope** [comment]
Yeah. It looks like [mdcat](https://crates.io/crates/mdcat) has some limitations, including:

> Not supported:
> 
> * CommonMark extensions: [Footnotes](https://github.com/swsnr/mdcat/issues/1) and [tables](https://github.com/swsnr/mdcat/issues/2)
> * [Re-filling paragraphs](https://github.com/swsnr/mdcat/issues/4)

Reflowing paragraphs will be a problem, especially with longer links.

An alternative could be [`termimad`](https://crates.io/crates/termimad) which supports reflowing and tables, but I think that is lacking in other areas, e.g. code highlighting.

**Comment by not-my-profile** [comment]
I intentionally did not include these links in the `ruff rule` output. The installed `ruff` may not always be up to date so having its output link to the latest documentation could be confusing.

I implemented the `config` subcommand in #2775, which can show all the information we have about config settings. I think it would make sense to either automatically add a note ``Learn more about these options with `ruff config <option>``` or alternatively simply automatically including the option description in the `ruff` rule output.
