### ISSUE TITLE
git integration

### ISSUE THREAD

**Issue by spaceone** [charliermarsh/ruff#2921]
It would be nice if there would be a `git` integration so that via a command line option and a option in `pyproject.toml` would restrict `ruff .` to only files which are tracked in git and leave untracked files untouched.

**Comment by charliermarsh** [comment]
I believe we already ignore anything in `.gitignore`. Are you seeing otherwise? Or are you imaging a different behavior?

**Comment by spaceone** [comment]
we track the `.gitignore` in the repo, so I have lot of files which are untracked and not listed in `.gitignore` as I would not commit/push that.

**Comment by not-my-profile** [comment]
Git lets you configure additional gitignore files via `git config core.excludesfile`. We could also pick that up.

**Comment by charliermarsh** [comment]
I _think_ that's already picked up: https://docs.rs/ignore/latest/ignore/struct.WalkBuilder.html#method.git_global

**Comment by spaceone** [comment]
OK, then using this as inspecting git might be too costy?

**Comment by not-my-profile** [comment]
Yeah I think we in general should try to avoid adding new options when existing features do the job just fine.

**Comment by charliermarsh** [comment]
(Agreed.)
