### ISSUE TITLE
Ruff mistakes with Protocol and positional-only arguments.

### ISSUE THREAD

**Issue by nstarman** [charliermarsh/ruff#2925]
I'm not sure if I've dug down to the root of the issue, but the following code incorrectly produces the following errors. When I remove the `/` and make `array` positional-or-keyword, rather than positional-only, the errors disappear.

```python
Array = TypeVar("Array")

class SomeCallable(Protocol):
    def __call__(self, array: Array, /, key: Any) -> Array:
        ...
```

```
[tool.ruff]
target-version = "py310"
select = ["ALL"]
```

```
>>> pre-commit run ruff -a

.../data.py:258:18: ANN001 Missing type annotation for function argument `self`
.../data.py:258:41: N805 First argument of a method should be named `self`
```

- [x] A minimal code snippet that reproduces the bug.
- [x] The command you invoked (e.g., `ruff /path/to/file.py --fix`), ideally including the `--isolated` flag.
- [x] The current Ruff settings (any relevant sections from your `pyproject.toml`).
- [x] The current Ruff version is "v0.0.243"

**Comment by charliermarsh** [comment]
Thank you!

**Comment by charliermarsh** [comment]
I think the `N805` error is fixed on `main` already.
