### ISSUE TITLE
Location span in check / message

### ISSUE THREAD

**Issue by Seamooo** [charliermarsh/ruff#293]
A nice-to-have for editor integration would be some sort of span indicated by the check or message.
The only information given at this stage is the start of the check, so the only inferred span possible is a single character.

Admittedly this would require additional work for every current check implemented, but if there's an agreed upon way of going about this I'm happy to put time into it

**Comment by charliermarsh** [comment]
One challenge here is that unlike Python's AST module, RustPython doesn't include end locations for nodes, only for tokens.
