### ISSUE TITLE
converting f-strings to normal strings, contents are not correctly preserved  f'{{test}}' == '{test}' != '{{test}}'

### ISSUE THREAD

**Issue by OliverTED** [charliermarsh/ruff#2936]
The f-string f"{{test}}" without a variable, it is automatically converted to "{{test}}".  

But they are not the same. (See: https://peps.python.org/pep-0498/#escape-sequences ; e.g. f'{{ {4*10} }}' == '{ 40 }')

Expected: f"{{test}}" -> "{test}"

BTW, Thanks for ruff ... !

**Comment by charliermarsh** [comment]
Thanks for filing!

**Comment by charliermarsh** [comment]
(Confirmed, the autofix here just removes the prefix, but doesn't un-escape any curly contents.)
