### ISSUE TITLE
Replace `mdcat` with a smaller dependency

### ISSUE THREAD

**Issue by charliermarsh** [charliermarsh/ruff#2938]
I didn't realize it at the time, but `mdcat` is a huge dependency, because it pulls in a request library, an image-rendering library, etc.

Without `mdcat`:

![Screen Shot 2023-02-15 at 4 01 37 PM](https://user-images.githubusercontent.com/1309177/219164357-552a28a3-25d9-4b59-af6f-b7a555031da8.png)

With `mdcat`:

![Screen Shot 2023-02-15 at 3 59 04 PM](https://user-images.githubusercontent.com/1309177/219164262-486a0097-daf2-4fe7-aa4a-c25348a80026.png)

**Comment by charliermarsh** [comment]
`termimad` is way, way smaller:

![Screen Shot 2023-02-15 at 4 02 45 PM](https://user-images.githubusercontent.com/1309177/219165209-85a12a49-6fac-4598-a9f5-58869cce6874.png)

But it admittedly looks less nice, or at least requires a lot more configuration and tuning.

**Comment by charliermarsh** [comment]
The other alternative is to submit some changes to `mdcat` to make the bigger dependencies optional via features.

**Comment by charliermarsh** [comment]
(Yeah, sorry, that's lazy of me, will avoid.)

**Comment by not-my-profile** [comment]
(I agree about the issue ... we should try to avoid bloat / unnecessary dependencies.)

**Comment by charliermarsh** [comment]
Yeah I probably can't spend much time on this right now, so maybe the question is: do we leave this in, and fix it later? Or remove it, and re-add when it's been improved?

**Comment by not-my-profile** [comment]
We could feature gate it and disable the feature by default.

**Comment by charliermarsh** [comment]
Would we enable it for releases? So just gate to speed up dev? Or disable in "prod" for now too?

**Comment by messense** [comment]
> The other alternative is to submit some changes to `mdcat` to make the bigger dependencies optional via features.

Opened https://github.com/swsnr/mdcat/pull/237

**Comment by charliermarsh** [comment]
You're a hero! Thank you.

**Comment by messense** [comment]
There is a bit of push back from `mdcat` maintainer on that PR so it'll take some time to land.

**Comment by charliermarsh** [comment]
My read from that response is that they only really intend `mdcat` to be used as a crate for tools in which Markdown rendering is a core feature -- or perhaps not at all? and instead intend it to be solely a command-line utility. If they're not interested in powering this kind of use-case, that's fine and totally their prerogative! If so, we'll just revert.

**Comment by messense** [comment]
I think piping/paging to `mdcat` is a good point, this way we can also support `bat` like Homebrew did: https://github.com/Homebrew/brew/pull/6504

**Comment by MichaReiser** [comment]
I see two alternatives.

## Use `mdcat` at compile time

We could use `mdcat` at compile time (or any markdown parser) and use it to embed the highlighted documentation into ruff. This has the added benefit that the markdown syntax can be validated at compile time and printing the documentation only requires serializing to the terminal. This would be similar to what Rome uses to document its rules (Rome didn't include the documentation as part of the CLI. We instead added a link to the diagnostic name that pointed to the website and generated the rules on the website).  [Source](https://github.com/rome/tools/blob/b6e7a394697d74b40242b18bac836428290b33f3/xtask/codegen/src/generate_configuration.rs#L63-L105)

## Use a custom syntax

Rome uses a custom markup syntax that is also used to format diagnostics consistently ([source](https://github.com/rome/tools/blob/b6e7a394697d74b40242b18bac836428290b33f3/crates/rome_console/README.md#L28)). Using that syntax directly would be a bit cumbersome in the documentation. Still, it could be a good intermediate representation into which the markdown gets turned into. 

## Drawbacks

Both approaches would require us to implement the logic for rendering the documentation while respecting the CLI width.

**Comment by charliermarsh** [comment]
> piping/paging to `mdcat` is a good point

Just to make sure I understand the suggestion, this would require that users install `mdcat` on their own, right?

> Use mdcat at compile time

This is interesting. What would it "compile" to exactly? Dumb question, but does mdcat not require knowledge of the target terminal when compiling Markdown for printing?

**Comment by charliermarsh** [comment]
I think I'm partial to removing this functionality for now, and revisiting later... It's a nice feature, but I don't think it's worth significant investment on our side, and it's not clear to me whether the `mdcat` changes will get merged (or if it's worth @messense's time to invest in them further).

**Comment by charliermarsh** [comment]
Closing for now as I've removed this. But we can revisit in the future, or if mdcat merges that change :)

**Comment by charliermarsh** [comment]
@swsnr - Thanks for the heads up, that's great to hear, and appreciate all your work on `mdcat` :)
