### ISSUE TITLE
The major open source projects using ruff list has gotten very long

### ISSUE THREAD

**Issue by not-my-profile** [charliermarsh/ruff#2939]
It's obviously very cool that all of these (27) major open source projects are using ruff but the list has gotten so long that it has become a navigation hurdle for users looking for information in our README (you need to scroll further to get to the table of contents).

So I think it would make sense to reduce the list before the table of contents to maybe 3-4 projects and either remove the links to the other projects or move them to a section at the bottom of the README and link them with a link such as `[and more](#projects-using-ruff)`.

**Comment by charliermarsh** [comment]
Yeah I can own this. I'll have to make some decisions around what to highlight up-top.

**Comment by not-my-profile** [comment]
Resolved by #2986. (Thanks!)
