### ISSUE TITLE
[Infinite loop] with missing required import rule

### ISSUE THREAD

**Issue by underyx** [charliermarsh/ruff#2944]
- target file contents before ruff: https://gist.github.com/underyx/ad1478d388cd61bfcb89e25a5ea3ddde
  - after ruff: https://gist.github.com/underyx/5741723fd6ffd373ec96f7967552c123 
  - re-running ruff keeps reporting `100 fixed` even on the 'after ruff' file
- ruff.toml contents: https://gist.github.com/underyx/c0b8d0b6d9c4dd6d1be9447185eaebab
- ruff 0.0.247

```terminal
$ ruff --version
ruff 0.0.247
$ ruff src/semgrep/app/version.py --select I002 --fix --no-cache

error: Failed to converge after 100 iterations.

This indicates a bug in `ruff`. If you could open an issue at:

    https://github.com/charliermarsh/ruff/issues/new?title=%5BInfinite%20loop%5D

...quoting the contents of `src/semgrep/app/version.py`, along with the `pyproject.toml` settings and executed command, we'd be very appreciative!

src/semgrep/app/version.py:1:1: I002 Missing required import: `from __future__ import annotations`
Found 101 errors (100 fixed, 1 remaining).
```

**Comment by underyx** [comment]
Seems like this simpler target also reproduces the issue:

```py
"""a
b"""
# b
import os
```

**Comment by charliermarsh** [comment]
Thanks for filing :)

**Comment by charliermarsh** [comment]
Woah not sure what happened here but definitely broken! Will make sure it's fixed for the next release (maybe Friday-ish).
