### ISSUE TITLE
feature: global / user-wide config

### ISSUE THREAD

**Issue by Roguelazer** [charliermarsh/ruff#2949]
It would be nice to have a way to configure this tool system-wide; I'm imagining that it could look at the standard XDG configuration sources (`~/.config/ruff.toml` and `/etc/ruff.toml`) in addition to walking up the filesystem from the current directory.

I know it's not quite as pure as having a `pyproject.toml` in every directory hierarchy, but sometimes it's nice to be able to set defaults for one-off scripts.

**Comment by charliermarsh** [comment]
I believe we actually do support this -- can you take a look at [this section](https://github.com/charliermarsh/ruff#how-can-i-change-ruffs-default-configuration) in the docs? If it's not quite what you're asking for, LMK and I can reopen!

**Comment by Roguelazer** [comment]
Ah, I was led astray because for some reason dirs decided to look in `~/Application Support/ruff/ruff.toml` on macos instead of `~/.config`; I think this is the only CLI tool I've ever used that does so. I moved my config in there and it works.

Also, fwiw, this functionality isn't mentioned in [the docs page](https://beta.ruff.rs/docs/configuration/), so perhaps that's a process improvement opportunity.

**Comment by charliermarsh** [comment]
Ah yeah, it's mentioned in the [FAQ](https://beta.ruff.rs/docs/faq/), but it should at least be mentioned in the configuration section.
