### ISSUE TITLE
[Panic] "`__future__` imports should be marked as used"

### ISSUE THREAD

**Issue by manueljacob** [charliermarsh/ruff#2967]
The following code was reduced from some output of pytype:

```python
import __future__
annotations: __future__._Feature
```

It crashes:

```
thread 'main' panicked at 'internal error: entered unreachable code: `__future__` imports should be marked as used', crates/ruff/src/rules/flake8_type_checking/rules/typing_only_runtime_import.rs:189:35
```

I tested it with ruff 0.0.247.

**Comment by charliermarsh** [comment]
Oh interesting! Will fix. What is this code doing? Trying to parse it myself.

**Comment by charliermarsh** [comment]
Oh, or is this not _Python_ code, but code _generated_ by Pytype per #2967?

**Comment by manueljacob** [comment]
Yes, the code is generated by pytype and put in the `.pytype` directory. With #2966, this is not a problem for me anymore, but I think it should still not panic.

**Comment by charliermarsh** [comment]
Hah, that's true :)

**Comment by charliermarsh** [comment]
I can fix.

**Comment by charliermarsh** [comment]
Do you mind posting the complete file, command, and pyproject.toml? Somehow not reproducing with `ruff --isolated --select ALL` on that snippet.

**Comment by manueljacob** [comment]
File:
```python
import __future__
annotations: __future__._Feature
```

Ruff command: `ruff utils.pyi --isolated --select TCH001`
But `ruff --isolated --select ALL utils.pyi` panics as well.

No `pyproject.toml`.

I build ruff from the `main` branch in the meantime, to check if I can reproduce it with that.

**Comment by manueljacob** [comment]
It fails for me on the main branch.

**Comment by charliermarsh** [comment]
Ah it depends on the `.pyi` suffix (since that enables deferred annotation handling).
