### ISSUE TITLE
Targeted Ignoring Failure: `A003` falls back to `A001`

### ISSUE THREAD

**Issue by ES-Alexander** [charliermarsh/ruff#301]
My team recently incorporated `ruff` into our CI pipeline, and I'm in the process of fixing some newly raised linting errors in our codebase from the latest `ruff` updates :-)

I would like to be able to ignore `A003: BuiltinAttributeShadowing`, but by doing so all the previous `A003` errors fall back to `A001: BuiltinVariableShadowing`, which I do not want to ignore in the general case. Shadowing by a class attribute is much less likely to cause issues or confusion than variables that are global or locally defined within a function, as most class definitions will not make use of builtins directly, and something like `MyClass.list` is not an ambiguous shadow of `list` in general.

While I can semantically understand that "attribute" is a subset of "variable", it seems to hamstring the useful functionality if ignoring a special case means it just gets treated as the general case. In my mind special cases should be treated as mutually exclusive to general cases for ignoring purposes, instead of the current behaviour where specialisation only provides a more specific error message. I'm not sure if this is a buggy implementation detail of this particular pair of errors, or a consistently applied (and potentially intentional) fallback behaviour throughout `ruff`.

**Comment by charliermarsh** [comment]
Taking a look now...

**Comment by charliermarsh** [comment]
This is actually just a bug :)

Will merge and cut a new release in a sec.

**Comment by charliermarsh** [comment]
Building now as `v0.0.50`. Thank you for filing, great issue!

**Comment by charliermarsh** [comment]
Keep 'em coming :)

**Comment by ES-Alexander** [comment]
That was fast - thanks! 😄

Will make sure I report anything else that comes up.
