### ISSUE TITLE
PLW0120 false positive for/with/break/else

### ISSUE THREAD

**Issue by pawamoy** [charliermarsh/ruff#3019]
* A minimal code snippet that reproduces the bug.

```python
from contextlib import suppress

for name in ["demo"]:
    with suppress(AttributeError, KeyError):
        thing = name
        break
else:
    thing = "other stuff"
```

* The command you invoked (e.g., `ruff /path/to/file.py --fix`), ideally including the `--isolated` flag.

```console
% ruff demo.py
demo.py:1:1: D100 Missing docstring in public module
demo.py:7:1: PLW0120 `else` clause on loop without a `break` statement; remove the `else` and de-indent all the code inside it
Found 2 errors.
```

* The current Ruff settings (any relevant sections from your `pyproject.toml`).

Just enabling a bunch of letters, plus targeting Python 3.7.

* The current Ruff version (`ruff --version`).

```console
% ruff --version
ruff 0.0.247
```

**Comment by charliermarsh** [comment]
Thanks! Looks like a bug.
