### ISSUE TITLE
N999 for `__main__.py`

### ISSUE THREAD

**Issue by scop** [charliermarsh/ruff#3042]
ruff 0.0.248 seems to issue `N999` for all `__main__.py`.

Maybe it should get the same treatment as `__init__.py`, or be ignored altogether?

**Comment by charliermarsh** [comment]
Ah yeah that's definitely a false positive.

**Comment by charliermarsh** [comment]
I will take a look at this now and perhaps cut a new release real quick.

**Comment by scop** [comment]
Thanks! :rocket:

**Comment by emirkmo** [comment]
Out of curiosity shall I make sure we don't use release 0.0.248 in CI or will this be backported to 0.0.248?

Trying to understand how to use ruff versions in our CI, thank you!

**Comment by charliermarsh** [comment]
I'm going to release 0.0.249 in a moment, but it will indeed be a new release -- we don't really have a way to backport or update existing releases.
