### ISSUE TITLE
[Autofix error] [PT009] return self.assertEqual (ruff 0.0.247)

### ISSUE THREAD

**Issue by jonathansp** [charliermarsh/ruff#3056]
Although `return self.assertEqual(True, False)` is not common usage, ruff shouldn't fail. The resulting file seems to be `return assert True == False`, which I don't understand what is wrong with `assertEqual`.

E.g.:

```python
import unittest
class MyTestCase(unittest.TestCase):
    def test_dummy(self: "MyTestCase") -> None:
        return self.assertEqual(True,  False)
```

```toml
[tool.ruff]
extend-ignore = [
  "D203",
  "D212",
  "EM101",
  "EM102",
  "INP001",
  "N812",
  "TCH002",
  "TRY003",
]
extend-select = ["ALL"]
target-version = "py39"
```

will return 

```shell
poetry run ruff . --fix

error: Autofix introduced a syntax error. Reverting all changes.

This indicates a bug in `ruff`. If you could open an issue at:

    https://github.com/charliermarsh/ruff/issues/new?title=%5BAutofix%20error%5D

...quoting the contents of `tests/test_consumer.py`, along with the `pyproject.toml` settings and executed command, we'd be very appreciative!
```

**Comment by ngnpope** [comment]
You're not using `pytest` and the `PT*` rules only really apply in that case, so you should probably be ignoring those.

It also isn't really conventional to explicitly return the result of `self.assert*()` from your test methods. These assertion helpers always return `None` anyway, and so should your test method (implicitly).

That said, ruff should try hard to avoid creating invalid code - it should either refuse to fix this case or strip the `return`.

**Comment by jonathansp** [comment]
Thanks @charliermarsh for this fantastic tool.
