### ISSUE TITLE
[N999] `__version__.py` flagged as false positive (Ruff 0.0.248)

### ISSUE THREAD

**Issue by eddiebergman** [charliermarsh/ruff#3065]
The rule N999 (snake_case module names) seems to trigger on `__version__.py` which seems incorrect based on the pep8 rule linked in the docs.

If you think it's correct however, feel free to close :)

Keep on truckin'

**Comment by charliermarsh** [comment]
I think this should be fixed in v0.0.249, which is building now (and was released early for this purpose :))

If you see it on v0.0.249, definitely let me know!

**Comment by eddiebergman** [comment]
Fixes the problem, thank you!
