### ISSUE TITLE
Private module names

### ISSUE THREAD

**Issue by WilliamJamieson** [charliermarsh/ruff#3069]
https://beta.ruff.rs/docs/rules/invalid-module-name/ is now raised on all the modules in my project that I have a leading underscore on. In my project, we have the convention that `_module.py` represents a private part of the API with the specific objects collected into public `module.py` files and the `__init__.py` file. This is to discourage end users from doing a `from my_package import _module` in their code (even though we specifically exclude `_module` from the `__init__.py`.

Typically the `_module` modules contain code that is "internally" public meaning we use it quite extensively inside the library, but it should not be used externally.

Would it be possible to add a configuration option to ruff that turns off the error for having a leading `_` on module names?

**Comment by WilliamJamieson** [comment]
Quoting part of [PEP8](https://peps.python.org/pep-0008/#public-and-internal-interfaces).

> Even with __all__ set appropriately, internal interfaces (packages, modules, classes, functions, attributes or other names) should still be prefixed with a single leading underscore.

So my internal interfaces, that is the aforementioned "private" modules, should be prefixed with a `_`.

**Comment by charliermarsh** [comment]
Can you try 0.0.249? The rules were significantly relaxed and should allow leading underscores.

**Comment by WilliamJamieson** [comment]
Sure, this was picked up by the pre-commit.ci update this morning.

**Comment by WilliamJamieson** [comment]
> Sure, this was picked up by the pre-commit.ci update this morning.

Yes 0.0.249 fixed this problem. Sorry I had not realized there was a newer release.

**Comment by charliermarsh** [comment]
No worries. Sorry for the churn. I turned around a new release specifically for this issue.

**Comment by WilliamJamieson** [comment]
No worries, it forced me to actually read part of PEP8, which was probably a good thing.
