### ISSUE TITLE
new cli option: --disable-noqa

### ISSUE THREAD

**Issue by onerandomusername** [charliermarsh/ruff#3070]
There are times when I want to go through the codebase and fix every error that uses a specific error code. It would be helpful to have a cli option to disable all noqa comments for a single command invoke.

For example, if I have a noqa comment for `E501`, I should be able to view all of my existing E501 errors by running `ruff . --disable-noqa --select E501`

**Comment by charliermarsh** [comment]
We already support this internally (we use this behavior for `--add-noqa`), so in theory we could expose it with a flag yeah.

**Comment by onerandomusername** [comment]
> We already support this internally (we use this behavior for `--add-noqa`), so in theory we could expose it with a flag yeah.

Thank you! I chose `--disable-noqa` because its what flake8 uses, but I wouldn't be opposed to `--ignore-noqa` or any other name.

**Comment by charliermarsh** [comment]
Yeah I'd probably prefer `--ignore-noqa` personally.

**Comment by sciyoshi** [comment]
Should there be a way to only disable/ignore noqa for certain error codes? For example, a codebase may want to disable using noqa for specific errors altogether. Maybe as a new config in `[tool.ruff]` for this purpose, e.g. `ignore-noqa = [ "E501" ]` would prevent `# noqa: E501` from working altogether.

**Comment by not-my-profile** [comment]
> Should there be a way to only disable/ignore noqa for certain error codes?

I'd rather have us implement a `forbid` or `force-deny` lint level as per https://github.com/charliermarsh/ruff/issues/1256#issuecomment-1414165258.

> Yeah I'd probably prefer `--ignore-noqa` personally.

I think the CLI option should be called something more generic since we might want to also support `# pylint:` directives in the future.

**Comment by charliermarsh** [comment]
Added in #3296. I left it as `--ignore-noqa` for now since it's consistent with (e.g.) `--add-noqa` but I'm open to suggestions.
