### ISSUE TITLE
Be able to specify supported Python version for `UP`

### ISSUE THREAD

**Issue by ThatXliner** [charliermarsh/ruff#3093]
The Pyupgrade rule set doesn't seem to be configurable to what minimally support Python version our project wants. For example, rule `UP007` is "Use `X | Y` for type annotations" which I don't want since I'm supporting 3.8+, which does not support the union syntax.

Sure, I can just ignore the rules that don't apply but I feel like being able to specify Python version is easier. But if you disagree, feel free to close this issue since this is more of an annoyance than a feature request or bug.

**Comment by charliermarsh** [comment]
We do support this! Via [`target-version`](https://beta.ruff.rs/docs/settings/#target-version), which you can specify on the command-line or in your `pyproject.toml`.

**Comment by ThatXliner** [comment]
Thanks for the fast response! I was just looking at the docs when I realized that I missed that.

Another thought, perhaps it could be auto-detected via the package manager's configuration? For example, `[tool.poetry.dependencies.python]` in the `pyproject.toml` tells Poetry the Python version a project supports

**Comment by charliermarsh** [comment]
No worries! Yeah this has come up before but I haven't started on it at all :joy: It's tracked in #2039.
