### ISSUE TITLE
Automatically remove coding comments 

### ISSUE THREAD

**Issue by charliermarsh** [charliermarsh/ruff#311]
Source: https://github.com/asottile/pyupgrade

![Screen Shot 2022-10-03 at 6 19 45 PM](https://user-images.githubusercontent.com/1309177/193696317-cfa5ccb7-4210-4cbc-9bf1-b201be3ebf9b.png)

**Comment by sobolevn** [comment]
It can also be `# -*- coding: utf8 -*-`
