### ISSUE TITLE
Avoid enforcing EXE001 and EXE002 checks on Windows

### ISSUE THREAD

**Issue by charliermarsh** [charliermarsh/ruff#3110]
I noticed this because pre-commit running on `windows-latest` [Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software) agents, failed, where the Linux jobs pass.

    I just `pip install ruff` there ¯\\_(ツ)_/¯

_Originally posted by @basnijholt in https://github.com/charliermarsh/ruff/issues/2118#issuecomment-1439402540_

**Comment by basnijholt** [comment]
Thanks for opening this and thanks for the amazing package! 

For reference, `flake8-executable` also ignore this on Windows https://github.com/xuhdev/flake8-executable/blob/2b6c3fec0f7ccb175fe34f2a613b762af2a35536/flake8_executable/__init__.py#L67-L86

**Comment by charliermarsh** [comment]
Oh nice! That's good to know too! And thank you for the kind words :)
