### ISSUE TITLE
Syntax errors with match statement

### ISSUE THREAD

**Issue by rslinckx** [charliermarsh/ruff#3118]
Here are 2 failing syntaxes for match statements using the latest 0.0.251 release. They both run fine but it seems to use more "esoteric" syntax from the match spec.

```
match {"test": 1}:
    case {
        **rest,
    }:
        print(rest)

```

```
match {"label": "test"}:
    case {
        "label": str() | None as label,
    }:
        print(label)

```

**Comment by charliermarsh** [comment]
Thank you! I’ll take a look at these today.

**Comment by charliermarsh** [comment]
This will be fixed by https://github.com/RustPython/RustPython/pull/4551.
