### ISSUE TITLE
Automatically remove quoted annotations

### ISSUE THREAD

**Issue by charliermarsh** [charliermarsh/ruff#314]
Source: https://github.com/asottile/pyupgrade

![Screen Shot 2022-10-03 at 6 20 42 PM](https://user-images.githubusercontent.com/1309177/193696486-3c970a8e-9db9-4a2a-bf56-f710bfb58e89.png)

**Comment by andersk** [comment]
This may want to wait until the future of `__future__.annotations` becomes less unclear (python/cpython#82786, python/cpython#93628, [PEP 649](https://peps.python.org/pep-0649/)).
