### ISSUE TITLE
feat request to resolve rule descrepancy

### ISSUE THREAD

**Issue by upstartjohnvandivier** [charliermarsh/ruff#3140]
there is a rule descrepancy in E7111 vs F632 we can't comply with both
one says i must `0.1 is not None`
the other says i must `0.1 != None`

may i request a `Ruff-specific rules (RUF)` that reconciles these? it basically would say "use != in constant comparisons that don't involve None else use is not None syntax`

**Comment by charliermarsh** [comment]
I think it has to go the other way, because `0.1 is not None` is a syntax warning. We should allow `0.1 != None` (although it seems strange to have code that compares two literals like that :))
