### ISSUE TITLE
For pre-commits, should ruff run before or after black?

### ISSUE THREAD

**Issue by bellini666** [charliermarsh/ruff#3143]
The documentation doesn't specify if ruff should run before or after black for best results.

**Comment by charliermarsh** [comment]
Before! I can add a note.

**Comment by charliermarsh** [comment]
(We test in CI that running Ruff, then Black, then Ruff again is a stable operation.)

**Comment by onerandomusername** [comment]
Out of curiosity, why does the order matter? I run black before I run ruff because black might fix some things that a linter would otherwise complain about, so it keeps actual errors to a minimum.

**Comment by charliermarsh** [comment]
Ruff's autofixes aren't guaranteed to output Black-compatible code. They often do, but it's not guaranteed. So running Black, then Ruff, then Black could result in changes on each invocation (whereas running Ruff, then Black should always be stable).

As a silly example, imagine we're converting a lambda to a function definition. When we do that, we don't take line lengths into account, and we certainly don't take all of Black's possible line length wrapping behaviors into account. So if you had a lambda with a ton of arguments, we might yield a function definition on one very long line, which Black would then wrap.

**Comment by onerandomusername** [comment]
Ah, so it only needs to run first *when autofix is enabled*. That makes more sense.

**Comment by charliermarsh** [comment]
Correct!
