### ISSUE TITLE
Implement rule PIE802

### ISSUE THREAD

**Issue by Skylion007** [charliermarsh/ruff#3144]
Implement flake8-PIE PIE802 from https://github.com/sbdchd/flake8-pie, it would be nice to have parity now that flake8-PIE is deprecated in favor of this tool.

**Comment by charliermarsh** [comment]
Sounds good, that rule is also autofixable.

**Comment by matthewlloyd** [comment]
Working on this.

**Comment by charliermarsh** [comment]
@matthewlloyd - The flake8-comprehensions rules and fixers are probably a good reference.
