### ISSUE TITLE
Is "A003 class attribute `set` is shadowing a python builtin" too aggressive?

### ISSUE THREAD

**Issue by amotl** [charliermarsh/ruff#315]
Dear Charlie,

after upgrading to `ruff 0.0.52` on https://github.com/isarengineering/SecPi, we found `ruff` would emit an admonition on a code like outlined below. Do you think it might be worth to build up a dedicated exclusion list for specific symbols, in order make ruff skip those cases?

With kind regards,
Andreas.

```python
class Foobar:
    def __init__(self):
        self.data = {}

    def get(self, key, default=None):
        return self.data.get(key, default)

    def set(self, key, value):
        self.data[key] = value
```
```
$ ruff foobar.py
Found 1 error(s).
foobar.py:8:5: A003 class attribute `set` is shadowing a python builtin
```

P.S.: The new features and rules added to ruff keep being an awesome driver for modernizing an outdated Python 2 code base, where I did not bother to run flake8 on it at all, see https://github.com/isarengineering/SecPi/pull/30. Cheers!

**Comment by andersk** [comment]
IMO, shadowing is a completely normal part of the language and doesn’t indicate a problem. This diagnostic seems too opinionated to be enabled by default.

**Comment by charliermarsh** [comment]
Sounds reasonable. I’ll remove it from the list of defaults. (In general, I’m not interested in enabling opinionated checks by default.)

**Comment by lovetox** [comment]
Can someone explain to me how defining a set() method on an Object is "shadowing" anything?

```
>>> class Test:  
...     pass
... 
>>> dir(Test())
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
>>>
```

A class has no inbuilt set method, if you mean the inbuilt `set()` method, we can pass a object to this method, but i dont see how this is relevant.

This check is not opinonated its just wrong in what the error text says. It does not shadow something in this example in my opinion.

**Comment by charliermarsh** [comment]
I agree that it's confusing but it is consistent with `flake8-builtins`:

```
∴ flake8 foo.py --select A003
foo.py:8:5: A003 class attribute "set" is shadowing a python builtin
```

I'm not sure what a more reasonable A003 would be, I think folks should just disable this check if they don't find the current behavior useful.

**Comment by lovetox** [comment]
I guess it's ok if you want to mirror the flake check exactly. Usually one wants to check variable names against builtins. Vor methods on classes we normally speak about overriding a method which is a common practice and not really worth a warning or error

**Comment by lovetox** [comment]
Thanks for that example, seems its indeed possible to shadow a builtin with a method, i didnt know that.

Nevertheless in the original examples, nothing was shadowed.
I guess the algo is just not very good, and just scans for method names with names of builtins.
