### ISSUE TITLE
Reformatting imports with aliases, causes noqa comments of long lines (E501) to be on the wrong line

### ISSUE THREAD

**Issue by zkaddach** [charliermarsh/ruff#3168]
Ruff version: 0.0.252
Ruff command: `ruff --fix --isolated --select E501,I001 /path/to/file.py`

Reformatting imports with aliases, causes **noqa comments of long lines (E501)** to be on the wrong line hence raising long line errors.

Before: 
```python
from myproject.my_very_long_sub_module_name.my_long_data_models_name.my_model_name import (  # noqa: E501
    MyModel as SomethingElse,
)
```

After: 
```python
from myproject.my_very_long_sub_module_name.my_long_data_models_name.my_model_name import (
    MyModel as SomethingElse,  # noqa: E501
)
```

PS: This doesn't happen when alias is not used.

**Comment by charliermarsh** [comment]
Will take a look today, thanks for filing.

**Comment by charliermarsh** [comment]
Def a bug, will require some refactoring.
