### ISSUE TITLE
bug: lost comments during autofix

### ISSUE THREAD

**Issue by upstartjohnvandivier** [charliermarsh/ruff#3185]
repro snippet autofixed from like:
```
        self.assertRegexpMatches(
            log,
            r"INFO:some.module:"
            # [35] foobar
            r"Titlecasedword [35] foo: "
            # comment i care about
            # other comment i care about
            r"\[\(\d{4}, \d{4,5}\), \d{5}\)\]",
            )
```
to like:
```
    assert re.search(
        "INFO:some.module: ...",
```

the logical code is correctly and nicely refactored but the intermediate comments are lost

can we either collect those just above the assert statement or omit blocks from refactor with interspersed comments?

**Comment by charliermarsh** [comment]
Yeah we can omit those from autofixing. We use that behavior for a bunch of rules, but it's not automatic so has to be enabled one-by-one as appropriate.

**Comment by charliermarsh** [comment]
(Some autofixes also preserve comments, but it varies.)
