### ISSUE TITLE
Include settings path in `--show-settings`

### ISSUE THREAD

**Issue by charliermarsh** [charliermarsh/ruff#3202]
We should tell you _which_ settings file was loaded on-disk.

**Comment by charliermarsh** [comment]
This is surprisingly difficult (or, at least, requires some refactoring).

**Comment by dhruvmanila** [comment]
I think I can take this up tomorrow, have been looking at the CLI code recently.

One doubt is what to output when ran in `--isolated` mode or using the default settings as a fallback. Maybe don't include the path or leave it blank like `"-"`:

https://github.com/charliermarsh/ruff/blob/333f1bd9ceff6390ae652790abb22cd175042bc7/crates/ruff_cli/src/resolve.rs#L65-L72

The output I'm thinking of:

```console
$ ruff check --show-settings .
Resolved settings for: "..."
Settings path: "..."
Settings {
    rules: RuleTable {
        enabled: {
			...
```
