### ISSUE TITLE
Failed to parse: Got unexpected unicode

### ISSUE THREAD

**Issue by rouge8** [charliermarsh/ruff#3207]
I'm getting an error parsing a few of our files like `error: Failed to parse t.py: Got unexpected unicode at line 1 column 4`.

## `t.py`

```python
"\N{BACKSPACE}another cool trick"
```

## output

```
❯ ruff --isolated t.py
error: Failed to parse t.py: Got unexpected unicode at line 1 column 4
t.py:1:5: E999 SyntaxError: Got unexpected unicode
Found 1 error.
```

## version

```
ruff 0.0.252
```

**Comment by charliermarsh** [comment]
Thanks, will take a look at this. Must be coming from the parser.

**Comment by charliermarsh** [comment]
It's something data-dependent. `print("\N{SNOWMAN} another cool trick")` works fine.

**Comment by rouge8** [comment]
That is fun 💀

**Comment by rouge8** [comment]
In our code base it looks like we only use `\N{BACKSPACE}` and `\N{ROBOT_FACE}` and only the first errors

**Comment by charliermarsh** [comment]
Being discussed a bit in the RustPython issue. Hopefully fixed there then we can upgrade to resolve this.
