### ISSUE TITLE
disable EXE001 when linting from stdin

### ISSUE THREAD

**Issue by dimbleby** [charliermarsh/ruff#3214]
I have set up my editor to run `ruff -- -`, passing the buffer contents via stdin

Everything with a shebang sees a false positive EXE001 "Shebang is present but file is not executable".

Ruff can't know either way, I've only given it the file contents.

**Comment by dimbleby** [comment]
providing `-stdin-filename` allows ruff to get this right (which I had thought I was doing, but I wasn't).

So that reduces the severity of this somewhat.  But still: ruff shouldn't declare that a file is or isn't executable when in fact it just doesn't know.

**Comment by charliermarsh** [comment]
Definitely agree.
