### ISSUE TITLE
Add support for GitHub Actions problemMatchers

### ISSUE THREAD

**Issue by cclauss** [charliermarsh/ruff#3235]
Add GitHub Actions annotations in the code of pull requests when ruff raises an error.
![image](https://user-images.githubusercontent.com/3709715/221401834-bb7ea339-d0cd-45e0-9326-c02398089e0c.png)
* https://github.com/actions/toolkit/blob/main/docs/problem-matchers.md
* https://fusectore.dev/2021/11/19/github-action-problem-matchers.html

An example of GitHub Action problemMatchers being applied to flake8 errors.
* https://github.com/python-social-auth/social-core/blob/master/.github/workflows/flake8.yml

**Comment by edgarrmondragon** [comment]
I think this is already supported via the `--format github` option.

**Comment by cclauss** [comment]
Awesome!!  Thx!
