### ISSUE TITLE
PTH-rules should name pathlib

### ISSUE THREAD

**Issue by MartinThoma** [charliermarsh/ruff#3246]
Currently, all [PTH rules](https://beta.ruff.rs/docs/rules/#flake8-use-pathlib-pth) are phrased rather confusingly.

## Code

```python
import os

os.unlink("foo.bar")
```

## What ruff does

```
$ ruff --select=PTH foo.py --isolated
foo.py:3:1: PTH108 `os.unlink` should be replaced by `.unlink()`
Found 1 error.
```

## What ruff should do

Telling the user to move `os.unlink` to `.unlink()` is just not helpful. Something like this would be better:

```
$ ruff --select=PTH foo.py --isolated
foo.py:3:1: PTH108 `os.unlink(name)` should be replaced by `Path(name).unlink()`
Found 1 error.
```

I think this might even be auto-fixable.

## Environment

```
$ python --version
Python 3.11.1

$ ruff --version
ruff 0.0.252
```

**Comment by evanrittenhouse** [comment]
I can try to take this one!

**Comment by charliermarsh** [comment]
E.g., we could change:

```rust
format!("`os.mkdir` should be replaced by `.mkdir()`")
```

...to:

```rust
format!("`os.mkdir(...)` should be replaced by `Path(...).mkdir()`")
```

**Comment by charliermarsh** [comment]
(I think it's ok to literally use "..." as a placeholder rather than trying to replicate the input value.)
