### ISSUE TITLE
Ruff removing import code, that may fail

### ISSUE THREAD

**Issue by qarmin** [charliermarsh/ruff#3279]
ruff 0.0.253

Unused import inside try and except block which catch ModuleNotFoundError error, should not be removed(`ruff check . --fix` do this, without any config file)
```
     @staticmethod
     def check_orjson():
         try:
-            import orjson
             return True
         except ModuleNotFoundError:
             return False
```

**Comment by charliermarsh** [comment]
Interesting, this is arguably correct but I can see why we'd want to avoid this -- the `ModuleNotFoundError` is arguably a "usage" of the import.

**Comment by qarmin** [comment]
I found this when trying to add basic ruff support for Bottles app, in my project I only once ever used such code.

When looking at https://github.com/search?l=Python&p=1&q=ModuleNotFoundError&type=Code, I see that this is used a lot
