### ISSUE TITLE
UP006: Incorrect autofix when shadowing builtin

### ISSUE THREAD

**Issue by jdahlin** [charliermarsh/ruff#3284]
The autofix for UP006 is not working correctly when shadowing a builtin such as `type`. 

Test case

```python
from typing import Type

class F:
    type = "abc"
    def foo(self) -> Type[list]:
        return list
```

Expected code after autofix:

```python
import builtins


class F:
    type = "abc"
    def foo() -> builtins.type[list]:
        return list
```

Actual code after autofix:

```python
class F:
    type = "abc"
    def foo() -> type[list]:
        return list
```

**Comment by charliermarsh** [comment]
Thanks, you're right! These should check for redefined builtins.

**Comment by jdahlin** [comment]
Wow, thanks for the quick fix! Should I open up a new issue to handle the case when the builtins are overriden/shadowed?

**Comment by jdahlin** [comment]
> What do you think the ideal behavior would be in that case?

To fetch the original object via the builtin module, e.g:

```python
import builtins


class F:
    type = "abc"
    def foo() -> builtins.type[list]:
        return list
```

**Comment by charliermarsh** [comment]
Yeah we can open an issue for that. It will be tricky to do right now because fixes can't introduce _new_ imports. So for now, we could support this in the event that a module _already_ imports `builtins`, but we couldn't "import `builtins` and change the reference". (Part of #835.)

**Comment by jdahlin** [comment]
@charliermarsh it can also be found in `__builtins__` which is even more unlikely to be imported, but feels like a stop gap thing until #835 is fixed.

**Comment by charliermarsh** [comment]
@jdahlin - True! Although that can _also_ be overridden :joy: Feel free to open an issue for it :)
