### ISSUE TITLE
Feature Request:  GitHub Action for Ruff

### ISSUE THREAD

**Issue by brucearctor** [charliermarsh/ruff#3289]
Would love an official GitHub Action for Ruff 

The docs for Black to which this idea follows and could mimic:  https://black.readthedocs.io/en/stable/integrations/github_actions.html

The link to the code in black:  https://github.com/psf/black/blob/main/action/main.py

The docs from GH for creating an action:  https://docs.github.com/en/actions/creating-actions

@charliermarsh -- I'd be happy to write and submit a PR.  Is that something you/this-project would be interested in, potentially willing to accept [ naturally TBD on code, etc ]?

**Comment by danieleades** [comment]
does a pre-commit action solve your use-case?

see https://github.com/charliermarsh/ruff-pre-commit
and https://github.com/pre-commit/action

**Comment by brucearctor** [comment]
Pre-Commit is ALSO great!  

I hope my teams use pre-commit, but I do not trust them to always use, which is why I would look to ruff to not surface any problems ( in, for example, GH ) before allowing the code to be merged

**Comment by danieleades** [comment]
using pre-commit in CI will give you what you're after, whether your team uses it locally or not. With the added advantage that they can opt in locally to the same checks that you run remotely

**Comment by edgarrmondragon** [comment]
One disadvantage of pre-commit (at least pre-commit.ci) is that it doesn't report annotations back to github, unlike what a `ruff check . --format github` run would do.

**Comment by wichert** [comment]
Perhaps that could be handled by checking [`GITHUB_ACTIONS ` environment variable](https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables), and if it is set to `true` default to the `github` format?

**Comment by Jackenmen** [comment]
> One disadvantage of pre-commit (at least pre-commit.ci) is that it doesn't report annotations back to github, unlike what a `ruff check . --format github` run would do.

pre-commit ran from GH Actions can though. You would want to set the `RUFF_FORMAT` env var so that the output format is appropriate when ran in CI while kept default when ran locally.

**Comment by luator** [comment]
The [documentation](https://beta.ruff.rs/docs/editor-integrations/#github-actions) already includes an example how to set up a GitHub workflow.  It's not using a dedicated action but just some "run" commands but it seems to be simple enough for me that no special action is needed.  Or am I missing some scenario where this would not work?

**Comment by brucearctor** [comment]
One can always run code.  There are a number of instances where packaging code to be a script, container, library, [ or action ], etc. can be nice ... 

For naive users, I imagine also much easier to have all the recommended defaults set, and then surface any config options with associated explinations, in the GH Action documentation.  

Is a packaged GH Action that people *could* use desirable to make it potentially easier on users  [ yes, the `run:` directive is a valid way to accomplish things ] ?  I would imagine that helps increase usability, but ...?  TBD, based on what this project expects of its userbase, the aims for support, etc.

**Comment by edgarrmondragon** [comment]
> Perhaps that could be handled by checking [`GITHUB_ACTIONS` environment variable](https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables), and if it is set to `true` default to the `github` format?

@wichert that was actually removed in https://github.com/charliermarsh/ruff/pull/1697

> pre-commit ran from GH Actions can though. You would want to set the `RUFF_FORMAT` env var so that the output format is appropriate when ran in CI while kept default when ran locally.

@Jackenmen yeah, even the official pre-commit action would work well with that env var, I think.

**Comment by mpizenberg** [comment]
@brucearctor I’d be interested in such a gh action but I can understand not wanting the maintenance burden in the ruff repo. Maybe go ahead and create that action under your name if you think that’s relatively easy. From there it will be easier to see tradeoffs and popularity of the action. If useful, it can be integrated later?

**Comment by kislyuk** [comment]
I too would love to see an officially supported ruff github action. I don't think any of the workarounds listed above (pre-commit hooks, etc.) are suitable workarounds for a standalone github action.

For reference, black and isort provide officially supported standalone github actions, and I think that has meaningfully contributed to their adoption among developers who work on github.

**Comment by charliermarsh** [comment]
If I were to go about this, I'd probably just try to mirror the Black action.

**Comment by brucearctor** [comment]
I got a Draft PR together.  How's this look?  Can extend/modify if needed [ and happy to help maintain ].  Once others believe code looks good, I'm happy to add docs to https://github.com/charliermarsh/ruff/pull/3756 or follow up with docs in another PR.

**Comment by brucearctor** [comment]
Accidently closed, and doesn't look like can re-open.  Is now found --> https://github.com/charliermarsh/ruff/pull/3820

**Comment by charliermarsh** [comment]
Rock on, this now exists as [`ruff-action`](https://github.com/chartboost/ruff-action) (docs added in https://github.com/charliermarsh/ruff/pull/3857).
