### ISSUE TITLE
On Windows, ruff doesn't support wildcards on the command line

### ISSUE THREAD

**Issue by pfmoore** [charliermarsh/ruff#3301]
The command `ruff *.py` gives the error "error: Failed to lint *.py: The filename, directory name, or volume label syntax is incorrect. (os error 123)". I would have expected it to check all `.py` files in the current directory.

**Comment by charliermarsh** [comment]
Thanks! Will take a look. My guess is that we're relying on patterns being expanded by the shell (so e.g. on macOS, `ruff *.py` works but `ruff "*.py"` does not).

**Comment by pfmoore** [comment]
Yeah, that's usually the issue. The Windows C runtime often does automatic glob expansion, but I guess Rust doesn't.

**Comment by charliermarsh** [comment]
We may be able to leverage this: https://gitlab.com/kornelski/wild
