### ISSUE TITLE
[RET503] Interaction with `mypy` assert_never 

### ISSUE THREAD

**Issue by eddiebergman** [charliermarsh/ruff#3304]
This is rather a niche circumstance but thought it's worth mentioning. For [exhaustive checking](https://typing.readthedocs.io/en/latest/source/unreachable.html) of Enums, there's an idiom to use with Mypy, checking each possible value and ending with `assert_never`. This is not a runtime check but purely a Mypy static type check.

Ruff will give a `RET503` here which makes sense without mypy but given mypy is telling us it's safe, it would be nice for Ruff to detect this too. In the example above, using ruff with `--fix` will actually insert the line `return None` after the assert which then further causes linting issues of unreachable code.  

```python
from enum import Enum, auto

from typing_extensions import assert_never


class E(Enum):
    A = auto()
    B = auto()
    C = auto()


def f(value: E) -> bool:
    if value == E.A:
        return True

    if value == E.B:
        return True

    if value == E.C:
        return True

    assert_never(value) # ruff: [RET503] [*] Missing explicit `return` at the end of function able to return non-`None` │ value (ruff) 
```

My naive solution to this is check for `assert_never(.*)` where the `return` should be and accept that as a valid explicit `return` statement.

Looking into the [checker code](https://github.com/charliermarsh/ruff/blob/3ed539d50ed6260358c97d2e00b49bad4abfa37e/crates/ruff/src/rules/flake8_return/rules.rs#L203). It seems like it could be added as a `StmntKind` to the following lines as I'm guessing this code block is where it says to do nothing.

https://github.com/charliermarsh/ruff/blob/3ed539d50ed6260358c97d2e00b49bad4abfa37e/crates/ruff/src/rules/flake8_return/rules.rs#L272-L275

However I'm really not a rustacian so just grasping at straws.

**Comment by NeilGirdhar** [comment]
`assert False` should also do the same thing

**Comment by charliermarsh** [comment]
I actually thought we _did_ account for this -- lemme look back at the code today.

**Comment by eddiebergman** [comment]
Major apologies, latest version does seem to solve this! The releases are just too fast to keep up :)

**Comment by charliermarsh** [comment]
Oh no worries at all! Glad to hear it :)

**Comment by henryiii** [comment]
Is it possible that the code ([I think here](https://github.com/charliermarsh/ruff/blob/280dffb5e161acb9deab97c9a2158055e4174d66/crates/ruff/src/rules/flake8_return/rules.rs#L201)) isn't accounting for the typing module reexport location?
