### ISSUE TITLE
Is there a `noqa` equivalent for do not fix

### ISSUE THREAD

**Issue by paddyroddy** [charliermarsh/ruff#3308]
Unfortunately for `pydantic` you can't use the new union syntax `X | Y` for models and so you have to change it to i.e. `Union[X, Y]` or `Optional[X]` (depending on use case) if using `python` < `3.10` pydantic/pydantic#2609.

For now I've got around it by doing, i.e.
```toml
[tool.ruff]
fix = true
select = [
    "UP",
]
per-file-ignores = {"btrack/models.py" = [
    "UP006",
    "UP007",
], "btrack/config.py" = [
    "UP006",
    "UP007",
]}
```

However, this would mean if there are cases of `X | Y` or `list[Z]` for example outside of `pydantic` then they won't be fixed. Is there a way of doing, i.e. `# nofix: UP006,UP007`?

**Comment by CalumY** [comment]
Setting a target version below 3.10 might be what you are looking for: https://beta.ruff.rs/docs/settings/#target-version.

**Comment by paddyroddy** [comment]
But we are also supporting `3.10`, i.e. `3.8<= x <= 3.10` at the moment.

**Comment by charliermarsh** [comment]
@paddyroddy - Hmm, you can turn off autofix for select rules like:

```py
unfixable = [
  "UP006",
  "UP007",
]
```

But that won't activate on a per-file or per-case basis -- it'll tell Ruff to still flag those errors, but not fix them.

**Comment by paddyroddy** [comment]
I guess `target-version` may be the easiest but not the most satisfying IMO as another thing to remember when, for example, dropping `3.8` support. But thank you.

**Comment by paddyroddy** [comment]
I'm not sure `target-version` works this way? I changed it to the following, but my code is still full of, e.g. `|` typings.
```
[tool.ruff]
fix = true
select = [
    "UP",
]
target-version = "py38"
```

**Comment by paddyroddy** [comment]
Seems like `target-version` may have worked, but the problem is I've already upgraded without that flag. So the solution doesn't work well for me as I'd have to manually downgrade throughout.

**Comment by charliermarsh** [comment]
Can you revert your change, then re-run Ruff? Ruff won't actively "downgrade" the code if those changes have already been applied.

**Comment by paddyroddy** [comment]
Yes but I've made a fair few manual changes since so a bit hesitant

**Comment by charliermarsh** [comment]
What's the advantage of `# nofix: UP006,UP007` over `# noqa: UP006,UP007`? Would the former _not_ ignore the violation?

**Comment by paddyroddy** [comment]
Not sure what happened there. `noqa` actually does the right thing - i.e. to not format it. I'm sure when playing around, it was doing something else, or I messed up.

**Comment by charliermarsh** [comment]
Oh no prob! Maybe it expected it on a different line than you tried initially or something.
