### ISSUE TITLE
RET503: autofix puts return statements before comments of preceeding line

### ISSUE THREAD

**Issue by onerandomusername** [charliermarsh/ruff#3317]
### Summary

Ruff's autofix for RET503 will insert the return statement before any comments that go to the line before.

ruff version: 0.0.253

### Repro steps

minimal example code:
```py
def example():
    if True:
        return ""  # type: ignore
```

**command: `ruff repro.py --select RET503 --fix`**

ruff's fixed code:
```py
def example():
    if True:
        return ""
    return None  # type: ignore
```

desired code:
```py
def example():
    if True:
        return ""  # type: ignore
    return None
```

This recreation was executed in an ephemeral environment. There is no pyproject.toml, and all settings are the default except for the command line as mentioned above.

This example has been paired down quite a bit, but I can provide the real-world file where this occurred if that's helpful.

**Comment by charliermarsh** [comment]
This has come up once before, will fix tomorrow.
