### ISSUE TITLE
D406 auto-detect pydocstyle

### ISSUE THREAD

**Issue by epenet** [charliermarsh/ruff#3321]
- `command`: `ruff .`
- `version`: `ruff 0.0.247`
- `pyproject.toml`: https://github.com/home-assistant/core/blob/3a34f818e8add8527ec66c85a4066162d2a715d9/pyproject.toml#L267-L274

We currently ignore `D406` on the Home Assistant repository, and I would like to remove that code from the ignore list.

We also currently have a mixture of `numpy` and `google` styles, so we are not setting the convention at this stage.

What I don't understand right now is why `Args:` passes but not `Returns:` in the following docstring:
```python
def get_gas_price(data: EasyEnergyData, hours: int) -> float | None:
    """Get the gas price for a given hour.

    Args:
        data: The data object.
        hours: The number of hours to add to the current time.

    Returns:
        The gas market price value.
    """
```

I would expect either both `Args` and `Returns` to fail, or neither.

**Comment by charliermarsh** [comment]
Will take a look at this today.

**Comment by charliermarsh** [comment]
`pydocstyle` does have the same behavior, I think:

```py
 foo.py:2 in public function `get_gas_price`:
        D406: Section name should end with a newline ('Returns', not 'Returns:')
```

**Comment by charliermarsh** [comment]
Yeah this kind of thing has come up before. Basically, "Returns" is _both_ a NumPy _and_ a Google-compatible section name (but "Args" is not).

So if you have both, we infer "NumPy", and don't validate the "Args" header. `pydocstyle` suffers from the same issue.

**Comment by charliermarsh** [comment]
I think a better heuristic would be to see if there are any headers that are only in one of the two conventions (like "Args").

**Comment by charliermarsh** [comment]
I'll improve this a bit.

**Comment by epenet** [comment]
Cc @frenck, for information.

**Comment by charliermarsh** [comment]
#3325 will improve this quite a bit, in that any docstring that contains (e.g.) `Args` will be treated as Google-style, any docstring that contains (e.g.) `Parameters` will be treated as NumPy-style, etc. (assuming you haven't set a `convention` in your config).
