### ISSUE TITLE
Use version from  `requires-python` if `target-version` is undefined

### ISSUE THREAD

**Issue by WhyNotHugo** [charliermarsh/ruff#3332]
If `target-version` is undefined, use the minimal `target-version` from [PEP-621](https://peps.python.org/pep-0621/#requires-python).

This is what black does: https://github.com/psf/black/pull/3219

Mainly, it means we don't have to repeat the target python twice in pyproject.toml.

**Comment by charliermarsh** [comment]
100%. I think this is a dupe of #2039 so closing in favor of that. I'd love for someone to contribute this :)

**Comment by WhyNotHugo** [comment]
Too many false positives looking for “python”, “version” and “target” in issues.

I’ll follow that one, thanks.

**Comment by charliermarsh** [comment]
Haha no worries.
