### ISSUE TITLE
[Panic] Expected docstring to start with a valid triple- or single-quote prefix

### ISSUE THREAD

**Issue by qarmin** [charliermarsh/ruff#3336]
Ruff 0.0.254

Steps to reproduce 
```
mkdir tt
cd tt
wget https://github.com/charliermarsh/ruff/files/10888419/AAA.zip
unzip AAA.zip
python3 -m venv venv
source venv/bin/activate
pip install packaging
pip install -r requirements.txt --no-deps
ruff .
```
causes to crash with message
```
error: `ruff` crashed. This indicates a bug in `ruff`. If you could open an issue at:

https://github.com/charliermarsh/ruff/issues/new?title=%5BPanic%5D

quoting the executed command, along with the relevant file contents and `pyproject.toml` settings, we'd be very appreciative!

thread '<unnamed>' panicked at 'internal error: entered unreachable code: Expected docstring to start with a valid triple- or single-quote prefix', crates/ruff/src/rules/pydocstyle/helpers.rs:24:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
```

Requirements file contains ~ 1000 the most popular python packages, mostly < 20 MB in size(I disabled some packages, that took need to download 500MB like nvidia cuda)

I suggest to check even more packages from time to time because this is quite easy way to find possible bugs in real code.

**Comment by qarmin** [comment]
Found minimal example
```
﻿""" SAM macro definitions """

```

**Comment by charliermarsh** [comment]
Thanks!

**Comment by charliermarsh** [comment]
That minimal example doesn't panic for me, but I'll try for the full repro based on the zip file (thanks for that).

**Comment by charliermarsh** [comment]
This is a very useful exercise!

**Comment by qarmin** [comment]
I forgot about config file(by default there is no crash)
```
select = ["D"]
```

**Comment by charliermarsh** [comment]
Is it possible that the file uses CR line endings? (Not CRLF, but CR.) I can't repro based on the snippet alone.

**Comment by charliermarsh** [comment]
Alternatively, if you know which file this is in, that works too.

**Comment by qarmin** [comment]
In notepad I see that file uses CL line ending and crash still happens - 
[ww.zip](https://github.com/charliermarsh/ruff/files/10889266/ww.zip)

**Comment by charliermarsh** [comment]
Awesome, thank you, _that_ I can reproduce.

**Comment by charliermarsh** [comment]
There's a zero-width non-breaking space at the start of the file...

https://www.compart.com/en/unicode/U+FEFF

**Comment by charliermarsh** [comment]
We should handle this gracefully, but it's typically an encoding or corruption error AFAICT?

https://www.freecodecamp.org/news/a-quick-tale-about-feff-the-invisible-character-cd25cd4630e7/
https://stackoverflow.com/questions/1972362/why-is-my-bash-script-adding-feff-to-the-beginning-of-files
