### ISSUE TITLE
Parsing error when using `match` as variable name

### ISSUE THREAD

**Issue by qarmin** [charliermarsh/ruff#3337]
```
event = 12
match = lambda query: query == event
print(match(12))
print(match(2))
```
prints with python 3.10 True, False, but ruff not wants to parse it due 
```
error: Failed to parse aa.py: invalid syntax. Got unexpected token '=' at line 2 column 7
aa.py:2:8: E999 SyntaxError: invalid syntax. Got unexpected token '='
```

Ruff 0.0.254
Config 
```
select = ["A", "B", "C", "E", "F"]

exclude = [
]

line-length = 140
```

**Comment by qarmin** [comment]
Similar problems with other builtin names 
```
Lookup.async = None
```
cause
```
invalid syntax. Got unexpected token 'async' at line 43 column 10
```
or 
```
case = lambda re, **kwargs: (re, TypeError, kwargs)
```

```
invalid syntax. Got unexpected token 'case' at line 485 column 5
```

**Comment by charliermarsh** [comment]
Thanks, that’s surprising, I’ll take a look!

**Comment by charliermarsh** [comment]
Hmm, I don't think `Lookup.async = None` is valid Python. `async` and `await` became reserved keywords in Python 3.7.

The main issue here is the handling of `match` and `case` with lambda assignments.

**Comment by charliermarsh** [comment]
Fixed by https://github.com/RustPython/RustPython/pull/4623 in RustPython.
