### ISSUE TITLE
SIM300 inconsistency with negative literal values

### ISSUE THREAD

**Issue by diceroll123** [charliermarsh/ruff#3346]
_Ruff 0.0.254_

`SIM300` is called `Yoda conditions`, which swaps the left and right hand expressions.

When running `ruff check . --select=SIM300 --isolated` on the code below, all of the negative literals are ignored by this refactoring.

```py
import random
blah = random.randint(-100, 100)

def test() -> None:
    assert 1 == blah
    assert -1 == blah

    assert 0b1 == blah
    assert -0b1 == blah

    assert 0o1 == blah
    assert -0o1 == blah

    assert 0x1 == blah
    assert -0x1 == blah
```

**Comment by charliermarsh** [comment]
Oh good call. Those are probably treated as unary operation nodes on constants.

**Comment by charliermarsh** [comment]
`flake8-simplify` also excludes these, but it seems wrong.
