### ISSUE TITLE
Ruff and Flake8's McCabe complexity differs

### ISSUE THREAD

**Issue by charliermarsh** [charliermarsh/ruff#3347]
From Discord: https://gitlab.com/ppentchev/temp-20230302-ruff-complexity

**Comment by charliermarsh** [comment]
Reproduced.

**Comment by charliermarsh** [comment]
Here's a more minimal repro -- Ruff calls this 3, Flake8 calls this 2:

```py
async def process_detect_lines():
    try:
        pass
    finally:
        if res:
            errors.append(f"Non-zero exit code {res}")
```

I may have to actually learn how this works, because I thought that would've been 3.

**Comment by charliermarsh** [comment]
I guess it makes sense that it's 2 if you say that the `finally` has to trigger, but then why is this 2 also?

```py
def process_detect_lines():
    try:
        pass
    finally:
        pass
```

**Comment by JonathanPlasse** [comment]
Maybe this is a bug in flake8.

**Comment by ashwinrajeev** [comment]
> I guess it makes sense that it's 2 if you say that the `finally` has to trigger, but then why is this 2 also?
> 
> ```python
> def process_detect_lines():
>     try:
>         pass
>     finally:
>         pass
> ```

I think this is a bug in flake8. This is supposed to be 1, not 2. [Radon](https://pypi.org/project/radon/) give this code 1 cc.

https://radon.readthedocs.io/en/latest/intro.html#cyclomatic-complexity

**Comment by charliermarsh** [comment]
Oh cool, I'll take another look at our implementation with those guidelines in mind.
