### ISSUE TITLE
Provide additional recommended ruff rules that points at others

### ISSUE THREAD

**Issue by qarmin** [charliermarsh/ruff#3356]
Currently ruff support ~500 rules in ~50 categories.

I tried to create a set of rules that would be as generic as possible, but it didn't work out very well for me(mostly probably because I only use Python for a few small projects).

I am currently using a hand-picked mix of F, E, SIM, A, B rules

I think rule sets pointing to other style rules like:

- Ruff minimal (RM)
- Ruff minimal autofixable (RMA)
- Ruff recommended (RR)
- Ruff recommended autofixable (RRA)
- Ruff advanced (RA)
- Ruff advanced autofixable (RAA)

would be useful, would work well without the need for configuration

**Comment by charliermarsh** [comment]
Yeah I'd really like to support ESLint-like "presets" for this. It needs scoping-out...

In the meantime, maybe I'll mention that if _I'm_ looking for a minimal setup, I tend to use something like this in my own projects:

```toml
[tool.ruff]
select = ["E", "F", "B", "UP"]
```

**Comment by charliermarsh** [comment]
Created a Discussion around this: https://github.com/charliermarsh/ruff/discussions/3363

**Comment by charliermarsh** [comment]
(Just closing in favor of the linked Discussion.)
