### ISSUE TITLE
Should TCH run on pyi files?

### ISSUE THREAD

**Issue by MarcoGorelli** [charliermarsh/ruff#3357]
Hi,

See here: https://github.com/pandas-dev/pandas/pull/51794

The TCH code is reporting lots of errors in typing stub files (`.pyi`) - is this right? They're only used by the type checker anyway, perhaps `TCH` shouldn't run for this file type?

**Comment by charliermarsh** [comment]
My initial reaction is that you’re right. Let me see what the originating plug-in does (though we may want to change it anyway even if they run on pyi files).

**Comment by MarcoGorelli** [comment]
I didn't think flake8 ran on cython files to begin with (or at least, [wasn't meant to](https://github.com/PyCQA/flake8/issues/1482))

**Comment by charliermarsh** [comment]
Sorry, I might be misunderstanding - we’re talking about pyi stub files here, not Cython files, right?

**Comment by charliermarsh** [comment]
I can fix this today.

**Comment by twoertwein** [comment]
using if `TYPE_CHECKING` in pyi files probably also violates flake8-pyi's Y002
