### ISSUE TITLE
Autofix PIE810 rule violations

### ISSUE THREAD

**Issue by Skylion007** [charliermarsh/ruff#3360]
PIE810 currently does not have implement any autofixes, but the rule should be readily autofixable using similar logic to SIM101 (which effectively does the same thing with isinstance calls). It would be nice if someone could implement this autofix. This rule is a common minor performance pitfall so having autofixes would help turning this rule on for large codebases.

**Comment by charliermarsh** [comment]
Cool, thanks :)
