### ISSUE TITLE
Score code on a 0-10 scale like pylint

### ISSUE THREAD

**Issue by Beliavsky** [charliermarsh/ruff#3364]
Pylint gives a score between 0 and 10 for code it analyzes? It's nice to have a simple metric that improves as you fix flaws. Could ruff add something similar?

I just started with ruff and appreciate how much faster it is than pylint -- thanks.

**Comment by charliermarsh** [comment]
Thanks for the kind words!

I think I'm gonna err on the side of closing this one as something that, while I understand the use and value, I don't want to support in Ruff right now.
