### ISSUE TITLE
GHA example in docs shows "email protected"

### ISSUE THREAD

**Issue by wichert** [charliermarsh/ruff#3381]
The [GitHub Action section](https://beta.ruff.rs/docs/editor-integrations/#github-actions) in the ruff documentation does not show actions correctly: it replaces them with "actions/[email protected]".

![image](https://user-images.githubusercontent.com/199657/223364787-89d4df61-0fd3-409d-80c4-a882b5cad0b3.png)

**Comment by charliermarsh** [comment]
Woah that's bizarre! For me it shows this:

![Screen Shot 2023-03-07 at 9 35 22 AM](https://user-images.githubusercontent.com/1309177/223453700-c5bafdfe-f4c6-4451-b8e9-83c3231cbe27.png)

**Comment by wichert** [comment]
Huh.. did something change? I can't seem to reproduce it anymore 🤔

**Comment by charliermarsh** [comment]
I actually did just reproduce it once but now I can't reproduce it again.

**Comment by charliermarsh** [comment]
I just turned it off, hopefully resolved.

**Comment by charliermarsh** [comment]
Thanks for bringing this to my attention!
