### ISSUE TITLE
Rule for find issue with late binding

### ISSUE THREAD

**Issue by worldmind** [charliermarsh/ruff#3384]
Thank you for amazing project!

Does ruff has rule for check [issue with late binding](https://docs.python-guide.org/writing/gotchas/#late-binding-closures)?

**Comment by charliermarsh** [comment]
Yeah!

Given:

```py
def create_multipliers():
    return [lambda x : i * x for i in range(5)]
```

Running Ruff shows:

```
❯ ruff --select B foo.py
foo.py:2:24: B023 Function definition does not bind loop variable `i`
Found 1 error.
```

(So you just need to enable the flake8-bugbear rules with `--select B`.)

**Comment by worldmind** [comment]
Cool, thank you again! It's really amazing how fast ruff works and how many rules you have implemented!
Really nice idea to have one tool for all kind of static analysis.

**Comment by charliermarsh** [comment]
Thank you! :)
