### ISSUE TITLE
ruff's `--fix` return a non-zero exit code even though there's only one fixable lint error.

### ISSUE THREAD

**Issue by snapdgn** [charliermarsh/ruff#341]
code snippet to reproduce the issue:
```python
import json

def fn():
    pass
```
command: `ruff . --fix`

output: ```No pyproject.toml found.
Falling back to default configuration...
Found 0 error(s) (1 fixed).```

`echo $?` gives 1(as exit code)

Image for reference:
![image](https://user-images.githubusercontent.com/85608760/194597790-c444218f-20a1-4477-897f-4c948890144a.png)

**Comment by charliermarsh** [comment]
Oh thanks! Will fix.

**Comment by charliermarsh** [comment]
[v0.0.58](https://github.com/charliermarsh/ruff/releases/tag/v0.0.58) is building now.
