### ISSUE TITLE
Add ability to check files one by one and print which are currently checked/parsed

### ISSUE THREAD

**Issue by qarmin** [charliermarsh/ruff#3423]
When trying to found file which crashes, I use binary search so I:
1. run ruff to check for crash
2. remove half of files
3. run again to see if crash still happens
4. if yes, back to point 2
5. if no, restore half of files, remove other part, back to point 3

With such output I will be able to find crash with seconds instead minutes(of course this should work only on 1 thread):
```
[[ Parsing a.py ]]
[[ Parsing b.py ]]
[[ Parsing c.py ]]
[[ Parsing d.py ]]

[[ Checking a.py file ]]
a.py:21:9: D400 [*] First line should end with a period
[[ Checking a.py file ]]
b.py:21:9: D415 [*] First line should end with a period, question mark, or exclamation point
[[ Checking c.py file ]]
[[ Checking d.py file ]]
```

**Comment by charliermarsh** [comment]
The single-threading part is achievable by setting the `RAYON_NUM_THREADS=1` environment variable, but not sure that we log the checked files. We could add that logging to `--verbose`, and then `RAYON_NUM_THREADS=1 ruff ... --verbose` would enable this, I think.

**Comment by charliermarsh** [comment]
You can now run with `RAYON_NUM_THREADS=1 ruff ... --verbose` to get this experience (as of next release, at least).
