### ISSUE TITLE
 E402 is still check 

### ISSUE THREAD

**Issue by linpan** [charliermarsh/ruff#3428]
import pathlib
import sys

sys.path.append(str(pathlib.Path(__file__).parent.parent.resolve()))  # noqa E402
from logging.config import fileConfig

alembic/env.py:5:1: E402 Module level import not at top of file

**Comment by charliermarsh** [comment]
I believe the snippet you want is like this:

```py
import pathlib
import sys

sys.path.append(str(pathlib.Path(file).parent.parent.resolve()))
from logging.config import fileConfig  # noqa: E402
```

The `noqa` needs to be on the line with the import, rather than the line in between.

**Comment by linpan** [comment]
this pattern, every import add noqa. 
need too noqas: 
<img width="939" alt="image" src="https://user-images.githubusercontent.com/6077601/224215294-dafa448a-9d5c-45e8-9f0b-dccd7602f3e7.png">
