### ISSUE TITLE
Should ruff be invoked in the same venv as the python code?

### ISSUE THREAD

**Issue by mpizenberg** [charliermarsh/ruff#3435]
So ruff is a python linter. Are there any lints requiring access to correct `site-package` stuff or other things only available when executing in the same python context as the python code should be executed? (like for example pyright, which needs to check dependencies)

I’m mainly asking in the context of GitHub actions. I saw [the example action](https://beta.ruff.rs/docs/editor-integrations/#github-actions) in your documentation (thx for that!) which does not detail this point (maybe it’s irrelevant?).

In particular, if using [`hatch`](https://github.com/pypa/hatch), is there ever a need to run ruff with `hatch run ruff ...` or does ruff not care at all about the environment it’s run in?

**Comment by charliermarsh** [comment]
Good question! No, it's not necessary. Ruff has no dependency on the current environment.

You might _want_ to manage Ruff alongside the rest of your environment if you care about keeping the dependency versions in-sync (i.e., if you have different projects that need to use different versions of Ruff). But Ruff doesn't behave differently when run inside or outside of a Python environment.
