### ISSUE TITLE
Implement rule for unnecessary import alias

### ISSUE THREAD

**Issue by stinodego** [charliermarsh/ruff#3437]
This is a feature request to implement the following lint from the `flake8-tidy-imports` package:
https://github.com/adamchainz/flake8-tidy-imports#i250-unnecessary-import-alias

Apparently, it is also an `isort` rule:
https://pycqa.github.io/isort/docs/configuration/options.html#remove-redundant-aliases

**Comment by charliermarsh** [comment]
I think we support this as `PLC0414`, Pylint's "useless-import-alias" rule.

**Comment by charliermarsh** [comment]
In combination with `PLR0402`, Pylint's "consider-using-from-import" rule.

**Comment by stinodego** [comment]
Oh great, that was indeed what I was looking for! Thanks for the help.

Still, I think this raises another question, which is: what to do about rules that are implemented by multiple sources? I'd argue that by enabling the `TID` lints, I should expect these rules to be enabled.

In any case, I have what I need for now. I'll close this issue - the point I raised above could get its own separate issue if you feel it's merited.

**Comment by charliermarsh** [comment]
Attaching this to #2186, where we're tracking these kinds of known aliases. I agree that enabling `TID` should give you this rule, and internally we actually _do_ support rule aliasing, we just haven't figured out all of the details -- there are some tricky cases which make the "right" behavior unclear.
