### ISSUE TITLE
Wrong fingerprint in Gitlab format

### ISSUE THREAD

**Issue by Agalin** [charliermarsh/ruff#3441]
Ruff version: 0.0.253

Gitlab Code Quality formatter [sets `fingerprint`](https://github.com/charliermarsh/ruff/blob/2383228709f109343de7821affd128ea00046677/crates/ruff_cli/src/printer.rs#L353) to a code of the issue, e.g. F401.

But this field should be a [unique value](https://docs.gitlab.com/ee/ci/testing/code_quality.html#implement-a-custom-tool) identifying a single violation, not its type. As a consequence, multiple violations of the same type are not visible (only the last one is shown).

It makes the feature unusable, for a project with currently 120 violations Gitlab only shows 7 (as there are 7 unique types of violations).

**Comment by Agalin** [comment]
Just checked and it's not possible to work around this using external tools - report doesn't provide column position which means that it's not possible to distinguish multiple issues of the same description in the same line.

**Comment by charliermarsh** [comment]
Makes sense, thanks for filing!
