### ISSUE TITLE
[feature-request] Ruff version of isort action comments

### ISSUE THREAD

**Issue by smackesey** [charliermarsh/ruff#3450]
This is pretty minor, but it's a bit confusing that `# isort` action comments are the only way to control Ruff's import formatting via action comments. Especially confusing for new contributors who see these comments and reasonably assume our project is using `isort`.

Not sure if `ruff` has greater plans for an action comment syntax, but it would be nice if something like `# ruff: isort: ...` also worked.

**Comment by charliermarsh** [comment]
Yeah this makes total sense. It’s nice to be isort-compatible, but strange that no Ruff-native version is supported.
