### ISSUE TITLE
`--ignore-noqa` isn't respected when `RUF100` is enabled

### ISSUE THREAD

**Issue by charliermarsh** [charliermarsh/ruff#3468]
If `RUF100` is enabled, we end up running the `noqa` checker even if the `noqa` flag is not enabled. As a result, `--ignore-noqa` has no effect when `RUF100` is selected.

**Comment by onerandomusername** [comment]
This is still an issue with 0.0.256, though not necessarily when RUF100 is enabled.

**Comment by onerandomusername** [comment]
Ignore me, I just realised I didn't have my virtual environment enabled.
