### ISSUE TITLE
Bug - Cannot ignore `TCH004` via config file

### ISSUE THREAD

**Issue by Kilo59** [charliermarsh/ruff#3472]
Ignoring `TCH004` in the configuration file has no effect. This seems to be true for `ruff.toml` and `pyproject.toml` files.

Suppressing in-line with `# noqa: TCH004` works fine.
Ignoring other `TCH**` rules seems to work fine.

```
ruff 0.0.254
```

```toml
# ruff.toml
select = ["TCH"]
ignore = ["TCH004"]
```

```python
# my_script.py
from typing import TYPE_CHECKING, Union

try:
    import numpy as np
except ImportError:
    np = None


if TYPE_CHECKING:
    import numpy as np


def my_func(a: Union[float, np.float64], b: Union[float, np.float64]):
    return a + b
```

```
❯ ruff my_script.py
my_script.py:10:12: TCH004 Move import `numpy` out of type-checking block. Import is used for more than type hinting.
Found 1 error.
```

☝️ I would expect to get no errors above due to the config ignore of `TCH004`

**Comment by Kilo59** [comment]
Maybe related to https://github.com/charliermarsh/ruff/pull/3452 ??

**Comment by charliermarsh** [comment]
Just a bug, fixing...
