### ISSUE TITLE
0.0.255: `C4` selector prefix emits warning and maps to `C40` only (subset of `flake8-comprehensions`)

### ISSUE THREAD

**Issue by bastimeyer** [charliermarsh/ruff#3486]
#3452 changed the mapping of some selector prefixes, one of them being `C` for `C40`, as `C` is used for both `mccabe` (`C90`) and `flake8-comprehensions` (`C4`).

However, the rules of `flake8-comprehensions` are prefixed with both `C40` and `C41`, so emitting a warning when `C4` is chosen that it was remapped to `C40` doesn't make sense, because it ignores parts of the available `flake8-comprehensions` rules.

Ruff's docs list `flake8-comprehensions` explicitly as `C4`:
https://beta.ruff.rs/docs/rules/#flake8-comprehensions-c4

```
$ ruff --version
ruff 0.0.255
$ ruff --select C4 .
warning: `C4` has been remapped to `C40`.
warning: `C4` has been remapped to `C40`.
warning: `C4` has been remapped to `C40`.
```

**Comment by charliermarsh** [comment]
Ah yeah, I think `("C4", "C40")` is probably a mistake and can just be omitted from that list.
