### ISSUE TITLE
UP035 --fix not working for quoted types

### ISSUE THREAD

**Issue by torarvid** [charliermarsh/ruff#3508]
Hello hello 👋🏻 

When running `ruff --fix test.py` (Ruff v0.0.255) for the following test file:
```python
from typing import List

class A:
    myList: List[str]
    quotedList: "List[str]"
```
it will fix the first (non-quoted) variant, but still only report the second (quoted) variant. Unsure if this is a bug or expected behavior, but I thought I would report it anyways 🙂 

Keep up the awesome work 🎉

**Comment by torarvid** [comment]
This test file is even simpler (no `class A:` needed):
```python
from typing import List

myList: List[str] = []
quotedList: "List[str]" = []
```

**Comment by JonathanPlasse** [comment]
This is the expected behavior. `pyupgrade` does not fix it either.
No forward references are auto-fixable as there are tricky corner cases.

**Comment by JonathanPlasse** [comment]
After spending some time in the issues, here it is!
I think that is all the problems we encountered.
- #2613.
  > Breaking pypa/build too: https://github.com/pypa/build/pull/576/files
  > ```python
  > - PathType = Union[str, 'os.PathLike[str]']
  > + PathType = Union[str, os.PathLike[str]]
  > 
  > - _TProjectBuilder = TypeVar('_TProjectBuilder', bound='ProjectBuilder')
  > + _TProjectBuilder = TypeVar('_TProjectBuilder', bound=ProjectBuilder)
  > ```
  > These are both broken. os.PathLike[str] is not valid on Python 3.7 (and it's not an annotation). TypeVar can't have the quotes removed, the thing it's bound to doesn't exist yet. And it's also not an annotation.
- #826
  > ```python
  > if TYPE_CHECKING:
  >     from app.models.model_a import ModelA
  >     from app.models.model_b import ModelB
  > 
  > ModelAOrB = Union["ModelA", "ModelB"]
  > ```
  > and it gets fixed into
  > ```python
  > if TYPE_CHECKING:
  >     from app.models.model_a import ModelA
  >     from app.models.model_b import ModelB
  > 
  > ModelAOrB = "ModelA" | "ModelB"
  > ```
  > which is not the same type as before

**Comment by charliermarsh** [comment]
Thank you! :)

I'm wondering if we could fix (but leave quoted) instances like `quotedList: "List[str]" = []`, i.e., change that to `quotedList: "list[str]" = []` 🤔

**Comment by charliermarsh** [comment]
Some of these are tricky (e.g., `quotedList: "Li" "st[str]" = []` is a valid annotation), but we should be able to fix the common cases.
