### ISSUE TITLE
Automatically rewrite `NamedTuple` and `TypedDict` with newer syntaxes

### ISSUE THREAD

**Issue by charliermarsh** [charliermarsh/ruff#351]
From `pyupgrade`:

<img width="792" alt="Screen Shot 2022-10-07 at 4 04 06 PM" src="https://user-images.githubusercontent.com/1309177/194644709-69165fc1-6da3-4551-abcc-4d86e1801036.png">

This could be a good use-case for the codegen module.

**Comment by martinlehoux** [comment]
I'll try this one if that's okay

**Comment by martinlehoux** [comment]
A few questions on top of my mind @charliermarsh 

- Should we handle `from typing import TypedDict as CustomTypedDict`?
- Should we handle `MyType = TypedDict("MyType", dict(a=str, b=int))`?
- What should we do for `MyType = TypedDict("OtherName", ...)`?

**Comment by charliermarsh** [comment]
Good questions!

> Should we handle `from typing import TypedDict as CustomTypedDict`?

Na, I think we should ignore (leave it unchanged).

> Should we handle `MyType = TypedDict("MyType", dict(a=str, b=int))`?

I think it's fine not to handle this case. It'd be nice to include it, but I don't see it as a requirement.

> What should we do for `MyType = TypedDict("OtherName", ...)`?

Let's ignore this case, if possible (leave it unchanged).

> And overall, do you think TypedDict rule and NamedTuple rule should be the same, or two different rules?

I would vote for two different rules.

**Comment by martinlehoux** [comment]
Regarding [NamedTuples](https://docs.python.org/3/library/collections.html#collections.namedtuple):
- Support `rename` (that converts invalid identifiers to  `_<k>` keys, and duplicated too) => _I  don't see a technical reason for why not, but doesn't seem very useful_
- Support `defaults` (that list fields defaults from right to left) => _I guess this one is useful_
- Support `module` (I don't event know if possible with class) => _I'd say we drop that_

**Comment by charliermarsh** [comment]
Completed by @martinlehoux! Thank you!
