### ISSUE TITLE
UP035 --fix not working for Deque

### ISSUE THREAD

**Issue by torarvid** [charliermarsh/ruff#3510]
When running `ruff --fix test.py` (Ruff 0.0.255), it doesn't change the `Deque` to `deque`
```python
from typing import Deque

a: Deque[str]
```

However, interestingly, if we replace `Deque` with `List`, it does change to `list`
```python
from typing import List

a: List[str]
```

**Comment by JonathanPlasse** [comment]
- `deque` is not a builtin like `list`. `deque` need to be imported. Currently, it is not possible to auto-fix. We first need #835.

**Comment by charliermarsh** [comment]
Yeah we can't fix this right now -- but, in theory, we should be able to.

**Comment by torarvid** [comment]
Ah, I didn't know about #835, but I understand this issue depends on that. Thanks for the info 👍🏻

**Comment by tmke8** [comment]
This is the full list of `typing` imports that can be rewritten on Python 3.9:

- `collections.deque`
- `collections.defaultdict`
- `collections.OrderedDict`
- `collections.Counter`
- `collections.ChainMap`
- `collections.abc.Awaitable`
- `collections.abc.Coroutine`
- `collections.abc.AsyncIterable`
- `collections.abc.AsyncIterator`
- `collections.abc.AsyncGenerator`
- `collections.abc.Iterable`
- `collections.abc.Iterator`
- `collections.abc.Generator`
- `collections.abc.Reversible`
- `collections.abc.Container`
- `collections.abc.Collection`
- `collections.abc.Callable`
- `collections.abc.Set` # typing.AbstractSet
- `collections.abc.MutableSet`
- `collections.abc.Mapping`
- `collections.abc.MutableMapping`
- `collections.abc.Sequence`
- `collections.abc.MutableSequence`
- `collections.abc.ByteString`
- `collections.abc.MappingView`
- `collections.abc.KeysView`
- `collections.abc.ItemsView`
- `collections.abc.ValuesView`
- `contextlib.AbstractContextManager` # typing.ContextManager
- `contextlib.AbstractAsyncContextManager` # typing.AsyncContextManager
- `re.Pattern` # typing.Pattern, typing.re.Pattern
- `re.Match` # typing.Match, typing.re.Match

source: https://peps.python.org/pep-0585/#implementation

**Comment by charliermarsh** [comment]
The rewrites that don't require _renames_ are already handled by `UP035` (e.g., importing `from collections import Counter` instead of `from typing import Counter`).
