### ISSUE TITLE
PIE810 autofixit bug - removes parentheses

### ISSUE THREAD

**Issue by Skylion007** [charliermarsh/ruff#3515]
flake8-PIE810 can accidentally remove parentheses and change the meetings of expressions. See below for a real world error.

Original Code
```python
a = "b"

a.startswith("c") or a.startswith("d") or (a.startswith('b') and not a.endswith('f'))
```

Autofixed code
```python
a = "b"

a.startswith(("c", "d")) or a.startswith("b") and not a.endswith('f')
```

The two if statements are not equivalent due to missing parentheses around the "and" statement. This bug may also affect the isinstance merge checks in flake8-SIM as well.

**Comment by charliermarsh** [comment]
Due to precedence, I believe those statements are the same? E.g., `a = "c"` returns the same thing in both cases.
