### ISSUE TITLE
M001 is not working

### ISSUE THREAD

**Issue by adriangb** [charliermarsh/ruff#352]
With ruff v0.0.59 given a file like:

```python
def foo() -> None:
    a = 1  # noqa: F401
    print(a)
```

Running:

```shell
ruff --extend-select M001 test.py
```

There are no errors

**Comment by charliermarsh** [comment]
Interestingly I actually get:

```
∴ ruff --select M001 foo.py
Found 1 error(s).
foo.py:2:10: M001 Unused `noqa` directive for: F401
1 potentially fixable with the --fix option.
```

**Comment by charliermarsh** [comment]
Does `ruff --show-settings test.py` have anything interesting?

**Comment by adriangb** [comment]
Oh duh user error, I had a config file floating around...

**Comment by charliermarsh** [comment]
Out of curiosity: what was the config file doing? Did it have an explicit ignore on M001? Something else?

**Comment by adriangb** [comment]
> Did it have an explicit ignore on M001?

Yes 🤦🏻 , I don't even remember why I put it in there. Embarrassing.

**Comment by charliermarsh** [comment]
Not embarrassing at all! It's bad that it was confusing for you as the user. If you explicitly `--select` something that's ignored by the config, we should warn you.
