### ISSUE TITLE
[Infinite Loop] Failed to converge after 100 iterations.

### ISSUE THREAD

**Issue by qarmin** [charliermarsh/ruff#3522]
Ruff 0.0.255
Command
```
ruff ~/Desktop/Ruff/Broken/AcquireFile6.py --config /home/rafal/Desktop/ruff.toml --fix --no-cache
```
Settings
```
select = ["ALL"]
```

[AcquireFile6.py.zip](https://github.com/charliermarsh/ruff/files/10973446/AcquireFile6.py.zip)

produce error 
```
error: Failed to converge after 100 iterations.

This indicates a bug in `ruff`. If you could open an issue at:

    https://github.com/charliermarsh/ruff/issues/new?title=%5BInfinite%20loop%5D

...quoting the contents of `AcquireFile6.py`, along with the `pyproject.toml` settings and executed command, we'd be very appreciative!

```

**Comment by vlindhol** [comment]
I took a look at this, and managed to narrow it down to the following minimal test case:

```python
class A:
    """
\ a
    """
```

With the config:

```toml
select = [
  "D207", # bad docstring indentation
  "W605", # invalid escape sequence
]
```

Those two rules clash in the following way

1. `W605` schedules an insertion of a `\` at column 0
2. `D207` schedules an insertion of `....` (four spaces) at column 0
3. End result: `\ a` -> `\` + `    ` + `\ a` -> `\    \ a`
4. GOTO 1

I'll make a PR about it!

**Comment by charliermarsh** [comment]
Thank you :heart:
