### ISSUE TITLE
flake8-unused-arguments: ARG001-ARG004 should be disabled for `.pyi` files

### ISSUE THREAD

**Issue by XuehaiPan** [charliermarsh/ruff#3532]
Thanks for the amazing tool. I'm gradually enabling as many as possible rules that `ruff` provides in my project. I'm running `ruff check --select=ALL .` and selecting reasonable rule code in my `pyproject.toml`.

I found `ruff check .` will glob all `.py` and `.pyi` in the directory. The `ARG001-ARG004` creates too much noise here for unused arguments in `.pyi` stub files. The function definitions in stub files are intentionally not to have implementation. So the arguments are never used.

```python
# test.pyi

def add(x: float, y: float) -> float: ...
```

```console
$ ruff --version
ruff 0.0.255

$ ruff check --select=ARG test.pyi
test.pyi:3:9: ARG001 Unused function argument: `x`
  |
3 | def add(x: float, y: float) -> float: ...
  |         ^^^^^^^^ ARG001
  |

test.pyi:3:19: ARG001 Unused function argument: `y`
  |
3 | def add(x: float, y: float) -> float: ...
  |                   ^^^^^^^^ ARG001
  |

Found 2 errors.
```

**Comment by charliermarsh** [comment]
Oh yeah, definitely not.
