### ISSUE TITLE
API Docu missing

### ISSUE THREAD

**Issue by buhtz** [charliermarsh/ruff#3536]
Hello,

it seems to me that there is no documentation about the API. Is it called "API Reference"?

I do
    import ruff

and then have no idea what to do with that module.

I don't want to run ruff from shell but in my own python scripts.

**Comment by MichaReiser** [comment]
:wave: @buhtz 

Ruff doesn't provide a public python API today, but we are considering adding it. Can you tell us a bit about your use case? It would help us prioritize and design the feature.

**Comment by buhtz** [comment]
Dear Micha,
thanks for your reply.

I would like to call ruff from my unit tests. I know it is not recommended today but I never understood why I should to PEP8 testing while unit testing. Pre commit hooks are IMHO not an option because they add an additional layer and that hooks often do feel like hacks or workarounds to me and not as solutions.

Here an example how I do it with pycode style.


```
class MirrorMirrorOnTheWall(unittest.TestCase):
    """Check all py-files in the package incl. its test files if they are
    PEP8 compliant.
    """
 
    # ...snipped...

    def test_pep8_conformance(self):
        """PEP8 conformance"""

        for fp in self._collect_py_files():
            with self.subTest(fp):
                print(fp)
                pep = pycodestyle.Checker(fp, ignore=None)
                self.assertEqual(pep.check_all(), 0, fp.name)
```

**Comment by charliermarsh** [comment]
Yeah we're not quite at the point at which we can offer a programmatic public API. The recommended solution is to go through `subprocess`, but we'll likely fix this at some point in the future :)
