### ISSUE TITLE
`C901`: Add `max-complexity` value to message

### ISSUE THREAD

**Issue by ngnpope** [charliermarsh/ruff#3539]
Having just seen output like the following:

```
example.py:851:9: C901 `function` is too complex (15)
example.py:851:9: PLR0912 Too many branches (16/15)
example.py:851:9: PLR0915 Too many statements (53/50)
```

It seems like it would be nice to include the value of `max-complexity` in the `C901` message too?

**Comment by charliermarsh** [comment]
Yeah makes sense. I feel like all of these would be clearer as `16 > 15`, rather than with the slash.
