### ISSUE TITLE
Add auto-fix for ARG

### ISSUE THREAD

**Issue by JonathanPlasse** [charliermarsh/ruff#3540]
```python
def a(b):
    pass
```
could be auto-fixed like this
```python
def a(_b):
   pass
```
This is similar to the `B007` auto-fix.

**Comment by ngnpope** [comment]
Not sure this is safe unless the argument is positional only. This could be called as `a(b=1)`, so autofixing as above, even if unused in the definition, could break at the call sites.

**Comment by charliermarsh** [comment]
Yeah I think this is too risky. It also may "mask" the error in some cases where the correct fix is too remove the argument entirely.
