### ISSUE TITLE
`printf-style-formatting` ignores direct-string interpolation

### ISSUE THREAD

**Issue by charliermarsh** [charliermarsh/ruff#3549]
Given:

```py
"%s" % "foo"
"%s" % ("foo",)
```

Ruff will raise UP031 for the latter, but not the former.

**Comment by globau** [comment]
🎉

**Comment by charliermarsh** [comment]
Sadly the most common case isn't safely fixable right now. I want to improve it... Sort of a long story, but if you have:

```py
print("%s" % x)
```

It turns out we _can't_ safely convert that to:

```py
print("{}".format(x))
```

Because `x` _could_ be a single-element tuple, like so:

```py
x = (1,)
print("%s" % x)
print("{}".format(x))
```

So for now, we can only convert these for cases in which the placeholder has more than one positional argument, or at least one keyword argument (in which case, we _know_ it's a tuple or a mapping respectively).

Though we do now fix cases like:

```py
"%d" % 1
"%s" % "foo"
"%s" % f"foo{bar}"
```
