### ISSUE TITLE
New Setting Request: Adjust the quotes in the problem from [`] to [']

### ISSUE THREAD

**Issue by Andy-dh-Luo** [charliermarsh/ruff#3577]
I'd like to know if I can adjust the quotations showing in the problems from \` \` (backquote) to ' ' or " " (single/ double quote) through configurations. For instance, I desire the {name} showed in the problem to be 'name' (just like flake8) or "name" instead of \`name\`. Ruff does help me a lot but it really bother me by this stuff since I simply don't like the backquote.  I would appreciate it if you could provide a new setting option to solve this. BTW I'm currently using the Ruff VSCode extention. Thanks. 

![image](https://user-images.githubusercontent.com/128155646/225923033-47883a62-9954-45de-9314-1d99cfa30b83.png)

**Comment by charliermarsh** [comment]
Here, are you referring specifically to the message that appears in the diagnostic?

**Comment by Andy-dh-Luo** [comment]
> Here, are you referring specifically to the message that appears in the diagnostic?

Yes.

**Comment by charliermarsh** [comment]
Ah yeah, this isn't currently configurable. I think it's a reasonable choice for us and to be honest, we're unlikely to parametrize it just given the maintenance burden.
