### ISSUE TITLE
Update C416 rule with dict comprehensions and make autofixable

### ISSUE THREAD

**Issue by Skylion007** [charliermarsh/ruff#3598]
I recently [updated flake8-comprehension's C416](https://github.com/adamchainz/flake8-comprehensions/pull/490) check to extend to dict comprehensions as well. It should also be auto-fixable just like the other C416 checks. Since the new version is now released on PyPy, it is a good idea to update to it.

**Comment by charliermarsh** [comment]
Sweet, thanks for the heads up.

**Comment by dhruvmanila** [comment]
Hi, can I take this?
