### ISSUE TITLE
pre-commit is not ran in ci, resulting in possible commits that don't pass pre-commit

### ISSUE THREAD

**Issue by onerandomusername** [charliermarsh/ruff#3612]
continuation of #3604 #3603
https://github.com/charliermarsh/ruff/blob/main/.github/workflows/ci.yaml doesn't contain an action to run pre-commit, so it only happens locally, and doesn't seem to be validated in ci.

There's two options for this, adding a job which runs pre-commit in ci, or installing https://pre-commit.ci on the repo (and perhaps adding configuration to change autoupdate)

Config will have to be added to skip the local hooks unless they aren't part of ci already.

I'm interested in adding the ci or pre-commit.ci config, for whichever route is chosen.

**Comment by charliermarsh** [comment]
Yeah we're in kind of a weird state right now. Some people want pre-commit, so it exists, and there's a set of checks that _only_ run on pre-commit right now, but candidly I don't use it at all, it's not part of the contributor guidelines or getting started, and I'm hesitant to make it something contributors _have_ to install and run.

As long as it exists, though, we should at least validate it on CI, i.e., incorporate it into `ci.yaml`. We'll want to skip the steps that are already captured by our established CI workloads (I believe they're enumerated at the bottom already) -- I think those are all the local hooks anyway.

**Comment by onerandomusername** [comment]
Would you rather implement it in CI or using the external plugin https://pre-commit.ci/ ?

**Comment by charliermarsh** [comment]
I would rather implement it in CI.

**Comment by JonathanPlasse** [comment]
Can I work on it?

**Comment by onerandomusername** [comment]
I would like to implement this

**Comment by JonathanPlasse** [comment]
Sorry, go ahead.
