### ISSUE TITLE
Add a step by step diff of the auto-fix

### ISSUE THREAD

**Issue by JonathanPlasse** [charliermarsh/ruff#3642]
To help debug auto-fix problems and add auto-fixes, it could be useful to be able to have a step-by-step diff for each application of a fix.

**Comment by jfmengels** [comment]
For what it's worth, this is the default behavior for `elm-review --fix`, which I think is the best approach to gain the user's trust: by showing that you're fixing each issue in the correct way. I talk about this in [this video](https://youtu.be/XjwJeHRa53A?t=1222).

![FaHfMbbX0AA_Sba](https://user-images.githubusercontent.com/3869412/227010991-a19a6003-2faf-4504-b819-6bad8c7c486e.png)

It does however look a lot less impressive if you're trying to impress the user with the speed of the tool though, which I guess is pretty important for Ruff's adoption at this point.

`elm-review` also has a `--fix-all` command which accumulates all errors and then prompts the user on whether to accept the larger diff. And there is a `--fix-all-without-prompt` flag (which is not very much documented on purpose) where the behavior is the same as what Ruff has today.

**Comment by JonathanPlasse** [comment]
It's awesome!

**Comment by charliermarsh** [comment]
If any contributor gets excited about implementing this, I do think it's something we'd like to support. Though there are some details to work out before diving in.

As a straw proposal:

- Invoke via `ruff --fix --review`.
- Render a `cargo insta review`-like experience: a diff, with "accept" or "skip" actions (might be some things we can reuse from `cargo insta`, I like their UI a lot).
- On completion: should we print out all remaining lint errors? Unclear, need to look at how other tools behave here.
- Once you've cycled through all the fixable errors: should we re-run Ruff, and show you the remaining fixable errors? Probably, that's how `--fix` works internally today (we iteratively fix until there's nothing left to fix).

\cc @MichaReiser

**Comment by jfmengels** [comment]
> On completion: should we print out all remaining lint errors? Unclear, need to look at how other tools behave here.

That's what `elm-review` does. I'd say you don't want to let the user re-run the tool to know whether he's done with linting (and can move on to other things) or not.

> Once you've cycled through all the fixable errors: should we re-run Ruff, and show you the remaining fixable errors? Probably, that's how --fix works internally today (we iteratively fix until there's nothing left to fix).

We do this as well.

---

If you want to try out how `elm-review` does it:
- Clone https://github.com/jfmengels/elm-spa-example
- Run `npm install`
- Play with
  - `npx elm-review --fix`
  - `npx elm-review --fix-all`

(There are a lot of errors in that example, so maybe you want to use `--rules` to limit which rules to run, like `--rules NoUnused.Patterns`)

**Comment by charliermarsh** [comment]
Consolidating into #4361.
