### ISSUE TITLE
Should .mako.py files be ignored?

### ISSUE THREAD

**Issue by JonathanPlasse** [charliermarsh/ruff#3653]
[Mozilla](https://github.com/mozilla/gecko-dev/blob/137075514eddc08c68ff652e9899da82e8043574/pyproject.toml#L71-L72) ignore mako files.

**Comment by charliermarsh** [comment]
I think what Mozilla is doing there strikes me as the right outcome. I could imagine it being confusing that Ruff omits those by defaults. In some rare cases, users might even _want_ them to checked. But it should be straightforward to omit them as they've done so there.
