### ISSUE TITLE
[Autofix error] Noqu remove in 0.0.256

### ISSUE THREAD

**Issue by Czaki** [charliermarsh/ruff#3666]
When adding `TRY` rules in ruff configuration for napari project, then I add # noqa TRY301

```python
        try:
            raise ValueError("a")  # noqa TRY301
        except ValueError:
            threading.excepthook(sys.exc_info())
```

Then in review there was a decision to skip `TRY301` For all test files.

Then running ruff ends with:

```
error: Autofix introduced a syntax error. Reverting all changes.

This indicates a bug in `ruff`. If you could open an issue at:

    https://github.com/charliermarsh/ruff/issues/new?title=%5BAutofix%20error%5D

...quoting the contents of `napari/_qt/_tests/test_qt_notifications.py`, along with the `pyproject.toml` settings and executed command, we'd be very appreciative!
```

Updating code to 

```python
        try:
            raise ValueError("a")  # noqa: TRY301
        except ValueError:
            threading.excepthook(sys.exc_info())
```

Makes auto-fix work. 

It comes from the incorrect noqa `# noqa TRY301` instead of `# noqa: TRY301`. But it looks like auto-fix should comment out the rest of the text if something is left after removing noqa

(in napari I introduce ruff in parts to make the review possible)

**Comment by charliermarsh** [comment]
I believe this was fixed in https://github.com/charliermarsh/ruff/pull/3589 (not yet released).
