### ISSUE TITLE
Support for nested classes

### ISSUE THREAD

**Issue by ShalokShalom** [charliermarsh/ruff#3667]
I know that nested classes are usually not considered to be pythonic, or usable at all. 
I actually found a use, and suggest to consider them:

![Screenshot_20230322_153212](https://user-images.githubusercontent.com/6344099/226937354-7619905c-fa3c-4245-a22a-5ee4265b56d9.png)

@choice implements choice classes, also called [tagged unions](https://en.wikipedia.org/wiki/Tagged_union), and I like to group them together, in order to increase readability. 

The error shows doesn't take this into account, since the nested classes seem to be considered, as you see. 

It thinks Exit is unused, and therefor doesn't assume, that it might be an indentation error. 
I understand, if you think this to be the edge case it might be, and the error to be accurate enough in this case. Still, I think its worth acknowledging this issue. 

I appreciate your response. :)

**Comment by JonathanPlasse** [comment]
```python
@choice
class ChoiceExit:
    class PassableExit: ...
    class LockedExit: ...
    class NoExit: ...

Exit = PassableExit | LockedExit | NoExit
```
Would the code above work for you?
The problem is that you are overriding Exit.

**Comment by ShalokShalom** [comment]
That's not implemented yet, also because I dont know, how I should implement it. 😄 

The plan was to inject the Union building structure, and eventually including the functionality of @final. 

But I am very new to Python, and try to bring over the DUs from FSharp, to continue this style of programming. It seems like I am going against the common coding practices in the Python community. 

There is also no real maintained, properly ergonomic sumtype implementation, as far as I see. 
Do you know more about that? 😄
