### ISSUE TITLE
SIM118 Incorrect error message and autofix

### ISSUE THREAD

**Issue by dosisod** [charliermarsh/ruff#3690]
Given the following code:

```python
x: dict[str, str] | None = None

y = "abc" in (x or {}).keys()
```

Ruff returns the following error:

```
$ ruff file.py
file.py:3:5: SIM118 [*] Use `"abc" in x or {}` instead of `"abc" in x or {}.keys()`
Found 1 error.
[*] 1 potentially fixable with the --fix option.
```

The error is correct except the `x or {}` part of the error message isn't wrapped in parenthesis. And, when running with `--fix`, the following (incorrect) code is produced:

```python
x: dict[str, str] | None = None

y = "abc" in x or {}
```

If `x` is `None`, this code will now cause a `NoneType` error, and if `x` is a `dict` but doesn't contain `"abc"`, then `y` will be a `dict` instead of a `bool`.

There might be other checks that have a similar issue, this just happened to be the first one I came across.

Currently using Ruff v0.0.258

**Comment by charliermarsh** [comment]
Oh yeah, definitely. Thanks for filing.

**Comment by JonathanPlasse** [comment]
Sorry @charliermarsh, I already finished implementing it before seeing that you self-assigned this issue.

**Comment by charliermarsh** [comment]
No worries, this is great! I'd started on this but got sidetracked IRL.
