### ISSUE TITLE
Is `v0.0.259` the latest release?

### ISSUE THREAD

**Issue by ZhongRuoyu** [charliermarsh/ruff#3710]
Hi! [Homebrew](https://github.com/Homebrew/brew) maintainer here. We noticed that `v0.0.259` was tagged, but is not yet marked as latest on the repo's [releases page](https://github.com/charliermarsh/ruff/releases). I'm filing this issue to confirm if the release is ready to be marked as latest, so that we can go ahead and ship it. Thanks!

**Comment by dhruvmanila** [comment]
Yes, `v0.0.259` is the latest release as there was a regression in `v0.0.258`. I guess he must've forgotten to mark it as the latest one.

References:
- https://github.com/charliermarsh/ruff/issues/3692
- Bugfix PR: https://github.com/charliermarsh/ruff/pull/3685

Also, the `v0.0.258` release has been [yanked from PyPi](https://pypi.org/project/ruff/#history).

**Comment by ZhongRuoyu** [comment]
Thanks @dhruvmanila for the info! Then let me proceed to ship `v0.0.259` at https://github.com/Homebrew/homebrew-core/pull/126506.

**Comment by charliermarsh** [comment]
Fixed, sorry about that!

**Comment by ZhongRuoyu** [comment]
No worries, thanks @charliermarsh!
