### ISSUE TITLE
Implement support for SIM120

### ISSUE THREAD

**Issue by MaxG87** [charliermarsh/ruff#3712]
I am using Ruff 0.0.259.

I noticed that the rule [SIM120](https://github.com/MartinThoma/flake8-simplify#SIM120) from `flake8-simplify` is not yet implemented. While this particular rule might become less relevant over time, I just today dealt with a legacy project which still had that issue.

I think this particular rule would lend itself to be automatically fixable too.

It would be great if it could be considered to implement this rule.

**Comment by charliermarsh** [comment]
That's right -- we support it under `pyupgrade`, rather than under `flake8-simplify`.
