### ISSUE TITLE
Inproper F401: "imported but unused" for sumodule if parent module is imported with an alias.

### ISSUE THREAD

**Issue by ghuls** [charliermarsh/ruff#373]
Inproper F401: "imported but unused" for sumodule if parent module is imported with an alias.

```python
import pyarrow as pa

import pyarrow.csv

print(pa.csv.read_csv("test.csv"))
```

```bash
$ ruff test_import.py 
No pyproject.toml found.
Falling back to default configuration...
Found 1 error(s).
test_import.py:3:1: F401 `pyarrow.csv` imported but unused
1 potentially fixable with the --fix option.
```

**Comment by charliermarsh** [comment]
Good catch, will fix this.

**Comment by charliermarsh** [comment]
(Found the offending code, working on fix now.)

**Comment by ghuls** [comment]
Thanks. It solves the problem.
Maybe it would be good to invalidate the ruff cache in the ruff binary is not the same between invocations as first I thought you pushed unrelated changes to master as the errors were the same after recompilation.

Found another one:
```
$ ruff test_import.py 
No pyproject.toml found.
Falling back to default configuration...
Found 1 error(s).
test_import.py:3:1: F401 `numpy` imported but unused
1 potentially fixable with the --fix option.
```

It might be more tricky to solve as in involves type annotations in quoted strings.
```python
import sys

import numpy as np

if sys.version_info >= (3, 10):
    from typing import TypeAlias
else:
    from typing_extensions import TypeAlias


CustomInt: TypeAlias = "np.int8 | np.int16"
```

**Comment by charliermarsh** [comment]
That one should work too, let me file a separate issue.

**Comment by charliermarsh** [comment]
> Maybe it would be good to invalidate the ruff cache in the ruff binary is not the same between invocations as first I thought you pushed unrelated changes to master as the errors were the same after recompilation.

Hmm yeah. We do put the Cargo version in the cache key, so it's invalidated between _releases_. But I can see how this would be confusing when running against Git etc.
