### ISSUE TITLE
`UP035` is showing as unfixable, when I would expect it to be fixable

### ISSUE THREAD

**Issue by samuelcolvin** [charliermarsh/ruff#3742]
I'm trying to use ruff as a replacement for pyupgrade when generating docs with different examples for different python versions, however I immediately ran into a problem where "errors" which I would expect to be fixable, are coming back as unfixable, specifically `UP035`.

---

Run `ruff --select U --target-version py310 --fix test.py` on the following code.

```py
from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel


class User(BaseModel):
    id: int
    name: str = 'John Doe'
    signup_ts: Optional[datetime] = None
    friends: List[int] = []
```

I'm getting the following error:

```
test.py:2:1: UP035 `typing.List` is deprecated, use `list` instead
Found 3 errors (2 fixed, 1 remaining).
```

I would expect `UP035` to be fixable

(updated to use code before running `--fix`)

**Comment by charliermarsh** [comment]
Can elaborate when I’m back at my computer, but the immediate workaround would be to enable the F rules. The “fix” is to remove the unused import, since List is now unused (presumedly), and the UP rules alone don’t handle unused import removals.

**Comment by samuelcolvin** [comment]
amazing, I'll try that.

**Comment by samuelcolvin** [comment]
works great, however interestingly still significantly slower than pyupgrade when invoked via subprocess for each code snippet.

**Comment by charliermarsh** [comment]
Yeah I guess the subprocess overhead is probably non-negligible in that context. We should benchmark that against a proper `pyo3` API. We could probably ship a `pyo3` API _relatively_ quickly... the main blocker is deciding whether we want to support it or whether there's some other style of programmatic usage we might prefer instead (vague handwave-y statement, not suggesting any specific alternative right now).

**Comment by JonathanPlasse** [comment]
I started working on a `pyo3` API.
Currently, it takes a toml string as configuration.
I only implemented lint checks.
The lint function returns a wrapper of `Message`.
https://github.com/JonathanPlasse/ruff-api/blob/main/src/lib.rs

**Comment by samuelcolvin** [comment]
In my experience the overhead of a pyo3 function call is ~80us, much much less than spinning up a process.

You could run ruff as a server and pipe data to it in this case, but in general it would be much less ergonomic than a python API.

**Comment by charliermarsh** [comment]
Yeah that's probably the most notable alternative: run Ruff as an LSP or something. Another would be to make a more flexible command-line API, e.g., something that takes JSON in and spits JSON out but supports all these use-cases. I expect that we'll end up shipping a `pyo3` API over those options.

**Comment by samuelcolvin** [comment]
You could ship a rust crate, then build a python API package using the rust crate, just to keep the current package small and simple.
