### ISSUE TITLE
TRY300 when returning a function result

### ISSUE THREAD

**Issue by Apakottur** [charliermarsh/ruff#3778]
Thank you for this awesome project!

Consider the following code:
```python
# test.py
def something_that_may_go_wrong():
    raise Exception

def func():
    try:
        _ = something_that_may_go_wrong()
        return something_that_may_go_wrong()
    except Exception:
        print("Failed")
```

I'm running ruff with:
```shell
ruff check --select TRY300 test.py
```

Which gives:
```shell
test.py:9:9: TRY300 Consider moving this statement to an `else` block
```

The intended fix, as I understand it, is:
```python
# test.py
def something_that_may_go_wrong():
    raise Exception

def func():
    try:
        _ = something_that_may_go_wrong()
        result = something_that_may_go_wrong()
    except Exception:
        print("Failed")
    else:
        return result
```

While I understand the motivation (put the return statement outside of the try clause), we end up adding another variable and 2 lines of code, which IMO make this specfic case less readable.

Note that if we remove the line ` _ = something_that_may_go_wrong()` then the code checks without errors (as I would expect it to), so I was a bit surprised to see that this is not the behavior for this case.

Running tryceratops gives the exact same result, so I don't think it's a bug in ruff but still wonder if there's a better way to handle the error in this specific case?

I'm using ruff 0.0.252.

**Comment by JonathanPlasse** [comment]
We could disable TRY300 when return is an expression with side effects.
