### ISSUE TITLE
Adding ability to choose certain codes to error on (instead of disabling all using `--exit-zero`) or not error on

### ISSUE THREAD

**Issue by JSpenced** [charliermarsh/ruff#3782]
This is more a feature request or maybe I missed something in the docs to enable it.

From what I see, currently, I have `--exit-zero` in our `pre-commit` file, but we would like it to output all linting errors that we have included. Then only error on certain ones in the `pre-commit`. I know something similar is possible using `fixable` and `unfixable`, but not for which codes to error on or not.

Does this feature seem useful and possibly will be implemented in the future?

**Comment by charliermarsh** [comment]
Yeah I think this could in theory be tackled by adding "severities" (so that users can differentiate errors from warnings), so I'm gonna close in favor of https://github.com/charliermarsh/ruff/issues/1256.

**Comment by JSpenced** [comment]
Yup 💯 ! Thanks for the link.

**Comment by charliermarsh** [comment]
Any time :) Links are easy, it's changes that take work :joy:
