### ISSUE TITLE
Pre-commit repo is not updated with new releases

### ISSUE THREAD

**Issue by mnestuley-marfatech** [charliermarsh/ruff#383]
pre-commit version is only 0.0.48
https://github.com/charliermarsh/ruff-pre-commit

**Comment by charliermarsh** [comment]
Yeah sadly I've been doing this manually. I'll update it now. But it should be automated.

**Comment by charliermarsh** [comment]
I just published v0.0.65. Will think on how to automate it.

**Comment by fsouza** [comment]
@charliermarsh I can send a PR with the automation. It's basically what I have here: https://github.com/fsouza/mirrors-ruff/blob/main/.github/workflows/main.yml

It leverages `pre-commit-mirror-maker`, created by the creator of pre-commit.

**Comment by charliermarsh** [comment]
Oh cool, that would be much appreciated!

**Comment by charliermarsh** [comment]
This is fixed thanks to some great work from @fsouza.
