### ISSUE TITLE
Flag unsupported `noqa` directives when using `M001`.

### ISSUE THREAD

**Issue by ghuls** [charliermarsh/ruff#384]
Flag unsupported `noqa` directives when using `M001`.

Now it calls some `noqa` unused while they are needed for some flake8 plugins:
```
$ ruff --extend-select M001 .
...: M001 Unused `noqa` directive for: E101, W191
```

Some flag that indicates that those are not implemented (yet) would be nice:
```
$ ruff --extend-select M001 .
...: M001 Unused `noqa` directive for: E101, W191 (not implemented)
```

**Comment by charliermarsh** [comment]
That's a nice idea.

**Comment by charliermarsh** [comment]
`M001` will still remove those "unknown" codes when autofixing -- not sure what the right behavior is there.

**Comment by ghuls** [comment]
Works nicely.

One way would be to collect all known codes from the most common plugins to have a whitelist of things to not remove.
