### ISSUE TITLE
Support `flake8-todos`

### ISSUE THREAD

**Issue by edgarrmondragon** [charliermarsh/ruff#3870]
https://github.com/orsinium-labs/flake8-todos

- [x] **T001**: use TODO instead of FIXME (or BUG) for consistency.
- [x] **T002**: add author into TODO ([motivation](https://dave.cheney.net/practical-go/presentations/qcon-china.html#_dont_comment_bad_code_rewrite_it)).
- [x] **T003**: add link on issue into TODO.
- [x] **T004**: missed colon in TODO.
- [x] **T005**: missed text in TODO.
- [x] **T006**: write TODO instead of ToDo (use upper case).
- [x] **T007**: missed space after colon in TODO.

Related:

- https://github.com/charliermarsh/ruff/issues/3859

**Comment by evanrittenhouse** [comment]
I can try to implement this!

**Comment by JonathanPlasse** [comment]
We can close this issue.
Congrats @evanrittenhouse.
