### ISSUE TITLE
Feature Request: Indents

### ISSUE THREAD

**Issue by navyamehta** [charliermarsh/ruff#3907]
Is there a way to directly specify the indentation style to apply in a codebase (4-space indent vs hanging indent etc.) via a config in ruff.toml? Thank you!

**Comment by charliermarsh** [comment]
It doesn't exist right now, but it would likely be part of the formatter configuration eventually :)

**Comment by chiamp** [comment]
I would also be interested in a feature where you can configure regular indent and hanging indent separately

**Comment by cgarciae** [comment]
Just want to add that this would be important for Google-related Open Source projects.

**Comment by zanieb** [comment]
I presume our existing formatter indentation configuration does not satisfy your requirement? https://docs.astral.sh/ruff/formatter/#configuration

Can you provide some concrete examples of what you need?

**Comment by cgarciae** [comment]
Hey @zanieb! Sure, so here is how it currently formats a function with a trailing comma in the arguments (or if the arguments are too long) using 2 space indentation:

```python
some_func(
  foo,
  bar,
)
```

Some Google projects use 2 space indentation with 4 space _hanging indentation_:

```python
some_func(
    foo,
    bar,
)
```
We are currently testing migrating from [pyink](https://github.com/google/pyink) to ruff, pyink does support 4 space hanging indentation on 2 space indentation. You can try it out with the following config:

```toml
[tool.pyink]
pyink-indentation = 2
```
