### ISSUE TITLE
`isort` thrash with `ruff` on imports

### ISSUE THREAD

**Issue by leos** [charliermarsh/ruff#3908]
`isort` version 5.12.0, `ruff` version 0.0.261

Relevant fragments from `pyproject.toml`:
```
[tool.isort]
profile = "black"
known_first_party = ["redacted", "redacted",]
lines_after_imports = 2

[tool.ruff]
select = ["I", "ICN", "YTT"]
target-version = "py310"

[tool.ruff.isort]
known-first-party = ["redacted", "redacted",]
lines-after-imports = 2
```

`isort` and `ruff` seem to aggregate these imports differently. This may be an `isort` issue (as I think `ruff`'s way is correct), but raising it here as it's a behavior difference:

After running `isort`:
```
from tenacity import before_sleep_log
from tenacity import retry as retry_decorator
from tenacity import stop_after_attempt, wait_fixed
```
After running `ruff --fix`:
```
from tenacity import before_sleep_log, stop_after_attempt, wait_fixed
from tenacity import retry as retry_decorator
```

`tenacity` is https://github.com/jd/tenacity

**Comment by charliermarsh** [comment]
Ah yeah, this is one of the two "known deviations" that we have with `isort` -- there's some discussion on it here: https://github.com/charliermarsh/ruff/issues/1381. (And I'll just link to the "known deviations" in the [FAQ](https://beta.ruff.rs/docs/faq/#how-does-ruffs-import-sorting-compare-to-isort) for completeness.) I also prefer our behavior, and there aren't currently plans to change it, though I know it's annoying that it causes larger-than-expected diffs during migration.

**Comment by leos** [comment]
Ah, got it, thanks. I was hoping to have both `isort` and `ruff` running for a bit just to ensure that everything was good between them, but I guess I'll just switch over.

I actually saw the FAQ entry before filing this, but it wasn't obvious to me (w/o clicking through to the actual issues) that "a few known, minor differences in how Ruff and isort break ties between similar imports, and in how Ruff and isort treat inline comments in some cases" was talking about this issue - I didn't think these were similar imports that would be tied and it's definitely not inline comments.

**Comment by charliermarsh** [comment]
Yeah that's a good point. I don't think I really internalized the scope of this deviation when I wrote that. Will fix.
