### ISSUE TITLE
Feature request: ignore `N802` for methods marked with `@override`

### ISSUE THREAD

**Issue by Avasam** [charliermarsh/ruff#3910]
Same as https://github.com/PyCQA/pep8-naming/issues/215 I think this would be useful whether it is added to pep8-naming or not

Python 3.12 will introduce the `override` decorator. It is already backported by `typing_extensions`.

Overridden method names are out of the dev's control when subclassing an external library. A strong example of this is PyQt6/PySide6, where I have to keep adding to `ignore-names` as I use more and more features. Ruff could understand that there's nothing the dev can do about the names if a method is marked with `@override` (and it'll still raise anyway on the base class if it's internal).

```
[tool.ruff.pep8-naming]
# PyQt methods
ignore-names = ["closeEvent", "paintEvent", "keyPressEvent", "mousePressEvent", "mouseMoveEvent", "mouseReleaseEvent"]
```

**Comment by charliermarsh** [comment]
Makes sense!
