### ISSUE TITLE
Consider publishing visitor trait, or the ast crate as a whole

### ISSUE THREAD

**Issue by sondrelg** [charliermarsh/ruff#3918]
Hi!

I just wanted to ask a quick question: 

I'm writing a little pre-commit hook to reformat some Python code, and I found the visitor trait in Ruff's `ruff_python_ast` crate extremely valuable. 

Right now I've just copied the whole thing into my little app.

Does the trait exist in some form in a published crate somewhere, and if not, would you consider publishing it in the future? Seems like something many would benefit from 🙂

**Comment by not-my-profile** [comment]
I think it would make sense to upstream the trait in question to RustPython.

**Comment by youknowone** [comment]
Hello from RustPython. If anyone interested in, RustPython is open to take patch to add `trait Visitor` to RustPython.
`rustpython-ast` looks like appropriate place.

**Comment by thejcannon** [comment]
@sondrelg check out https://github.com/RustPython/RustPython/pull/4930

**Comment by youknowone** [comment]
If anyone use rustpython-ast or rustpython-parser, please take a look if splitting parser will be helpful or not https://github.com/RustPython/RustPython/issues/4941

**Comment by sondrelg** [comment]
My motivation is I need to be able to do the equivalent `ast.parse(...)` and python and implement a `NodeVisitor`, so pulling in the parser as a component seems like it might be ideal for that. My use-case probably isn't super important, but that's at least one datapoint for you 🙂

**Comment by youknowone** [comment]
@sondrelg could you check if this covers your use case? https://github.com/RustPython/Parser/pull/12

**Comment by sondrelg** [comment]
Yes that seems to cover everything :heart: Here's the plugin for reference: https://github.com/snok/printf-log-formatter/blob/main/src/gen_visitor.rs

**Comment by charliermarsh** [comment]
Awesome. Going to close since it looks like this will be covered from the RustPython side :heart:
