### ISSUE TITLE
Ruff detecting external import as local import

### ISSUE THREAD

**Issue by Nar67** [charliermarsh/ruff#3932]
We are switching our projects to ruff and found that it sorts the `alembic` import as a local import instead of an external import and so it places it in the incorrect block of imports. 
We have a local `alembic` folder in the root of our projects and I assume it's what is causing the problem.

ruff version: `ruff 0.0.261`
python version: `3.9`

pyproject.toml:
```
[tool.ruff.isort] 
force-single-line = false
split-on-trailing-comma = true
lines-after-imports = 2
lines-between-types = 1
known-first-party = ["something"]
```

![image](https://user-images.githubusercontent.com/23257592/231154968-ca25d02c-d395-4197-92a2-420e591e804d.png)

**Comment by charliermarsh** [comment]
Ah, ok, and that `alembic` local folder is _not_ a Python module? Like it's a folder with some other contents?

**Comment by Nar67** [comment]
Thank you, it worked!
