### ISSUE TITLE
F821 at struct

### ISSUE THREAD

**Issue by KyleJeong** [charliermarsh/ruff#3945]
I use ALE with Ruff for Python lint.
I met "F821 Undefined name strcut" when I tried the code like this.
~~~
sec, usec, caplen, wirelen, dummy = struct.unpack(....)
~~~

In my understanding, struct is a basic component of Python. So I didn't import anything.
The code worked fine, but Ruff gave me an F821 message.

**Comment by charliermarsh** [comment]
Hm, I believe `struct` is a standard library module that has to be imported, and not a builtin. E.g.:

```
Python 3.11.2 (main, Mar 20 2023, 17:17:17) [Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> struct.unpack
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'struct' is not defined
```

So it seems correct to warn here, but I'm wondering how your code worked without the import.

**Comment by KyleJeong** [comment]
Thank you for your response.
I will double-check soon and get back to you

**Comment by charliermarsh** [comment]
Thanks :)

**Comment by KyleJeong** [comment]
I am so sorry. You are correct. The sentence was designed to be executed in a specific condition. So I hadn't realized that that was the bug.

I used another linter, but it didn't recognize the problem. Only Ruff identified the problem.

Great linter!

**Comment by charliermarsh** [comment]
No worries, I'm glad we could resolve :)
