### ISSUE TITLE
feat: ruff rule to replace `.pop(...)` with `del dict[...]` when the return is unused

### ISSUE THREAD

**Issue by markis** [charliermarsh/ruff#3965]
When using a dictionary, a developer could use the `dict.pop(key)` or `del dict[key]` syntax to remove an item from a dictionary.  The `pop` syntax has the additional feature of returning the value from the dictionary, but it comes with a slight performance cost over the `del` syntax.  It would be nice if ruff could identify places that the return from the `pop` call was unused and would suggest the `del` instead.

Example
```python
fruits = { 'apples': 3, 'pears': 4, 'bananas': 1 }

fruits.pop('apples') # <-- suggest that developer change this to `del fruits['apples']`
del fruits['pears']

print(fruits)  # output: {'bananas':1}
```

**Comment by dhruvmanila** [comment]
Do you have any benchmark to support the performance difference? I'm doing a preliminary analysis and it shows no significant difference:

```python
In [21]: %timeit d = {chr(i): i for i in range(10000)}; del d[chr(456)]
1.29 ms ± 55.5 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [22]: %timeit d = {chr(i): i for i in range(10000)}; d.pop(chr(456))
1.25 ms ± 14.6 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
```

**Comment by dhruvmanila** [comment]
Another thing to note is this example:

```python
fruits = {'apples': 3, 'pears': 4, 'bananas': 1}

# This will raise a KeyError
fruits.pop('oranges')

# This will _not_ raise a KeyError, so we can't recommend to use `del fruits['oranges']`
fruits.pop('oranges', None)
```

**Comment by dhruvmanila** [comment]
> Thanks for checking, @dhruvmanila !

Happy to help! :)
