### ISSUE TITLE
"# noqa" is ignored when `per-file-ignores` is provided

### ISSUE THREAD

**Issue by DmytroLitvinov** [charliermarsh/ruff#3972]
Hi there.
I am trying to integrate `ruff` as a possible replacement of `flake8` and I see that behavior of `per-file-ignores` option is not the same as in `flake8`. 

* `flake8` settings
```
[flake8]
max-line-length = 120
per-file-ignores =
    __init__.py:F401,F403
```
flake8 respects `noqa` in that case, but not `ruff`. Not sure is it expected behavior for `ruff` or not?

* Code snippet to reproduce the issue:
```python
# __init__.py file
"""
See what is changed since then - https://github.com/ui/django-post_office/compare/3fead089a4e7e7fc2ae5ab56383f4ebf64c8777b...master  # noqa: E501
After you adapt it, then please change hash commit in url.
"""
```
* Ruff settings:
```
# pyproject.toml
[tool.ruff]
line-length = 120
# Sync with flake8 configuration
[tool.ruff.per-file-ignores]
"__init__.py" = ["F401", "F403"]
```
* Ruff version: 0.0.261
* Ruff issue: `__init__.py:2:121: E501 Line too long (144 > 120 characters)`

**Comment by DmytroLitvinov** [comment]
As far as I see right now also, it is not about `per-file-ignores` option, but because of docstrings.

```python
"""
# docsting.py
https://github.com/robbitt07/django_boilerplate/blob/fcd03f03e9e9e54088cf69cd3c4bc83eabfd2666/utils/storage_backends.py#L8  # noqa: E501
"""
```

Issue: `docstring.py:2:121: E501 Line too long (138 > 120 characters)`

**Comment by charliermarsh** [comment]
Yeah that's correct -- we don't support `# noqa` comments within multi-line strings. There's a note on it [here](https://beta.ruff.rs/docs/configuration/#error-suppression). Instead, we respect `# noqa` comments at the end of docstrings, like:

 ```py
"""
# docsting.py
https://github.com/robbitt07/django_boilerplate/blob/fcd03f03e9e9e54088cf69cd3c4bc83eabfd2666/utils/storage_backends.py#L8 
"""  # noqa: E501
```

Flake8 respects _either_ variant, so changing this should retain Flake8 compatibility.
