### ISSUE TITLE
[Autofix error] E712 Comparison to `True` should be `cond is True` inside an f-string

### ISSUE THREAD

**Issue by sdenier** [charliermarsh/ruff#3974]
Actually this code deals with Pandas series, so the real solution for us is to ignore the error as per https://github.com/charliermarsh/ruff/issues/1852 - so maybe this is too much of an edge case ?

This is an excerpt from our code which should be enough to reproduce:

```
def supprimer_doublons_osm_bpe(df_commerces):
    print(f"Suppression de {df_commerces['doublon_a_supprimer'] == True}")
```

Then `python -m ruff --fix  .` returns

```
error: Autofix introduced a syntax error. Reverting all changes.
```

* Version and settings

ruff 0.0.260

Settings same as https://beta.ruff.rs/docs/configuration/#using-pyprojecttoml, only with:
```
line-length = 150
```

**Comment by JonathanPlasse** [comment]
This is now fixed and works with Ruff 0.0.269.
