### ISSUE TITLE
Add flake8-comprehensions C418, C419

### ISSUE THREAD

**Issue by janosh** [charliermarsh/ruff#3976]
3.12.0 (2023-04-13)

Add rule C418 to check for calls passing a dict literal or dict comprehension to dict().
Add rule C419 to check for calls passing a list comprehension to any()/all().

https://github.com/adamchainz/flake8-comprehensions/blob/main/CHANGELOG.rst

**Comment by charliermarsh** [comment]
I believe I added these last night:

- https://github.com/charliermarsh/ruff/pull/3969
- https://github.com/charliermarsh/ruff/pull/3971

**Comment by janosh** [comment]
Oh snap, that was fast! 🚀

**Comment by charliermarsh** [comment]
We pride ourselves on good service!
