### ISSUE TITLE
Fails with assignment expression used in "any()" function

### ISSUE THREAD

**Issue by lorien** [charliermarsh/ruff#3997]
Content of "test.py":
```python
if any((key := x) for x in ["ok"]):
    print(key)
```
Ruff command:
```
ruff --isolated test.py
```

Ruff output:
```
test.py:2:11: F821 Undefined name `key`
```

Ruff version: 0.0.261

**Comment by lorien** [comment]
```python
if all((key := x) for x in []):
    print(key)
```

To me it looks like bad language design and might be considered as bug in python itself.

**Comment by charliermarsh** [comment]
Yeah it's "correct" behavior (`any` is false on empty lists, `all` is true), it's just that we have no way of knowing whether `key` will be defined within the loop. It looks like other static tools assume it will be.

**Comment by charliermarsh** [comment]
Looks like it is formally defined that the `NamedExpr` needs to be treated as a definition in the parent scope: https://peps.python.org/pep-0572/#scope-of-the-target

**Comment by madkinsz** [comment]
Is ruff capable of detecting empty iterators? It seems like the name will always be defined otherwise. It seems like if we cannot tell if it is empty, we must assume that it is not and that the name is indeed defined.

**Comment by charliermarsh** [comment]
We don't have that capability right now (to detect empty iterators). Agree that we should assume that the comprehension will execute, and that the name will thus be added to the parent scope. I started on this a bit, but it requires some changes to our semantic model (to add a binding to the non-current scope).
