### ISSUE TITLE
TID251 doesn't respect relative imports

### ISSUE THREAD

**Issue by henryiii** [charliermarsh/ruff#4013]
If you ban `typing.Protocol`, then `from .typing import Protocol` is flagged, defeating the purpose of the check for that usage (forcing a wrapper module to be used). Shouldn't this require and resolve absolute names?

Trying to keep a bug from happening again in cibuildwheel and ran into this. Currently looking into renaming the module to `._compat.typing`, which I think would work around this (edit: it does).

**Comment by charliermarsh** [comment]
Yeah that seems wrong. Will look into it.

**Comment by charliermarsh** [comment]
I should be able to fix this tomorrow and include it in the upcoming release.

**Comment by henryiii** [comment]
Nice, thanks!
