### ISSUE TITLE
error: Found argument '--force-exclude' which wasn't expected, or isn't valid in this context

### ISSUE THREAD

**Issue by lexicalunit** [charliermarsh/ruff#4017]
I'm using the vscode extension and whenever I try to run `Ruff: Format imports` on my python file I get this error, which I found in the log output:
```
Using environment executable: /usr/local/Caskroom/miniconda/base/bin/ruff
Inferred version ruff 0.0.135 for: /usr/local/Caskroom/miniconda/base/bin/ruff
Running Ruff with: ['/usr/local/Caskroom/miniconda/base/bin/ruff', '--force-exclude', '--no-cache', '--no-fix', '--quiet', '--format', 'json', '-', '--fix', '--extend-ignore', 'ALL', '--extend-select', 'I001', '--stdin-filename', '/Users/amytroschinetz/source/spellbot/src/spellbot/services/games.py']
error: Found argument '--force-exclude' which wasn't expected, or isn't valid in this context

  If you tried to supply '--force-exclude' as a value rather than a flag, use '-- --force-exclude'

Usage: ruff [OPTIONS] <FILES>...

For more information try '--help'
```

vscode indicates that the version installed is `v2023.12.0`.

From my vscode settings:

```json
  "ruff.importStrategy": "fromEnvironment"
```

```shell
/usr/local/Caskroom/miniconda/base/bin/ruff --version
ruff 0.0.135
```

```shell
poetry run ruff --version
ruff 0.0.261
```

I think `ruff` is using the wrong path. In vscode the python environment that I have selected is `./env`. But the extension seems to be using my miniconda environment for some reason.

Here you can see I've selected the local virtualenv, so it should be using the ruff from here:

<img width="596" alt="Screenshot 2023-04-18 at 11 27 47 PM" src="https://user-images.githubusercontent.com/1903876/232985517-41d88b0f-f787-42c1-8df1-0ac8c8783dee.png">

**Comment by dhruvmanila** [comment]
I think this issue should be opened in the relavant repository: https://github.com/charliermarsh/ruff-vscode

**Comment by charliermarsh** [comment]
Thank you! I re-opened here: https://github.com/charliermarsh/ruff-vscode/issues/174
