### ISSUE TITLE
[Question] Does this have a VSCode plugin?

### ISSUE THREAD

**Issue by dsmurrell** [charliermarsh/ruff#4019]
I currently use black + isort and I see things jump around.

I tried ruff recently but gave up because I couldn't find a suitable VSCode plugin to use it with so that it would format on save.

Maybe I'm not looking hard enough. 

Does one exist currently?

Thank you!

**Comment by CalumY** [comment]
There is one here: https://github.com/charliermarsh/ruff-vscode

**Comment by dsmurrell** [comment]
Thanks, I'll give that one a try!

**Comment by Commando-Brando** [comment]
Yes sir!

![image](https://user-images.githubusercontent.com/60548867/233665404-0638ff31-5975-4036-8adc-30761287f9b4.png)

**Comment by dsmurrell** [comment]
Thanks both! I tried this... can confirm it works :D
