### ISSUE TITLE
Support `flake8-typing-as-t`

### ISSUE THREAD

**Issue by edgarrmondragon** [charliermarsh/ruff#4034]
PyPI: https://pypi.org/project/flake8-typing-as-t/

<blockquote>
<p>This is a <code>flake8</code> plugin which ensures that imports from the <code>typing</code> library must be written using <code>import typing as t</code>.</p>

<ul>
<li><code>TYT01</code>: Bare <code>import typing</code> usage</li>
<li><code>TYT02</code>: <code>import typing as X</code> where <code>X</code> is not literal <code>t</code></li>
<li><code>TYT03</code>: <code>from typing import X</code> usage</li>
</ul>
</blockquote>

`TYT01` and `TYT02` could be covered by [`ICN001`](https://beta.ruff.rs/docs/rules/unconventional-import-alias/#aliases) if the following config is added:

```toml
[tool.ruff.flake8-import-conventions.extend-aliases]
"typing" = "t"
```

but `TYT03` is still valuable to have.

Another option is to extend `flake-import-conventions` to flag cases like

```python
from pandas import DataFrame  # Use `import as pd` and `pd.DataFrame` instead
```

**Comment by charliermarsh** [comment]
My vote would be to find a way to enable this within the import conventions plugin since it's so closely related.

**Comment by edgarrmondragon** [comment]
I've gone for a new `ICN003` rule that bans `from ... import ...` for any configured modules
