### ISSUE TITLE
ruff --fix doesn't fix anything

### ISSUE THREAD

**Issue by anentropic** [charliermarsh/ruff#4041]
```
$ ruff --version
ruff 0.0.262
```
```
$ ruff check --fix anetz
anetz/mappings.py:92:89: E501 Line too long (98 > 88 characters)
anetz/tools/evaluate.py:44:89: E501 Line too long (95 > 88 characters)
anetz/tools/evaluate.py:91:89: E501 Line too long (92 > 88 characters)
anetz/tools/evaluate.py:96:89: E501 Line too long (93 > 88 characters)
anetz/tools/evaluate.py:143:89: E501 Line too long (100 > 88 characters)
Found 5 errors.

$ ruff check --fix anetz
anetz/mappings.py:92:89: E501 Line too long (98 > 88 characters)
anetz/tools/evaluate.py:44:89: E501 Line too long (95 > 88 characters)
anetz/tools/evaluate.py:91:89: E501 Line too long (92 > 88 characters)
anetz/tools/evaluate.py:96:89: E501 Line too long (93 > 88 characters)
anetz/tools/evaluate.py:143:89: E501 Line too long (100 > 88 characters)
Found 5 errors.
```

I found the same with the VS Code plugin, it doesn't seem to do anything when you ask it to fix.

What am I doing wrong?

**Comment by dhruvmanila** [comment]
You aren't doing anything wrong. Auto-fixes aren't available for all rules. As per the analysis output, the file only contains diagnostics which aren't fixable, so nothing happens.

You can refer to the [rules documentation](https://beta.ruff.rs/docs/rules/) and check if a diagnostic code has a fix available or not. In your case there's only `E501` for which `ruff` doesn't provide a fix.

**Comment by anentropic** [comment]
ah, shame... "line too long" is the most common error and most useful one to have auto fixed

**Comment by dhruvmanila** [comment]
Usually, a formatter like `black` would take care of splitting long lines but I guess, in your case, this might be a long string which it cannot _reliably_ split and thus doesn't.

**Comment by anentropic** [comment]
ah I see, so I should still use `black` as well... I had thought this would replace it

**Comment by evanrittenhouse** [comment]
I believe we have plans to add a Ruff formatter, but it's a ways off. For now, `black` is still required.

**Comment by charliermarsh** [comment]
That's right. For now, we don't autofix line wrapping, and we do recommend using Ruff alongside Black.
