### ISSUE TITLE
ruff --fix removes import which is needed

### ISSUE THREAD

**Issue by Qumeric** [charliermarsh/ruff#4044]
I am running `ruff --fix` with the default config and it removes an import which is needed.

```
# observation_log.py
from __future__ import annotations
from dataclasses import dataclass, field
from typing import TYPE_CHECKING
from game_time import current_datetime

if TYPE_CHECKING:
    from datetime import datetime

@dataclass
class Observation:
    datetime: datetime = field(default_factory=current_datetime)
```

```
# game_time.py
from datetime import datetime, timedelta

_ticks = 0
def current_datetime() -> datetime:
    return datetime(1, 1, 1) + timedelta(minutes=_ticks)

```

Ruff removes `datetime` import. It is clearly used and also `mypy` reports it as an error `[name-defined]`.

Moving it from `TYPE_CHECKING` to the top level didn't help either.

v0.0.262

**Comment by Qumeric** [comment]
Oh, I guess that my code is problematic, I didn't notice I named my variable `datetime`, the same name as the other `datetime` I use.

However, it works fine in Python (I think) and the current behaviour is not ideal.

FWIW when I added `# noqa` to the import line, I got 
`components/observation_log.py:28:5: F811 Redefinition of unused 'datetime' from line 18`

**Comment by charliermarsh** [comment]
Ah yeah, I agree that this is a bug, though I think it's a duplicate of an old issue (https://github.com/charliermarsh/ruff/issues/1401), so I'm going to mark it as a duplicate. Let me know if that seems off.

**Comment by charliermarsh** [comment]
Funnily enough it's always `datetime` shadowing `datetime`!
