### ISSUE TITLE
Check for no side-effects during import

### ISSUE THREAD

**Issue by worldmind** [charliermarsh/ruff#4056]
Initial issue: ruff removed imports which looks unused, but they are actually needed and to be honest I also tried to remove those imports and realized they are needed only after tests starts failing.
That gave me idea, but I am not sure is it even possible to implement, if it's fully stupid question just close it.
I am wondering about check that there is no side effects during import: usually when you do import you just want to bring some names to current namespace, but in practice sometimes, in addition to that, you can get some side-effects, for example if you are using django's [receiver decorator](https://docs.djangoproject.com/en/4.2/topics/signals/) in imported file, import will also register django signal handler(s).
As for me, good practice is not having any side-effects, so, if it's possible good to have such check.

**Comment by JonathanPlasse** [comment]
Can you share a minimal reproducible example of this problem to see if we can avoid the false positive?

**Comment by dhruvmanila** [comment]
I think what the author means is for ruff to detect if a specific import is having a _side effect_ or not. The only reason the import is being done is for the side effect and is not used anywhere in the module. Ruff will mark this as unused import and thus remove it.

As far as I know that would require runtime analysis which ruff isn't capable of doing currently. The best option would be to use `noqa` for that. Another option would for ruff to resolve the import and check if there are any _patterns_ for side effects in that module but that'll quite a challenge with Python's dynamism.

**Comment by charliermarsh** [comment]
Hmm, yeah, unfortunately I think this is probably unfixable. Even if an imported module contains some runnable code, it’s hard to know whether any of that code is significant. I’d generally suggest trying to avoid side-effects on imports as much as possible, but when not possible, I’d have to recommend a noqa here.
