### ISSUE TITLE
[feature req] is ruff possible to offer auto-fix hint for auto-import?

### ISSUE THREAD

**Issue by Shane-XB-Qian** [charliermarsh/ruff#4059]
i am not very sure how ruff worked, but since pylsp-ruff based on this/ruff,
per the discussion https://github.com/python-lsp/python-lsp-ruff/issues/29 here,
would you mind consider adding a feature to make it work for auto-fix for auto-import?

**Comment by dhruvmanila** [comment]
Looking at the linked issue, do you mean to suggest that `ruff` offers a way to auto-import symbols which are missing in the current namespace / module?

Language servers do provide this ability on _selecting_ a completion item i.e., to auto-import the symbol if not present.

**Comment by Shane-XB-Qian** [comment]
yes.
make it work via code action, or TextadditionalEdit, or compl item, etc depended on lsp server preferred.
// normally i think better be auto import.
// then isort can tidy it.

but now wish ruff gave a way to Pylsp-ruff firstly to make it be possible to implement it.

--
shane.xb.qian

**Comment by charliermarsh** [comment]
Hmm, we might support this eventually, but it's a little out-of-scope right now. I recommend using Ruff alongside another LSP to provide some of those more general language server features, since Ruff's LSP right now is mostly focused on enforcing and facilitating Ruff-related rules.
