### ISSUE TITLE
Consider adding a rule to enforce positional unpacking always precede keyword arguments

### ISSUE THREAD

**Issue by NeilGirdhar** [charliermarsh/ruff#4060]
```python
def f(a, b, c):
    return a + b + c

args = 1, 2

f(c=3, *args)  # Suggest f(*args, c=3)
```
Note that the following are already syntax errors:
```python
f(**kwargs, *args)
f(c=3, 1, 2)
```

**Comment by charliermarsh** [comment]
This might be the same as B026, do you mind checking?

**Comment by NeilGirdhar** [comment]
My mistake!

**Comment by charliermarsh** [comment]
No prob! I think we used to implement this as a custom RUF rule and then eventually it was either added to bugbear or we just noticed that it already existed.
