### ISSUE TITLE
Broken refactor from UP032

### ISSUE THREAD

**Issue by ionelmc** [charliermarsh/ruff#4078]
This:
```py
a = {'foo': 'bar'}
print('{[foo]}'.format(a))
```
gets changed to:
```py
a = {'foo': 'bar'}
print(f'{a[foo]}')
```

Which obviously is invalid code. Perhaps this type of code should be skipped from UP032?

My ruff settings have `target-version = "py37"`.

**Comment by JonathanPlasse** [comment]
I would like to work on it.

**Comment by bluetech** [comment]
I was curious why the difference here. Answer is here: https://peps.python.org/pep-0498/#differences-between-f-string-and-str-format-expressions. Apparently it is the only difference between f-strings and format!

**Comment by charliermarsh** [comment]
Woah, fascinating! Thanks for sharing that, I was wondering the same thing.
