### ISSUE TITLE
commandline length limit easily reached on windows shell invocations

### ISSUE THREAD

**Issue by carpenterjc** [charliermarsh/ruff#4079]
We use bazel to invoke ruff during the build so that the exclusions are contained in the bazel build files, and invoke ruff in a batch file which writes out a file on each batch when it is linted successfully. 

What I have noticed is that we regularly reach the command line length limit which for batch files/windows shell is very low. The normal solution of this, for things like c++ compiler/linker is to provide a response file which contains a line per argument. Something like: https://crates.io/crates/argfile for rust. However I cannot see how to do this or if it needs building into ruff. 

On windows, you will see ruff can't be invoked with a relatively small number of files if they have longish paths. 
```
import subprocess
subprocess.run([
  "ruff",
  "check",
  "--no-cache",
  "--target-version",
  "py37",
  "--config",
  "pyproject.toml",
  "--quiet",] + ["abcdefghijklmnopqrstuvwxyz/abcdefghijklmnopqrstuvwxyz/abcdefghijklmnopqrstuvwxyz/abcdefghijklmnopqrstuvwxyz.py"] * 116, 
  shell=True,
  )
```

**Comment by charliermarsh** [comment]
We should be able to support this, but it does require changes within Ruff AFAICT.

**Comment by charliermarsh** [comment]
Will be available in the next release. See #4087 for an example.
