### ISSUE TITLE
E714 Complex logic handling

### ISSUE THREAD

**Issue by justinchuby** [charliermarsh/ruff#4082]
Example

```python
if not (index.start is index.stop is index.step is None):
    pass
```

raises E714

<img width="604" alt="image" src="https://user-images.githubusercontent.com/11205048/234056372-378889d2-6112-4eb7-a9f9-0c5418b1d1ef.png">

but it is not straightforward to see what the fix should be or if it is a better representation of the logic.

**Comment by JonathanPlasse** [comment]
I think it should be ignored like for the following case.
```python
if not (index.start == index.stop == index.step == None):
    pass
```
I can pick it up.
