### ISSUE TITLE
`RUF009` not covered by published documentation

### ISSUE THREAD

**Issue by jakob-keller** [charliermarsh/ruff#4088]
I am not sure which release introduced `RUF009`, but since `ruff==0.0.262` it triggers additional detections in my codebase. I believe the rule is currently undocumented, i.e. is not listed on https://beta.ruff.rs/docs/rules/#ruff-specific-rules-ruf, which makes it hard to determine whether the detections are false positives or not.

**Comment by Czaki** [comment]
I build docs locally and there is a description of rules in such docs. So it looks like a bug in the docs deployment process. Same like in #4089
