### ISSUE TITLE
`--fix-only` returns exit code 1 upon fixes

### ISSUE THREAD

**Issue by spapanik** [charliermarsh/ruff#4092]
Thank you for the great work! Ruff is fantastic, and I have replaced all my linters with it. I just have a small feature request on the fixers of it.

Now, the cli options to fix the ruff issues are: `ruff --fix .` and ` ruff --fix-only .` They are a bit problematic to work with in scripts, as even if they fix all the issues that are fixable, the exit code can be zero, if there are no fixable issues. There is the obvious workaround of adding `|| true`, but this will mask all errors, for example ruff itself panicking instead of fixing the fixable issues. A new option that would allow just run it in fix mode.

**Comment by JonathanPlasse** [comment]
Would [`--exit-non-zero-on-fix`](https://beta.ruff.rs/docs/configuration/#exit-codes) work for you?

**Comment by spapanik** [comment]
@JonathanPlasse it does exactly the opposite. I was looking for a `--exit-zero-on-fix`. Let me explain the scenario: I have two errors in my code: `I001` which is fixable, and `N801` that's not fixable. What I would like to do is run it, fix `I001` and return 0, because it successfully fixed all the fixable errors. Now, the closest is to do `ruff --fix-only . || true` but this means that if ruff breaks, I will still get an exit code 0, which is wrong.

**Comment by charliermarsh** [comment]
I assumed that if you run Ruff in that scenario with `ruff --fix-only .`, and it fixed `I001` but left `N801`, it would exit with code 0. Does it not?

**Comment by spapanik** [comment]
No, it doesn't:

```command
venv:(***)$ ~/programming/*** git:(main) ✗
stephanos@marco $ ruff --fix-only foo.py
Fixed 1 error.
venv:(***)$ ~/programming/*** git:(main) ✗
stephanos@marco $ echo $?
1
```

**Comment by charliermarsh** [comment]
Ahh ok, that strikes me as a bug, but will look into it.

**Comment by charliermarsh** [comment]
I guess, in this framing, `ruff --fix-only` would _always_ return 0 (unless the program hit an internal error), whereas `ruff --fix-only --exit-non-zero-on-fix` would return 1 when at least one error was fixed. Is that right?
