### ISSUE TITLE
Using ruff check diff suppresses errors

### ISSUE THREAD

**Issue by aminalaee** [charliermarsh/ruff#4093]
Hey, thanks for the great work.
I don't know if this is a bug or maybe unclear flag, but doing `ruff check --diff .` does not fail:

```py
try:
    pass
except:
    pass
```

But running `ruff check .` shows proper errors:

```
E722 Do not use bare `except`
```

Is this expected? I didn't expect `--diff` to have this side-effect, maybe the help is not clear?

**Comment by JonathanPlasse** [comment]
If the [help of the CLI](https://beta.ruff.rs/docs/configuration/#command-line-interface) you can find
> `--diff` Avoid writing any fixed files back; instead, output a diff for each changed file to stdout

`--diff` is to be used in conjunction with `--fix`.
Without `--fix`, it will always return nothing with exit code 0.

**Comment by aminalaee** [comment]
Thanks for the clarification, that makes more sense now.
Maybe it might be a good idea to force this combination since without one it's not really doing much.

**Comment by dhruvmanila** [comment]
I think updating the `--help` text to include this would help. Better option would be to exit with an appropriate message stating the usage of the flag (`--diff` is to be used in conjunction with `--fix` flag).

**Comment by charliermarsh** [comment]
@dhruvmanila - Agreed, would be nice if we could exit with a meaningful error there.

**Comment by odie5533** [comment]
Is there an option to output both diffs it could make as well as errors that don't have fixes? It would be useful for me to output all errors + all fixes.

**Comment by zanieb** [comment]
Hey @odie5533 that should become the default `ruff check` behavior after #7352 — it's on our roadmap!
