### ISSUE TITLE
C419 autofix can remove comment

### ISSUE THREAD

**Issue by Skylion007** [charliermarsh/ruff#4094]
We did a large change of the PyTorch codebase with ruff in https://github.com/pytorch/pytorch/pull/99890 by enabling C419 with autofixes. It mostly worked out of the box, but we did have to add back in one type comment for mypy that got deleted by the autofix: https://github.com/pytorch/pytorch/pull/99890/commits/ad98f63af41f54ebb76a817037d1fda0612e3e1a

**Comment by charliermarsh** [comment]
👍 Thanks. We preserve some comments in the comprehension fixes, but clearly not that one :)

**Comment by dhruvmanila** [comment]
I can pick this up, wanted to get into CST :)

**Comment by dhruvmanila** [comment]
Ok, so it seems like we're not copying over the `lbracket` and `rbracket` fields from the `ListComp` node. Now, this is a challenge as we need to convert it into a `GeneratorExp` which only has the `lpar` and `rpar` fields. We'll need to pick the required parts from the Bracket nodes into the Parenthesis nodes.
