### ISSUE TITLE
Question: What is the plan for plugin support?

### ISSUE THREAD

**Issue by ambroselittle** [charliermarsh/ruff#410]
Is it possible to provide backwards compat with pylint plugins, for example? 

I had written one, but I do find pylint to be very slow (not just my plugin :) ), so would be happy to migrate to faster option.

**Comment by charliermarsh** [comment]
Ruff will almost certainly support plugins. I'm not certain when, but it's very important :)

I don't expect pylint (or Flake8) plugins to work out-of-the-box; instead, there'll be a separate plugin API to implement for Ruff specifically. I'm hoping that users will be able to write plugins in Rust _or_ Python.

If your plugin is generic and/or OSS, I'm also happy to see if I can include those rules in Ruff directly, if it's helpful for you!

**Comment by ambroselittle** [comment]
Thank you. Ours is very context-specific. 

OK. Supporting Python would definitely make it more feasible for us to adopt. 👍🏻

**Comment by charliermarsh** [comment]
Closing this for now in favor of #283.
