### ISSUE TITLE
Request: autofix for EM102 with `msg`

### ISSUE THREAD

**Issue by jamesbraza** [charliermarsh/ruff#4103]
```python
some_string = "ruff"
raise ValueError(f"Hello {some_string}.")
```

Running with `ruff==0.0.263`:
```
> ruff --fixable=EM102 --fix --select=EM102 a.py
a.py:2:18: EM102 Exception must not use an f-string literal, assign to variable first
Found 1 error.
```

It would be nice if `EM102` supported autofix with `msg` like the [rule explanation](https://beta.ruff.rs/docs/rules/f-string-in-exception/) so:

```python
some_string = "ruff"
msg = f"Hello {some_string}."
raise ValueError(msg)
```

**Comment by charliermarsh** [comment]
👍 I think we should be able to support this.

**Comment by dhruvmanila** [comment]
What if the `msg` variable is already defined in same or outer scope? Should we try different variable names or maybe a config option for the user to specify the variable name? In any case, this would be a `AutofixKind::Sometimes`.

**Comment by charliermarsh** [comment]
I'd suggest just skipping the fix if `msg` is defined in the same scope or any parent scope (but not making the name configurable).

**Comment by dhruvmanila** [comment]
I would like to work on this, will get my hands dirty with the autofix API :)

**Comment by charliermarsh** [comment]
Rock on, thanks @dhruvmanila! (Know I owe you some responses in other PRs too.)
