### ISSUE TITLE
Request: `fixable = ["ALL"]`

### ISSUE THREAD

**Issue by jamesbraza** [charliermarsh/ruff#4104]
Currently per https://beta.ruff.rs/docs/configuration/#using-pyprojecttoml with `ruff==0.0.263`, to fix all, one needs to pass all codes:

```toml
# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["A", "B", "C", "D", "E", "F", "G", "I", "N", "Q", "S", "T", "W", "ANN", "ARG", "BLE", "COM", "DJ", "DTZ", "EM", "ERA", "EXE", "FBT", "ICN", "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PTH", "PYI", "RET", "RSE", "RUF", "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT"]
```

In a config, if one has `select = ["ALL"]`, it would be nice to have an accompanying `fixable = ["ALL"]`:

```toml
[tool.ruff]
fix = true
fixable = ["ALL"]
select = ["ALL"]
```

This is simpler, future compatible, and more readable.

**Comment by charliermarsh** [comment]
What you have in the example should actually work, we respect the same set of selectors between `fixable` and `select`. (Note, though, that `fixable = ["ALL"]` doesn't meant that we're able to fix _all_ rules; rather, it means that Ruff is allowed to fix all _fixable_ rules.)

If you see otherwise, happy to re-open :)

**Comment by charliermarsh** [comment]
(If you want all rules to be fixable, you should just be able to ignore `fixable` entirely, since that's the default.)

**Comment by jamesbraza** [comment]
> (If you want all rules to be fixable, you should just be able to ignore fixable entirely, since that's the default.)

Okay that's good to know!

From https://beta.ruff.rs/docs/configuration/#using-pyprojecttoml:

> By default, Ruff's autofix is aggressive

I see now what "aggressive" means, it would be good to document that "aggressive" just means autofix everything possible.
