### ISSUE TITLE
Request: `I001` respecting `[tool.isort]` in `pyproject.toml`

### ISSUE THREAD

**Issue by jamesbraza** [charliermarsh/ruff#4106]
I have a `[tool.isort]` section in a `pyproject.toml` that configures `isort` with `known_first_party` and `known_local_folder`.

I am migrating from `isort` (amongst other tools) to `ruff`.  It would be cool if `ruff` either:
- Respected `[tool.isort]` config section
- Supported a `[tool.ruff.isort]` config section

**Comment by charliermarsh** [comment]
We do support `[tool.ruff.isort]`! It supports a lot of the same configuration options -- you can see some examples here: https://beta.ruff.rs/docs/settings/#isort.

**Comment by charliermarsh** [comment]
(Closing but let me know if I'm misunderstanding your issue!)
