### ISSUE TITLE
Docs request: linking settings with rules

### ISSUE THREAD

**Issue by jamesbraza** [charliermarsh/ruff#4109]
I made https://github.com/charliermarsh/ruff/issues/4106 because I didn't know how to configure `ruff`'s internal `isort`.  I had just been looking here: https://beta.ruff.rs/docs/rules/#isort-i.

However, there's a whole `isort` config section here: https://beta.ruff.rs/docs/settings/#isort

The request: can we link the settings page in the rules page, for all tools where both pages exist?

**Comment by charliermarsh** [comment]
It would be nice to include a reference + link to the settings at the top of each rule section.
