### ISSUE TITLE
Request: `docformatter` autofixing

### ISSUE THREAD

**Issue by jamesbraza** [charliermarsh/ruff#4112]
https://github.com/charliermarsh/ruff/issues/1335 talks about adding [`docformatter`](https://github.com/PyCQA/docformatter) support.  Then it seems to get distracted by `pydocstyle` discussions and closed.

As of `ruff==0.0.263`, the `README.md` makes no mention of `docformatter` rules.

The request is to:
- Implement `docformatter` with autofixes (starting point is `docformatter --in-place`)
- Document it in the `README.md` and [docs](https://beta.ruff.rs/docs/rules/)

**Comment by charliermarsh** [comment]
Our support for `docformatter` is such that we have autofix enabled for the `pydocstyle` rules -- so, like `autoflake`, it doesn't fit cleanly into our existing documentation structures. I think I'll settle for this issue itself as the answer to the question, though open to other ways to clarify it.
