### ISSUE TITLE
[feature request] Also watch config files, like `pyproject.toml` in `--watch` mode. 

### ISSUE THREAD

**Issue by bgianfo** [charliermarsh/ruff#4126]
It would be very nice if the watch mode would also watch for changes to configuration files.

Such a feature would make iterating on enabling new rulesets a lot easier.

**Comment by mikeleppane** [comment]
Hi! Would it be okay if I take a look on this. 
Proposal: detect changes in pyproject.toml and ruff.toml config files.

**Comment by charliermarsh** [comment]
@mikeleppane - Definitely. I haven't thought too hard about what's required, but feel free to ask questions here as they come up. My guess is that, in the `match rx.recv()` loop in `crates/ruff_cli/src/lib.rs`, we can check if the file ends in `.toml`, then re-run the code to generate the `pyproject_strategy` and other variables that make it into the `commands::run::run` call.

**Comment by charliermarsh** [comment]
Oh, we added this! From @mikeleppane in https://github.com/charliermarsh/ruff/pull/4169.
