### ISSUE TITLE
Ruff fails to exclude a file, tries to parse it, and bails

### ISSUE THREAD

**Issue by flying-sheep** [charliermarsh/ruff#4134]
I have a git repository. Since it’s a cookiecutter template, it contains a directory called `{{cookiecutter.project_name}}`[sic]. I try to run Ruff on the other files in the repo like this:

```console
$ ruff "--extend-exclude=\\{\\{cookiecutter.project_name\\}\\}/**" --force-exclude -v .
[2023-04-27][17:17:32][ruff::resolver][DEBUG] Ignored path via `exclude`: "/Users/phil/Dev/cookiecutter-scverse/.git"
error: TOML parse error at line 50, column 1
   |
50 | {% if cookiecutter.project_name.lower().replace('-', '_') != cookiecutter.package_name -%}
   | ^
invalid key
```

Ruff shouldn’t try to parse that TOML file, I’m excluding it!

**Comment by charliermarsh** [comment]
Hmm yeah, that does look like a bug. I thought I'd fixed this in #3588, just confirming that you're on a recent release?

**Comment by charliermarsh** [comment]
The linked PR suggests v0.0.250 -- mind checking if something like v0.0.260 or newer resolves this?

**Comment by flying-sheep** [comment]
Huh, did use a freshly installed command line Ruff to verify (without actually checking if it was the newest version), but now I can’t reproduce it.

Apologies!
