### ISSUE TITLE
Add autofix for B027 (missing @abstractmethod decorator).

### ISSUE THREAD

**Issue by Skylion007** [charliermarsh/ruff#4163]
B027 currently does not have an autofix, but the autofix seems fairly straightforward (just add an `@abstractmethod` decorator). I would recommend someone take a look at adding the autofix here. It is also probably a good first issue.

**Comment by aacunningham** [comment]
I'm game to give this a shot, never messed with autofix logic before so should be fun

**Comment by MichaReiser** [comment]
> I'm game to give this a shot, never messed with autofix logic before so should be fun

Enjoy!

**Comment by justinchuby** [comment]
I wonder how safe this fix is, since it may lead to broken code when existing derived classes don’t implement the supposed-to-be abstract methods

**Comment by aacunningham** [comment]
That's a good point, actually dealt with that once after realizing I completely misused `abc`. Realized I had failed to fully implement the class in a few spots.

It's probably not the safest fix. Trading out one lint error for another (plus a runtime error). I know there's that effort to add safety levels to fixes, and this would probably fall into that unsafe category (or maybe some middle one). Are there any guidelines on how aggressive autofixes can be without something like that in place?

**Comment by charliermarsh** [comment]
There aren't hard-and-fast rules, but autofix safety is being worked on and the severity levels are being defined, so this may be a useful example to lean on. We could also revert this fix until safety levels are introduced.

**Comment by aacunningham** [comment]
I can revert this if it hasn't been done yet. Something like:
1. New MR to revert the change
2. Reopen this ticket and comment that we're waiting for autofix safety to get closer to done
3. Once it's ready, update the branch and start a new MR?

It looks like the change is already in a published version, but I'm assuming it's fine to still revert it?

**Comment by charliermarsh** [comment]
@aacunningham - Yeah that sounds reasonable to me -- it's ok to revert, it's not a breaking change to remove autofix capabilities.
