### ISSUE TITLE
[feature] remove unused imports

### ISSUE THREAD

**Issue by upstartjohnvandivier** [charliermarsh/ruff#4195]
currently when i run autofix on a large codebase in py 3.7, `from __future__ import annotations` gets added and Dict, List, Tuple, Union...many others are no longer used but their imports remain in many files

at a minimum, cleaning up these specific changes would be helpful, and a general remove unused import change would be even better

related iSort issue:
https://github.com/PyCQA/isort/issues/1105

**Comment by charliermarsh** [comment]
We do provide a rule for unused imports, and it can remove unused imports automatically too (F401). Does that work for your use-case?

**Comment by charliermarsh** [comment]
Closing but let me know if I've misunderstood.
