### ISSUE TITLE
F841 is raised when `case other:`

### ISSUE THREAD

**Issue by mmahmoudian** [charliermarsh/ruff#4204]
Ruff seems to be sensitive to `other` in match-case situation and throws `F841 [*] Local variable `other` is assigned to but never used`. For example consider this example

```py
def my_func(var):
    match var:
        case 'foo':
            print('blah1')
        case 'bar':
            print('blah2')
        case other:
            print('invalid blah')


my_func('boo')
```

The `case other:` is equivalent of `case _:` but more readable, and should be treated in the same way imho.

```console
❯  ruff test.py
test.py:8:14: F841 [*] Local variable `other` is assigned to but never used
Found 1 error.
[*] 1 potentially fixable with the --fix option.
```

I just installed Ruff version 0.0.261 and I have not done any Ruff specific settings 

-------
P.s: I searched smong open and closed issues, but considering that the `match`, `case`, and `other` are very common words and Github returns several pages of "matched issues", I might have missed seeing the correct issue and created a duplicate. I apologize if that is the case.

**Comment by JonathanPlasse** [comment]
Here are [codes](https://github.com/search?q=%22case+other%3A%22+language%3APython&type=code) that use the pattern `case other:`.

**Comment by mmahmoudian** [comment]
Github search engine is nauseatingly bad, so even with your well-crafted query it still bring lots of false-positive. Nonetheless, in the first page of the same search there are python codes that have indeed used `case other:`.

Thanks for the PR. I'm n00b in Rust and also not familiar with Ruff codebase, but to me it seems in your PR, only the change in `crates/ruff/src/rules/pyflakes/rules/unused_variable.rs` is related to this issue (along with the test stuff. For instance I don't quite understand how [this](https://github.com/charliermarsh/ruff/pull/4212/files#diff-c2c8422959405016e1fb54ca23edee9716bd06ad64e610ceea9612a8291122fcL4137-R4137) or [this](https://github.com/charliermarsh/ruff/pull/4212/files#diff-7c1ff8e582049ed4a051f3895b903c6032838c2e427b7044296cc53c83db10f4R257) are related. 😅 

Anyways, I'm glad that it was a quick fix, and thanks again for working on this  👍🏼

**Comment by JonathanPlasse** [comment]
This is needed otherwise an normal assignment to a variable named `other` would be a false negative.
```python
other = 1
```
The code above would not raise an error.
Only pattern should ignore `other` not other assignment kinds.

**Comment by CobaltCause** [comment]
> If it works and python does not complaint, it is correct

Why are you using a linter at all then?

**Comment by mmahmoudian** [comment]
> Why are you using a linter at all then?

Simple:
1. To help me avoid mistakes before running the code
2. To help me structure my code better

And I don't expect to get false alarm about a non-existing mistake 😊

How about you?

**Comment by Xiretza** [comment]
> The other is not a variable, it is a key word.

Is it? I'm pretty sure it's just an arbitrary name, there's nothing special about `other` compared to `foo`. Why should the linter not warn when the name happens to be `other`, but should warn when it's `foo`?

**Comment by mmahmoudian** [comment]
> it's just an arbitrary name, there's nothing special about `other` compared to `foo`

You are right. Thanks for pointing it out. I always thought it is a keyword, but literally anything there would do!!

I still think the linter should not complain, or at least it should complaint with a special dedicated code that can be suppressed by the user. That said, I think this feature request is mostly pointless and should be closed.

@Xiretza Thanks again for correcting my mistake.

**Comment by Xiretza** [comment]
> it should complaint with a special dedicated code that can be suppressed by the user.

Not sure why that would be necessary, but a good addition might be a note that `_` should be used if the result of the match is not intended to be used.

**Comment by mmahmoudian** [comment]
> Not sure why that would be necessary

Simply because the [F841](https://www.flake8rules.com/rules/F841.html) is "Local variable name is assigned to but never used" which is literally not the case here. Actually here (assuming that `other` or `foo` are variables) a variable is **not** defined but **is** used.

**Comment by Xiretza** [comment]
> Actually here (assuming that `other` or `foo` are variables) a variable is **not** defined but **is** used.

That's not how `match` works. In this case, it assigns the content of `var` to `other` unless it's `"foo"` of `"bar"`. You then never use that variable.

**Comment by charliermarsh** [comment]
My feeling is that the rule is correct as-implemented. The `match` statement is defining the `other` variable, and it takes on whatever value is being matched against (it's a "wildcard" match, IIRC). In this case, the `other` variable is being defined, but not used. If you _do_ have a fall-through case like that, I think `_` better matches the intent and Python idioms of an "intentionally unused value".

Note that, if you feel strongly about allowing `other` specifically, you can change the [`dummy-variable-rgx`](https://beta.ruff.rs/docs/settings/#dummy-variable-rgx) in your configuration file to treat `other` as a permitted-unused value.
