### ISSUE TITLE
Missing newline before import makes SIM105 produce invalid autofix

### ISSUE THREAD

**Issue by konstin** [charliermarsh/ruff#4221]
Command: `ruff --no-cache --select SIM105 --fix file.py`, ruff version 59d40f9f81056a8433db4de490857a6a23f93d2c

Input:

```python
import json


def foo():
    try:
        json.loads("data.json")
    except json.decoder.JSONDecodeError:
        pass
```

This produces:

```python
import jsonimport contextlib



def foo():
    with contextlib.suppress(json.decoder.JSONDecodeError):
        json.loads("data.json")
```

I originally found this when testing bokeh in [this file](https://github.com/bokeh/bokeh/blob/fcb4ae4836b9422e40ae511a77ac2e339ed789e0/docs/bokeh/docserver.py)

**Comment by dhruvmanila** [comment]
Duplicate of #4203

**Comment by konstin** [comment]
thanks
