### ISSUE TITLE
Skip __debuggerskip__ variable

### ISSUE THREAD

**Issue by propertone** [charliermarsh/ruff#4228]
[IPython 7.29](https://ipython.readthedocs.io/en/7.31.0/whatsnew/version7.html#ipython-7-29) added a feature to support a `__debuggerskip__` variable which give Pdb the ability to skip code in decorators. Similar to `__tracebackhide__`, can ruff be updated to allow the use of `__debuggerskip__` as an unused variable by default for rule F841? These are white listed [here](https://github.com/charliermarsh/ruff/blob/b71cc3789fbb91ede0fcbe2d09479feb82558d84/crates/ruff/src/rules/pyflakes/rules/unused_variable.rs#L327).

**Comment by charliermarsh** [comment]
Sure thing, easy enough.

**Comment by propertone** [comment]
Thanks for the quick fix!
