### ISSUE TITLE
Implement `ruff config-convert` to generate `pyproject.toml` from Flake8 configs

### ISSUE THREAD

**Issue by charliermarsh** [charliermarsh/ruff#423]
See: #414.

**Comment by charliermarsh** [comment]
@fsouza - FYI, I'm working on this now.

**Comment by charliermarsh** [comment]
This now exists as [`flake8-to-ruff`](https://pypi.org/project/flake8-to-ruff/). Anyone willing to test it out and give feedback? Maybe @fsouza?

**Comment by fsouza** [comment]
> This now exists as [`flake8-to-ruff`](https://pypi.org/project/flake8-to-ruff/). Anyone willing to test it out and give feedback? Maybe @fsouza?

I'll give it a try!

**Comment by fsouza** [comment]
I left a comment in #527, it seems to be working, just failed with one setting (`max-line-length`).

**Comment by charliermarsh** [comment]
Fixed in https://github.com/charliermarsh/ruff/pull/541.
