### ISSUE TITLE
Cascading per-file-ignores

### ISSUE THREAD

**Issue by nstarman** [charliermarsh/ruff#4230]
In Astropy, for various reasons we want to separate our ruff config into `pyproject.toml`, where the "official" ruff config lives, and `.ruff.toml`, where we have our `ignore` list of things we intend to fix.
In the `.ruff.toml` we want to use `extend = "pyproject.toml"` to make this all work.
However, we've found that `per-file-ignores` don't seem to cascade, so only the config in `.ruff.toml` gets picked up.
I believe this is a bug, or I just haven't implemented `extend` correctly 😆.

**Comment by charliermarsh** [comment]
Two quick questions: Do you have different `per-file-ignores` defined in both, or only in the "parent" configuration? And are the configuration files in the same directory?

**Comment by nstarman** [comment]
We have it defined in both. In `pyproject.toml` are the permanent settings and in `.ruff.toml` we have the temporary settings related to the incremental nature of fixing an `ignore`. And yes, both config files are at the same directory level.

**Comment by charliermarsh** [comment]
Ah okay, yeah we don't currently "merge" properties across configuration files, with the exception of the `extend-*` properties, like `extend-ignore`. So this is working as intended, though it'd be reasonable to suggest that it should be changed.

**Comment by nstarman** [comment]
Ah, thanks for the clarification! Yes, some type of per-file-ignore merge would be excellent and very helpful to us!

**Comment by aacunningham** [comment]
So would the idea be to create a new `extend-per-file-ignores` so that `per-file-ignore` still behaves as expected (like the rest of the non-merging settings)? Or maybe `per-file-ignores` makes sense to merge?

Out of curiosity, what's the benefit of the separate files as opposed to leaving it all in the `pyproject.toml` with a comment to differentiate the two sections of the `per-file-ignores` table (like `#Temporary ignores`)?

**Comment by nstarman** [comment]
Either means is fine with us!
Separate files is useful for us ATM because of GH Codeowner auto PR review request settings while we work through the TODOs.

**Comment by aacunningham** [comment]
Aight ya gotcha. Well I think implementing this seems pretty straightforward, I'd be down to give it a whirl. Making it cascade in the same way some of the other rules do makes sense, unless someone more knowledgeable of the project's has other ideas on this.
