### ISSUE TITLE
Docs error: isort `section-order` default

### ISSUE THREAD

**Issue by Secrus** [charliermarsh/ruff#4231]
The [docs](https://beta.ruff.rs/docs/settings/#section-order) for `isort` `section-order` setting, list default value as `[]`. From my testing and [code spelunking](https://github.com/charliermarsh/ruff/blob/64b7280eb824d0e5f9da887e82dcda53838dd38d/crates/ruff/src/rules/isort/settings.rs#LL343C83-L343C83), it seems, that the default value is actually not empty, but the same as the order of sections in the enum that represent this.

**Comment by charliermarsh** [comment]
Yeah, I think you're right.
