### ISSUE TITLE
Implement flake8-async

### ISSUE THREAD

**Issue by dacevedo12** [charliermarsh/ruff#4246]
https://github.com/cooperlees/flake8-async

It'd be good to implement (and hopefully extend) the concept of this project in enforcing best practices for asyncio usage.

**Comment by charliermarsh** [comment]
Looks pretty straightforward for anyone that's interested in learning to write rules for Ruff.

**Comment by inikolaev** [comment]
I want to give it a try - have a working prototype already and will push shortly.

**Comment by qdegraaf** [comment]
> I want to give it a try - have a working prototype already and will push shortly.

Missed this. Had some chats about working on this the last few days in the Discord but did not mention it here. Just opened PR, but as a first time contributor I might not have come up with the most elegant solution. Happy to close for your solution if it's better, or merge the two or something else along those lines.

**Comment by qdegraaf** [comment]
Yeah I could have been more clear as well 😅 . Going to leave it to @charliermarsh to decide what's to happen for this one and be a bit more transparent on the next one.

**Comment by dacevedo12** [comment]
Please keep in mind the original one has a bug.

time.sleep -> triggers rule
from time import sleep -> doesnt

It also lacks validations for async defs that dont use await inside them.

Just pointing this out if the PRs port the code exactly as it is on that project to avoid the same mistakes

**Comment by dacevedo12** [comment]
Thanks for the contributions. I'd like to complement those myself but my skills in rust are currently lacking

**Comment by qdegraaf** [comment]
> Please keep in mind the original one has a bug.
> 
> time.sleep -> triggers rule from time import sleep -> doesnt
> 
> It also lacks validations for async defs that dont use await inside them.
> 
> Just pointing this out if the PRs port the code exactly as it is on that project to avoid the same mistakes

Good catch., cheers! I'll mark mine as draft with some TODOs, but will hold off on implementing them in case https://github.com/charliermarsh/ruff/pull/4433 covers that already, in which case I can close mine.

**Comment by charliermarsh** [comment]
I'm going to move forward with reviewing #4432 since it strikes me as a bit more complete (uses scoping logic to detect the async function context, includes documentation for the rules). I'm sorry @inikolaev, I know it's disappointing to put in work on a PR and not see it merged into the codebase, but we now have two similar PRs for the same scope of the work and so I have to choose between them somehow.

If you're interested in contributing, I'd love to help you find something else to work on (e.g., I'd love to finish the `flake8-pyi` rules from https://github.com/charliermarsh/ruff/issues/848), but I totally understand if you'd rather not.

**Comment by inikolaev** [comment]
> I'm going to move forward with reviewing #4432 since it strikes me as a bit more complete (uses scoping logic to detect the async function context, includes documentation for the rules). I'm sorry @inikolaev, I know it's disappointing to put in work on a PR and not see it merged into the codebase, but we now have two similar PRs for the same scope of the work and so I have to choose between them somehow.
> 
> If you're interested in contributing, I'd love to help you find something else to work on (e.g., I'd love to finish the `flake8-pyi` rules from #848), but I totally understand if you'd rather not.

No worries, I will look for something else to implement 👍
