### ISSUE TITLE
I suggest that ruff should update the code for detecting ambiguous unicode characters with following VSCode's code.

### ISSUE THREAD

**Issue by yuji38kwmt** [charliermarsh/ruff#4268]
# Python code

`sample.py`

```python
# HIRAGANA LETTER
"""
あいうえお
かきくけこ
さしすせそ
たちつてと
なにぬねの
はひふへほ
まみむめも
やゆよ
らりるれろ
わゐゑを
ん
"""

# KATAKANA LETTER
"""
アイウエオ
カキクケコ
サシスセソ
タチツテト
ナニヌネノ
ハヒフヘホ
マミムメモ
ヤユヨ
ラリルレロ
ワヰヱヲ
ン
"""

```

# Command

```
$ ruff check sample.py --select RUF
sample.py:22:5: RUF001 [*] String contains ambiguous unicode character `ノ` (did you mean `/`?)
Found 1 error.
[*] 1 potentially fixable with the --fix option.
```

# Issue
The above python code contains all HIRAGANA and KATAKANA LETTERS, but Ruff only identifies ノ ([Katakana Letter No](https://www.compart.com/en/unicode/U+30CE)) as an ambiguous unicode character.

Ruff's code for detecting ambiguous Unicode characters was ported from [VSCode's code](https://github.com/microsoft/vscode/blob/095ddabc52b82498ee7f718a34f9dd11d59099a8/src/vs/base/common/strings.ts#L1195), but this code was modified in 2021. In March 2023, [VSCode fixed the code](https://github.com/microsoft/vscode/pull/175918). Therefore, I suggest that Ruff should update its code for detecting ambiguous Unicode characters.

# Settings
no pyproject.toml

# Version

```
$ ruff --version
ruff 0.0.264

```

**Comment by charliermarsh** [comment]
Nice, we'll pull in this update, thanks.
