### ISSUE TITLE
[Autofix error] My File: pandas\tests\groupby\test_apply.py

### ISSUE THREAD

**Issue by FishAlchemist** [charliermarsh/ruff#4277]
## Version(ruff --version)
**ruff 0.0.265**
## Command(Powershell)
```powershell
 ruff check --select=ALL  .\test_apply.py
```
**If you add --isolated , there will be no problem about Autofix error**
## Terminal Content
```powershell
warning: `one-blank-line-before-class` (D203) and `no-blank-line-before-class` (D211) are incompatible. Ignoring `one-blank-line-before-class`.
warning: `multi-line-summary-first-line` (D212) and `multi-line-summary-second-line` (D213) are incompatible. Ignoring `multi-line-summary-second-line`.

error: Autofix introduced a syntax error. Reverting all changes.

This indicates a bug in `ruff`. If you could open an issue at:

    https://github.com/charliermarsh/ruff/issues/new?title=%5BAutofix%20error%5D

...quoting the contents of `test_apply.py`, along with the `pyproject.toml` settings and executed command, we'd be very appreciative!

test_apply.py:1:1: D100 Missing docstring in public module
test_apply.py:1:1: I001 Import block is un-sorted or un-formatted
test_apply.py:22:5: ANN201 Missing return type annotation for public function `test_apply_issues`
test_apply.py:22:5: D103 Missing docstring in public function
test_apply.py:38:5: PD901 `df` is a bad variable name. Be kinder to your future self.
.....(Hide more)
```
[full_terminal_content.txt](https://github.com/charliermarsh/ruff/files/11420281/full_terminal_content.txt)
### Command(Powershell): --isolated
```powershell
ruff check --select=ALL --isolated .\test_apply.py
```
[full_terminal_content_isolated.txt](https://github.com/charliermarsh/ruff/files/11420301/full_terminal_content_isolated.txt)
## Python Code
**Please change the file extension from txt to py**
[test_apply.txt](https://github.com/charliermarsh/ruff/files/11420307/test_apply.txt)
## pyproject.toml
**Please change the file extension from txt to toml**
[pyproject.txt](https://github.com/charliermarsh/ruff/files/11420318/pyproject.txt)

**Comment by charliermarsh** [comment]
We definitely have guards against this somewhere else (to avoid fixes that convert expressions-to-statements when within an expression)... Maybe the rule that converts lambdas to function definitions, in Pyflakes?

**Comment by dhruvmanila** [comment]
My first thought was to _just_ remove the `inplace = True` and _not_ add the assignment when inside a `lambda` scope. The reason being that when `inplace` is `True` the function will return `None`, while in the other case it'll return a new object. As `lambda` expressions return whatever they evaluate, I thought the above solution would make sense.

Do we want to continue with that or just avoid to fix?
