### ISSUE TITLE
Request: `SIM105` autofix including (and not removing) inline comments

### ISSUE THREAD

**Issue by jamesbraza** [charliermarsh/ruff#4318]
Please see the below code snippet:

```python
try:
    _ = 0
except KeyError:
    pass  # Some reason for the suppression
```

With `ruff==0.0.265`, and running `ruff --fixable=SIM105 --select=SIM105 --fix a.py`, this is autofixed to:

```python
import contextlib
with contextlib.suppress(KeyError):
    _ = 0
  # Some reason for the suppression
```

The autofix is great, but the explanatory comment isn't moved too, so the comment now becomes misplaced.

I think it is desirable for the autofix to move the comment as well, like so:

```python
import contextlib
with contextlib.suppress(KeyError):
    # Some reason for the suppression
    _ = 0

# or

import contextlib
with contextlib.suppress(KeyError):  # Some reason for the suppression
    _ = 0
```

Thank you for your consideration!

**Comment by jamesbraza** [comment]
Similarly, please see this snippet:

```python
try:
    _ = 0
except KeyError:  # Some reason for the suppression
    pass
```

`ruff --fixable=SIM105 --select=SIM105 --fix a.py,` autofixes to the below, which actually removes the explanatory comment entirely:

```python
import contextlib
with contextlib.suppress(KeyError):
    _ = 0
```

I think it's not desirable for an autofix to remove inline comments.  Thanks again!

**Comment by charliermarsh** [comment]
It's difficult to retain comments in these cases, since it's not always clear what the comment is meant to be attached to. In general, we often avoid fixes if the fix would result in a lost comment, so perhaps we should extend that logic to this rule.
