### ISSUE TITLE
Editor integration: `ruff --fix -` may destroy file contents when an update is available

### ISSUE THREAD

**Issue by fsouza** [charliermarsh/ruff#432]
Use case: when formatting with the text editor, I send the file contents as stdin and replace the file contents with the stdout of `ruff`, but that output ends-up being the message about an update being available.

I just ran into it, I can't send a PR right now, but may be able to do it tomorrow night or Sunday. Reporting it just in case someone wants to work on it first :)

**Comment by charliermarsh** [comment]
Oh hah, I can fix this :)

**Comment by fsouza** [comment]
Weird that I'm still seeing this issue (on ruff 0.0.79, I was offered an upgrade to 0.0.80 in the stdout). For now I'm setting `--quiet` in the editor config, but I'll also try to investigate to get more details.

**Comment by fsouza** [comment]
Nevermind, this was a different issue 😁
