### ISSUE TITLE
Suggestion to use bare `raise` instead of `raise exc`

### ISSUE THREAD

**Issue by madkinsz** [charliermarsh/ruff#4333]
I've been championing the use of `raise` instead of `raise exc` when re-raising a captured exception as it removes a frame from the traceback. When many exceptions are chained, this can make a significant difference in the length of a traceback.

WRONG: Extra frame included in traceback
```
try:
    raise ValueError("1")
except Exception as exc:
    raise exc
```
```
Traceback (most recent call last):
  File "/Users/mz/dev/prefect/example.py", line 4, in <module>
    raise exc
  File "/Users/mz/dev/prefect/example.py", line 2, in <module>
    raise ValueError("1")
ValueError: 1
```

RIGHT: No frame added when the exception is re-raised
```python
try:
    raise ValueError("1")
except Exception:
    raise
```
```
Traceback (most recent call last):
  File "/Users/mz/dev/prefect/example.py", line 2, in <module>
    raise ValueError("1")
ValueError: 1
```

I don't think this is covered by any existing linters. I checked `flake8` and `pylint`.

**Comment by tjkuson** [comment]
As I understand it, this is covered by [tryceratops](https://github.com/guilatrova/tryceratops) and is implemented in ruff as [`TRY201`](https://beta.ruff.rs/docs/rules/verbose-raise/).

**Comment by charliermarsh** [comment]
Thanks for the clear issue :) My read is that this is covered by `TRY201` as @tjkuson mentioned -- but just LMK if I'm misunderstanding.

**Comment by madkinsz** [comment]
Cool! I'm interested in adding explanation there as they call it "redundant" but it has an actual runtime effect.

What kind of criteria is there for a rule being included by default?

I've noticed this is also not an auto-fixable issue but it seems like it could be

```
example.py:4:11: TRY201 Use `raise` without specifying exception name
Found 1 error.
```

**Comment by tylerlaprade** [comment]
Hi @zanieb and @charliermarsh, I would also enjoy seeing this rule become auto-fixable.
