### ISSUE TITLE
Possibility to port darglint to ruff?

### ISSUE THREAD

**Issue by jsh9** [charliermarsh/ruff#4362]
Hi, would it be possible to port [darglint](https://github.com/terrencepreilly/darglint) to ruff?

Darglint differs from pydocstyle in that it actually check the arguments in the docstring against the ground truth (the arg list in the function signature).

Darglint is effective, but it runs quite slow.

Thank you!

**Comment by charliermarsh** [comment]
We plan to do this. We haven't started on it yet but it's within scope. Closing in favor of #458 :)

**Comment by jsh9** [comment]
Thanks!  Great to hear.
