### ISSUE TITLE
Support error selection via prefix codes

### ISSUE THREAD

**Issue by charliermarsh** [charliermarsh/ruff#438]
E.g., you should be able to `--select D` to enable all of the `pydocstyle` rules.

**Comment by matteosantama** [comment]
My concern with this is that `numpy` and `google` convention are surely the most common `pydocstyle` settings, and I'm not sure if `--select D` would make using those two any easier.

For example, to turn on `convention=numpy`, would you do `--select D --exclude ...` and list out all the codes you don't want? But then you start running into precedence issues, ie. should `select` or `exclude` take precedence?

**Comment by charliermarsh** [comment]
Alternatively, we could support a `--docstring-convention=...` setting that effectively adds the right codes to `--select`? Also interesting could be something more general that looks more like ESLint's system of "configs" (where each "config" turns on a set of error codes).

> But then you start running into precedence issues, ie. should `select` or `exclude` take precedence?

(Yeah, the point totally stands but FWIW we've already defined this such that `--ignore` takes precedence over `--select`.)

**Comment by charliermarsh** [comment]
Oh, I'm actually going to close this as a duplicate of #325. That's my bad. We can continue discussion in there.
