### ISSUE TITLE
PLW3301: incorrect autofix when using generator expression

### ISSUE THREAD

**Issue by oefe** [charliermarsh/ruff#4410]
The autofix for `PLW3301` generates incorrect code if the nested call is using a generator expression.

## Example

PLW3301.py:
```python
x = max(1, max(i for i in range(10)))
```

## Observed 
```
ruff --isolated --diff --select PLW3301  PLW3301.py
--- PLW3301.py
+++ PLW3301.py
@@ -1 +1 @@
-x = max(1, max(i for i in range(10)))
+x = max(1, (i for i in range(10)))

Would fix 1 error.
```

## Issue

This is incorrect. `max` [takes either an iterable, or a variable number of arguments, but not both](https://docs.python.org/3/library/functions.html#max):
```
python -c "max(1, (i for i in range(10)))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: '>' not supported between instances of 'generator' and 'int'
```                                        

## Expected

The correct fix would be:
```
max(1, *(i for i in range(10)))
```

## Ruff Version

```
ruff --version
ruff 0.0.267
```

**Comment by JonathanPlasse** [comment]
I can work on it.

**Comment by charliermarsh** [comment]
We may just want to avoid including `max` calls with a single argument altogether, since max seems to assume that the single argument is iterable.
