### ISSUE TITLE
[Autofix error] SyntaxError from RUF010

### ISSUE THREAD

**Issue by janosh** [charliermarsh/ruff#4414]
Applying `ruff --fix` (v0.0.267) to [this line](https://github.com/materialsproject/pymatgen/blob/8fded9b450fb1952d3d915adebff2e551d69c360/pymatgen/io/packmol.py#L217)

```py
file_contents += f"  number {str(d['number'])}\n"
```

causes

> error: Autofix introduced a syntax error. Reverting all changes.

The attempted fix is

> pymatgen/io/packmol.py:217:42: RUF010 Use conversion in f-string

Workaround is to manually change to

```py
file_contents += f"  number {d['number']!s}\n"
```

**Comment by JonathanPlasse** [comment]
I can work on this.
