### ISSUE TITLE
Add autocompletion for xonsh

### ISSUE THREAD

**Issue by rpdelaney** [charliermarsh/ruff#4416]
[xonsh](https://xon.sh/) is a python-powered shell. It would be nice to have autocompletion for xonsh too!

If you would accept a PR please let me know. :-)

**Comment by charliermarsh** [comment]
Hi! We need this to be supported in Clap in order to resolve, so I'm going to close in favor of that upstream issue: https://github.com/clap-rs/clap/issues/4693
