### ISSUE TITLE
[Infinite loop] D403 Docstring not starting with a letter

### ISSUE THREAD

**Issue by Nodd** [charliermarsh/ruff#4455]
D403 should check that the first character of a docstring is a letter :
```
D403 First word of the first line should be capitalized: `'ele'` -> `'ele'`
```

**Comment by charliermarsh** [comment]
Can you include your Ruff version? Thought we fixed this in a recent release.

**Comment by charliermarsh** [comment]
No worries, if it pops up again feel free to re-open.
