### ISSUE TITLE
target-version refers version from .python-version file

### ISSUE THREAD

**Issue by jay0129** [charliermarsh/ruff#4464]
.python-version

My pyproject.toml look like this:
```
[tool.ruff]
# https://github.com/charliermarsh/ruff/blob/main/docs/configuration.md

line-length = 119

# Python 3.9.9
target-version = "py39"
```
My .python-version looks like this:
`3.9.9`

Is there a way for the file `pyproject.toml`  to refer version from `.python-version` ?

**Comment by JonathanPlasse** [comment]
Currently, no.
It could be detected by `flake-to-ruff` for conversion from old settings but it is not standard so it should not use `.python-version` if `target-version` is not specified.
If you use `projet.require-python`, it will use it.
Black `line-length` is only use during conversion and not when using `ruff` directly as it is not standard as well.
