### ISSUE TITLE
Ruff --fix on COM812 introducing TypeError

### ISSUE THREAD

**Issue by fennerm** [charliermarsh/ruff#4480]
I think I'm seeing some buggy behavior with the COM812 rule (running ruff v0.0.267).

Minimal example:
```
from collections import namedtuple

foo = namedtuple(
    name="foo",
    status="bar",
    message="sfdsdfsdgs fsdfsdf output!dsfdfsdjkg  ghfskdjghkdssd sd fsdf  s\n"[
        :20
    ],
)
```
Ruff returns error: `7:13: COM812 [*] Trailing comma missing`. `ruff --fix` inserts a comma after `:20` which is a TypeError.

**Comment by charliermarsh** [comment]
Thanks for reporting!
