### ISSUE TITLE
Ruff --add-noqa placed incorrectly for multi-line strings

### ISSUE THREAD

**Issue by fennerm** [charliermarsh/ruff#4483]
(ruff=v0.0.267).

Minimal example:
```
weirdly_Cased: str = """
Some long
string.
"""
```

When running `ruff --add-noqa` it inserts the noqa annotation into the string itself
```
weirdly_Cased: str = """  # noqa: N816
Some long
string.
"""
```

Thanks!

**Comment by charliermarsh** [comment]
(Gonna close in favor of #4483 since these are roughly the same issue.)
