### ISSUE TITLE
Ruff picks wrong scope for variable

### ISSUE THREAD

**Issue by notatallshaw** [charliermarsh/ruff#4486]
Specifically, Ruff incorrectly identifies the scope a variable is chosen from when it's inside a comprehension inside a class inside a function and a variable with the same name exists inside the class scope.

Here is shortest code to reproduce this example, I named it `scopetest.py`:

```python
def f():
    b = 'Function Scope'
    class C:
        b = 'Class Scope'
        d = [b for _ in range(1)]
    return C

print(f().d[0])  # Prints "Function Scope"
```

Running Ruff:

```bash
> ruff --version
ruff 0.0.267
> ruff scopetest.py
scopetest.py:2:5: F841 [*] Local variable `b` is assigned to but never used
Found 1 error.
```

If I run `ruff` with `--fix` it deletes the line that b is sourced from causing the code to now throw an exception.

The reason b is scoping from the function scope and not the class scope is that generators / comprehensions implicitly create an anonymous function and source their scope from locals, non-locals, globals, and builtins and skip the class scope as all other functions do.

I came across this testing different versions of code [posted here](https://discuss.python.org/t/pep-709-one-behavior-change-that-was-missed-in-the-pep/26691) where the Steering Council has decided to keep the behavior as-is for at least Python 3.12.

**Comment by charliermarsh** [comment]
Interesting, thank you for filing.

**Comment by charliermarsh** [comment]
Do you understand why this runs without error?

```py
class A:
    T = range(10)

    Z = (x for x in T)
    L = [x for x in T]
    B = dict((i, str(i)) for i in T)
```

**Comment by charliermarsh** [comment]
Ah, so this scoping only applies to the generator body, and not the iterable.

**Comment by notatallshaw** [comment]
> Ah, so this scoping only applies to the generator body, and not the iterable.

Yes, your example initially threw me off, but I think in this case the iterable can be thought of like a function definition, it's scope is in the outer area and the body is like a function body.

**Comment by charliermarsh** [comment]
Here's another interesting wrinkle -- this does _not_ work:

```py
class A:
    T = range(10)

    L = [x for x in T for y in T]
 ```

I noticed this via the comment in Carl Meyer's [finder tool](https://github.com/carljm/compfinder/blob/8dabc1d256431b1b2bd4c578a28d38f4ccad0ea0/finder.py#L207).

**Comment by charliermarsh** [comment]
So it's only the first generator (?) that's evaluated in the parent scope.

**Comment by charliermarsh** [comment]
Thank you, that's a really helpful model.
