### ISSUE TITLE
[Autofix error] RUF010 autofix fails when the expression is in parentheses, e.g. `f"{(str(a))}"`

### ISSUE THREAD

**Issue by konstin** [charliermarsh/ruff#4520]
RUF010 creates an invalid autofix when the expression is already in parentheses, e.g.
```python
f"{(str(a))}"
```
is replaced by 
```python
f"{(a!s)}"
```
which is invalid syntax.

Command:

```
ruff --no-cache --select RUF010 --fix code.py
```

ruff version fd16d658e9407ce76bc38cd8f5112dd272fc5be0

**Comment by JonathanPlasse** [comment]
This version of `RUF010` using `libcst` should not have this problem.
[`ec263ce` (#4423)](https://github.com/charliermarsh/ruff/pull/4423/commits/ec263ceeb2e0800a22739f62b79e39defb56828d)
