### ISSUE TITLE
[Autofix error] UP036 autofix fails on complex nested block

### ISSUE THREAD

**Issue by konstin** [charliermarsh/ruff#4522]
UP036 transforms the following 

```python
import sys

if sys.version_info < (3, 8):

    def a():
        if b:
            print(1)
        elif c:
            print(2)
        return None

else:
    pass
```

to 

```python
import sys

if c:
            print(2)
        return None

else:
    pass
```

which is invalid syntax and also removed ~~a lot of~~ the code incompletely.

Command:

```
ruff --no-cache --select UP036 --fix code.py 
```

ruff version fd16d658e9407ce76bc38cd8f5112dd272fc5be0

**Comment by charliermarsh** [comment]
Removing code is intended (it's removing the outdated version check based on the currently-specified minimum version), but the output is clearly wrong.

**Comment by JonathanPlasse** [comment]
I would like to work on this.

**Comment by charliermarsh** [comment]
Thanks @JonathanPlasse.
