### ISSUE TITLE
`FLY` flagged as missing in TOML `select` schema

### ISSUE THREAD

**Issue by janosh** [charliermarsh/ruff#4529]
`FLY` appears to be missing from the TOML `select` schema.

https://beta.ruff.rs/docs/rules/#flynt-fly

Red squiggly line powered by https://github.com/tamasfe/taplo ([VS Code marketplace](https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml))

![Screenshot 2023-05-19 at 06 41 13](https://github.com/charliermarsh/ruff/assets/30958850/66764947-885f-4b5a-bd4c-8ed1ba8c507a)

**Comment by konstin** [comment]
will do
