### ISSUE TITLE
`code_gen.rs` should take into account existing code preferences

### ISSUE THREAD

**Issue by charliermarsh** [charliermarsh/ruff#454]
It'd be great to generate code that's aware of existing indentation and quotation preferences.

**Comment by leos** [comment]
I just ran into this as well with `E712` on the following example code:
```python
image = {"primary": 23}

if image["primary"] == True:
  print("hello!")
```
Running `ruff` 0.0.196 on this results in:
```python
image = {"primary": 23}

if image['primary'] is True:
  print("hello!")
```

If the intent is to have `ruff` work with `Black` out of the box then it should default to double quotes - although obviously it would be nice to detect the quoting style before the fix as well.

**Comment by charliermarsh** [comment]
Yeah agreed. It actually used to double-quote, but it required forking RustPython. I’ll look into it again and see if we can at least preserve double quotes, since it’d go a long way towards compatibility.

**Comment by charliermarsh** [comment]
(Also: thank you for the clear example + version number etc.)

**Comment by charliermarsh** [comment]
I'm gonna ship some improvements to this today.
