### ISSUE TITLE
Split `ruff` into multiple subcommands

### ISSUE THREAD

**Issue by charliermarsh** [charliermarsh/ruff#455]
We could already support `ruff format` or `ruff fmt` or `ruff rtrip` (in Astor parlance). Soon there will be more tools and sub-commands, e.g., #423.

A few open questions:

- Do we want to move the core linting functionality to `ruff check`? Or leave it as a "default" sub-command? (I think the latter can cause a variety of ambiguities but it'd be nice to do something backwards compatible here.)
- Do we want to expose a dedicated `ruff fix` command in lieu of or in addition to `--fix`? Perhaps `ruff fix` applies fixes recursively.

**Comment by thejcannon** [comment]
Taking this a smidge further: one distinction I introduced to [Pants](https://github.com/pantsbuild/pants) is the distinction between `fmt` and `fix`. The former is safe to do on save, the latter isn't. The razor is something like removing imports. Not safe to do on save (as I'm still typing code and I save very often) but is safe to do in `fix`, which I'll issue manually.

We also have `fix` imply `fmt`, so users could decide which behavior they care about.

**Comment by not-my-profile** [comment]
@thejcannon Thanks, that's a very interesting idea! I think the relevant issue is *rule applicability* (#1997).
