### ISSUE TITLE
Sphinx and D409

### ISSUE THREAD

**Issue by Nodd** [charliermarsh/ruff#4555]
I have this nice code, which passes fine with ruff:
```python
def foo(a):
    """Summary

    Args:
    ----
    a: list
        parameter a
    """
```

The problem is that Sphinx will throw a warning when building the documentation:

```
***/lib/python3.11/site-packages/numpydoc/docscrape.py:460: UserWarning: potentially wrong underline length... 
Args: 
---- in 
***
... in the docstring of foo in ***.
  warn(msg)
```

Sphinx condiders that the comma is part of the title, so wants this:
```python
def foo(a):
    """Summary

    Args:
    -----
    a: list
        parameter a
    """
```
but ruff is now unhappy with D409. I think that in this case ruff is wrong and Sphinx is right, the whole title should be underlined, including the colon.

Note that if I remove the colon, ruff triggers D416, so it's not a workaround.

This is with ruff 0.0.265.

**Comment by charliermarsh** [comment]
Interesting... We have the same behavior as pydocstyle -- do you know if this has ever been reported or discussed in pydocstyle?

**Comment by Nodd** [comment]
I couldn't find it. I'll double-check the different docstring styles, it seems that when using `Args:` the title shouldn't be underlined at all.

**Comment by charliermarsh** [comment]
What I'm seeing is that the NumPy standard actually wants you to omit the `:`, not increase the length of the underline. That's what I see in all the official examples.

**Comment by Nodd** [comment]
D409 and D416 correspond to different docstring styles : https://github.com/PyCQA/pydocstyle/blob/master/docs/error_codes.rst. From this link: D416 is incompatible with `numpy` style, while D409 is incompatible with `google` style. I'll have to choose one or the other.
