### ISSUE TITLE
Add pre commit hook

### ISSUE THREAD

**Issue by lusmoura** [charliermarsh/ruff#459]
In order to use Ruff as a hook in other projects, the repo needs to contain a pre-commit-hooks.yaml file configuring the new hook.

Documentation [here](https://pre-commit.com/#new-hooks)

**Comment by lusmoura** [comment]
@jack1142 thank you!

**Comment by charliermarsh** [comment]
@lusmoura - if you have any issues using the pre-commit hook, don’t hesitate to ask!
