### ISSUE TITLE
Blanket opt-in to nursery rules possible?

### ISSUE THREAD

**Issue by ThiefMaster** [charliermarsh/ruff#4601]
When converting my [flake8 config](https://raw.githubusercontent.com/indico/indico/master/.flake8) using `flake8-to-ruff`, I got some warnings about unsupported options, one of them being `E265`. But it turned out that these rules are in fact supported, just considered "beta" quality and thus in nursery (if i understood its purpose correctly).

Having an existing project where flake8 passes with no warnings, I obviously do not want to lose functionality. On the other hand, I'd be perfectly fine with the occasional false positive due to a bug in a nursery rule.

I DO NOT want to manually build a list of all flake8 rules and list them explicitly in the config file. This would be ugly and cumbersome to maintain.

Something like this would be great:

- `enable_nursery = true` setting which simply enables all nursery rules as long as their category (e.g. `E`) is selected.
- something like `select = ['E!']` with the `!` enabling nursery rules for that category. Probably more work to implement but also more flexible.

**Comment by charliermarsh** [comment]
I totally understand why the current nursery setup is inconvenient but I think I'd rather focus on elevating rules out of the nursery category rather than improving support for enabling nursery rules.

**Comment by ThiefMaster** [comment]
Wouldn't such a setting help with this though?

People are lazy, and they often don't even install prereleases of libraries to test against them - but having to opt into into many rules individually just means that there are even fewer people testing them, making it more likely that bugs only show up later when they leave nursery, kind of defeating its purpose!

**Comment by charliermarsh** [comment]
Yeah, some kind of nursery flag would help! I would support its existence, probably. I'm just conveying the sentiment that every ask has to be prioritized given infinite scope and limited time, so I'm unlikely to work on this myself.

**Comment by charliermarsh** [comment]
@ThiefMaster - Thank you so much for asking :) Honestly part of the reason I'm hesitant is that it's not trivial to do, and I'm not actually sure how we would implement it. The "rule selector" stuff is very macro heavy and can be difficult to reason about (we want to change this), plus it also tends to require that all the various rule selectors are defined at compile time and not at runtime.

(Defining all this stuff at compile time does have some benefits, e.g., we accept `--select E265` on the CLI, via autocomplete, and in the JSON schema, but not `--select E26`.)

**Comment by charliermarsh** [comment]
We added a `NURSERY` selector in #4852, so you can do `--select NURSERY` or add it to your pyproject.toml's `select` field.
