### ISSUE TITLE
Investigate performance regression for 100,000s of violations

### ISSUE THREAD

**Issue by charliermarsh** [charliermarsh/ruff#4606]
As of #3931, most rule categories (on the CPython benchmark) got faster, but a few got slower, especially D, ANN, PT, and Q. So running `cargo build --release && hyperfine --ignore-failure --warmup 10 "./target/release/ruff ./crates/ruff/resources/test/cpython/ --no-cache --silent --select D,ANN,PT,Q"` went from ~436ms to ~2s on my machine.

I think the categories themselves are irrelevant -- it just turns out that these categories have many, many violations (e.g., `Q000` has 143,807 violations).

The inverse (`--select ALL --ignore D,ANN,PT,Q`) went from 452ms to 764ms, despite the fact that running any of the categories _individually_ got faster.

Though most projects (and most Ruff invocations) don't have hundreds of thousands of violations :) it'd be good to understand where this slowdown is coming from. We're running with `--no-cache` and `--silent`, so we shouldn't be serializing the diagnostics in any way.

**Comment by MichaReiser** [comment]
What changed is that we now always include the source code with the `Diagnostic`, regardless if `silent` is specified. This can have a significant cost if there are many diagnostics. 

I remember the previous version had a fast-path for when silent is enabled. 

I think the solution to this is to make `source_code` on `Message` optional as described in #4571. We could then omit the source file when `--silent`  has been passed.

**Comment by charliermarsh** [comment]
For my understanding: why does including the source code come with a cost? Isn't it just refcounted?

**Comment by charliermarsh** [comment]
But the number of files for which we're generating violations doesn't change between these rule sets. I just want to sanity check that we're not doing something unintentional like cloning the `str` to `String` for every _diagnostic.

**Comment by Boshen** [comment]
Probably relevant:
* https://github.com/Boshen/oxc/issues/166

Diagnostic printing is probably where you want to look at.

**Comment by charliermarsh** [comment]
`--silent` should mean that we're not printing diagnostics at all :joy:

**Comment by MichaReiser** [comment]
Here a [flamegraph](https://share.firefox.dev/3pWDYUr) running the above on main (without hyperfine). You can see that ruff spends the most time in the first thread, sorting diagnostics. 

[This is a profile](https://share.firefox.dev/3pWDYUr) from before the PR, it doesn't show the long sorting at the end of the analysis on the main thread.

**Comment by MichaReiser** [comment]
I'll follow up with a pr. i have an idea how we could speed this up even more
