### ISSUE TITLE
UP035 `typing.List` is deprecated, use `list` instead

### ISSUE THREAD

**Issue by jackdesert** [charliermarsh/ruff#4609]
Ruff is raising UP035 (typing.List is deprecated, use list instead), but when I run `pyupgrade` on the same file, it says the file is fine. I actually prefer using `typing.List` over using `list` for type annotations. But I didn't want to simply disable UP035 since there may be other outdated import styles that also fall under rule UP035. I'm not sure if this is a bug or not. The docs for pyupgrade do not appear to mention that it alters `from typing import List`. 

Code Snippet:
    
    from typing import List

    def hello(names: List[str]):
        for name in names:
            print(name)

Ruff version: ruff 0.0.269

Command invoked:

    ruff --isolated --select=UP /tmp/sample.py

Output from ruff:

    /tmp/sample.py:1:1: UP035 `typing.List` is deprecated, use `list` instead
    /tmp/sample.py:3:18: UP006 [*] Use `list` instead of `List` for type annotation

**Comment by bersbersbers** [comment]
I would say `ruff` is right and maybe `pyupgrade` is wrong: `typing.List` *is* deprecated, see https://docs.python.org/3/library/typing.html#typing.List.

> I actually prefer using typing.List over using list for type annotations

I am not sure this is relevant, but may I ask why that is?

**Comment by jackdesert** [comment]
This makes sense now. At first I preferred `List[str]` because I did not realize that `list[str]` was an option. I'll start using `list[str]` and avoid the extra import.
