### ISSUE TITLE
Create an official VS Code extension

### ISSUE THREAD

**Issue by charliermarsh** [charliermarsh/ruff#463]
Related: #271.

**Comment by charliermarsh** [comment]
\cc @Seamooo (I'm going to build this on top of `ruffd`)

**Comment by Seamooo** [comment]
feel free to spam me with issues to get this working

**Comment by charliermarsh** [comment]
@Seamooo - Is there any risk in modifying `ruffd` to run on-edit, in addition to on-save? In my testing, it seems fast and responsive enough even on very large Python files.

**Comment by charliermarsh** [comment]
(I've made these changes locally and will upstream them.)

**Comment by Seamooo** [comment]
If it's fast enough, that's exciting. I didn't want to add it initially as there was a decent amount of effort put into making partial edits very fast. Adding diagnostic generation on-edit requires the whole file, losing this speed up. I had thought of adding a debounced call on-edit but if it's fast enough that even that isn't necessary I'm happy to see it upstreamed

**Comment by Seamooo** [comment]
At a later date ideally operating on lines changed and the ast/cst diff would be preferrable such that the whole file isn't required

**Comment by charliermarsh** [comment]
So I think the options are as follows:

- Use their extension template, implement a Ruff extension that doesn't use `ruffd`.
- Write a VS Code extension that _does_ use `ruffd`, but require users to install `ruffd` separately (via `pip`).
- Write a VS Code extension that _does_ use `ruffd`, and find some way to distribute it as a Python extension that bundles both `ruff` and `ruffd`.

Those are roughly in order by how much work they would require (and, I think, how powerful they would be). Perhaps I'll start with (1), then we can do (2) or (3)?

**Comment by tiangolo** [comment]
I understand the Pylance (VS Code Python) are currently splitting their support for linters in independent but connected extensions. I understand that's the case for the Flake8 and Isort support. I suspect for black as well.

I don't know if they are bundling a version of those packages in the new extensions. But up to now, that the support has been just part of Pylance, it asks to install Flake8 and mypy in the current environment on the first automatic run of the linter, it shows a button prompting to install, that when clicked runs the `pip install` command on the terminal.

And when running the thing to "format code", as I have it configured with Black, it shows the prompt asking to install Black.

Just my two cents of the behavior I've seen.

But also, that's probably changing in some way with the new separated extensions, not sure.

But anyway, maybe worth checking how they are doing that to copy the behavior, maybe.

**Comment by charliermarsh** [comment]
Oh interesting, that's really helpful to hear. (I almost exclusively use PyCharm so I'm not that familiar with extension norms.) Will look into this.

**Comment by fannheyward** [comment]
@charliermarsh only `ruffd` binary. `rust-analyzer` does in this way.

**Comment by charliermarsh** [comment]
Thanks tons.

**Comment by charliermarsh** [comment]
This makes a lot of sense, it just requires that we build for each platform (which is fine).

**Comment by charliermarsh** [comment]
For now, I did the easier thing and published a VS Code extension based on Microsoft's Python template: https://marketplace.visualstudio.com/items?itemName=charliermarsh.ruff. I'd like to move that codebase over to `ruffd` internally.

**Comment by charliermarsh** [comment]
The extension is implemented in https://github.com/charliermarsh/vscode-ruff.

\ht to @harupy for some of the scaffolding.

**Comment by charliermarsh** [comment]
I'll enable autofix and code actions within that extension shortly. For now, it's just diagnostics.

**Comment by charliermarsh** [comment]
If you can, please give it a whirl! Would also appreciate reviews for the extension and stars on the repo if you're so inclined 🙏

**Comment by tiangolo** [comment]
Awesome! 🚀 

Right now it expects `ruff` to be in the environment. And if it is not, it logs an error in the Ruff-specific output, but there's no UI telling the user there was an error with Ruff, or asking the user to install Ruff in the current environment.

Not sure how Pylance does that, that shows a dialog asking the user to install, e.g. `mypy` and when clicking "OK" it runs the pip command to install it in the current environment, I think that would help.

**Comment by charliermarsh** [comment]
Oh interesting! My expectation from the template had been that if Ruff wasn't in your environment, it'd fall back to a bundled version. Let me play around with.

**Comment by charliermarsh** [comment]
(Having trouble with this because VS Code seems to omit the Ruff binary from the VSIX package, so the "bundled" version isn't working as expected.)

**Comment by charliermarsh** [comment]
(Looking at the rust-analyzer workflow file for guidance.)

**Comment by charliermarsh** [comment]
There's a `bundled/libs/bin/**` in the `.vscodeignore` from the extension template 🤦 

But I may still need to create separate builds for each platform? Since it's bundling a binary?

**Comment by charliermarsh** [comment]
The Ruff VS Code extension now comes bundled with the native `ruff` binary: https://github.com/charliermarsh/vscode-ruff/pull/10. So it should work out-of-the-box with no additional installation step.
