### ISSUE TITLE
Unexpected number of statements(PLR0915 Too many statements)

### ISSUE THREAD

**Issue by FishAlchemist** [charliermarsh/ruff#4659]
## Ruff Version
**ruff 0.0.269**
## Command(Powershell)
```powershell
ruff check --isolated --extend-select=PLR  .\main.py
```
## Output
```powershell
main.py:1:5: PLR0915 Too many statements (51 > 50)
Found 1 error.
```
## Source
**Please change the file extension from txt to py**
[main.txt](https://github.com/charliermarsh/ruff/files/11567206/main.txt)

**Comment by charliermarsh** [comment]
Interestingly, now that I test it, this _is_ consistent with Pylint.

**Comment by charliermarsh** [comment]
It looks like that choice predates the history on GitHub, can't find any information on it...

**Comment by charliermarsh** [comment]
I am inclined to change it though.
