### ISSUE TITLE
Create an official Sublime Text extension

### ISSUE THREAD

**Issue by charliermarsh** [charliermarsh/ruff#466]
This may require exposing Ruff's API as a Python interface. Or we could interop via subprocesses.

Here's one example: https://github.com/toreriklinnerud/sublime-rubyfmt/

**Comment by Jackenmen** [comment]
One thing of note is that there's an LSP extension for Sublime Text (SublimeLSP) so you could get away with just making `LSP-ruff` extension which appears to only require a simple stub:
https://github.com/sublimelsp/LSP-pylsp/blob/master/plugin.py
https://github.com/sublimelsp/lsp_utils/blob/f4b60cacb25ec7bb4141f1589bc8e1f828212f0b/st3/lsp_utils/pip_client_handler.py#L10

**Comment by lambdaq** [comment]
This is good idea. I am trying to config Ruff with SublimeLinter but didn't go anywhere.

**Comment by charliermarsh** [comment]
You can use `python-lsp-ruff` with Sublime Text -- I'm going to ship some upgrades to that extension, but it does surface errors.

I added some instructions to the README in https://github.com/charliermarsh/ruff/pull/1271.
