### ISSUE TITLE
F401 fix leaves empty space behind

### ISSUE THREAD

**Issue by radeklat** [charliermarsh/ruff#4661]
When unused imports (F401) are auto-fixed and no imports are remaining in the import group, empty space is left behind. In the example below, `\n` is used to denote empty new lines as GitHub markdown removed them.

I appreciate the code can be reformatted later by other tools like `black`. But it would be great if `ruff` could take care of the imports completely and remove the extra white space left behind as well. This would bring `ruff` closer to being a replacement for `isort`, which it already seems to be aiming to be.

### Initial code (`test.py`)

```python
from collections import defaultdict  # unused import
from typing import Any  # unused import
\n
import requests  # used import
\n
requests.get("https://github.com/charliermarsh/ruff")
```

### Command

```shell
ruff check --fix --isolated test.py
```

Outputs:

```text
Found 2 errors (2 fixed, 0 remaining).
```

### Expected output

```python
import requests  # used import
\n
requests.get("https://github.com/charliermarsh/ruff")
```

### Actual output

```python
\n
import requests  # used import
\n
requests.get("https://github.com/charliermarsh/ruff")
```

### Ruff settings

 None (no config file)

### Ruff version

0.0.270

**Comment by charliermarsh** [comment]
So in Ruff, we delegate this responsibility to the import-sorting rules, rather than having the unused-import rules take care of that kind of formatting . Have you tried adding the `"I"` rules to your configuration? E.g., `ruff check --fix --extend-select I test.py`, or with:

```toml
[tool.ruff]
select = ["E", "F", "I"]
```

**Comment by radeklat** [comment]
Delegation to the `I` rules makes sense. However, none of them fixes that either (not even on repeated runs) :( I tried:

- `ruff check --fix --isolated --select=I,E test.py`
- `ruff check --fix --isolated --select=ALL test.py`

**Comment by charliermarsh** [comment]
I’ll test it out myself in a bit - it’s possible we’re missing some case related to removing the first line in a file!

**Comment by charliermarsh** [comment]
So it does seem that we leave the empty line at the top of the file, but isort does too. (Generally, isort only modifies the newlines _after_ an import or set of imports, but not before.) So I'm torn on whether we should actually change anything here. My instinct is to leave our behavior as-is, and wait for the Ruff autoformatter to handle this anyway.

**Comment by radeklat** [comment]
I didn't know an auto-formatter was planned! I presume you mean https://github.com/charliermarsh/ruff/issues/1904 ? That would be acceptable solution. As mentioned initially, this issue can be already solved by `black`. So that is a reasonable workaround in the mean time.
