### ISSUE TITLE
support literal rule names in `noqa`

### ISSUE THREAD

**Issue by t184256** [charliermarsh/ruff#4705]
Rules, conveniently, have names.
I want to be able to suppress errors by rule names and not codes.

With ruff 0.0.270:

`a = 3; not a is None  # noqa: E714` -> finds `E702` \
`a = 3; not a is None  # noqa: not-is-test` -> suppresses both errors

Expectations:

`a = 3; not a is None  # noqa: E714` -> finds `E702` \
`a = 3; not a is None  # noqa: not-is-test` -> finds `E702`

**Comment by JonathanPlasse** [comment]
- Duplicate of #1773.

**Comment by t184256** [comment]
Indeed, sorry for the noise.

**Comment by charliermarsh** [comment]
All good, we plan to support this eventually.
