### ISSUE TITLE
docs: ambiguous link to settings from rule N802

### ISSUE THREAD

**Issue by saippuakauppias** [charliermarsh/ruff#4707]
The current version of the documentation for rule [`invalid-function-name (N802)`](https://beta.ruff.rs/docs/rules/invalid-function-name/) has a link to option `pep8-naming.ignore-names`, but it leads to rule [`flake8-self.ignore-names`](https://beta.ruff.rs/docs/settings/#ignore-names), not [`pep8-naming.ignore-names`](https://beta.ruff.rs/docs/settings/#ignore-names_1)

**Comment by JonathanPlasse** [comment]
Good catch!
Would you like to contribute to fix this?

**Comment by saippuakauppias** [comment]
If I'm not mistaken, according to the code - here need not just [add a link in multiple the comments](https://github.com/search?q=repo%3Acharliermarsh%2Fruff+ignore-names+path%3A%2F%5Ecrates%5C%2Fruff%5C%2Fsrc%5C%2Frules%5C%2Fpep8_naming%5C%2F%2F+path%3A%2F%5Ecrates%5C%2Fruff%5C%2Fsrc%5C%2Frules%5C%2Fpep8_naming%5C%2Frules%5C%2F%2F&type=code), but change something in the [autogenerated documentation](https://github.com/search?q=repo%3Acharliermarsh%2Fruff+ignore-names+path%3A*.json&type=code).

I'm afraid that I'm not able to figure it out now :(

**Comment by JonathanPlasse** [comment]
You are right, the auto-generated-documentation needs to be updated.

**Comment by jlaneve** [comment]
@JonathanPlasse I have a PR incoming to fix this!
