### ISSUE TITLE
docs: Disable rules sorting in the table of contents

### ISSUE THREAD

**Issue by saippuakauppias** [charliermarsh/ruff#4709]
On page https://beta.ruff.rs/docs/rules/ in the table of contents, the rules are sorted by name, and then they go on in the order in which they were added to the linter. 

For ease of use, it is best to disable the sorting of the table of contents.

**Comment by charliermarsh** [comment]
Sorry, which list are you suggesting should be reordered, and based on what ordering? The list in the sidebar?

**Comment by saippuakauppias** [comment]
Oh, excuse me. I meant the list here:
<img width="812" alt="image" src="https://github.com/charliermarsh/ruff/assets/945306/f2c183bc-2944-4d61-96cf-d9569237f8b8">


But it turns out that these are links to pypi packages, not links within the page. It's just that this huge list of packages that are supported is confusing, I thought it was the table of contents inside the page.

**Comment by charliermarsh** [comment]
Oh, no problem. Yeah, I can see why that's confusing. It may not be correct to include those at all in this context, since the rules are enumerated on the left anyway.
