### ISSUE TITLE
Implement W605, invalid escape sequence

### ISSUE THREAD

**Issue by andersk** [charliermarsh/ruff#474]
Python 3.6 [deprecated](https://docs.python.org/3/whatsnew/3.6.html#deprecated-python-behavior) unrecognized backslash escape sequences in string literals such as `"\c"`, and they will eventually become errors. Pycodestyle raises `W605 invalid escape sequence '\c'`. These aren’t adjusted by Black, so it’d be good for Ruff to have this rule too. This probably requires a CST parser (#286).

```console
$ cat a.py
"\c"
$ black a.py
All done! ✨ 🍰 ✨
1 file left unchanged.
$ flake8 a.py
a.py:1:2: W605 invalid escape sequence '\c'
$ python -Wall a.py
/tmp/a.py:1: DeprecationWarning: invalid escape sequence '\c'
  "\c"
$ python -Werror a.py
  File "/tmp/a.py", line 1
    "\c"
    ^^^^
SyntaxError: invalid escape sequence '\c'
$ ruff a.py
No pyproject.toml found.
Falling back to default configuration...
```

**Comment by charliermarsh** [comment]
I can implement this via token iteration for now.
