### ISSUE TITLE
PLE0117 - nonlocal name found without binding - false possitive

### ISSUE THREAD

**Issue by rmorshea** [charliermarsh/ruff#4746]
- version - 0.0.270
- command `ruff .`
- no especially relevant settings

It seems that [`PLE0117`](https://beta.ruff.rs/docs/rules/nonlocal-without-binding/) erroneously considers `del` statements when determining if a variable as been assigned

```python
def f():
    x = 1

    def g():
        nonlocal x  # error: PLE0117
        x = 2

    del x
```

**Comment by charliermarsh** [comment]
Agreed.
