### ISSUE TITLE
`--fix` doesn't have any effect on nursery rules

### ISSUE THREAD

**Issue by charliermarsh** [charliermarsh/ruff#4761]
Running, e.g., `cargo run -p ruff_cli -- check ../scipy --select E201,E202,E203 --fix` doesn't actually cause those rules to be marked as fixable. In `src/settings/mod.rs`, we initialize the set of fixable rules with `let mut fixable_set: RuleSet = RuleSelector::All.into_iter().collect();`. However, nursery rules are omitted from `RuleSelector::All`, to avoid adding them when users do `--select ALL`.

**Comment by evanrittenhouse** [comment]
@charliermarsh I'm actually curious how we want to do this. I was originally thinking the easiest way would be to find all autofixable rules in the `--select` block, then change them into `RuleSelectors` and add them to `Configuration::fixable`. I don't think that would respect the specificity differences between `--select` and `--extend-select`. I guess we can just merge them and let `Configuration` handle it later, right?

**Comment by charliermarsh** [comment]
I'm not sure. I was wondering if we could change the `let mut fixable_set: RuleSet = RuleSelector::All.into_iter().collect();` initialization line in some way, such that it includes _all_ rules rather than using the `ALL` selector.

**Comment by evanrittenhouse** [comment]
Ah interesting, okay let me take a look at that. That seems like it'd be easier than what I was thinking anyway (parsing `RuleSelectors` from the CLI into `Rules`, checking if they're autofixable, then translating back into `RuleSelectors`).

**Comment by charliermarsh** [comment]
What if we did the opposite: added a RuleSelector::NURSERY? And then initialized the fixable set to ALL and NURSERY.

**Comment by evanrittenhouse** [comment]
Sounds like a plan to me!
