### ISSUE TITLE
PLR1701: can be automatically fixed

### ISSUE THREAD

**Issue by saippuakauppias** [charliermarsh/ruff#4768]
Rule: https://beta.ruff.rs/docs/rules/repeated-isinstance-calls/

The text of the error provides an example to correct it, you can use it to fix it automatically.

It is important to note that if the settings option `target-version` is set to a version higher than 3.9 - you can use the syntax: `isinstance(x, int | float)`

**Comment by charliermarsh** [comment]
I actually thought we _did_ have autofix for this, but looks like we don't!

(We do have `isinstance(x, (int, float))` to `isinstance(x, int | float)` conversion implemented as part of the `UP` ruleset.)

**Comment by dhruvmanila** [comment]
I'll take this one up :)

**Comment by Skylion007** [comment]
This rule already had an autofix in: https://docs.astral.sh/ruff/rules/duplicate-isinstance-call/, sigh...
