### ISSUE TITLE
F523: Single variable with single quotes triggers syntax violation

### ISSUE THREAD

**Issue by addisoncrump** [charliermarsh/ruff#4823]
## Reproduction

The following snippet is a minimal reproduction:

```py
x = 5
'".'.format(x)
```

The fix attempted:

```py
x = 5
"".".format()
```

## Command line

```bash
ruff check format.py --fix --isolated
```

## Version information

Built on e82160a83a76c11d04d727ee2349091351e63b32 (latest, bleeding).

## Misc

Discovered by #4822.

**Comment by charliermarsh** [comment]
Thanks!

**Comment by charliermarsh** [comment]
Looks like F523 _always_ uses double quotes: `new_format_string = format!(r#""{new_format_string}""#);`
