### ISSUE TITLE
RET504 when origin of return value is mixed

### ISSUE THREAD

**Issue by hynek** [charliermarsh/ruff#4824]
I have [a function](https://github.com/hynek/structlog/blob/a23932c4a8e87b9fcc79ef893d1822b2c5acf6aa/src/structlog/processors.py#L170C6-L217) in structlog that generates a function based on arguments and can be simplified to the following:

```python
def func(x):
    if x:
        def f(): ...
    else:
        f = 42

    return f
```

And this gives me:

```
t.py:8:12: RET504 Unnecessary variable assignment before `return` statement
```

It passes if both origins of `f` are a function definition or if both are simple value assignments.

Version is 0.0.270

**Comment by charliermarsh** [comment]
👍 Can fix this today, thanks for reporting.
