### ISSUE TITLE
F523: Single variable leads to literal rendering of newline

### ISSUE THREAD

**Issue by addisoncrump** [charliermarsh/ruff#4826]
## Reproduction

The following snippet is a minimal reproduction:

```py
x = 5
"\n".format(x)
```

The fix attempted:

```py
x = 5
"
".format(x)
```

## Command line

```bash
ruff check format2.py --fix --isolated
```

## Version information

Built on e82160a83a76c11d04d727ee2349091351e63b32 (latest, bleeding).

## Misc

Discovered by #4822.

This is potentially a duplicate of #4823, but I couldn't diagnose a root cause. Notably, I chose to open a separate issue because, where #4823 causes an incorrect replacement of single quotes with double quotes, this issue literally renders the content of a string (!) and may have a separate root cause.

**Comment by charliermarsh** [comment]
I think we should rewrite the F523 fix to use LibCST.

**Comment by dhruvmanila** [comment]
This got fixed in d8a6109b698f4a53475926e88efc3907fd0386ad:

```diff
--- /Users/dhruv/playground/ruff/src/F523.py
+++ /Users/dhruv/playground/ruff/src/F523.py
@@ -1,2 +1,2 @@
 x = 5
-"\n".format(x)
+"\n".format()

Would fix 1 error.
```

**Comment by charliermarsh** [comment]
I think it will still do the wrong thing in some cases, like if we need to rewrite the string to remove positionals, in which case we end up reconstructing from the AST.

**Comment by charliermarsh** [comment]
Actually, I don't think we can use LibCST for this. It doesn't include a format-string parser. Instead, we probably need to change the format-string parser to include ranges on the various pieces, so that we can update the string in-place rather than recreate it.
