### ISSUE TITLE
Check for decorators

### ISSUE THREAD

**Issue by Bendabir** [charliermarsh/ruff#4830]
Hi,
I was wondering if Ruff would be able to check if a function, a method or a class is actually decorated by a given decorator. PyLint does support such thing through custom checkers and plugins (not native, but possible). Can we do the same with Ruff 🤔 ?

The first use case I see is for deprecations. To the best of my knowledge, there's no deprecation mecanism built-in with Python, so it requires to use some extra stuff (such as [deprecated](https://pypi.org/project/Deprecated/)) to decorate deprecated functions/methods. One downside of these approaches is that they only trigger (some warnings) at runtime. I could be nice to spot these deprecations ahead.

Thanks for your time 😄 

PS : I couldn't find any issue/question related to this, so feel free to redirect me if I missed something !

**Comment by JonathanPlasse** [comment]
Yes, the decorators of functions and classes are available in the AST.

**Comment by Bendabir** [comment]
Okay, nice. I'll have a look. Thanks !

**Comment by Bendabir** [comment]
Hmmm, I checked what's available in the AST and I'm not sure that what I had in mind is feasible. I can indeed access the decorators when declaring the function. For example :

```python
@deprecated(reason = "Will be removed.", version = "1.0.0")
def some_function():
    ...
```

However, when using the function itself, it's basically a call statement where I don't have access to much information.

```python
some_function()
```

As I would like to check for decorated functions at call time, I would need to get the decorators information  and I'm not sure that's possible.
