### ISSUE TITLE
`--fix` flag removes imports in `__init__` files if there is a lack of `__all__`

### ISSUE THREAD

**Issue by Czaki** [charliermarsh/ruff#484]
If `__init__` file does not contain `__all__` variable and `--fix` option is specified then `ruff` removes imports instead of create `__all__` variable with include all variables imported from submodules. 
Or report it as an error without modifications to files. And highlight lack of `__all__` variable.

**Comment by charliermarsh** [comment]
Will take a look at this today!

**Comment by charliermarsh** [comment]
Some relevant discussion from Flake8: https://github.com/PyCQA/pyflakes/issues/162, https://github.com/PyCQA/pyflakes/issues/471

**Comment by charliermarsh** [comment]
A couple options:

1. Suppress these errors entirely in `__init__.py` (always ignore unused imports for those files).
2. Suppress these errors when `__init__.py` only contains imports (potentially confusing).
3. Keep these errors under F401, but don't autofix them.
4. Keep these errors under F401, but don't autofix them _and_ add a custom message regarding `__all__`.
5. Move these errors to a new error code, and don't autofix them.

My preferences are either (1) or (4).

**Comment by Czaki** [comment]
I like 4.

**Comment by tgross35** [comment]
from x import Something as Something` is usually equivalent to `__all__ = ["Something"]`. You probably know that, but just making sure that case is covered :)

**Comment by charliermarsh** [comment]
(Going out in v0.0.86, which is building now.)

**Comment by fsouza** [comment]
@charliermarsh any thoughts on instructing users to configure `per-file-ignores` instead? Or adding a dedicated flag (similar to autoflake's `--ignore-init-module-imports`)?

I feel like that if an import error is reported is should be fixable?

**Comment by charliermarsh** [comment]
I’m open to making it a configuration setting!

**Comment by smackesey** [comment]
+1 for making it an option to autofix these. Our project ([Dagster](https://github.com/dagster-io/dagster)) has two types of `__init__.py` files (1) pure "export" files (i.e. they just import from submodules); (2) those that define a bunch of functions themselves (and so are more like standard modules). The rule as currently implemented prevents removing all of the unused imports from type (2).

FWIW, one can get around the conundrum of having intended-to-be-reexported symbols in `__init__.py` files appear to be unused (and flagged with F401) by using redundant aliases. That's what we do for [top-level `dagster`](https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/__init__.py):

```python
from dagster._core.definitions.decorators.sensor_decorator import (
    asset_sensor as asset_sensor,
    sensor as sensor,
    multi_asset_sensor as multi_asset_sensor,
)
from dagster._core.definitions.decorators.source_asset_decorator import (
    observable_source_asset as observable_source_asset,
)
from dagster._core.definitions.dependency import (
    DependencyDefinition as DependencyDefinition,
    MultiDependencyDefinition as MultiDependencyDefinition,
    NodeInvocation as NodeInvocation,
)
```

We had to add this because pyright/pylance complains the symbols are private otherwise (since they are imported rather than defined in the module).

So since other popular tools require you to do this (or use `__all__`) to mark imported symbols as public, and this is also a developing [Python standard](https://github.com/python/typing/blob/master/docs/source/libraries.rst#how-much-of-my-library-needs-types), it seems reasonable to me to by default not treat `__init__.py` imports as special, and have users opt into the "don't fix" special-casing.

**Comment by charliermarsh** [comment]
Yeah, that makes sense. I'll fix this today.

**Comment by charliermarsh** [comment]
This is going out in [v0.0.157](https://github.com/charliermarsh/ruff/releases/tag/v0.0.157) (building now), feedback welcome!

**Comment by mara004** [comment]
Can [ignore-init-module-imports](https://beta.ruff.rs/docs/settings/#ignore-init-module-imports) only be set in a configuration file, or is it also possible to pass this on the command line? (I'm new to ruff.)

**Comment by dhruvmanila** [comment]
Currently, it's not possible to pass arbitrary config keys as flag on the command-line but that's likely to change in the future (https://github.com/charliermarsh/ruff/pull/4297#issuecomment-1539466250).

**Comment by ethanmsl** [comment]
Was this fix/improvement rolled back?

using `ruff 0.0.292` and it has the same behavior as described originally : it complains about unused imports in __init__.py [`F401`].

And the `--fix` option merely deletes them.

![error reporting](https://github.com/astral-sh/ruff/assets/33399972/aa029182-c03f-4de9-bbaf-10ebf07b3ee1)

![auto-fix changes](https://github.com/astral-sh/ruff/assets/33399972/fe1d7d0e-88b0-490b-85bc-a55a6c6d2908)

**Comment by charliermarsh** [comment]
Do you have the relevant setting enabled? https://docs.astral.sh/ruff/settings/#ignore-init-module-imports

**Comment by cthorrez** [comment]
I do have the [ignore-init-module-imports](https://docs.astral.sh/ruff/settings/#ignore-init-module-imports) setting enabled in my pyproject.toml but it doesn't really "ignore" them. It doesn't fix them but it still fails the ruff run which is an issue if ruff is being used in a precommit hook.

with `ignore-init-module-imports = false`, it just removes the imports breaking my code

with `ignore-init-module-imports = true` I get this type of error blocking my commit

```
ruff.....................................................................Failed
- hook id: ruff
- exit code: 1

riix/utils/__init__.py:1:25: F401 `.data_utils.RatingDataset` imported but unused; consider adding to `__all__` or using a redundant alias
riix/utils/__init__.py:1:40: F401 `.data_utils.generate_matchup_data` imported but unused; consider adding to `__all__` or using a redundant alias
Found 2 errors.```

**Comment by joostsijm** [comment]
@cthorrez workaround for pre-commit hook picking up the error message is to ignore F401 error per file type like in the following pyproject.toml:
```toml
[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]
```

**Comment by vergenzt** [comment]
FYI all, I ended up writing an [`ast-grep`](https://ast-grep.github.io/) rule to rewrite such imports to use the redundant import alias. Figured I'd share it here:

```yaml
id: _
language: py
files:
- ./src/**/__init__.py

rule:
  all:

  - pattern: $NAME

  - inside:
      kind: import_from_statement
      stopBy: end

  - kind: dotted_name

  # has to NOT be the first dotted_name in the import statement (that's the source module)
  - follows:
      any:
      - has: { kind: dotted_name }
      - kind: dotted_name
      stopBy:
        kind: import_from_statement

transform:
  REDUNDANT_ALIAS:
    replace:
      source: $NAME
      replace: (.*)
      by: $1 as $1

fix: $REDUNDANT_ALIAS

```

**Comment by grahamannett** [comment]
> @cthorrez workaround for pre-commit hook picking up the error message is to ignore F401 error per file type like in the following pyproject.toml:
> 
> ```toml
> [tool.ruff.per-file-ignores]
> "__init__.py" = ["F401"]
> ```

this is very helpful and what I ended up using but seems like it is then required for any code base that uses ruff with F401 (or pyflakes rules) and __init__.py as a way to import classes/functions/etc from elsewhere.  Is this not the suggested project structure and there is a more modern/appropriate way to do that?  I don't really think `__all__` makes sense in this case

**Comment by zanieb** [comment]
Note we changed this behavior again recently in https://github.com/astral-sh/ruff/pull/10365, you can see more discussion there.

> __init__.py as a way to import classes/functions/etc from elsewhere

What do you mean? I would say that `__init__` is very much _not_ intended for external imports unless you are intentionally exposing them as a part of your public interface in which case `__all__` or a redundant alias `import foo as foo` are the appropriate ways to do so.

**Comment by linpan** [comment]
fix it ?
