### ISSUE TITLE
`BestFitting` export ambiguous in `rust_formatter` crate

### ISSUE THREAD

**Issue by madkinsz** [charliermarsh/ruff#4840]
A run of `cargo +nightly check` warns on this ambiguous export

```
 --> crates/ruff_formatter/src/prelude.rs:1:9
  |
1 | pub use crate::builders::*;
  |         ^^^^^^^^^^^^^^^^^^ the name `BestFitting` in the type namespace is first re-exported here
...
4 | pub use crate::format_element::*;
  |         ------------------------ but the name `BestFitting` in the type namespace is also re-exported here
  |
  = note: `#[warn(ambiguous_glob_reexports)]` on by default
```

https://github.com/charliermarsh/ruff/blob/86ced3516ba8b86581677bd11e89279dfc405a56/crates/ruff_formatter/src/builders.rs#L2134-L2136

https://github.com/charliermarsh/ruff/blob/86ced3516ba8b86581677bd11e89279dfc405a56/crates/ruff_formatter/src/format_element.rs#L292-L297

**Comment by MichaReiser** [comment]
I think the best here is to rename the BestFitting in builders to FormatBestFitting
