### ISSUE TITLE
F523: Newline between string and format invocation triggers extraction error

### ISSUE THREAD

**Issue by addisoncrump** [charliermarsh/ruff#4865]
It is possible to split a format invocation across multiple lines:

```py
(''
.format(2))
```

This makes ruff a bit mad:

```
error: Failed to create fix for StringDotFormatExtraPositionalArguments: Failed to extract expression from source
fuzz/artifacts/ruff_fix_validity/minimized-from-f670b0a6b2f154ee6d66e9ad4f601cab0b3d4609:1:2: F523 `.format` call has unused arguments at position(s): 0
Found 1 error.
```

Discovered by #4822.

**Comment by addisoncrump** [comment]
Hm, okay. I will need to filter out this particular case in the fuzzers (to prevent the panic induced in code I didn't write :sweat_smile:).

**Comment by addisoncrump** [comment]
So, should we reopen with different title?

**Comment by charliermarsh** [comment]
I'll just fix it real quick.
