### ISSUE TITLE
[flake8-comprehensions] C413 autofix bug

### ISSUE THREAD

**Issue by zariiii9003** [charliermarsh/ruff#4879]
The autofix for C413 can lead to bugs if the `key` parameter is used. Here is a little code example to show, that the results before and after the autofix are different.

```python3
original = [(1, 0), (2, 0), (3, 1), (4, 1)]
print(list(reversed(sorted(original, key=lambda x: x[1]))))
print(sorted(original, key=lambda x: x[1], reverse=True))
```

Here is the output:
```text
[(4, 1), (3, 1), (2, 0), (1, 0)]
[(3, 1), (4, 1), (1, 0), (2, 0)]
```

**Comment by charliermarsh** [comment]
Do `reversed(...)` and `reverse=True` break ties differently?

**Comment by charliermarsh** [comment]
Yeah, it looks like `reversed` does a full reversal, whereas `reverse` ends up retaining the original order for ties.

**Comment by dhruvmanila** [comment]
Wow, didn't know about this. I think the solution would be to make the auto-fix "sometimes" and not fix it when there's a `key` parameter present. The `key` parameter makes the sorting different for `reversed` and `sorted(..., reverse=True)`.
