### ISSUE TITLE
Omitted target_version when using ruff.toml

### ISSUE THREAD

**Issue by HealthyPear** [charliermarsh/ruff#4902]
I am using `ruff.toml` for my configuration and my Python package is configured with `pyproject.toml`.

In my ruff configuration, I omitted `target_version`.

I am using `ruff v0.0.270`.

When I launch `ruff check -v .` from the root of my repository I get,

> [2023-06-06][13:32:44][ruff::settings::pyproject][DEBUG] `project.requires_python` in `pyproject.toml` will not be used to set `target_version` when using `ruff.toml`.

If the expected behavior (infer from `pyproject.toml`) is not supported from `ruff.toml`, I think that the [documentation](https://beta.ruff.rs/docs/settings/#target-version) should be clearer.

If instead this is supposed to work maybe it's a bug or I missed something...

**Comment by dhruvmanila** [comment]
This is the expected behavior although I'm not sure the reasoning behind this. @charliermarsh could provide more info about this. But I do agree that this should be added in the documentation.

**Comment by charliermarsh** [comment]
This is the expected behavior -- I'll update the documentation. We don't want to reconcile settings inferred from multiple files, it adds a lot of complexity to the code and ultimately to the user-facing behavior. I think it's the right tradeoff, but it should be better documented here.

**Comment by charliermarsh** [comment]
By "inferred from multiple files", I mean that we would need to identify both the `ruff.toml` and the `pyproject.toml`, and extract + reconcile information from both of them, rather than using a single configuration file as the source of truth.
