### ISSUE TITLE
git submodule files not being excluded

### ISSUE THREAD

**Issue by mckib2** [charliermarsh/ruff#4920]
Working on https://github.com/scipy/scipy/pull/18642, I'm having trouble getting the ruff `lint.toml` file to ignore python files found in 3rd party git submodules.  It's reproducible locally and in CI.  I've tried the following locally:
- add additional `exclude` item `"scipy/_lib/highs/**/*.py"`
- added additional `per-file-ignore`:
    - `"scipy/_lib/highs/highspy/tests/test_highspy.py" = ["ALL"]`

Both result in the unhelpful message for 3rd-party code found in a git submodule:
```
scipy/_lib/highs/highspy/tests/test_highspy.py:57:4 found test function 'get_infeasible_model' which does not start with 'test'
```

Command I'm running: `python dev.py lint`, which I understand is running:
```
ruff --config=lint.toml [list of files that notably does not include scipy/_lib/highs/highspy/tests/test_highspy.py]
```

Version info:
```
$  python --version
Python 3.10.6
$ ruff --version
ruff 0.0.271
```

**Comment by charliermarsh** [comment]
Adding this to `lint.toml` does seem to resolve the issue for me:

```diff
❯ git diff HEAD
diff --git a/tools/lint.toml b/tools/lint.toml
index 67b996939..6f6756372 100644
--- a/tools/lint.toml
+++ b/tools/lint.toml
@@ -25,6 +25,7 @@ target-version = "py39"
 "scipy/optimize/_linprog.py" = ["F401"]
 "scipy/optimize/_linprog_ip.py" = ["F401"]
 "setup.py" = ["ALL"]
+"scipy/_lib/highs/**/*.py" = ["ALL"]

 [mccabe]
 # Unlike Flake8, default to a complexity level of 10.
```

Running `ruff --config=tools/lint.toml .` before and after suppresses an error in `test_highspy.py`. Do you mind giving that a try?

**Comment by mckib2** [comment]
Thanks @charliermarsh!  This is actually working, it's another utility printing out that message that's causing me grief.  Ruff is (and was) working as expected, operator error :)

**Comment by charliermarsh** [comment]
No worries, glad to hear it :)
