### ISSUE TITLE
Putting "T" in ignore does not ignore flake8-fixme (T)

### ISSUE THREAD

**Issue by ColemanDunn** [charliermarsh/ruff#4945]
* A minimal code snippet that reproduces the bug.

   `# TODO: this is not getting ignored`

* The command you invoked (e.g., `ruff /path/to/file.py --fix`), ideally including the `--isolated` flag.

   ruff check .

* The current Ruff settings (any relevant sections from your `pyproject.toml`).

   using select = ["ALL"] and ignore = ["T"]

* The current Ruff version (`ruff --version`).

   0.0.271

getting the following:
<img width="242" alt="Screenshot 2023-06-07 at 5 15 23 PM" src="https://github.com/charliermarsh/ruff/assets/42652642/16eff95a-d28d-4243-b761-8ae50a19b971">

Putting the explicit rule ("T002") happens to work. Luckily there are only 4 of them. But "T" without any numbers is not working. 

Tagging @evanrittenhouse in case you know anything about this. 

Thanks!

**Comment by charliermarsh** [comment]
Hey sorry — this is fixed in the next release, which I plan to cut tonight, but there’s some info on temporary workarounds here: https://github.com/charliermarsh/ruff/issues/4916

**Comment by ColemanDunn** [comment]
Thanks!
