### ISSUE TITLE
C402 false positive with extra kwargs to dict()

### ISSUE THREAD

**Issue by andersk** [charliermarsh/ruff#511]
`ruff --select=C402` gives “C402 Unnecessary generator - rewrite as a `dict` comprehension” on both of these lines. But the second cannot be rewritten as a `dict` comprehension due to the extra keyword argument `c`, so only the first should be an error.

```python
dict((a, b) for a, b in [("a", "b")])
dict(((a, b) for a, b in [("a", "b")]), c="d")
```

([Examples in real code](https://github.com/zulip/zulip/blob/925fa4ca50215e7d4ba0e7d72b1b77ad3f0b5a38/zerver/lib/exceptions.py#L114-L123). Also reported “upstream” at adamchainz/flake8-comprehensions#457.)

**Comment by charliermarsh** [comment]
Fix is included in https://github.com/charliermarsh/ruff/releases/tag/v0.0.91 (building now).
