### ISSUE TITLE
Implement a `--show-source` setting

### ISSUE THREAD

**Issue by charliermarsh** [charliermarsh/ruff#525]

**Comment by charliermarsh** [comment]
I want this to feel like Clippy:

<img width="750" alt="Screen Shot 2022-11-03 at 4 55 12 PM" src="https://user-images.githubusercontent.com/1309177/199832204-46d7ef8e-dac0-4ce4-aa9b-50009f7969d9.png">

In fact, I'd be happy for it to look _exactly_ like Clippy.

**Comment by charliermarsh** [comment]
Clippy is open-source so maybe parts of it can leveraged directly for this kind of reporting?

**Comment by squiddy** [comment]
I don't think I'll get anything in a mergeable state, but I'll look into this anyway.
