### ISSUE TITLE
Automatically disable color printing on non-tty terminals

### ISSUE THREAD

**Issue by charliermarsh** [charliermarsh/ruff#526]

**Comment by squiddy** [comment]
@charliermarsh From my testing, `colored` is already taking care of this, even though it's not mentioned specifically. From their README.

> Respect the CLICOLOR/CLICOLOR_FORCE behavior (see [the specs](http://bixense.com/clicolors/))
> Respect the NO_COLOR behavior (see [the specs](https://no-color.org/))

The page for CLICOLOR has an example of how to implement it, and they do check for TTY.

`colored` is doing it here (2.0.0): https://github.com/mackwic/colored/blob/v2.0.0/src/control.rs#L108

```rust
ShouldColorize {
            clicolor: ShouldColorize::normalize_env(env::var("CLICOLOR")).unwrap_or_else(|| true)
>>                && atty::is(atty::Stream::Stdout),
            clicolor_force: ShouldColorize::resolve_clicolor_force(
                env::var("NO_COLOR"),
                env::var("CLICOLOR_FORCE"),
            ),
            ..ShouldColorize::default()
        }
```

Confirmed on my machine as well.

**Comment by charliermarsh** [comment]
Oh, perfect, thank you.
