### ISSUE TITLE
Crash on parenthesized with statement

### ISSUE THREAD

**Issue by antonagestam** [charliermarsh/ruff#54]
I tried running ruff on a large project, which resulted in this crash:

```
[2022-08-31][10:33:40][ruff][ERROR] Failed to check repr-with.py: invalid syntax. Got unexpected token 'as' at line 9 column 13
```

It seems like the crash happens on parenthesized context managers introduced in Python 3.10. Minimal reproducible example:

```python
from contextlib import contextmanager

@contextmanager
def ctx():
    yield

with (ctx() as foo):
    ...
```

**Comment by charliermarsh** [comment]
Thanks for reporting! Looks like a bug in the parser. I'll look into it :)

**Comment by charliermarsh** [comment]
Will come back to this, but reported in the parser here too: https://github.com/RustPython/RustPython/issues/4145

**Comment by charliermarsh** [comment]
(This is a blocker for 0.1.0.)
