### ISSUE TITLE
Public api for fix generation

### ISSUE THREAD

**Issue by Seamooo** [charliermarsh/ruff#547]
Currently the checks returned by `ruff::check` will never include fixes, as `ruff::check_path` is called with `ruff::autofix::fixer::Mode::None`.

It would be preferable if either `ruff::autofix::fixer::Mode::Generate` was the default or that this is a parameter passed by the public API.

Alternatively another interface could be created such as `check_with_fixes` that runs with `Mode::Generate` instead of `Mode::None`.

In essence any public api for fix generation

**Comment by Seamooo** [comment]
I'm happy to put together a PR for this but given that the solution is more personal preference than anything else, this issue exists.

**Comment by charliermarsh** [comment]
Ah yeah, my mistake. Let’s change the default in that path to Generate.
