### ISSUE TITLE
N806 thinks a single `_` is uppercase

### ISSUE THREAD

**Issue by tgross35** [charliermarsh/ruff#560]
It looks like a single `_` as a variable name gets considered uppercase for N806. I don't think this happens for names that start with an underscore, like `_test`

```shell
root@5d53afc0df87:/home# ruff test_n806.py --select N --no-cache
Found 1 error(s).
test_n806.py:3:8: N806 Variable `_` in function should be lowercase
```

```py
def x():
    t = (1, 2)
    a, _ = t
```

**Comment by charliermarsh** [comment]
Good catch! Going out in [v0.0.97](https://github.com/charliermarsh/ruff/releases/tag/v0.0.97) (building now -- I had another quick fix to include anyway).
