### ISSUE TITLE
Make --quiet more quiet

### ISSUE THREAD

**Issue by jlangeveld** [charliermarsh/ruff#564]
Would it be possible to make the output more quiet when using the `--quiet` option?
Right now ruff reports
- That there are diagnostics
- That it's possible to fix some of them automatically.

But that means I have to use `grep -v` to filter out the diagnostics.

**Comment by charliermarsh** [comment]
Good idea.

**Comment by charliermarsh** [comment]
Will fix this today. I want to do a small refactor around those settings.

**Comment by charliermarsh** [comment]
This is going out in [v0.0.98](https://github.com/charliermarsh/ruff/releases/tag/v0.0.98) (building now).
