### ISSUE TITLE
feat: Ambiguous character detection

### ISSUE THREAD

**Issue by samuelcolvin** [charliermarsh/ruff#565]
vscode identifies ambiguous unicode characters and warns about them, screenshot:

![image](https://user-images.githubusercontent.com/4039449/199698850-608984e7-0422-4b8c-95b8-e8067a5b6205.png)

It would be great if ruff could do the same. I guess most useful in comments and docstrings, but I guess could also be useful in any string - though you might get false positives.

I :heart: sourcegraph, it makes finding this stuff much easier in big codebases, [here](https://sourcegraph.com/github.com/microsoft/vscode@86f0f9bfa268fe21af7efae37d8f0da1dba8137f/-/blob/src/vs/base/common/strings.ts?L1094) is the raw data used by vscode, see also https://github.com/hediet/vscode-unicode-data.

This idea came from https://github.com/pydantic/pydantic/pull/4714 thanks to @adriangb.

**Comment by samuelcolvin** [comment]
Great, ye I was thinking auto-fixing would be great, not sure if the available dataset includes the substitution characters, but I would assume it does.

**Comment by charliermarsh** [comment]
Coming together:

![Screen Shot 2022-11-03 at 11 29 08 PM](https://user-images.githubusercontent.com/1309177/199879066-1017f334-a5f6-469f-a2bf-2f379dcfb3c1.png)

**Comment by charliermarsh** [comment]
Any input on what the error code should be for this? (E.g., I just used `X001` above.) It's one of the first rules that isn't indexed based on another plugin's coding.

**Comment by samuelcolvin** [comment]
I think the above wording looks great.

**Comment by samuelcolvin** [comment]
What did you decide about docstrings, comments, strings?

Thinking about it, imagine I would want the error in all places. I guess if you used a different error code, people could easily switch it off in strings.

**Comment by charliermarsh** [comment]
For now it's just doing errors in strings (including docstrings). I could add comments too. I'm hesitant to check _every_ character in every file since it's hard to make that fast.

**Comment by samuelcolvin** [comment]
Makes sense, but I do think a different code for strings vs docstrings would be good - there are legimate reasons to use unicode characters in strings that are unlike to be intentional in docstrings.

**Comment by charliermarsh** [comment]
Okay, sounds good, I can change that.

**Comment by charliermarsh** [comment]
Resolved in https://github.com/charliermarsh/ruff/pull/590.

**Comment by charliermarsh** [comment]
Comment support went out in #653 as `RUF003`.
