### ISSUE TITLE
What should Ruff's error code prefix be?

### ISSUE THREAD

**Issue by charliermarsh** [charliermarsh/ruff#591]
That is: what prefix should we use for errors that are specific to Ruff, and not implemented out of compatibility with another tool?

Right now, we use `X001` and `X002`, which is maybe ok, but feels slightly awkward.

`R001` and `R002` could work, but `flake8-return` uses the `R` prefix.

`RUFF001` and `RUFF002` is another option.

Would love input + suggestions.

**Comment by andersk** [comment]
`🐶001` and `🐶002`! 😛

I note that the [Flake8 documentation](https://flake8.pycqa.org/en/stable/plugin-development/registering-plugins.html) uses `X` as the example plugin prefix, restricts prefixes to at most 3 characters, and recommends 2 or 3 (so maybe `RF` or `RUF`?). We needn’t obey its restrictions, of course.

**Comment by charliermarsh** [comment]
I don't mind `RUF` :)
