### ISSUE TITLE
No obvious way to use a glob or regexp pattern in `exclude`

### ISSUE THREAD

**Issue by the9000** [charliermarsh/ruff#61]
With many Django apps in one project,  one usually has a lot of auto-generated DB migrations, each under its own app directory. It looks like so:
```
apps/foo/migrations/...
apps/bar/migrations/...
```

It would be great to be able to match them in one exclude pattern, like `apps/*/migrations`, or, `**/migrations/`,  or even just `/migrations/`.

None of these appears to work right now; the only to list every app explicitly.

**Comment by charliermarsh** [comment]
Good feedback, will add!
