### ISSUE TITLE
Undefined name when using `Literal`

### ISSUE THREAD

**Issue by matteosantama** [charliermarsh/ruff#629]
```
❯ ruff --version
ruff 0.0.104
```

I am getting `F821 Undefined name 'uniform'` on this line,

```python
pi: Literal["uniform"] | torch.Tensor = "uniform"
```

Perhaps it has to do with the way I am importing `Literal`,

```python
if sys.version_info >= (3, 8):
    from typing import Literal
else:
    from typing_extensions import Literal
```

**Comment by matteosantama** [comment]
When I remove the `if/else` and import directly `from typing import Literal` there is no error. But when I instead to import directly with `from typing_extensions import Literal` the error crops up again.

So it is related to the usage of `typing_extensions`, not the `if/else`.

**Comment by charliermarsh** [comment]
Ok cool. Both should work. Let me take a look.

**Comment by charliermarsh** [comment]
This file runs for me without error:

```py
import sys

import torch


if sys.version_info >= (3, 8):
    from typing import Literal
else:
    from typing_extensions import Literal

pi: Literal["uniform"] | torch.Tensor = "uniform"
```

Can you help me tweak it to reproduce?

**Comment by matteosantama** [comment]
Hm ok, let me add a few more things.

```python
from __future__ import annotations

import sys
from dataclasses import dataclass

import torch

if sys.version_info >= (3, 8):
    from typing import Literal
else:
    from typing_extensions import Literal


@dataclass
class FictitiousPlay:  # <-- in my code, this actually subclasses something

    pi: Literal["uniform"] | torch.Tensor = "uniform"
```

**Comment by charliermarsh** [comment]
That's perfect, thanks.

**Comment by charliermarsh** [comment]
(The `from __future__ import annotations` is necessary to reproduce.)

**Comment by charliermarsh** [comment]
Will fix this.

**Comment by charliermarsh** [comment]
Thank you!

**Comment by charliermarsh** [comment]
I'll cut another release in a little bit.

**Comment by matteosantama** [comment]
Man you're speedy! Thanks!
