### ISSUE TITLE
Automatically remove .encode("utf-8")

### ISSUE THREAD

**Issue by charliermarsh** [charliermarsh/ruff#641]
See: https://github.com/asottile/pyupgrade#encodeutf-8

**Comment by charliermarsh** [comment]
If interested, there are some instructions on adding new rules in the `CONTRIBUTING.md` and [here](https://github.com/charliermarsh/ruff/issues/312#issuecomment-1280008634).

**Comment by andersk** [comment]
Note that pyupgrade only does this on string *literals*: [rationale](https://github.com/asottile/pyupgrade/issues/138#issuecomment-496044965), [source](https://github.com/asottile/pyupgrade/blob/v3.2.0/pyupgrade/_plugins/default_encoding.py), [tests](https://github.com/asottile/pyupgrade/blob/v3.2.0/tests/features/default_encoding_test.py).

For string literals with only ASCII characters, it actually rewrites `"foo".encode("utf-8")` to `b"foo"`: [documentation](https://github.com/asottile/pyupgrade/tree/v3.2.0#encode-to-bytes-literals), [source](https://github.com/asottile/pyupgrade/blob/v3.2.0/pyupgrade/_main.py#L225), [tests](https://github.com/asottile/pyupgrade/blob/v3.2.0/tests/features/binary_literals_test.py).

[Synonyms](https://docs.python.org/3/library/codecs.html#standard-encodings) of `utf-8`: `utf_8`, `u8`, `utf`, `utf8`, `cp65001` (all case-insensitive).

**Comment by martinlehoux** [comment]
Hi there! I'm quite interested in giving this one a try

**Comment by charliermarsh** [comment]
@martinlehoux - Awesome! Let me know if you have any questions at all. Happy to help.

**Comment by martinlehoux** [comment]
Hi! I have a first draft, but I wonder how you provide "complex" fixes for a piece of code.

For instance, to fix this
```py
"foo".encode("utf-8") # b"foo"
```

I tried to do something like this, only to discover that you can have only a single fix
```rust
check.amend(Fix::insertion("b".to_string(), expr.location));
let mut after_variable = variable.end_location.unwrap();
after_variable.go_right();
check.amend(Fix::deletion(
	after_variable,
	expr.end_location.unwrap(),
));
```

**Comment by charliermarsh** [comment]
I would structure that as a `Fix::replacement` of the entire string: `"foo".encode("utf-8")` -> `b"foo"`. [`assert_false.rs`](src/flake8_bugbear/plugins/assert_false.rs) could be a good example -- you'd basically build a new AST, then use `SourceGenerator` to convert that AST to source code, and use _that_ output as your replacement.

**Comment by martinlehoux** [comment]
Hi, I submitted a PR so we can discuss about it. Obviously I had no idea about error code, name or message ^^
