### ISSUE TITLE
Automatically rewrite `lru_cache` calls

### ISSUE THREAD

**Issue by charliermarsh** [charliermarsh/ruff#642]
See: https://github.com/asottile/pyupgrade#remove-parentheses-from-functoolslru_cache and https://github.com/asottile/pyupgrade#replace-functoolslru_cachemaxsizenone-with-shorthand.

**Comment by charliermarsh** [comment]
If interested, there are some instructions on adding new rules in the `CONTRIBUTING.md` and [here](https://github.com/charliermarsh/ruff/issues/312#issuecomment-1280008634).

**Comment by chammika-become** [comment]
@charliermarsh I have a working version on this. ATM, it can correctly identify the and generate checks. Could you please have a look at this. 
https://github.com/charliermarsh/ruff/compare/main...chammika-become:ruff:rewrite-lru-cache

sp.  `src/pyupgrade/checks.rs#unnecessary_lru_cache_params`

Any improvements are appreciated. FYI, I am learning Rust. If you are satisfied I will make a PR 👍

**Comment by charliermarsh** [comment]
Generally looks good! I have some small comments, but feel free to send a PR and I'll make them inline.

The biggest comment is: rather than using two arms for the `match &func.node` with very similar case bodies, could we instead use `match_name_or_attr` in `src/ast/helpers.rs` to match against `lru_cache`, then move all the check logic into a single code block?

**Comment by charliermarsh** [comment]
If we want to be even more rigorous, you could use `match_name_or_attr_from_module` in the same module, and add `functools` to `TRACK_FROM_IMPORTS` in `check_ast.rs`. That way, we would enforce that `lru_cache` has to be imported from `functools`.

**Comment by chammika-become** [comment]
@charliermarsh above! Thanks 
I was wondering how to enforce that we are checking only the `functools.lru_cache` and not any user defined `lru_cache`
