### ISSUE TITLE
Plans on creating a full LSP

### ISSUE THREAD

**Issue by jhossbach** [charliermarsh/ruff#665]
Hey,
I was thinking about adding a plugin for linting the code using ruff for the python language server (https://github.com/python-lsp/python-lsp-server) but it seems like there already exists a language server using ruff, namely ruffd by @Seamooo.
I am wondering whether the plan for the ruffd language server is to become a full-blown LSP server according to the [Microsoft specification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/) or if the goal is to be integrated into existing LSP's?

**Comment by charliermarsh** [comment]
My current thinking is that `ruffd` will evolve into a full-blown LSP server (it already _is_ an LSP server following that spec, IIRC, though maybe it needs some more features).

The [vscode-ruff](https://github.com/charliermarsh/vscode-ruff) plugin also implements Ruff into an LSP, though that's based on [pygls](https://github.com/openlawlibrary/pygls) as per the VS Code Python extension template, and there are plans to migrate that plugin to `ruffd`.

Does that make sense?

**Comment by jhossbach** [comment]
Sounds great, I will ask the python-language-server maintainers in the meantime if they are interested in a plugin for linting purely.

**Comment by charliermarsh** [comment]
Thanks! Cross-posting for posterity: https://github.com/python-lsp/python-lsp-server/issues/299

**Comment by kuator** [comment]
Will gladly ditch pyright for ruffd once it's mature
