### ISSUE TITLE
Should respect isort:skip comments

### ISSUE THREAD

**Issue by andersk** [charliermarsh/ruff#674]
`ruff` currently respects `noqa: I001` comments to prevent sorting certain imports. For improved isort compatibility, it should also respect `isort:skip` and `isort:skip_file` comments ([documentation](https://pycqa.github.io/isort/#skip-processing-of-imports-outside-of-configuration)).

**Comment by charliermarsh** [comment]
Good call.

**Comment by charliermarsh** [comment]
It looks like `isort:off` and `isort:on` are [recommended](https://pycqa.github.io/isort/docs/configuration/action_comments.html#isort-off) in the docs, so maybe I'll do those first.

**Comment by charliermarsh** [comment]
Some extremely crude metrics from code search:

<img width="274" alt="Screen Shot 2022-11-10 at 10 34 02 PM" src="https://user-images.githubusercontent.com/1309177/201257440-14ed2eaf-13f2-47be-b104-a47baad57afb.png">
<img width="282" alt="Screen Shot 2022-11-10 at 10 34 10 PM" src="https://user-images.githubusercontent.com/1309177/201257446-4f32c83e-3cba-4ea4-88a0-1890040596e1.png">
<img width="228" alt="Screen Shot 2022-11-10 at 10 34 17 PM" src="https://user-images.githubusercontent.com/1309177/201257447-da94ca14-8d4e-4d7a-b8f7-0c6f92a14576.png">
