### ISSUE TITLE
Import sorting deletes comments

### ISSUE THREAD

**Issue by andersk** [charliermarsh/ruff#675]
(This is a known limitation mentioned in https://github.com/charliermarsh/ruff/issues/465#issuecomment-1311075618, but might as well be tracked as an issue.)

`ruff --select=I --fix` incorrectly transforms

```python
# preserved
import os  # deleted

# deleted
import third_party  # deleted
```

into

```python
# preserved
import os

import third_party
```

**Comment by charliermarsh** [comment]
I don't understand isort's comment behavior yet, trying to make sense of it.

Before:
```py
# Comment 1
# Comment 2
import D

# Comment 3a
import C
# Comment 3b
import C

import B  # Comment 4

# Comment 5

# Comment 6
from A import (
	a,  # Comment 7
	b,
	c,  # Comment 8
)
from A import (
	a,  # Comment 9
	b,  # Comment 10
	c,  # Comment 11
)
```

After:
```py
# Comment 1
# Comment 2
import B  # Comment 4

# Comment 3b
# Comment 3a
import C
import D

# Comment 6
from A import a  # Comment 9
from A import b  # Comment 10
from A import c  # Comment 11

# Comment 5
```

**Comment by charliermarsh** [comment]
I'll just try to come up with something reasonable that does the right thing in the common cases (comment at end-of-line, etc.).

**Comment by charliermarsh** [comment]
Gonna try to fix this today. I've added comment extraction, now I just need to figure out the preservation strategy.

**Comment by tiangolo** [comment]
Amazing! This is one of the two things not allowing me to switch to Ruff's sorting, I need to preserve some comments for some `# type: ignore` and things like that.

**Comment by charliermarsh** [comment]
This took longer than expected. I'm not super happy with the amount of code required to handle comments, but the output is looking pretty good.

Here's the diff on Zulip:

![Screen Shot 2022-11-15 at 9 27 05 PM](https://user-images.githubusercontent.com/1309177/202068800-3850a40d-45c9-4bfd-a936-cd5b296a77e6.png)

Here's the diff on FastAPI:

![Screen Shot 2022-11-15 at 9 27 48 PM](https://user-images.githubusercontent.com/1309177/202068828-ccd37a18-0775-4378-80d8-cee4210e4097.png)
