### ISSUE TITLE
Crash if no pyproject.toml file is found

### ISSUE THREAD

**Issue by HallerPatrick** [charliermarsh/ruff#70]
Hey! 

Great project! I just found a bug that occurs if `ruff` cannot find a `pyproject.toml` file. It will assume that
there is a `pyproject.toml` file at `$HOME/.ruff`. When trying to parse it, the program crashes (silently) with a file not found error.

To reproduce:

Try running `ruff` in a location where it cannot find a `pyproject.toml`file at all.

I already forked and fixed the bug :)

**Comment by charliermarsh** [comment]
Much appreciated!
