### ISSUE TITLE
(feature) pre-commit support

### ISSUE THREAD

**Issue by kierun** [charliermarsh/ruff#72]
It would be nice to have [pre-commit](https://pre-commit.com/) support. [How to create new hooks](https://pre-commit.com/#new-hooks) in case it is needed.

It can wait… Definitely not an urgent task.

**Comment by ahonnecke** [comment]
:+1:

**Comment by charliermarsh** [comment]
#55 has something to this effect! Just need to get around to testing + merging it.

**Comment by charliermarsh** [comment]
Solved via #55.
