### ISSUE TITLE
Enhancement request - fixers for pycodestyle rules

### ISSUE THREAD

**Issue by peterjc** [charliermarsh/ruff#722]
Many of the pycodestyle rules ruff can detect ought to be easy to fix:

https://github.com/charliermarsh/ruff#pycodestyle

e.g. E713 could replace ``not x in y`` with ``x not in y`` and similar.

Tested with ruff 0.0.114

**Comment by harupy** [comment]
+1. I can work on this.

**Comment by harupy** [comment]
Are there any other auto-fixable checks?

**Comment by harupy** [comment]
Is `E722` auto-fixable?

Fix:

```python
try
    ...
except:
    ...
```

to:

```python
try
    ...
except Exception:
    ...
```

**Comment by JonathanPlasse** [comment]
> Is `DoNotUseBareExcept` auto-fixable?
> 
> Fix:
> 
> ```python
> try
>     ...
> except:
>     ...
> ```
> 
> to:
> 
> ```python
> try
>     ...
> except Exception:
>     ...
> ```

No, this is still bad. `flake8-blind-except` consider this an error.

**Comment by charliermarsh** [comment]
@harupy - Probably ok to close? Do you agree?

**Comment by harupy** [comment]
Yes, let's close this.
