### ISSUE TITLE
F821 Undefined name when using Literal from typing

### ISSUE THREAD

**Issue by adilkhash** [charliermarsh/ruff#733]
Hey 👋,

I discovered the problem with Literal discussed in another issue: https://github.com/charliermarsh/ruff/issues/629 but I have a slightly different use case which `ruff` doesn't like:

```python
import typing as t


class MyClass:
    category: t.Literal['A', 'B', 'C']
````

```bash
> ruff --version
ruff 0.0.117

> ruff mycode.py
Found 3 error(s).
mycode.py:5:25: F821 Undefined name `A`
mycode.py:5:30: F821 Undefined name `B`
mycode.py:5:35: F821 Undefined name `C`
```

It is interesting that if I import Literal from typing without using an alias then everything is OK:

```python
from typing import Literal


class MyClass:
    category: Literal['A', 'B', 'C']
````

**Comment by charliermarsh** [comment]
Yeah this is a legitimate deficiency right now! It’s similar to #720 but a slightly different case. We don’t track import aliases right now. But what you have here feels like a common pattern so I’ll try to prioritize fixing it.

**Comment by charliermarsh** [comment]
(I'll try to fix this today.)

**Comment by adilkhash** [comment]
Thanks for your quick responses, but I see that you've released the 0.0.119 version but it doesn't solve the problem:

```bash
> ruff --version           
ruff 0.0.119

> ruff mycode.py
Found 3 error(s).
mycode.py:5:25: F821 Undefined name `A`
mycode.py:5:30: F821 Undefined name `B`
mycode.py:5:35: F821 Undefined name `C`

**Comment by charliermarsh** [comment]
🤦 I missed a one-line change specific to `Literal`, one sec.

**Comment by charliermarsh** [comment]
Cutting a new release to fix this: [v0.0.120](https://github.com/charliermarsh/ruff/releases/tag/v0.0.120)

**Comment by crypdick** [comment]
This issue appears to have resurfaced. Unlike the OP, the second example is not working for me:

```python
from typing import Literal
# same issue with`from beartype.typing import Literal`

class MyClass:
    category: Literal["A", "B", "C"]
```

```
> ruff --version
ruff 0.2.1
> ruff tmp.py
tmp.py:5:24: F821 Undefined name `A`
tmp.py:5:29: F821 Undefined name `B`
tmp.py:5:34: F821 Undefined name `C`
Found 3 errors.
```

**Comment by crypdick** [comment]
@charliermarsh FYI this is still an issue on ruff 0.6.7
![image](https://github.com/user-attachments/assets/bfca0069-83b6-4073-b9f1-dff6c61626d3)
