### ISSUE TITLE
Formatting results on Windows

### ISSUE THREAD

**Issue by kaniak274** [charliermarsh/ruff#737]
Hi!

I've got one minor issue with how the result are formatted. On Linux the result is nicely formatted in the following way:
```
Found 1 error(s).
tf_gen_docs/markdown/service.py:44:1: T201 `print` found
```

and it's great! However, I sometimes use Windows and when I tried to run `ruff` inside the Powershell the result like this:
```
←[1;37mtf_gen_docs\resources\service.py←[0m←[36m:←[0m9←[36m:←[0m1←[36m:←[0m ←[1;31mT201←[0m `print` found
```

and the output is hard to read on Windows.

**Comment by charliermarsh** [comment]
Weird! I'm guessing that it's related to the color printing? Does adding setting the `NO_COLOR=1` environment variable help? Like `NO_COLOR=1 ruff path/to/file.py`?

**Comment by kaniak274** [comment]
Ah it does :D I was not thinking about that. Thanks!

**Comment by charliermarsh** [comment]
I wish it worked on Windows though! I wonder why that's happening. We use the `colored` crate under the hood.
