### ISSUE TITLE
D213 and D400 incompatibility

### ISSUE THREAD

**Issue by andriilahuta** [charliermarsh/ruff#740]
`D213` rule is not compatible with `D400` and some others.

Running `ruff --select D --ignore D100,D212` for the following file:
```py
def foo():
    """
    Foo.

    Bar.
    """
```
gives the following errors:
```
D400 First line should end with a period
D415 First line should end with a period, question mark, or exclamation point
```

**Comment by charliermarsh** [comment]
Thanks, this looks like a bug since `pydocstyle` doesn't throw here.

**Comment by andriilahuta** [comment]
@charliermarsh thanks! I've also found a couple of new bugs:

- Apparently `noqa` doesn't work for multiline docstrings. The code below still gives the error I'm trying to suppress:
  ```py
  def foo():
      """
      Foo.
      """  # noqa: D200
  ```
- Spaceless multiline strings don't throw `E501`.
  This throws an error:
  ```py
  foo = '''
  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  '''
  ```  
  And this doesn't:
  ```py
  foo = '''
  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  '''
  ```
