### ISSUE TITLE
Documentation request: conform to black settings

### ISSUE THREAD

**Issue by ahonnecke** [charliermarsh/ruff#75]
https://pypi.org/project/black/ is a very popular auto code formatter / style guide.

Many tools include documentation that specifically lay out how to configure said tool to conform to black.  I think that would be a helpful subsection.

**Comment by charliermarsh** [comment]
Good suggestion. Given Black's popularity, I do want ruff to focus less on stylistic linting and more on semantic linting, which would make this less of an issue, but it should def be documented.

**Comment by charliermarsh** [comment]
👍 Added a note to the README.
