### ISSUE TITLE
Version upgrade notice should only pop up once a day.

### ISSUE THREAD

**Issue by marscher** [charliermarsh/ruff#751]
When using Ruff in other tools, it'd be nice if one could turn off the "new version available" notice. It clutters the output badly, if Ruff is being invoked for every individual file (which is done by the IDE, or another embedding tool).

A simple console argument switch should do the trick.

Thanks for this great tool btw! :)

**Comment by charliermarsh** [comment]
The --quiet flag might do what you want? It omits the version check and only logs errors (nothing else).

I do think the version check is too spammy. I was under the impression that it would only log once a day, so need to revisit it. (It’s also possible that it deserves its own flag and config option.)

**Comment by marscher** [comment]
This is exactly what I was looking (not too focused) for. Thanks!
