### ISSUE TITLE
Missing --line-length in the command line API

### ISSUE THREAD

**Issue by peterjc** [charliermarsh/ruff#752]
At the command line flake8 exposes two line length settings:

```
$ flake8 --help | grep length
  --max-line-length n   Maximum allowed line length for the entirety of this
  --max-doc-length n    Maximum allowed doc line length for the entirety of
```

These control E501 (already in ruff) and W505 (also from pycodestyle but off by default in flake8 - see https://pycodestyle.pycqa.org/en/latest/intro.html#error-codes - not yet in ruff) respectively.

See also https://github.com/PyCQA/flake8-bugbear/issues/285 for a discussion about what flake8-bugbear B950 ought to obey.

Currently ruff has nothing like this at the command line:

```
$ ruff --help | grep length
```

However ruff does have a ``line-length`` configuration setting: 
https://github.com/charliermarsh/ruff#configuration

I would like you to add this to the ruff command line, e.g. as ``--line-length`` or if you want to match flake8 and/or add W505 support later, ``--max-line-length``

**Comment by charliermarsh** [comment]
Good call! I’ll add this today. I actually thought it already existed but clearly not!
