### ISSUE TITLE
Erroneous F821 on nested class

### ISSUE THREAD

**Issue by torarvid** [charliermarsh/ruff#754]
First off: Amazing looking tool. Love the work! 🏆 

Ruff version 0.0.120

Steps to reproduce:

1. Create test.py with the following contents

```python
class RandomClass:
    """This class needs to be present to trigger the bug."""

    def random_func(self):
        """The class also needs a function"""
        pass


class OuterClass:
    class InnerClass:
        pass

    def failing_func(self) -> "InnerClass":
        return self.InnerClass()
```

Then run `ruff test.py`:
```
Found 1 error(s).
test.py:13:31: F821 Undefined name `InnerClass`
```

But if, say, you remove all of `random_func`, the execution seems to succeed 😁

**Comment by charliermarsh** [comment]
Thank you! Weird bug, will try to fix today! :)

**Comment by charliermarsh** [comment]
Figured this one out, hopefully fixed in next release but let me know if you hit it again!

**Comment by charliermarsh** [comment]
Used your example as a new test case.
