### ISSUE TITLE
Suggestion: Do not print update information if `--format=json`

### ISSUE THREAD

**Issue by dhruvmanila** [charliermarsh/ruff#756]
When passing the flag to output in the JSON format, the update information is still being provided which leads to parsing error when passing the output to any JSON processor.

```console
❯ ruff --format=json .
[]

A new version of ruff is available: v0.0.117 -> v0.0.120
Run to update: pip3 install --upgrade ruff
```

Example using the `jq` command-line tool:

```console
❯ ruff data_structures/linked_list/__init__.py --format=json | jq
[]
parse error: Invalid numeric literal at line 3, column 2
```

This problem also persists when using the JSON output for editor integration.

**Comment by charliermarsh** [comment]
Yeah this makes sense.

**Comment by charliermarsh** [comment]
(You can pass `--quiet` alongside `--format=json` for now to suppress this.)

**Comment by charliermarsh** [comment]
(But this will get fixed today.)
