### ISSUE TITLE
Consider using hypothesmith

### ISSUE THREAD

**Issue by sobolevn** [charliermarsh/ruff#76]
Consider using https://pypi.org/project/hypothesmith/
It generates lots of python programms to run your tool on.

It really helps finding ones that crash.
Example: https://github.com/wemake-services/wemake-python-styleguide/blob/master/tests/test_checker/test_hypothesis.py

**Comment by charliermarsh** [comment]
We've been getting good panic coverage via `cargo-fuzz` so going to close for now.
