### ISSUE TITLE
Imported but not used fix under conditional as last import

### ISSUE THREAD

**Issue by LefterisJP** [charliermarsh/ruff#767]
Hey I got a kind of an edge case to report but guess it may be fixable so thought why not make an issue.

Consider the following

```python
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from random import randint
    from typing import List

a = 1
```

If you run `ruff --fix` on this it will detect that the 2 imports unde the if are not used and will delete them. But this will leave the `if TYPE_CHECKING` block empty, which is a syntax error.

Would it be possible to detect this and also delete the if?

Funnily enough if I only put one unused import, ruff fix will add a `pass` under the if which will fix the syntax error.

Another corollary of this is that a second run of ruff should also delete the `from typing import TYPE_CHECKING` since it's also unused. Could those two runs be combined?

**Comment by charliermarsh** [comment]
Thanks for filing! The intended behavior is to remove the two imports in the if-block, and replace them with a pass… so sounds like a big if it’s leaving you with an empty body.

I’d been hesitant to remove the if itself since it introduces a lot of complexity, but in theory it’s possible…

**Comment by charliermarsh** [comment]
Can I just confirm: are you on the latest version? I’m seeing Ruff correctly add a pass statement in that example.

**Comment by LefterisJP** [comment]
Hey @charliermarsh apologies. I should have checked. I was in an 1 week older venv and had `ruff 0.0.105` there. With `ruff 0.0.122` I also see the correct behavior.

**Comment by charliermarsh** [comment]
No prob! That was a regression anyway. Glad it’s working now.
