### ISSUE TITLE
Remove unnecessary abspath has been removed from pyupgrade

### ISSUE THREAD

**Issue by JonathanPlasse** [charliermarsh/ruff#773]
Hi, 
I just discovered `Ruff`, love it :heart_eyes: 
This is the [commit](https://github.com/asottile/pyupgrade/commit/a89ff428e9c6f394bd91135e5eee568df77814f2), which removed it.
Should it be removed?

**Comment by charliermarsh** [comment]
Sadly yes, it should be! Anthony made me aware of this yesterday. Thanks for filing the issue.

**Comment by JonathanPlasse** [comment]
Can I make a pull request to remove it?

**Comment by charliermarsh** [comment]
Of course, that would be welcome.

**Comment by charliermarsh** [comment]
Thanks again for the fix @JonathanPlasse!
