### ISSUE TITLE
Add flake8-blind-except rules

### ISSUE THREAD

**Issue by JonathanPlasse** [charliermarsh/ruff#788]
This would check when `BaseException` or `Exception` is used instead of a specific one.

I would like to work on it.
In which rule group would this go?

**Comment by charliermarsh** [comment]
I think we could add it as B902 to match the existing plugin.

**Comment by charliermarsh** [comment]
@JonathanPlasse - Can we close? Or was there another rule to add here?

**Comment by JonathanPlasse** [comment]
Yes, the other rule is redundant.

**Comment by charliermarsh** [comment]
Awesome.
