### ISSUE TITLE
N804 skips positional-only args

### ISSUE THREAD

**Issue by nstarman** [charliermarsh/ruff#834]
Rule N804 erroneously skips positional-only args. I found this in a piece of code similar to the following MWE.
Ruff is saying that ``other`` should be `cls`.

```python
class Class:
    @classmethod
    def method(cls, x, /, other):
        ...
```

**Comment by JonathanPlasse** [comment]
I would like to look into it.

**Comment by charliermarsh** [comment]
Fixed in https://github.com/charliermarsh/ruff/pull/836 thanks to @JonathanPlasse.
