### ISSUE TITLE
N807 should account for PEP 562

### ISSUE THREAD

**Issue by ofek** [charliermarsh/ruff#840]
`__getattr__` / `__dir__` - https://peps.python.org/pep-0562/

**Comment by charliermarsh** [comment]
I can fix this.

**Comment by ofek** [comment]
Thanks!

**Comment by charliermarsh** [comment]
Should be live now in [v0.0.132](https://github.com/charliermarsh/ruff/releases/tag/v0.0.132), but let me know if you see otherwise.

**Comment by ofek** [comment]
Success https://github.com/pypa/hatch/pull/609
