### ISSUE TITLE
support light theme

### ISSUE THREAD

**Issue by kemingy** [charliermarsh/ruff#852]
Currently, the style of `filename` is bold white: 

https://github.com/charliermarsh/ruff/blob/6733aad216295a9f7850d16291f7831cc31ec7fa/src/message.rs#LL59C71-L59C71

This means, if users are using a light theme, it's almost invisible.

![image](https://user-images.githubusercontent.com/12974685/203072105-8253bef8-e9e0-4bd6-8f01-02feeb80518f.png)

I wonder if this can be another color.

**Comment by charliermarsh** [comment]
Nice idea, for sure.
