### ISSUE TITLE
[Bug] unused `typing` imports are not auto-fixed when pyupgrade option is selected

### ISSUE THREAD

**Issue by ukalwa** [charliermarsh/ruff#866]
Ruff version: 0.0.132
Ruff configuration: Default
Python version: 3.10

## Simple reproduction

```py
# test.py
from typing import List
def test_sum_of_sequence(numbers: List[int]) -> int:
    return sum(numbers)
```

```toml
# pyproject.toml
[tool.ruff]
select = ["E", "F", "U"]
target-version = "py310"
```

When I ran `ruff test.py --fix`, the file changed to:

```py
from typing import List # unused import
def test_sum_of_sequence(numbers: list[int]) -> int: # Notice typing.List changed to built-in list
    return sum(numbers)
```
I would expect it to also remove unused imports `from typing import List`. As a workaround I run the command again to remove unused imports but it would be great if ruff can do it automatically.

Let me know if there is anything I could do to help.

Thank you for this amazing package. It is super fast and works great!

**Comment by charliermarsh** [comment]
Thank you for the kind words, and for the detailed report!

This is sort of a "known" bug but definitely something I'd like to fix. (This would be resolved automatically if we change Ruff to iteratively fix + re-run until the code stabilizes, as suggested in #660.)

**Comment by ukalwa** [comment]
Yes, that makes sense.

If no one hasn’t started working on this, I can give it a try if you can point me in the right direction.

**Comment by charliermarsh** [comment]
@ukalwa - I started on this last night! Sorry to step on your toes!

**Comment by ukalwa** [comment]
Cool, no worries 😀

**Comment by charliermarsh** [comment]
Should be fixed by https://github.com/charliermarsh/ruff/pull/875.
