### ISSUE TITLE
Publish to Homebrew

### ISSUE THREAD

**Issue by charliermarsh** [charliermarsh/ruff#873]

**Comment by messense** [comment]
Per https://docs.brew.sh/Acceptable-Formulae#niche-or-self-submitted-stuff

> be stable (e.g. not declared “unstable” or “beta” by upstream)

The 0.0.x versioning of ruff might be an issue? Perhaps a 0.1.x should be release before submitting formulae to homebrew-core. It doen't matter if you just want to maintain a [tap](https://docs.brew.sh/Taps).

**Comment by charliermarsh** [comment]
I think I have a working recipe here, but I need Homebrew to update to Rust 1.65.0.

**Comment by charliermarsh** [comment]
Maybe it'll get rejected, we'll see!

https://github.com/Homebrew/homebrew-core/pull/116712

**Comment by charliermarsh** [comment]
Good to go!

<img width="591" alt="Screen Shot 2022-11-26 at 12 58 50 PM" src="https://user-images.githubusercontent.com/1309177/204102601-699b8eec-c829-49c9-8e22-b011008e9e43.png">
