### ISSUE TITLE
Support # flake8: noqa tag at top of file to ignore entire file

### ISSUE THREAD

**Issue by jhallard** [charliermarsh/ruff#888]
We occasionally have files in our code base that we want to ignore certain flake8 errors for. Instead of marking each line, `flake8` allows one to simply tag the file with 
```
# flake8: noqa F402
```

to ignore a specific error or 
```
# flake8: noqa
```

to ignore all errors

**Comment by onerandomusername** [comment]
I might be in the minority here, but I appreciate that ruff *doesn't* support this. The same thing can be accomplished with providing the file in the pyproject.toml config key `tool.ruff.per-file-ignores`, and using this mandates a single list of all per file ignored error codes, which I think is less confusing.

**Comment by jhallard** [comment]
Seems like an odd thing to appreciate _not_ supporting? @onerandomusername if you don't like that way of specifying ignores, you'd be free to not use it, but since that method is used extensively in the wild, it makes it much easier to transition to `ruff` if it was supported.

**Comment by charliermarsh** [comment]
I can probably do it today.

**Comment by charliermarsh** [comment]
@jhallard - AFAICT `# flake8: noqa F402` isn't supported by Flake8, in that any `# flake8: noqa` disables Flake8 for the entire file.

As an example:

```py
# flake8: noqa F841

import os

def f():
    x = 1
```

This snippet contains an F841 violation (`F841 local variable 'x' is assigned to but never used`) and an F401 violation (`F401 'os' imported but unused`), but both are ignored no matter how I modify the `noqa` at the top. The Flake8 source code seems to suggest the same thing.
