### ISSUE TITLE
pyupgrade Python Version

### ISSUE THREAD

**Issue by gitpushdashf** [charliermarsh/ruff#896]
This is awesome!

Is there anything like pyupgrade's python_version? It lets you set the Python version that you want to update your code to. I find it nice to set that to the oldest non-EOLed Python version for open source libraries and to the latest version for applications.

The arguments for pyupgrade are `--py36-plus`, `--py37-plus`, etc.

**Comment by charliermarsh** [comment]
Let me know if you run into any issues with that :)

**Comment by gitpushdashf** [comment]
My bad! You're right. Seems to work so far. Thank you!
