### ISSUE TITLE
Use better style for per-file-ignores

### ISSUE THREAD

**Issue by lovetox** [charliermarsh/ruff#928]
currently the docs say to use an inline table

`per-file-ignores = {"__init__.py" = ["E402"], "path/to/file.py" = ["E402"]}`

inline tables allow no newlines, and are intended for really small tables.
In bigger codebases this will not stay small, and an inline table would force you to describe everything on one line.

I tested it and there is another representation that just works fine

i wasted 30 minutes to find this, so i thought maybe you are interested in it

```
[tool.ruff.per-file-ignores]
"__init__.py" = ["E402"]
"path/to/file.py" = ["E402"]
```

**Comment by charliermarsh** [comment]
Yeah those are equivalent representations, it's more of a TOML thing than any specific choice made in Ruff. I'm sorry you lost time on it! I'll change the docs to use the non-inline syntax, for clarity.
