### ISSUE TITLE
brew install ruff not find  

### ISSUE THREAD

**Issue by linpan** [charliermarsh/ruff#938]
Warning: No available formula with the name "ruff". Did you mean riff?
==> Searching for similarly named formulae...
These similarly named formulae were found:
truffle                                  riff
To install one of them, run (for example):
  brew install truffle
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.

**Comment by charliermarsh** [comment]
Can you try running `brew update` first?

**Comment by linpan** [comment]
cool,  figure out . by brew update . thanks.
