### ISSUE TITLE
Allow excluding functions with some decorators (like `@override`) from the docstring rules

### ISSUE THREAD

**Issue by thomkeh** [charliermarsh/ruff#940]
I use [typing_extensions.override](https://github.com/python/typing_extensions/blob/main/CHANGELOG.md#release-440-october-6-2022) to annotate methods that are overriding a method in the super class. The overriding methods don't need (but of course can optionally have) docstrings because the super method already has one.

**Comment by charliermarsh** [comment]
I thought this was supported, let me take a look...

**Comment by charliermarsh** [comment]
Oh, I was thinking of `@overload`, not `@override`!

**Comment by charliermarsh** [comment]
This is going out in [v0.0.143](https://github.com/charliermarsh/ruff/releases/tag/v0.0.143).
