### ISSUE TITLE
Auto-generate options reference in `README.md`

### ISSUE THREAD

**Issue by charliermarsh** [charliermarsh/ruff#945]
I just put that together manually for now, roughly in the style of [rustfmt](https://rust-lang.github.io/rustfmt/?version=v1.5.1&search=), but it'd be far preferable to auto-generate that section.

**Comment by squiddy** [comment]
Work happening here https://github.com/charliermarsh/ruff/pull/1015

**Comment by charliermarsh** [comment]
@squiddy made this happen! It's awesome!
