### ISSUE TITLE
Turn on U006 with 'from __future__ import annotations'

### ISSUE THREAD

**Issue by brandon-leapyear** [charliermarsh/ruff#949]
It seems like if `target-version` is below 3.9, U006 doesn't get triggered _at all_, even if `from __future__ import annotations` is included:

https://github.com/charliermarsh/ruff/blob/731fba90060de58f9893251d62913b9294fa2458/src/check_ast.rs#L1231-L1236

Repro:
```py
from __future__ import annotations

from typing import Optional

def foo(x: int) -> Optional[int]:
  return None
```
```console
$ ruff --select U foo.py
Found 1 error(s).
foo.py:5:20: U007 Use `X | Y` for type annotations
1 potentially fixable with the --fix option.

$ ruff --target-version=py38 --select U foo.py
```

Related: https://github.com/charliermarsh/ruff/issues/778

**Comment by charliermarsh** [comment]
Interesting, I honestly had no idea that `from __future__ import annotations` enabled this behavior for pre-3.9 versions (https://peps.python.org/pep-0585/#implementation). Will fix.

**Comment by brandon-leapyear** [comment]
To be extra clear, this only affects _annotations_. Anything at runtime should _not_ be converted pre-3.9

**Comment by charliermarsh** [comment]
This is going out in [v0.0.145](https://github.com/charliermarsh/ruff/releases/tag/v0.0.145).

**Comment by thomkeh** [comment]
It seems that in the new release, type aliases also trigger the check. Like in

```python
from __future__ import annotations
from typing import List, Union
from typing_extensions import TypeAlias

MyList: TypeAlias = Union[List[int], List[str]]
```

ruff output:
```
Found 3 error(s).
main.py:5:21: U007 Use `X | Y` for type annotations
main.py:5:27: U006 Use `list` instead of `List` for type annotations
main.py:5:38: U006 Use `list` instead of `List` for type annotations
3 potentially fixable with the --fix option.
```

However, if I went along with the suggested fix, I would get runtime errors.

**Comment by charliermarsh** [comment]
Taking a look...

**Comment by charliermarsh** [comment]
Okay I think this is going to require a more thoughtful fix. I see the issue but need to differentiate between a few cases in the code.

You should be able to disable this for now with:

```toml
[tool.ruff.pyupgrade]
# Preserve types, even if a file imports `from __future__ import annotations`.
keep-runtime-typing = true
```

**Comment by charliermarsh** [comment]
(I'll try to fix this today, gotta get to a few other things first! Now tracking in #979.)
