### ISSUE TITLE
Ignore E501 for long URLs in comments or docstrings

### ISSUE THREAD

**Issue by brandon-leapyear** [charliermarsh/ruff#950]
https://github.com/PyCQA/pycodestyle/blob/1063db8747e7d4e213160458aa3792e5ec05bc10/pycodestyle.py#L278-L285

**Comment by charliermarsh** [comment]
Thanks! Do you have a minimal code snippet that reproduces the issue for you? I thought we _did_ support this so want to ensure I have the right example to work from.

**Comment by brandon-leapyear** [comment]
This fails with `ruff` but passes with `flake8`:
```py
# https://google.com/aowriejfaeoifjawoeihfjawoiuehfjoaiwejfoaiwejfoawiejfoiawejfoaajwfoiaewjfoiawejfoiwajfweaoi
```

**Comment by charliermarsh** [comment]
I think this was actually a regression, fixing.

**Comment by brandon-leapyear** [comment]
So fast! Thanks!

**Comment by charliermarsh** [comment]
This is going out in [0.0.144](https://github.com/charliermarsh/ruff/releases/tag/v0.0.144).

**Comment by charliermarsh** [comment]
No prob! Appreciate the issues.
