### ISSUE TITLE
Support registering custom noqa codes

### ISSUE THREAD

**Issue by brandon-leapyear** [charliermarsh/ruff#951]
Until #872 is implemented, we would like to keep using `# noqa: V101` ignores. This is an [undocumented feature](https://github.com/jendrikseipp/vulture/commit/2488be07b115ef4c45c77c6ea8e500a5fc9c595a) in vulture, but we would still prefer using this for the time being. However, turning on M001 would remove these comments. It would be nice to tell the M001 rule what noqa rules third-party tools might use.

**Comment by charliermarsh** [comment]
Makes sense. (We may also want to support this in `--add-noqa` calls.)
