### ISSUE TITLE
Add GitHub output format

### ISSUE THREAD

**Issue by edgarrmondragon** [charliermarsh/ruff#974]
GitHub actions can annotate code locations using so-called [workflow commands](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions).

For example:

```yaml
      - name: Create annotation for build error
        run: echo "::error file=app.js,line=1,col=1::Missing semicolon"
```

If this is deemed valuable, I can submit a PR.

**Comment by charliermarsh** [comment]
Oh cool, I've never seen that. Happy to include it!
