### ISSUE TITLE
PyCharm Inspections support

### ISSUE THREAD

**Issue by nikolaik** [charliermarsh/ruff#978]
Hi there,

More of a question than a request, have you looked into supporting any of the [PyCharm inspections](https://www.jetbrains.com/help/pycharm/code-inspection.html)? I found a lot of overlap with the existing ruff and to be implemented pylint rules though, but there might be some worth checking out.

Does ruff support something similar to the  _Redeclared names without usage_ one (like I requested [here](https://github.com/PyCQA/pylint/issues/3471))?

PS: Seeing all the good progress being made with ruff is super exciting 💖

**Comment by charliermarsh** [comment]
Thank you!

I haven't looked closely but I mostly use PyCharm so I _am_ familiar with them. I do want to add unused argument detection soon.

Would _ Redeclared names without usage_ be equivalent to Flake8's [F811](https://www.flake8rules.com/rules/F811.html)?

**Comment by nikolaik** [comment]
Nice!

> Would _ Redeclared names without usage_ be equivalent to Flake8's [F811](https://www.flake8rules.com/rules/F811.html)?

That is very similar at least, by the description it looks like it detects redeclared imports only. I believe the pycharm rule works on any attribute. An example would be:

```py
class A:
    b = "ninja"
    b = "turtles"
```

**Comment by charliermarsh** [comment]
Gonna close this for now as F811 is being tracked separately (and I'd like it to be as expansive as is suggested here).
