### ISSUE TITLE
Implement pygrep-hooks

### ISSUE THREAD

**Issue by JonathanPlasse** [charliermarsh/ruff#980]
# [pygrep-hooks](https://github.com/pre-commit/pygrep-hooks/blob/main/tests/hooks_test.py)

- [x] **`python-check-blanket-noqa`**: Enforce that `noqa` annotations always occur with specific codes. Sample annotations: `# noqa: F401`, `# noqa: F401,W203`
- [x] **`python-check-blanket-type-ignore`**: Enforce that `# type: ignore` annotations always occur with specific codes. Sample annotations: `# type: ignore[attr-defined]`, `# type: ignore[attr-defined, name-defined]`
- [ ] **`python-check-mock-methods`**: Prevent common mistakes of `assert mck.not_called()`, `assert mck.called_once_with(...)` and `mck.assert_called`.
- [x] **`python-no-eval`**: A quick check for the `eval()` built-in function
- [x] **`python-no-log-warn`**: A quick check for the deprecated `.warn()` method of python loggers
- [x] **`python-use-type-annotations`**: Enforce that python3.6+ type annotations are used instead of type comments

**Comment by JonathanPlasse** [comment]
May be tag this issue `good first issue`.

**Comment by squiddy** [comment]
I'm working on `python-no-log-warn`.

**Comment by squiddy** [comment]
Working on `python-check-blanket-type-ignore` now.

**Comment by JonathanPlasse** [comment]
- #3302

**Comment by finswimmer** [comment]
Hey,

`python-use-type-annotations` is marked as implemented in the OP. But it isn't, is it? 🤔 

fin swimmer

**Comment by JonathanPlasse** [comment]
> Hey,
> 
> `python-use-type-annotations` is marked as implemented in the OP. But it isn't, is it? thinking
> 
> fin swimmer

> * [Add flake-pyi PYI033 "Do not use type comments in stubs" #3302](https://github.com/charliermarsh/ruff/pull/3302)

It is implemented as `PYI033`.

**Comment by finswimmer** [comment]
> It is implemented as PYI033.

Hm, looks like this is only for stub files (`.pyi`) I cannot get it work for normal python files. :man_shrugging:
