### ISSUE TITLE
Choose a badge for Ruff

### ISSUE THREAD

**Issue by ofek** [charliermarsh/ruff#989]
Like https://hatch.pypa.io/dev/next-steps/#community

**Comment by ofek** [comment]
Any thoughts? 🙂

**Comment by smackesey** [comment]
When there is a badge/logo/icon, it would also be nice to have it added to [Buildkite Emojis](https://github.com/buildkite/emojis#contributing-new-emoji) for Buildkite CI.

**Comment by charliermarsh** [comment]
I want this but I need a logo first!

**Comment by charliermarsh** [comment]
@ofek - Do you have any pointers on how you went about creating a badge? Any docs or references you could share?

**Comment by ofek** [comment]
Only https://github.com/pypa/hatch/issues/370

**Comment by saadmk11** [comment]
@charliermarsh This is an example from black https://github.com/psf/black#show-your-style

### Ruff Example:

**For README.md:**

```md
[![Linter: Ruff](https://img.shields.io/badge/Linter-Ruff-brightgreen?style=flat-square)](https://github.com/charliermarsh/ruff)
```

**For README.rst:**

```
.. image:: https://img.shields.io/badge/Linter-Ruff-brightgreen?style=flat-square
    :target: https://github.com/charliermarsh/ruff
```

**Looks like this:**

[![Linter: Ruff](https://img.shields.io/badge/Linter-Ruff-brightgreen?style=flat-square)](https://github.com/charliermarsh/ruff)

### Add Custom Logo:

> `?logo=data:image/png;base64,…`
> 
> Insert custom logo image (≥ 14px high). There is a limit on the total size of request headers we can accept (8192 bytes). From a practical perspective, this means the base64-encoded image text is limited to somewhere slightly under 8192 bytes depending on the rest of the request header.

**Source:** https://shields.io/category/build

**Comment by charliermarsh** [comment]
This is what I'm considering:

[![Ruff](https://user-images.githubusercontent.com/1309177/210483680-5d4f9d1d-e202-48d6-bc3e-13ed3de21001.svg)](https://github.com/charliermarsh/ruff)

**Comment by ofek** [comment]
Is there a way you can encode that in a single URL so it doesn't have to hit an endpoint every time?

**Comment by charliermarsh** [comment]
I think shields.io caches the call?

**Comment by charliermarsh** [comment]
I thought this was preferable to base64-encoding the SVG logo in the URL.

**Comment by charliermarsh** [comment]
Just confirming that these are cached on the CDN, so there shouldn't be any endpoint penalty AFAIU:

<img width="375" alt="Screen Shot 2023-01-05 at 11 00 35 PM" src="https://user-images.githubusercontent.com/1309177/210927502-c1c00bae-315c-4a08-80a2-349e3dca090f.png">

**Comment by ofek** [comment]
Awesome!
