### ISSUE TITLE
Implement F811 ("redefinition of unused name from line N")

### ISSUE THREAD

**Issue by charliermarsh** [charliermarsh/ruff#996]

**Comment by LefterisJP** [comment]
Question charlie. Is my understanding correct that this is the last flake8 rule to not exist in ruff? So one could completely replace flake8 with ruff once this is done? If yes I am watching this one :smile:

**Comment by charliermarsh** [comment]
@LefterisJP - Yeah this is the last Flake8 rule! (Assuming you use Black, which makes a bunch of the pycodestyle rules around spacing and such redundant.)

**Comment by LefterisJP** [comment]
> @LefterisJP - Yeah this is the last Flake8 rule! (Assuming you use Black, which makes a bunch of the pycodestyle rules around spacing and such redundant.)

We dont't use black unfortunately. I am in the minority that can't stand black and am still looking for a code styler that is a bit more customizable to make it enforce the style we have at rotki.

yapf (https://github.com/google/yapf) comes close to that but still some rules it does not check/for enforce yet. Do you know of any other?

**Comment by charliermarsh** [comment]
Sounds like you need ruff fmt!

**Comment by charliermarsh** [comment]
It's on my roadmap. I kind of want the customizability of `rustfmt` (never used `clangformat` so hard for me to compare).

**Comment by charliermarsh** [comment]
(I will get to this soon, it does add complexity but is hopefully worth the milestone...)
