### ISSUE TITLE
F401 false positive with future annotations

### ISSUE THREAD

**Issue by joouha** [charliermarsh/ruff#999]
Not sure if this is already fixed in #992, but given the follow code, ruff incorrectly flags F401:

```python
from __future__ import annotations

from typing import Callable, Optional


def my_func(param: "Optional[Callable]" = None) -> "None":
    pass
```

```
Found 1 error(s).
example.py:5:20: F401 `typing.Callable` imported but unused
1 potentially fixable with the --fix option.
```

If `from __future__ import annotations` is not used, there are no errors.

This happens with Python 3.8, 3.9, 3.10, 3.11, and ruff 0.0.151

P.S. Thanks for making ruff so fast

**Comment by charliermarsh** [comment]
Cool, still seeing this on `main` so will fix!

**Comment by charliermarsh** [comment]
(Although if you have `from __future__ import annotations` enabled, I think you can safely remove the quotes around the annotation?)

**Comment by charliermarsh** [comment]
This is going out in [v0.0.152](https://github.com/charliermarsh/ruff/releases/tag/v0.0.152) (building now).
